### PR TITLE
fsm: Fix snapshot bug with restoring node/service/check indexes

### LINKED ISSUE #8377: Inconsistent Consul Catalog
#### Overview of the Issue

We register external services in Consul, and are using Consul ESM to perform health checks. And we're using prepared queries along with the DNS interface to failover to another datacenter if a service becomes unhealthy in the local datacenter. The problem we're observing is when Consul ESM marks a service as unhealthy, sometimes only the leader is reflecting the update, so stale queries to follower servers are incorrectly returning the unhealthy endpoint. It's not a matter of being slow to update; the followers just never update.

We believe we have traced this down to inconsistent `CreateIndex` and `ModifyIndex` values across server nodes for the health checks:
```
➜  ~ pdsh -w 99com82,99com103,99com122 "curl -s 'http://localhost:8500/v1/health/checks/foo?stale' | jq -c '.[] | [.CreateIndex,.ModifyIndex]'"
99com103: [1573507,1573507]
99com82: [1491640,1491640]
99com122: [1491639,2428888]
➜  ~
```

Consistent queries are forwarded to the leader and return the expected results:
```
➜  ~ pdsh -w 99com82,99com103,99com122 "curl -s 'http://localhost:8500/v1/health/checks/foo' | jq -c '.[] | [.CreateIndex,.ModifyIndex]'"
99com103: [1491639,2428888]
99com82: [1491639,2428888]
99com122: [1491639,2428888]
➜  ~
```

While at the same time the servers all agree about the current index value:
```
➜  ~ pdsh -w 99com82,99com103,99com122 "curl -i -s 'http://localhost:8500/v1/health/checks/foo?stale' | grep X-Consul-Index"
99com103: X-Consul-Index: 2443513
99com122: X-Consul-Index: 2443513
99com82: X-Consul-Index: 2443513
➜  ~
```

We don't understand how some services found themselves in this state, but they never recover from it. At the same time, newly registered services do not demonstrate this behavior. And deregistering/re-registering an impacted service fixes that service.

#### Reproduction Steps

We don't know how to reproduce this scenario, but we detected the problem in 3 separate clusters. Given a 3 node cluster, we can find inconsistencies using the Prometheus query `(sum(consul_catalog_service_node_healthy) by (cluster,service_id) > 0) != 3`.

### Consul info

This example is from a 1.7.4 cluster, but we're observing the same behavior from a 1.8.0 cluster as well.

<details>
  <summary>Server info</summary>

```
cbroglie@99com82:~$ consul info
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 1
	services = 1
build:
	prerelease =
	revision = d149d7e9
	version = 1.7.4+1
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = [2a06:98c0:1400:100::c629:990d]:8300
	server = true
raft:
	applied_index = 2443786
	commit_index = 2443786
	fsm_pending = 0
	last_contact = 53.901869ms
	last_log_index = 2443786
	last_log_term = 74
	last_snapshot_index = 2436056
	last_snapshot_term = 74
	latest_configuration = [{Suffrage:Voter ID:432355ab-4fa6-502d-8837-3c1bf3719ff2 Address:[2a06:98c0:1400:100::c629:990d]:8300} {Suffrage:Voter ID:89b25347-d6b8-53de-b7d1-b96e7e0b4183 Address:[2a06:98c0:1400:100::c629:98fa]:8300} {Suffrage:Voter ID:1b23682c-c1b0-5067-bfd8-4aab2efe1d5d Address:[2a06:98c0:1400:100::c629:98e5]:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 74
runtime:
	arch = amd64
	cpu_count = 96
	goroutines = 1112
	max_procs = 96
	os = linux
	version = go1.13.12
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 16
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1654
	members = 311
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 116
	members = 8
	query_queue = 0
	query_time = 1
cbroglie@99com82:~$
```
```
cbroglie@99com103:~$ consul info
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 1
	services = 1
build:
	prerelease =
	revision = d149d7e9
	version = 1.7.4+1
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 2
	leader = false
	leader_addr = [2a06:98c0:1400:100::c629:990d]:8300
	server = true
raft:
	applied_index = 2444037
	commit_index = 2444037
	fsm_pending = 0
	last_contact = 5.948419ms
	last_log_index = 2444037
	last_log_term = 74
	last_snapshot_index = 2436056
	last_snapshot_term = 74
	latest_configuration = [{Suffrage:Voter ID:432355ab-4fa6-502d-8837-3c1bf3719ff2 Address:[2a06:98c0:1400:100::c629:990d]:8300} {Suffrage:Voter ID:89b25347-d6b8-53de-b7d1-b96e7e0b4183 Address:[2a06:98c0:1400:100::c629:98fa]:8300} {Suffrage:Voter ID:1b23682c-c1b0-5067-bfd8-4aab2efe1d5d Address:[2a06:98c0:1400:100::c629:98e5]:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 74
runtime:
	arch = amd64
	cpu_count = 96
	goroutines = 1102
	max_procs = 96
	os = linux
	version = go1.13.12
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 16
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1654
	members = 311
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 116
	members = 8
	query_queue = 0
	query_time = 1
cbroglie@99com103:~$
```
```
cbroglie@99com122:~$ consul info
agent:
	check_monitors = 0
	check_ttls = 1
	checks = 1
	services = 1
build:
	prerelease =
	revision = d149d7e9
	version = 1.7.4+1
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 2
	leader = true
	leader_addr = [2a06:98c0:1400:100::c629:990d]:8300
	server = true
raft:
	applied_index = 2444054
	commit_index = 2444054
	fsm_pending = 0
	last_contact = 0
	last_log_index = 2444054
	last_log_term = 74
	last_snapshot_index = 2436054
	last_snapshot_term = 74
	latest_configuration = [{Suffrage:Voter ID:432355ab-4fa6-502d-8837-3c1bf3719ff2 Address:[2a06:98c0:1400:100::c629:990d]:8300} {Suffrage:Voter ID:89b25347-d6b8-53de-b7d1-b96e7e0b4183 Address:[2a06:98c0:1400:100::c629:98fa]:8300} {Suffrage:Voter ID:1b23682c-c1b0-5067-bfd8-4aab2efe1d5d Address:[2a06:98c0:1400:100::c629:98e5]:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 74
runtime:
	arch = amd64
	cpu_count = 96
	goroutines = 1235
	max_procs = 96
	os = linux
	version = go1.13.12
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 16
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1654
	members = 311
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 116
	members = 8
	query_queue = 0
	query_time = 1
cbroglie@99com122:~$
```
</details>

### Operating system and Environment details

Our clusters are deployed on bare metal Linux machines.

### Log Fragments

We haven't found anything interesting in the logs. If we make a service fail the health check, we can observe Consul ESM marking it unhealthy:
```
Jul 23 09:40:14 99com81 consul-esm[60990]: 2020/07/23 09:40:14 [WARN] agent: Check 'node/foo/http-check' is now critical Jul 23 09:40:14 99com81 consul-esm[60990]: 2020/07/23 09:40:14 [TRACE] Registered check status to the catalog with ID http-check
```
And the update to the catalog:
```
2020-07-23T09:40:14.117Z [DEBUG] agent.tlsutil: IncomingRPCConfig: version=2
2020-07-23T09:40:14.117Z [DEBUG] agent.tlsutil: IncomingRPCConfig: version=2
2020-07-23T09:40:14.133Z [DEBUG] agent.http: Request finished: method=GET url=/v1/health/node/foo?dc=bar from=127.0.0.1:65410 latency=1.061054ms
2020-07-23T09:40:14.140Z [DEBUG] agent.http: Request finished: method=PUT url=/v1/txn?dc=bar from=127.0.0.1:65410 latency=6.606603ms
```
After which only the leader reflects the update, but we don't see any errors in the logs from followers.

### PR DESCRIPTION
**Pull request by kyhavlov**
This PR fixes a bug where nodes, services, and checks would not be restored with the correct Create/ModifyIndex when restoring from a snapshot. The KV entries didn't have this issue because we do a raw tx.Insert of the entry that we read from the transaction (so it includes the Create/ModifyIndex), but when loading in catalog objects we have to do additional bookkeeping, so we weren't doing a raw insert there. This PR adds a `preserveIndex` argument to some of the internal state store functions to enable keeping the index we read from the snapshot, without allowing users to arbitrarily modify these fields during a normal update.

Fixes #8377.

### CODE REVIEW

File: agent/consul/state/catalog.go [hunk 1]
```diff
@@ -1601,7 +1612,7 @@ func (s *Store) ensureCheckTxn(tx *txn, idx uint64, hc *structs.HealthCheck) err
 		existingCheck := existing.(*structs.HealthCheck)
 		hc.CreateIndex = existingCheck.CreateIndex
 		hc.ModifyIndex = existingCheck.ModifyIndex
-	} else {
+	} else if !preserveIndexes {
 		hc.CreateIndex = idx
 		hc.ModifyIndex = idx
```
Comment (freddygv) [inline agent/consul/state/catalog.go:1617]: Is setting `hc.ModifyIndex` here necessary? If `existing == nil` I think we should be able to always make it down to L1691
