### PR TITLE
consul operator raft transfer-leader should send the id

### LINKED ISSUE #16955: consul operator raft list-peers doesn't actually use the -id flag
#### Overview of the Issue

```
consul operator raft transfer-leader --id="<id of new leader>"
```
Doesn't actually set the leader to the sent id.

---

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with 3 server nodes
2. Run `consul operator raft list-peers` and pick a non leader
3. Run `consul operator raft transfer-leader --id="<id of new leader>"`
4. Observe random leader chose instead.

```
curl --request POST "http://127.0.0.1:8500/v1/operator/raft/transfer-leader?id=c4a1bc71-d25b-d271-083e-f843628dd112"
```
Works fine.

#### Code Details

In `command/operator/raft/transferleader/transfer_leader.go` the flag is setup `c.flags.StringVar(&c.id, "id", "", "The ID of the node to transfer leadership to.")` but it's never used. I think this is because there isn't an `id` field in `api.QueryOptions` that we can pass along to `RaftLeaderTransfer`. I'm willing to work on this but it's unclear what the solution should be. Should `RaftLeaderTransfer` just accept an optional `id string` parameter? That seems like it would be a breaking change. Should we instead add a `RaftLeaderTransferToID` method that has the new parameter and then the command would use one or the other based on the flag?

### PR DESCRIPTION
**Pull request by jameshartig**
### Description

Fixes #16955

Previously `consul operator raft transfer-leader` did not send the ID.

### PR Checklist

* [x] updated test coverage
* [x] external facing docs updated
* [x] appropriate backport labels added
* [x] not a security concern

### CODE REVIEW

File: api/operator_raft_test.go [hunk 1]
```diff
@@ -27,33 +28,181 @@ func TestAPI_OperatorRaftGetConfiguration(t *testing.T) {
 
 func TestAPI_OperatorRaftRemovePeerByAddress(t *testing.T) {
 	t.Parallel()
-	c, s := makeClient(t)
-	defer s.Stop()
+	c1, s1 := makeClientWithConfig(t, nil, func(conf *testutil.TestServerConfig) {
+		if conf.Autopilot == nil {
+			conf.Autopilot = &testutil.TestAutopilotConfig{}
+		}
+		conf.Autopilot.ServerStabilizationTime = "1ms"
```
Comment (jameshartig) [inline api/operator_raft_test.go:35]: This might be a useful default for the test server but I don't know if there are downsides with setting it. Without this, the `WaitForVoting` function would timeout since it would take 10s+ to become voting.

**Comment by jameshartig** [comment]
@dhiaayachi looks like in `go-test-api-1-20 / go-test` the `TestAPI_OperatorRaftLeaderTransfer` test failed with:
```
server.go:487: server.go:513: Server is not voting: []testutil.raftServer{testutil.raftServer{ID:"a1ef4e7e-cec8-8bfb-267a-7df6927b6df5", Voter:true}, testutil.raftServer{ID:"834e8b27-f1ef-bf4b-62b1-af40411be010", Voter:true}, testutil.raftServer{ID:"312565bc-a190-a54e-8755-28c75de87096", Voter:false}}
```

I'll have to do some more digging into why.

**Comment by dhiaayachi** [comment]
Thank you for working on this @jameshartig!
I also need to do some digging on to why some of the CI is failing for forks.

**Review by dhiaayachi — APPROVED** [review]
It seems that the fail was just a flake, we can check that later.
LGTM! I will check with the team if it's appropriate to merge this right away, before hitting merge.

Thank you for your contribution @jameshartig!

**Comment by ksmiley** [comment]
@dhiaayachi Can this be merged?

**Comment by hc-github-team-consul-core** [comment]
Backport failed @dhiaayachi. Run: https://github.com/hashicorp/consul/actions/runs/6201667603

**Comment by david-yu** [comment]
Merged, the backports failed so we will likely release this starting with 1.17.0.

**Comment by jameshartig** [comment]
The backport error was about a branch not existing?

> backport-assistant backport error: unknown error applying commits: error retrieving branch: GET https://api.github.com/repos/hashicorp/consul/branches/refs/heads/backport/16955-transfer-leader/safely-positive-bobcat: 404 Branch not found []

**Comment by david-yu** [comment]
This PR was deemed too risky to backport so we also decided not to backport in addition to seeing the failure.
