### PR TITLE
fix 'consul connect envoy' to try to use previously-configured grpc port

### LINKED ISSUE #5011: connect: prevent "consul connect envoy" from working if the gRPC port is not open on the agent
The command line helper tool `"consul connect envoy"` doesn't interrogate the running Consul Agent to determine if its gRPC port was actually configured. It only looks for some command line arguments or environment variables configured on the tool's invocation to know what the port is. If these aren't found it assumes dev mode is enabled and blindly uses `localhost:8502`.

This is great for dev purposes, but it causes some black hole of debugging when an operator is attempting to setup envoy with Connect outside of dev. The bootstrap config for envoy is generated pointing back to a port that consul is not listening on. Envoy starts up and patiently waits for xDS to be up where it will never be.

There is no error message or operator guidance at this point to help diagnose that they just have to reconfigure the Agent to explicitly set the gRPC port.

Suggestion is to have the command line tool either:
* use an agent endpoint to interrogate the gRPC port
* do a pre-flight port probe of the port to validate that it's even up before generating the bootstrap config

### PR DESCRIPTION
**Pull request by adams-sarah**
...on running agent before defaulting to 8502

Fixes #5011

### CODE REVIEW

File: command/connect/envoy/envoy.go [hunk 1]
```diff
@@ -321,6 +331,27 @@ func (c *cmd) lookupProxyIDForSidecar() (string, error) {
 	return proxyCmd.LookupProxyIDForSidecar(c.client, c.sidecarFor)
 }
 
+func (c *cmd) lookupGRPCPort() (int, error) {
+	self, err := c.client.Agent().Self()
+	if err != nil {
+		return 0, err
+	}
+	cfg, ok := self["DebugConfig"] // TODO: use string?
```
Comment (banks) [inline command/connect/envoy/envoy.go]: Seems fine to me :)

File: command/connect/envoy/envoy.go [hunk 2]
```diff
@@ -321,6 +331,27 @@ func (c *cmd) lookupProxyIDForSidecar() (string, error) {
...
+	if !ok {
+		return 0, fmt.Errorf("no debug config") // TODO: error msg: what is acceptable to show to client?
```
Comment (banks) [inline command/connect/envoy/envoy.go]: I'd suggest something simple. I _think_ this could only happen due to a bug or being run against a different version of Consul that happens not to export that field right? It's not optional to expose that?

If correct it's not likely to come up but something like:
```suggestion
		return 0, fmt.Errorf("unexpected agent response: no debug config")
```
Seems fine to me

File: command/connect/envoy/envoy.go [hunk 3]
```diff
@@ -321,6 +331,27 @@ func (c *cmd) lookupProxyIDForSidecar() (string, error) {
...
+	}
+	port, ok := cfg["GRPCPort"]
+	if !ok {
+		return 0, fmt.Errorf("no grpc port") // TODO: error msg
```
Comment (banks) [inline command/connect/envoy/envoy.go]:
```suggestion
		return 0, fmt.Errorf("agent does not have gRPC port enabled")
```

File: command/connect/envoy/envoy.go [hunk 4]
```diff
@@ -321,6 +331,27 @@ func (c *cmd) lookupProxyIDForSidecar() (string, error) {
...
+	}
+	portN, ok := port.(float64)
+	if !ok {
+		return 0, fmt.Errorf("non-float64 port number") // TODO: error msg
```
Comment (banks) [inline command/connect/envoy/envoy.go]:
```suggestion
		return 0, fmt.Errorf("invalid grpc port in agent response")
```
This is weird and jank message but it Shouldn't Happen(tm).

File: command/connect/envoy/envoy.go [hunk 5]
```diff
@@ -321,6 +331,27 @@ func (c *cmd) lookupProxyIDForSidecar() (string, error) {
 	return proxyCmd.LookupProxyIDForSidecar(c.client, c.sidecarFor)
 }
 
+func (c *cmd) lookupGRPCPort() (int, error) {
+	self, err := c.client.Agent().Self()
```
Comment (banks) [inline command/connect/envoy/envoy.go]: This is so magical. I'd never even considered actually just asking the agent which port to use. 👍

File: command/connect/envoy/envoy.go (hunk 2 above)
Comment (adams-sarah) [reply command/connect/envoy/envoy.go]: awesome!! thanks for these error suggestions

**Comment by adams-sarah** [comment]
Thanks for the review @banks!
