### PR TITLE
agent: cache notifications work after error if the underlying RPC returns index=1

### LINKED ISSUE #6521: Connect Envoy sidecar proxy "cannot create upstream cluster without discovery chain"
#### Overview of the Issue

I'm facing an issue with the envoy connect proxy. When I add an upstream to a service, the envoy proxy isn't configured correctly by consul, instead getting a `gRPC config stream closed: 2, cannot create upstream cluster without discovery chain` error message. A similar message `Error handling ADS stream: cannot create upstream cluster without discovery chain` is logged by the agent.

The issue is not present in the built-in proxy. Both were started using the `consul connect proxy|envoy` command, although the issue persists if envoy is started manually with the bootstrapped config.

#### Reproduction Steps

1. Create a cluster with at least 1 server and client
1. Place 2 service defintions on the client(s) with one having the other as an upstream
1. Run envoy with `consul connect envoy -sidecar-for [service]`

### Consul info for both Client and Server

<details>
  <summary>Client config</summary>

```
datacenter = "dc"
data_dir = "/opt/consul/"
connect {
  enabled = true
}
retry_join = ["test-server.lxd"]
ports {
  grpc = 8502
}
```

</details>

<details>
  <summary>Server config</summary>

```
datacenter = "dc"
data_dir = "/opt/consul/"
connect {
  enabled = true
}
retry_join = [ "test-server.lxd" ]
server = true
bootstrap_expect = 1
```

</details>

<details>
  <summary>Service defintions</summary>

```
service {
  id = "web-1"
  name = "web"
  port = 8080
  connect {
    sidecar_service {
      proxy {
        upstreams = [{
            destination_name = "redis"
            local_bind_port = 8128
        }]
      }
    }
  }
}
```

```
service {
  id = "redis-1"
  name = "redis"
  port =  15123
  connect {
    sidecar_service {}
  }
}
```

</details>

### Operating system and Environment details

I'm running consul on LXD Containers. The Host is an Ubuntu Server 18.04 LTS and the Containers are Debian 10. Arch is amd64. I could reproduce the issue on Consul 1.6.0 and 1.6.1 as well as envoy 1.9.1, 1.11.0 and 1.11.1.

### Log Fragments

<details>
  <summary>Envoy Logs</summary>

```
[2019-09-22 15:09:41.201][5337][info][main] [source/server/server.cc:516] starting main dispatch loop
[2019-09-22 15:09:41.204][5337][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 2, cannot create upstream cluster without discovery chain
[2019-09-22 15:09:41.204][5337][info][upstream] [source/common/upstream/cluster_manager_impl.cc:148] cm init: all clusters initialized
[2019-09-22 15:09:41.204][5337][info][main] [source/server/server.cc:500] all clusters initialized. initializing init manager
[2019-09-22 15:09:41.353][5337][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 2, cannot create upstream cluster without discovery chain
[2019-09-22 15:09:41.353][5337][info][config] [source/server/listener_manager_impl.cc:761] all dependencies initialized. starting workers
[2019-09-22 15:09:41.590][5337][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 2, cannot create upstream cluster without discovery chain
[2019-09-22 15:09:43.845][5337][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 2, cannot create upstream cluster without discovery chain
[2019-09-22 15:09:51.225][5337][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 2, cannot create upstream cluster without discovery chain

```

</details>

<details>
  <summary>Consul Agent logs</summary>

```
2019/09/22 15:09:41 [DEBUG] http: Request GET /v1/agent/services (1.105611ms) from=127.0.0.1:44378
2019/09/22 15:09:41 [DEBUG] http: Request GET /v1/agent/self (1.811474ms) from=127.0.0.1:44378
2019/09/22 15:09:41 [DEBUG] http: Request GET /v1/agent/service/web-1-sidecar-proxy (266.444µs) from=127.0.0.1:44378
2019/09/22 15:09:41 [WARN] agent: Check "service:redis-1-sidecar-proxy:1" socket connection failed: dial tcp 127.0.0.1:21000: connect: connection refused
2019/09/22 15:09:41 [DEBUG] Error handling ADS stream: cannot create upstream cluster without discovery chain
2019/09/22 15:09:41 [DEBUG] Error handling ADS stream: cannot create upstream cluster without discovery chain
2019/09/22 15:09:41 [DEBUG] Error handling ADS stream: cannot create upstream cluster without discovery chain
2019/09/22 15:09:43 [WARN] agent: Check "service:web-1-sidecar-proxy:1" socket connection failed: dial tcp 127.0.0.1:21001: connect: connection refused
2019/09/22 15:09:43 [DEBUG] Error handling ADS stream: cannot create upstream cluster without discovery chain

```

</details>

### PR DESCRIPTION
**Pull request by rboyer**
Fixes #6521

Ensure that initial failures to fetch an agent cache entry using the
notify API where the underlying RPC returns a synthetic index of 1
correctly recovers when those RPCs resume working.

The bug in the Cache.notifyBlockingQuery used to incorrectly "fix" the
index for the next query from 0 to 1 for all queries, when it should
have not done so for queries that errored.

Also fixed some things that made debugging difficult:

- config entry read/list endpoints send back QueryMeta headers
- xds event loops don't swallow the cache notification errors

### CODE REVIEW

File: agent/agent_test.go [hunk 1]
```diff
@@ -3574,3 +3576,97 @@ func TestConfigSourceFromName(t *testing.T) {
...
+	deadlineCh := time.After(10 * time.Second)
+	start := time.Now()
+AGAIN:
+	select {
+	case evt := <-ch:
+		// We may receive several notifications of an error until we get the
+		// first successful reply.
+		require.Equal(t, "foo", evt.CorrelationID)
+		if evt.Err != nil {
+			goto AGAIN
```
Comment (banks) [inline agent/agent_test.go]: Can we just put this in a loop? I know we use GOTO in places in the code despite it being controversial for some but I feel like here it doesn't make the code substantially simpler. In my mind seeing a loop is actually a clearer indication that this block is going to be retried.

File: agent/agent_test.go [hunk 2]
```diff
@@ -3574,3 +3576,97 @@ func TestConfigSourceFromName(t *testing.T) {
...
+		}
+		require.NoError(t, evt.Err)
+		require.NotNil(t, evt.Result)
+		t.Logf("took %s to get first success", time.Since(start))
+	case <-deadlineCh:
+		t.Fatal("did not get notified successfully")
+	}
```
Comment (banks) [inline agent/agent_test.go]: Awesome you managed to write a test to exercise this issue!

File: agent/cache/watch.go [hunk 3]
```diff
@@ -126,7 +126,7 @@ func (c *Cache) notifyBlockingQuery(ctx context.Context, t string, r Request, co
 			}
 		}
 		// Sanity check we always request blocking on second pass
-		if index < 1 {
+		if err == nil && index < 1 {
```
Comment (banks) [inline agent/cache/watch.go]: There is is!

File: agent/agent_test.go (hunk 1 above)
Comment (rboyer) [reply agent/agent_test.go]: Yep.
