### PR TITLE
xds: ensure that dependent xDS resources are reconfigured during primary type warming

### LINKED ISSUE #10379: Connect: CDS update makes all service sidecars return only 503
#### Overview of the Issue

We have services that are Connect-enabled and deployed with Nomad (job provided below). 
The services are connected to upstreams through intentions and are accessed through the service mesh.
On a CDS update the sidecar will start responding with ONLY 503 "no healthy upstream" for the upstreams.

We have 4  jobs with the almost same config that experience this error at _different_ times.
All 4 jobs have the same upstream. The upstream itself is alive and whenever this happens - it only affects one of the jobs - even though the upstream is the same.

To clarify - any time this happens, it happens to both instances/sidecars of the job at the same time - but no other jobs connecting to the same upstream.

When the jobs have been running for a while we see this log message from Envoy, at the same time from both sidecars:

```
[1][info][upstream] [source/common/upstream/cds_api_helper.cc:28] cds: add 2 cluster(s), remove 0 cluster(s)
```

Right after that the containers sidecar proxy (Envoy) starts responding with only a 503 and "no healthy upstream" for the upstream requests.

Looking at this Grafana screenshot its pretty clear that we go from steady traffic to zero successful traffic and 503 (5xx)-response codes. It gets resolved on a restart/redeploy of the services about 15 minutes later.
image

It seems to match this issue in Envoy:
https://github.com/envoyproxy/envoy/issues/11498

Our services are configured with "http" as the mesh-protocol. We are trying TCP with 2/4 jobs to see if we still hit the issue.

The issue seems to start occuring within 3 days of starting the job.

#### Reproduction Steps

Not sure what triggers the issue.

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 3
	checks = 56
	services = 42
build:
	prerelease = beta4
	revision = 477a6c73
	version = 1.10.0
consul:
	acl = enabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 1342
	max_procs = 4
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 68
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 51906
	members = 32
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 4
	services = 4
build:
	prerelease = beta4
	revision = 477a6c73
	version = 1.10.0
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 3
	leader = false
	leader_addr = 10.30.0.201:8300
	server = true
raft:
	applied_index = 8868882
	commit_index = 8868882
	fsm_pending = 0
	last_contact = 28.896572ms
	last_log_index = 8868882
	last_log_term = 9099
	last_snapshot_index = 8862611
	last_snapshot_term = 9099
	latest_configuration = [{Suffrage:Voter ID:849ab75f-2371-f504-3689-8443661ae78c Address:10.30.0.201:8300} {Suffrage:Voter ID:49c24e2d-e561-7e00-fa55-39e0b272d530 Address:10.30.0.200:8300} {Suffrage:Voter ID:29bb8d7e-0926-9cf2-cf0d-9d8e38941f83 Address:10.30.0.202:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 9099
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 634
	max_procs = 1
	os = linux
	version = go1.16.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 68
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 51906
	members = 32
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 3
	intent_queue = 0
	left = 0
	member_time = 2162
	members = 9
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Nomad job</summary>
```
{
  "ID": "academy-web@se",
  "Name": "academy-web@se",
  "Type": "service",
  "Datacenters": [
    "prod-az1"
  ],
  "Meta": {
    "timestamp": "1623419681",
    "version": "aeab287"
  },
  "Constraints": [
    {
      "LTarget": "${node.class}",
      "RTarget": "build",
      "Operand": "!="
    }
  ],
  "Update": {
    "Stagger": 10000000000,
    "MaxParallel": 2,
    "HealthCheck": "checks",
    "MinHealthyTime": 10000000000,
    "HealthyDeadline": 301000000000,
    "AutoRevert": true,
    "AutoPromote": true,
    "Canary": 2
  },
  "TaskGroups": [
    {
      "Name": "academy-web",
      "Count": 2,
      "Networks": [
        {
          "Mode": "bridge",
          "DynamicPorts": [
            {
              "Label": "healthcheck",
              "Value": 0,
              "To": -1,
              "HostNetwork": "default"
            },
            {
              "Label": "envoy-metrics",
              "Value": 0,
              "To": 9102,
              "HostNetwork": "default"
            }
          ]
        }
      ],
      "Services": [
        {
          "Name": "academy-web--se",
          "Port": 3000,
          "PortLabel": "3000",
          "AddressMode": "auto",
          "Tags": [
            "team=cawa",
            "namespace=se",
            "service=academy-web",
            "version=aeab287",
            "awesomejobid=91f39385-f187-4076-a4b4-5dd7b20947c7",
            "external",
            "mesh",
            "prometheus_metrics_path=/metrics",
            "prometheus_metrics_address=${attr.unique.network.ip-address}:${NOMAD_PORT_metrics}",
            "prometheus_metrics=false"
          ],
          "Checks": [
            {
              "Type": "http",
              "Protocol": "http",
              "Port": null,
              "Path": "/api/health",
              "AddressMode": "",
              "Interval": 10000000000,
              "Timeout": 2000000000,
              "CheckRestart": {
                "Limit": 5,
                "Grace": 90000000000,
                "IgnoreWarnings": true
              },
              "PortLabel": "healthcheck",
              "Expose": true
            }
          ],
          "Connect": {
            "Native": false,
            "SidecarService": {
              "Tags": [
                "mesh",
                "ingress",
                "prometheus_metrics_address=${NOMAD_HOST_ADDR_envoy-metrics}",
                "prometheus_metrics_path=/metrics"
              ],
              "Proxy": {
                "ExposeConfig": {
                  "Path": [
                    {
                      "Path": "/api/health",
                      "Protocol": "http",
                      "LocalPathPort": 3000,
                      "ListenerPort": "healthcheck"
                    }
                  ]
                },
                "Upstreams": [
                  {
                    "DestinationName": "academy-api",
                    "LocalBindPort": 13370
                  },
                  {
                    "DestinationName": "assessio-service",
                    "LocalBindPort": 13371
                  }
                ],
                "Config": {
                  "envoy_prometheus_bind_address": "0.0.0.0:9102",
                  "local_request_timeout_ms": 15000
                }
              }
            },
            "SidecarTask": {
              "Config": {
                "labels": [
                  {
                    "environment": "prod",
                    "namespace": "se",
                    "owner": "cawa",
                    "service": "academy-web-connect-proxy"
                  }
                ]
              },
              "Resources": {
                "CPU": 100,
                "MemoryMB": 128
              }
            }
          }
        }
      ],
      "Tasks": [
        {
          "Name": "academy-web",
          "Vault": null,
          "Driver": "docker",
          "Config": {
            "network_mode": null,
            "image": "...redacted",
            "volumes": [
              "/usr/local/share/ca-certificates/:/certs/",
              "local/etc/hosts:/etc/hosts"
            ],
            "logging": [],
            "labels": [
              {
                "image": "...redacted",
                "environment": "prod",
                "image_tag": "aeab287",
                "namespace": "se",
                "owner": "cawa",
                "service": "academy-web"
              }
            ]
          },
          "Services": null,
          "Env": {
            "SERVICE_PORT": "3000",
            "SERVICE_NAME": "academy-web",
            ...redacted
          },
          "Templates": [
            {
              "SourcePath": "",
              "DestPath": "local/etc/hosts",
              "EmbeddedTmpl": "127.0.0.1 localhost\n"
            }
          ],
          "Resources": {
            "CPU": 100,
            "MemoryMB": 256
          },
          "RestartPolicy": {
            "Attempts": 10,
            "Interval": 1800000000000,
            "Delay": 15000000000,
            "Mode": "fail"
          },
          "Artifacts": [],
          "KillTimeout": 15000000000
        }
      ],
      "EphemeralDisk": {
        "SizeMB": 300
      }
    }
  ]
}
```
</details>

### Operating system and Environment details

- Running on Azure
- Consul 1.1.10-beta4, same issue with beta3
- Nomad 1.1.1 (same with 1.1.0)
- Ubuntu 20.04
- Envoy with this image: envoyproxy/envoy:v1.18.3 (same with 1.18.2)

### Log Fragments
Haven't been able to capture meaningful logs from Consul YET - will update when I have them.

Envoy logs just before this is happening:

```
[1][info][upstream] [source/common/upstream/cds_api_helper.cc:28] cds: add 2 cluster(s), remove 0 cluster(s)
```
_Edit: Wrong Nomad job template_

### PR DESCRIPTION
**Pull request by rboyer**
Updates to a cluster will clear the associated endpoints, and updates to
a listener will clear the associated routes. Update the incremental xDS
logic to account for this implicit cleanup so that we can finish warming
the clusters and listeners.

Fixes #10379

### CODE REVIEW

File: agent/xds/delta_test.go [hunk 1]
```diff
@@ -327,6 +327,137 @@ func TestServer_DeltaAggregatedResources_v3_BasicProtocol_HTTP2(t *testing.T) {
...
+
+	// Send initial cluster discover.
+	envoy.SendDeltaReq(t, ClusterType, &envoy_discovery_v3.DeltaDiscoveryRequest{})
+
+	// Check no response sent yet
+	assertDeltaChanBlocked(t, envoy.deltaStream.sendCh)
+
+	requireProtocolVersionGauge(t, scenario, "v3", 1)
+
+	// Deliver a new snapshot (tcp with one tcp upstream)
```
Comment (freddygv) [inline agent/xds/delta_test.go:353]:
```suggestion
	// Deliver a new snapshot (tcp proxy with two tcp upstreams)
```

File: agent/xds/delta_test.go [hunk 2]
```diff
@@ -327,6 +327,137 @@ func TestServer_DeltaAggregatedResources_v3_BasicProtocol_HTTP2(t *testing.T) {
 	}
 }
 
+func TestServer_DeltaAggregatedResources_v3_BasicProtocol_TCP_clusterChangesImpactEndpoints(t *testing.T) {
```
Comment (freddygv) [inline agent/xds/delta_test.go:330]: Are the TODOs at the top of this file still needed?

File: agent/xds/delta_test.go [hunk 3]
```diff
@@ -327,6 +327,137 @@ func TestServer_DeltaAggregatedResources_v3_BasicProtocol_HTTP2(t *testing.T) {
...
+		Resources: makeTestResources(t,
+			// SAME makeTestCluster(t, snap, "tcp:local_app"),
+			makeTestCluster(t, snap, "tcp:db:timeout"),
+			// SAME makeTestCluster(t, snap, "tcp:geo-cache"),
+		),
+	})
+
+	envoy.SendDeltaReqACK(t, ClusterType, 4, true, nil)
+
+	// And we re-send the endpoints for the updated cluster after getting the
```
Comment (freddygv) [inline agent/xds/delta_test.go:437]: Can you add a test for the listeners/routes side of this?

**Review by freddygv — APPROVED** [review]
LGTM, added some non-blocking requests around the testing

File: .changelog/10381.txt [hunk 4]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+xds: ensure that dependent xDS resources are reconfigured during primary type warming
```
Comment (banks) [inline .changelog/10381.txt:2]: IIUC we only introduced this bug in 1.10 betas right? Should we make that clear here - this isn't fxing a bug from 1.9.x or earlier right?

**Review by banks — APPROVED** [review]
LGTM! Great job getting this fix in, I like that we have a test that could reproduce 👏

File: .changelog/10381.txt (hunk 4 above)
Comment (rboyer) [reply .changelog/10381.txt:2]: Maybe I could change the message to be something like `xds: (beta-only) ...` so that when we generate the flattened GA changelog we just omit the beta-only messages?

File: agent/xds/delta_test.go (hunk 2 above)
Comment (rboyer) [reply agent/xds/delta_test.go:330]: Yes. I did not come back and add a bunch of additional protocol tests.

File: agent/xds/delta_test.go (hunk 3 above)
Comment (rboyer) [reply agent/xds/delta_test.go]: done. Had to change the entire mechanism too because it's not as easy as CDS/EDS

**Review by freddygv — APPROVED** [review]
I think this looks good, just had a couple, likely non-blocking, questions

File: agent/xds/delta_test.go [hunk 5]
```diff
@@ -340,114 +340,311 @@ func TestServer_DeltaAggregatedResources_v3_BasicProtocol_TCP_clusterChangesImpa
...
-	// ACK for the cluster.
-	assertDeltaResponseSent(t, envoy.deltaStream.sendCh, &envoy_discovery_v3.DeltaDiscoveryResponse{
-		TypeUrl: EndpointType,
-		Nonce:   hexString(5),
-		Resources: makeTestResources(t,
-			makeTestEndpoints(t, snap, "tcp:db"),
-			// SAME makeTestEndpoints(t, snap, "tcp:geo-cache"),
-		),
+func TestServer_DeltaAggregatedResources_v3_BasicProtocol_HTTP2_RDS_listenerChangesImpactRoutes(t *testing.T) {
+	// NOTE: this actually has to be a multi-terminating gateway
```
[the remark this answers is not in the document]
Comment (rboyer) [reply agent/xds/delta_test.go:467]: ugh, this is a WIP comment trail before i came up with a way to have a snapshot change that bumped a listener without causing the route to bump at the same time for unrelated reasons.

File: agent/xds/listeners.go [hunk 6]
```diff
@@ -663,6 +663,51 @@ const (
...
+				return nil, err
+			}
+
+			if hcm.RouteSpecifier == nil {
+				continue
+			}
+
+			rds, ok := hcm.RouteSpecifier.(*envoy_http_v3.HttpConnectionManager_Rds)
+			if !ok {
+				continue
```
[the remark this answers is not in the document]
Comment (rboyer) [reply agent/xds/listeners.go:697]: So if the listener isn't configured to use RDS, there can't possibly be a bug as defined in this issue. Independently edited routes is what RDS is.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/386296.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 848ad8535bad41e992ac349160f4bdb39433bb87 onto `release/1.10.x` succeeded!
