### PR TITLE
Fix envoy config when both RetryOn* values are set

### LINKED ISSUE #7209: Consul connect conflict with RetryOnConnectFailure and RetryOnStatusCodes
#### Overview of the Issue

RetryOnStatusCodes and RetryOnConnectFailure conflict when using both in a service-router definition

#### Reproduction Steps

Service router definition :
```
Kind = "service-router"
Name = "myservice"
Routes = [
  {
    Destination {
      RequestTimeout = "300s"
      NumRetries = 3
      RetryOnConnectFailure = true
      RetryOnStatusCodes = [500,503,504]
    }
  }
]
```
Envoy live config :
```
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "myservice.default.dc1.internal.4ac8e688-8425-9ab1-6c11-86bbc2e198af.consul",
           "timeout": "300s",
           "retry_policy": {
            "retry_on": ",retriable-status-codes",
            "num_retries": 3,
            "retriable_status_codes": [
             500,
             503,
             504
            ]
           }
          }
         }
```
### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 58
	services = 58
build:
	prerelease = beta4
	revision = ef60c572
	version = 1.7.0
consul:
	acl = disabled
	known_servers = 3
	server = false
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 2629
	max_procs = 4
	os = linux
	version = go1.12.13
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2103
	members = 10
	query_queue = 0
	query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = beta4
	revision = ef60c572
	version = 1.7.0
consul:
	acl = disabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.100.98.20:8300
	server = true
raft:
	applied_index = 13115629
	commit_index = 13115629
	fsm_pending = 0
	last_contact = 44.731385ms
	last_log_index = 13115630
	last_log_term = 111
	last_snapshot_index = 13098863
	last_snapshot_term = 111
	latest_configuration = [{Suffrage:Voter ID:dabe53a8-ea5c-133e-5c72-eeae2a721807 Address:10.100.99.8:8300} {Suffrage:Voter ID:eb288b71-8633-7d21-d8f1-e4b0c1724398 Address:10.100.98.20:8300} {Suffrage:Voter ID:89d5cfe7-0932-2684-2cee-4c9c54bd2fab Address:10.100.98.136:8300}]
	latest_configuration_index = 0
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 111
runtime:
	arch = amd64
	cpu_count = 4
	goroutines = 326
	max_procs = 4
	os = linux
	version = go1.12.13
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 2103
	members = 10
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 94
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

I'm using consul 1.7.0 beta4 in a GKE cluster.

### PR DESCRIPTION
**Pull request by crhino**
Fixes #7209

### CODE REVIEW

**Comment by crhino** [comment]
Decided against adding an Envoy integration test for this since the setup/testing would be fairly complex, and hopefully the `golden` envoy config testdata will be enough to stop regressions.

File: agent/xds/routes.go [hunk 1]
```diff
@@ -129,7 +129,7 @@ func makeUpstreamRouteForDiscoveryChain(
 					}
 					if len(destination.RetryOnStatusCodes) > 0 {
 						if retryPolicy.RetryOn != "" {
-							retryPolicy.RetryOn = ",retriable-status-codes"
+							retryPolicy.RetryOn = retryPolicy.RetryOn + ",retriable-status-codes"
```
Comment (banks) [inline agent/xds/routes.go]: I guess the original intent was to use `+=`... It's easier to see it's correct with the more explicit concatenation though.
