### PR TITLE
connect: generate intermediate at same time as root

### LINKED ISSUE #6269: connect: cluster bootstrapped with Vault CA cannot issue certs
#### Overview of the Issue

If you bootstrap a new Consul cluster with Vault as the Connect CA, Consul will fail to generate any certificates because it doesn't correctly initialize the intermediate CA.

If you bootstrap with Consul's internal CA and then switch to Vault after leader election, it works as expected.

#### Reproduction Steps

1. Start Consul with Vault as the CA.
```
./consul agent -dev -hcl 'connect {enabled=true, ca_provider="vault", ca_config{token="redacted",root_pki_path="/root",intermediate_pki_path="/inter",address="http://localhost:8200"}}'
```

2. Try to issue a leaf cert.
```
curl localhost:8500/v1/agent/connect/ca/leaf/foobar
```

3. Observe the Consul output.
```
error issuing cert: Error making API request.

URL: PUT http://localhost:8200/v1/inter/sign/leaf-cert
Code: 404. Errors:

* no handler for route 'inter/sign/leaf-cert'
```

### Consul info for both Client and Server

Confirmed with both 1.5.3 and 1.6.0-beta3.

### PR DESCRIPTION
**Pull request by tradel**
Fixes #6269 by generating intermediate CA during `initializeRootCA()`.

### CODE REVIEW

File: agent/consul/leader_connect.go [hunk 1]
```diff
@@ -209,12 +209,21 @@ func (s *Server) initializeRootCA(provider ca.Provider, conf *structs.CAConfigur
...
-
 	rootCA, err := parseCARoot(rootPEM, conf.Provider, conf.ClusterID)
 	if err != nil {
 		return err
 	}
 
+	// Also create the intermediate CA, which is the one that actually signs leaf certs
+	interPEM, err := provider.GenerateIntermediate()
+	if err != nil {
+		return fmt.Errorf("error getting intermediate cert: %v", err)
```
Comment (freddygv) [inline agent/consul/leader_connect.go]:
```suggestion
		return fmt.Errorf("error generating intermediate cert: %v", err)
```

File: agent/consul/leader_connect.go [hunk 2]
```diff
@@ -209,12 +209,21 @@ func (s *Server) initializeRootCA(provider ca.Provider, conf *structs.CAConfigur
...
+	}
+	_, err = connect.ParseCert(interPEM)
+	if err != nil {
+		return fmt.Errorf("error getting intermediate cert: %v", err)
```
Comment (freddygv) [inline agent/consul/leader_connect.go]:
```suggestion
		return fmt.Errorf("error parsing intermediate cert: %v", err)
```

**Comment by tradel** [comment]
Thanks Freddy. I accepted your suggestions and merged into the release branch.
