### PR TITLE
ca: set the correct SigningKeyID after config update with Vault provider

### LINKED ISSUE #11662: ca: CARoot.SigningKeyID is wrong after config update when using the Vault CA provider
It looks like we mostly fixed this issue a couple years ago in #6513 (#6507). That PR fixed it by updating the signing key to the correct version during initialize, but I believe the same bug still exists in the `UpdateConfiguration` flow.

In `parseCARoot` we set the `SigningKeyID` to the encoded `rootCert.SubjectKeyId`, which is correct for the Consul and AWS providers in the Primary DC, but not for the Vault provider, because the Vault provider uses an intermediate (not the root) to sign leafs:
https://github.com/hashicorp/consul/blob/7bbad6fe560ab27f51dd6c5cd16f28418082424c/agent/consul/leader_connect_ca.go#L224

`parseCARoot` is called from two places: `primaryInitialize` (when a server is elected leader and initializes the provider) and `primaryUpdateRootCA` when a CA config change is made by a user.

In `primaryInitialize` this bug is hidden by the migration code that was added in #6513:
https://github.com/hashicorp/consul/blob/7bbad6fe560ab27f51dd6c5cd16f28418082424c/agent/consul/leader_connect_ca.go#L456-L461

Despite the comment, I believe this condition continues to be true today, because `parseCARoot` above still sets it to the wrong value.

In `primaryUpdateRootCA` there is no corresponding fix-up code, so we are left with the wrong signing key:
https://github.com/hashicorp/consul/blob/7bbad6fe560ab27f51dd6c5cd16f28418082424c/agent/consul/leader_connect_ca.go#L826

It is possible #7012 (#6886) mitigates this in the secondary DC.

I haven't yet written a test to reproduce the problem, but it seems like it should be possible to.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #11662
Branched from #11671 

Two other instance of this same bug were fixed a year+ ago in #6513 and  #7012, but this last one remained.

The test failed before the fix, and I extracted a new function for this since the logic is the same in all places, and the method name helps indicate the significance of this intermediate certificate.

We already have logic to fix the `SigningKeyID` on stored `CARoot` when the `CAMananger` is initialized, so we don't need to add more logic for it.

### CODE REVIEW

File: agent/consul/leader_connect_ca_test.go [hunk 1]
```diff
@@ -462,3 +464,62 @@ func TestCADelegateWithState_GenerateCASignRequest(t *testing.T) {
...
+
+	_, newRoot, err := s1.fsm.State().CARootActive(nil)
+	require.NoError(t, err)
+	require.Len(t, newRoot.IntermediateCerts, 2,
+		"expected one cross-sign cert and one local leaf sign cert")
+	require.NotEqual(t, origRoot.ID, newRoot.ID)
+
+	cert, err = connect.ParseCert(newRoot.LeafSigningCert())
+	require.NoError(t, err)
+	require.Equal(t, connect.HexString(cert.SubjectKeyId), newRoot.SigningKeyID)
```
Comment (dnephin) [inline agent/consul/leader_connect_ca_test.go:524]: This is the line that failed before this fix.

**Review by FFMMM — APPROVED** [review]
LGTM 📦 !

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/514121.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 0c7a2257ec7bccf4aee9f279c7589387fbb12026 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/514121)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 0c7a2257ec7bccf4aee9f279c7589387fbb12026 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/514121)
