### PR TITLE
Handle rules translation when coming from the JSON compat HCL

### LINKED ISSUE #5493: ACL migration doesn't correctly convert '_prefix' eligible items
#### Overview of the Issue

`consul acl translate-rules` and `consul acl policy create ... -from-token <legacy-token>` do not correctly translate ACL rules from pre-1.4 (1.3.1 ) to post-1.4 (1.4.2.); they fail to translate `node "foo"` to `node_prefix "foo"` etc

According to the [Migration Doc](https://www.consul.io/docs/guides/acl-migrate-tokens.html#rule-syntax-changes) regarding syntax changes; items like node should convert to node_prefix. 

From [Rule Specification doc](https://www.consul.io/docs/agent/acl-rules.html#rule-specification), you'll note the return looks like:

```
On success, the Policy is returned:

{
    "CreateIndex": 7,
    "Hash": "UMG6QEbV40Gs7Cgi6l/ZjYWUwRS0pIxxusFKyKOt8qI=",
    "ID": "5f423562-aca1-53c3-e121-cb0eb2ea1cd3",
    "ModifyIndex": 7,
    "Name": "my-app-policy",
    "Rules": "key \"\" { policy = \"read\" } key \"foo/\" { policy = \"write\" } key \"foo/private/\" { policy = \"deny\" } operator = \"read\""
}
```

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Have ACLs enable in legacy mode (say consul 1.3.1), upgrade to Consul >1.4, 

2. Find an existing ACL with node, session, service, key, etc: that should be translated to node_prefix, etc. 
<details>
  <summary>Example</summary>

```
curl -H "${creds}" localhost:8500/v1/acl/info/anonymous | jq .
[
  {
    "ID": "anonymous",
    "Name": "Anonymous Token",
    "Type": "client",
    "Rules": "{\"key\": {\"\": {\"policy\": \"read\"}, \"privatething1/\": {\"policy\": \"deny\"}, \"anapplication/private/\": {\"policy\": \"deny\"}, \"privatething2/\": {\"policy\": \"deny\"}}, \"session\": {\"\": {\"policy\": \"write\"}}, \"node\": {\"\": {\"policy\": \"read\"}}, \"agent\": {\"\": {\"policy\": \"read\"}}, \"service\": {\"\": {\"policy\": \"read\"}}, \"event\": {\"\": {\"policy\": \"read\"}}, \"query\": {\"\": {\"policy\": \"read\"}}}",
    "CreateIndex": 4,
    "ModifyIndex": 137
  }
]
```

</details>

3. Run `consul acl translate-rules` (note, same result from: `consul acl policy create -name "migrated-$id" -from-token $id --description ...`)

<details>
  <summary>Example</summary>

```
consul acl translate-rules -token-accessor anonymous
"key" "" {
  "policy" = "read"
}

"key" "privatething1/" {
  "policy" = "deny"
}

"key" "anapplication/private/" {
  "policy" = "deny"
}

"key" "privatething2/" {
  "policy" = "deny"
}

"session" "" {
  "policy" = "write"
}

"node" "" {
  "policy" = "read"
}

"agent" "" {
  "policy" = "read"
}

"service" "" {
  "policy" = "read"
}

"event" "" {
  "policy" = "read"
}

"query" "" {
  "policy" = "read"
}
```

</details>

4. Note that the ACLs under 1.4 are WRONG. They should be node_prefix, session_prefix, etc.

### Consul info for both Client and Server

<details>
  <summary>Server and Client info (this is a server)</summary>

```
$ consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = c97c712e
	version = 1.4.2
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.207.70.59:8300
	server = true
raft:
	applied_index = 33604
	commit_index = 33604
	fsm_pending = 0
	last_contact = 28.86653ms
	last_log_index = 33604
	last_log_term = 322
	last_snapshot_index = 32776
	last_snapshot_term = 322
	latest_configuration = [{Suffrage:Voter ID:ff71ee77-3719-bb4d-3455-e16406a7d8c3 Address:10.207.70.59:8300} {Suffrage:Voter ID:f1190421-379d-c1a0-80a0-e6d41d9f6c02 Address:10.207.70.51:8300}]
	latest_configuration_index = 1820
	num_peers = 1
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 322
runtime:
	arch = amd64
	cpu_count = 2
	goroutines = 87
	max_procs = 2
	os = linux
	version = go1.11.4
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 43
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 39
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 34
	members = 2
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 18.04 Bionic; x86_64.

### Code References
All the tests in [policy_test.go](https://github.com/hashicorp/consul/blob/master/acl/policy_test.go) presently pass. But I believe this is because those tests take legit JSON input, but NOT the input that would be created/returned by the Rules field of an ACL info call: 

```
{
    "CreateIndex": 7,
    "Hash": "UMG6QEbV40Gs7Cgi6l/ZjYWUwRS0pIxxusFKyKOt8qI=",
    "ID": "5f423562-aca1-53c3-e121-cb0eb2ea1cd3",
    "ModifyIndex": 7,
    "Name": "my-app-policy",
    "Rules": "key \"\" { policy = \"read\" } key \"foo/\" { policy = \"write\" } key \"foo/private/\" { policy = \"deny\" } operator = \"read\""
}
```

When running the output of Rules through: [the policy code translating](https://github.com/hashicorp/consul/blob/master/acl/policy.go#L813), but add in some debugs to make it:

```
		switch n := node.(type) {
		case *ast.ObjectKey:
			fmt.Printf("Node: '%v'\n", n.Token.Text)
			switch n.Token.Text {
			case "agent":
				n.Token.Text = "agent_prefix"
			case "key":
				n.Token.Text = "key_prefix"
			case "node":
				n.Token.Text = "node_prefix"
			case "query":
				n.Token.Text = "query_prefix"
			case "service":
				n.Token.Text = "service_prefix"
			case "session":
				n.Token.Text = "session_prefix"
			case "event":
				n.Token.Text = "event_prefix"
			default:
				fmt.Printf("Didnt match anything: '%s'\n", n.Token.Text)
			}
		}
```

Output:
```
Node: '"session"'
Didnt match anything: '"session"'
```

So when we look at the token `"session"` (with quotes still there) that never matches in the case statement (looking for `session` (no quotes)) we essentially pass though every single case and don't translate anything.

### PR DESCRIPTION
**Pull request by mkeeler**
We were not handling some object keys when they were strings instead of identifiers. Now both are handled.

Fixes #5493

### CODE REVIEW

File: acl/policy.go [hunk 1]
```diff
@@ -819,7 +821,17 @@ func TranslateLegacyRules(policyBytes []byte) ([]byte, error) {
 	rewritten := ast.Walk(parsed, func(node ast.Node) (ast.Node, bool) {
```
Comment (rboyer) [inline acl/policy.go]: It occurred to me that this walk is too general. If someone is unfortunate to have a segment value that happens to match one of these top level resource names like `key` or `session` it will mangle the translated rules:
```
consul (bugfix/5493)$ git diff
diff --git a/acl/policy_test.go b/acl/policy_test.go
index 8f5a100a8..e9191acb6 100644
--- a/acl/policy_test.go
+++ b/acl/policy_test.go
@@ -1422,6 +1422,9 @@ func TestRulesTranslate_GH5493(t *testing.T) {
                },
                "privatething2/": {
                        "policy": "deny"
+               },
+               "key": {
+                       "policy": "deny"
                }
        },
        "session": {
@@ -1472,6 +1475,10 @@ key_prefix "privatething2/" {
   policy = "deny"
 }
 
+key_prefix "key/" {
+  policy = "deny"
+}
+
 session_prefix "" {
   policy = "write"
 }

consul (bugfix/5493)$ go test ./acl -run TestRulesTranslate
--- FAIL: TestRulesTranslate_GH5493 (0.00s)
    require.go:157: 
        	Error Trace:	policy_test.go:1508
        	Error:      	Not equal: 
        	            	expected: "key_prefix \"\" {\n  policy = \"read\"\n}\n\nkey_prefix \"privatething1/\" {\n  policy = \"deny\"\n}\n\nkey_prefix \"anapplication/private/\" {\n  policy = \"deny\"\n}\n\nkey_prefix \"privatething2/\" {\n  policy = \"deny\"\n}\n\nkey_prefix \"key/\" {\n  policy = \"deny\"\n}\n\nsession_prefix \"\" {\n  policy = \"write\"\n}\n\nnode_prefix \"\" {\n  policy = \"read\"\n}\n\nagent_prefix \"\" {\n  policy = \"read\"\n}\n\nservice_prefix \"\" {\n  policy = \"read\"\n}\n\nevent_prefix \"\" {\n  policy = \"read\"\n}\n\nquery_prefix \"\" {\n  policy = \"read\"\n}"
        	            	actual  : "key_prefix \"\" {\n  policy = \"read\"\n}\n\nkey_prefix \"privatething1/\" {\n  policy = \"deny\"\n}\n\nkey_prefix \"anapplication/private/\" {\n  policy = \"deny\"\n}\n\nkey_prefix \"privatething2/\" {\n  policy = \"deny\"\n}\n\nkey_prefix key_prefix {\n  policy = \"deny\"\n}\n\nsession_prefix \"\" {\n  policy = \"write\"\n}\n\nnode_prefix \"\" {\n  policy = \"read\"\n}\n\nagent_prefix \"\" {\n  policy = \"read\"\n}\n\nservice_prefix \"\" {\n  policy = \"read\"\n}\n\nevent_prefix \"\" {\n  policy = \"read\"\n}\n\nquery_prefix \"\" {\n  policy = \"read\"\n}"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -16,3 +16,3 @@
        	            	 
        	            	-key_prefix "key/" {
        	            	+key_prefix key_prefix {
        	            	   policy = "deny"
        	Test:       	TestRulesTranslate_GH5493
FAIL
FAIL	github.com/hashicorp/consul/acl	0.002s
```

Comment (mkeeler) [reply acl/policy.go]: I think this should now be taken care of.

An ObjectItem can have a list of keys so

```
key "key" {
   policy = "read"
```

and

```
{
   "key" : {
      "key": {
         "policy": "read"
      }
   }
}
```
end up using a single ObjectItem with a key length of 2. Whenever we encounter one of these we only ever modify the first key which should prevent modifying the resource segment.
