### PR TITLE
Atomic writes for persisting service/check state

### LINKED ISSUE #1221: unexpected end of JSON input after server crash
After rebooting a server running Consul agent (in server mode), attempting to restart Consul's agent with its previously used parameters throws these errors:
==> Starting Consul agent...
==> Error starting agent: unexpected end of JSON input

Looking in the directories: <consul_data_dir>/checks & <consul_data_dir>/services, I see several files with size 0.

The server's reboot occurred at the same time that we registered health checks to Consul, so I believe that the files are corrupt (empty actually) because they are not being written atomically.
1. Can the files written to the directories mentioned be written atomically?
2. As a workaround, is it safe to delete these directories and restart Consul? It seems to work.

Thanks,
Amir

### PR DESCRIPTION
**Pull request by kyhavlov**
Modified #2240 to call file.Sync() when persisting services/checks. We don't want to do it for check state though because that happens a lot more frequently, so instead just handle the case where we load a malformed file.

Fixes #1221

### CODE REVIEW

File: command/agent/agent.go [hunk 1]
```diff
@@ -1092,8 +1096,15 @@ func (a *Agent) persistCheckState(check *CheckTTL, status, output string) error
 
 	// Write the state to the file
 	file := filepath.Join(dir, checkIDHash(check.CheckID))
-	if err := ioutil.WriteFile(file, buf, 0600); err != nil {
-		return fmt.Errorf("failed writing file %q: %s", file, err)
+
+	// Create temp file in same dir, to make more likely atomic
```
Comment (slackpad) [inline command/agent/agent.go]: Let's add a comment here about why we aren't calling `writeFileAtomic()`.

File: command/agent/agent.go [hunk 2]
```diff
@@ -733,6 +714,29 @@ func (a *Agent) purgeCheck(checkID types.CheckID) error {
...
+func writeFileAtomic(path string, contents []byte) error {
+	tempPath := path + ".tmp"
+	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
+		return err
+	}
+	fh, err := os.OpenFile(tempPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
+	if err != nil {
+		return err
+	}
+	if _, err := fh.Write(contents); err != nil {
```
Comment (slackpad) [inline command/agent/agent.go]: Oh that's a good point. We should probably even do a best-effort delete on the temp file if something goes wrong (do a deferred fn that we disarm at the end). We originally used a file name that was 1:1 with the service name but changed that to fix a race condition.

**Comment by a86c6f7964** [comment]
just as an fyi. possibly related to this change, recently I just got 'Error starting agent: failed decoding service file "/var/lib/consul/services/bef2a566bb452d18967ed9d7f574f22a-ad21449f-29ac-c4e0-f185-73bd4791a2be.tmp": unexpected end of JSON input'

the name seems extra long.
