### PR TITLE
snapshot: read meta.json correctly.

### LINKED ISSUE #4452: consul snapshot save fails to verify snapshot
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

trying to do consul snapshot save <file_name> from 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1.just a consul cluster on 1.2.1
 

### Consul info for both Client and Server

consul info
agent:
	check_monitors = 0
	check_ttls = 3
	checks = 3
	services = 4
build:
	prerelease =
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.200.4.70:8300
	server = true
raft:
	applied_index = 375494809
	commit_index = 375494809
	fsm_pending = 0
	last_contact = 0
	last_log_index = 375494809
	last_log_term = 68349
	last_snapshot_index = 375491206
	last_snapshot_term = 68349
	latest_configuration = [{Suffrage:Voter ID:673e0ff3-815a-4c56-0b5b-1ccf17d7a7d1 Address:10.200.1.154:8300} {Suffrage:Voter ID:082aa7eb-3692-0d7b-b4fe-7efd1ab5b42e Address:10.200.4.70:8300} {Suffrage:Voter ID:1b0d7168-4d6c-0b73-b8e9-c805223a6428 Address:10.200.10.157:8300}]
	latest_configuration_index = 374999275
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 68349
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 15765
	max_procs = 4
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 4155
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 289
	member_time = 1462570
	members = 1456
	query_queue = 0
	query_time = 245
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 3321
	members = 3
	query_queue = 0
	query_time = 1
output from client 'consul info' command here
```

</details>

the error im getting is:
:~# consul snapshot save consul-us-$(date +%Y-%m-%d).snap
Error verifying snapshot file: failed to read snapshot file: failed checking integrity of snapshot: hash check failed for "meta.json"


<details>
  <summary>Server info</summary>


### Operating system and Environment details
ubuntu14.04

### PR DESCRIPTION
**Pull request by i0rek**
Fixes #4452.

I basically did what @maf23 suggested, and made sure we read the file entirely. Since we don't need the json decoder in this case I read the file first and unmarshal afterwards. Apparently `ReadAll` reads everything in contrast to `Decode`. I added a test with the file provided by @maf23 which couldn't be verified before even though it is a valid snapshot. This will prevent us from changing the decoding in a way that runs into that same problem again.
I do think this is a very strange bug btw.

### CODE REVIEW

File: snapshot/archive.go [hunk 1]
```diff
@@ -193,8 +194,11 @@ func read(in io.Reader, metadata *raft.SnapshotMeta, snap io.Writer) error {
 
 		switch hdr.Name {
 		case "meta.json":
-			dec := json.NewDecoder(io.TeeReader(archive, metaHash))
-			if err := dec.Decode(&metadata); err != nil {
+			buf, err := ioutil.ReadAll(io.TeeReader(archive, metaHash))
```
Comment (banks) [inline snapshot/archive.go]: I think it's worth commenting on why this is needed. The root cause seems to be something like:

```
// json.Decode will stop reading as soon as the initial JSON element (the object) is closed 
// (i.e. at the closing brace) which means the final newline, if any, is not read and so is not 
// delivered to `metaHash`. This means that the hash calculated is not the same as the
// one in SHA256SUMS which was calculated over the raw bytes in the file. By explicitly 
// reading the whole thing first we ensure that we calculate the hash over the exact
// same bytes regardless of whitespace.
```

Comment (i0rek) [reply snapshot/archive.go]: Good point, I will add a comment!
