### PR TITLE
connect: use stronger validation that ingress gateways have compatible protocols defined for their upstreams

### LINKED ISSUE #8466: Consul crashed with error "panic: unexpected first node in discovery chain using protocol"
I want to use canary deployment with ingress-gateway, refer to the following sample
https://github.com/nicholasjackson/demo-consul-service-mesh

## Reproduction Steps
+ step-1
```
docker-compose up -d
```

+ step-2 Deploy and start the ingress gateway
```
curl localhost:8500/v1/config -XPUT -d @l7_config/ingress_gateway.json
docker-compose -f docker-compose-ingress.yml up -d
```
+ step-3 deregister payments-1-v1
```
curl --request PUT localhost:8500/v1/agent/service/deregister/payments-1-v1-sidecar-proxy
curl --request PUT localhost:8500/v1/agent/service/deregister/payments-1-v1
docker-compose stop payments_1_v1
```

+ step-4
```
curl localhost:8500/v1/config -XPUT -d @l7_config/payments_service_defaults.json
```
+ step-5
```
curl localhost:8500/v1/config -XPUT -d @l7_config/payments_service_resolver_1.json
```
+ step-6
```
curl localhost:8500/v1/config -XPUT -d @l7_config/payments_service_router_1.json
```
After executing step-6, consul-server crashes with the following error:
```
consul_server_1        | panic: unexpected first node in discovery chain using protocol="tcp": router
consul_server_1        |
consul_server_1        | goroutine 397 [running]:
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).makeUpstreamListenerForDiscoveryChain(0xc000528ea0, 0xc00087b300, 0xc0005fc650, 0x9, 0xc000e00460,                                                                   0xc0005eb180, 0x0, 0x2b75c00, 0x1, 0x15, ...)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:780 +0xbab
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).makeIngressGatewayListeners(0xc000528ea0, 0xc0005fc650, 0x9, 0xc0005eb180, 0x1, 0xc000cf6c90, 0x0,                                                                   0x1, 0x0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:301 +0x413
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).listenersFromSnapshotGateway(0xc000528ea0, 0xc0005eb180, 0x0, 0x0, 0xe, 0x1, 0xc0009768c0, 0xc0008                                                                  7b7f0, 0x50bf98)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:261 +0x8ee
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).listenersFromSnapshot(0xc000528ea0, 0xc0005eb180, 0x0, 0x0, 0xc0007211a0, 0x3232d6f, 0xe, 0xc0003e                                                                  b3f8, 0xc000721201)
consul_server_1        |        /home/circleci/project/consul/agent/xds/listeners.go:49 +0x291
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*xDSType).SendIfNew(0xc0000a1630, 0xc0005eb180, 0x6, 0xc00087b930, 0xc00087bb50, 0x0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/server.go:408 +0xaf
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).process(0xc000528ea0, 0x388dc00, 0xc0005a7de0, 0xc0007a7e60, 0x0, 0x0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/server.go:369 +0x832
consul_server_1        | github.com/hashicorp/consul/agent/xds.(*Server).StreamAggregatedResources(0xc000528ea0, 0x388dc00, 0xc0005a7de0, 0x382c680, 0xc000528ea0)
consul_server_1        |        /home/circleci/project/consul/agent/xds/server.go:171 +0xc5
consul_server_1        | github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x319c3e0, 0xc0005                                                                  28ea0, 0x3883a60, 0xc0009eac00, 0x54519f8, 0xc0005afc00)
consul_server_1        |        /go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.8.0/envoy/service/discovery/v2/ads.pb.go:197 +0xad
consul_server_1        | google.golang.org/grpc.(*Server).processStreamingRPC(0xc0002a06e0, 0x3893e40, 0xc00054e300, 0xc0005afc00, 0xc0005aa060, 0x53f0360, 0x0, 0x0, 0x0)
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1199 +0xd21
consul_server_1        | google.golang.org/grpc.(*Server).handleStream(0xc0002a06e0, 0x3893e40, 0xc00054e300, 0xc0005afc00, 0x0)
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1279 +0xcd6
consul_server_1        | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000718d00, 0xc0002a06e0, 0x3893e40, 0xc00054e300, 0xc0005afc00)
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
consul_server_1        | created by google.golang.org/grpc.(*Server).serveStreams.func1
consul_server_1        |        /go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

##  Operating system and Environment details
OS: Centos 7.7
consul: 1.8.0
docker: 19.03.5
docker-compose: 1.25.0

## my config

docker-compose.yml
```
version: "3.3"
services:

  consul_server_1:
    image: nexus.xxx.proxy:8442/consul:1.8.0
    container_name: consul_server_1
    command: ["consul","agent", "-server", "-bootstrap", "-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - "8500:8500"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  payments_1_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/fake-service:v0.7.8
    container_name: payments_1_v1
    environment:
      NAME: payments-1-v1
      MESSAGE: "PAYMENTS 1 V1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  payments_1_proxy_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/consul-envoy:v1.8.0-v1.14.2
    container_name: payments_1_proxy_v1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_1_v1.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-1-v1"]
    network_mode: "service:payments_1_v1"

  payments_2_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/fake-service:v0.7.8
    container_name: payments_2_v1
    environment:
      NAME: payments-2-v1
      MESSAGE: "PAYMENTS 2 V1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  payments_2_proxy_v1:
    image: nexus.xxx.proxy:8442/nicholasjackson/consul-envoy:v1.8.0-v1.14.2
    container_name: payments_2_proxy_v1
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_2_v1.hcl
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-2-v1"]
    network_mode: "service:payments_2_v1"

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
```

ingress_gateway.json
```
{
    "kind": "ingress-gateway",
    "name": "ingress-service",
    "listeners": [
        {
            "port": 8080,
            "protocol": "tcp",
            "services": [
                {
                    "name": "payments"
                }
            ]
        }
    ]
}
```

docker-compose-ingress.yml
```
version: "3.3"
services:

  ingress_proxy:
    image: nexus.xxx.proxy:8442/nicholasjackson/consul-envoy:v1.8.0-v1.14.2
    container_name: ingress_proxy
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      #      CENTRAL_CONFIG: "/central_config/api_service_defaults.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    ports:
      - "8080:8080"
      - "9092:8888"
    command: consul connect envoy -gateway=ingress -register -service ingress-service -address 10.5.0.10:8888

    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    external:
      name: service-mesh-sample_vpcbr
```

payments_service_defaults.json
```
{
    "kind": "service-defaults",
    "name": "payments",
    "protocol": "http"
}
```

payments_service_resolver_1.json
```
{
    "kind": "service-resolver",
    "name": "payments",
    "default_subset": "v1",
    "subsets": {
        "v1": {
            "filter": "Service.Meta.version == 1"
        },
        "v2": {
            "filter": "Service.Meta.version == 2"
        },
        "payments-1-v2": {
            "filter": "Service.Meta.sid == 1 and Service.Meta.version == 2"
        }
    }
}
```

payments_service_router_1.json
```
{
    "kind": "service-router",
    "name": "payments",
    "routes": [
      {
        "match": {
            "http": {
                "header": [
                    {
                    "name": "testgroup",
                    "exact": "b"
                    }
                ]
          }
        },
        "destination": {
            "service": "payments",
            "service_subset": "payments-1-v2"
        }
      },
      {
        "match": {
            "http": {
                "path_prefix": "/"
          }
        },
    
        "destination": {
            "service": "payments",
            "service_subset": "v1"
        }
      }
    ]
}
```

### PR DESCRIPTION
**Pull request by rboyer**
Fixes #8466

Since Consul 1.8.0 there was a bug in how ingress gateway protocol
compatibility was enforced. At the point in time that an ingress-gateway
config entry was modified the discovery chain for each upstream was
checked to ensure the ingress gateway protocol matched. Unfortunately
future modifications of other config entries were not validated against
existing ingress-gateway definitions, such as:

1. create tcp ingress-gateway pointing to 'api' (ok)
2. create service-defaults for 'api' setting protocol=http (worked, but not ok)
3. create service-splitter or service-router for 'api' (worked, but caused an agent panic)

If you were to do these in a different order, it would fail without a
crash:

1. create service-defaults for 'api' setting protocol=http (ok)
2. create service-splitter or service-router for 'api' (ok)
3. create tcp ingress-gateway pointing to 'api' (fail with message about
   protocol mismatch)

This PR introduces the missing validation. The two new behaviors are:

1. create tcp ingress-gateway pointing to 'api' (ok)
2. (NEW) create service-defaults for 'api' setting protocol=http ("ok" for back compat)
3. (NEW) create service-splitter or service-router for 'api' (fail with
   message about protocol mismatch)

In consideration for any existing users that may be inadvertently be
falling into item (2) above, that is now officiall a valid configuration
to be in. For anyone falling into item (3) above while you cannot use
the API to manufacture that scenario anymore, anyone that has old (now
bad) data will still be able to have the agent use them just enough to
generate a new agent/proxycfg error message rather than a panic.
Unfortunately we just don't have enough information to properly fix the
config entries.

### CODE REVIEW

**Comment by rboyer** [comment]
Note I also flipped any `panic` instances in the `agent/xds` package to just return errors now. Only one of these mattered for #8466, but I figured it made sense to just fix them all.

File: agent/xds/listeners.go [hunk 1]
```diff
@@ -780,9 +780,9 @@ func (s *Server) makeUpstreamListenerForDiscoveryChain(
 	} else if cfg.Protocol == "tcp" {
 		startNode := chain.Nodes[chain.StartNode]
 		if startNode == nil {
-			panic("missing first node in compiled discovery chain for: " + chain.ServiceName)
+			return nil, fmt.Errorf("missing first node in compiled discovery chain for: %s", chain.ServiceName)
 		} else if startNode.Type != structs.DiscoveryGraphNodeTypeResolver {
-			panic(fmt.Sprintf("unexpected first node in discovery chain using protocol=%q: %s", cfg.Protocol, startNode.Type))
```
Comment (rboyer) [inline agent/xds/listeners.go:785]: This is the main place the linked issue was getting its panic from.

File: agent/structs/config_entry_gateways.go [hunk 2]
```diff
@@ -203,6 +204,34 @@ func validateHost(tlsEnabled bool, host string) error {
 	return nil
 }
 
+func (e *IngressGatewayConfigEntry) ListRelatedServices() []ServiceID {
```
Comment (rboyer) [inline agent/structs/config_entry_gateways.go:207]: FYI this is the same mechanism that `service-resolver`, `service-splitter`, and `service-router` use during graph validation. It is indexed on the config entry memdb table and named `"link"` (which is only used in one place).

File: agent/consul/state/config_entry.go [hunk 3]
```diff
@@ -822,48 +918,6 @@ func configEntryWithOverridesTxn(
 	return configEntryTxn(tx, ws, kind, name, entMeta)
 }
 
-func validateProposedIngressProtocolsInServiceGraph(
```
Comment (rboyer) [inline agent/consul/state/config_entry.go:825]: No longer necessary as the general graph validation handles ingress now.

File: agent/consul/state/config_entry.go [hunk 4]
```diff
@@ -413,32 +444,93 @@ func (s *Store) validateProposedConfigEntryInServiceGraph(
...
+
+				svcProto := svcProtocols[svcID]
+
+				if svcProto != expectedProto {
+					// The only time an ingress gateway and its upstreams can
+					// have differing protocols is when:
+					//
+					// 1. ingress is tcp and the target is not-tcp
+					//    AND
+					// 2. the disco chain has a resolver as the top node
```
Comment (crhino) [inline agent/consul/state/config_entry.go:504]: From testing this out, I am also able to generate a scenario where ingress is http and the target is not-http:
1. `IG http -> svc http`
2. svc has no L7 config defined
3. Update service-default to `tcp`
4. Config entry is written, `IG http -> svc tcp`

I don't think that is necessarily a bad behavior, but worth thinking about explicitly.

File: agent/structs/config_entry_gateways.go (hunk 2 above)
Comment (crhino) [reply agent/structs/config_entry_gateways.go:207]: I would probably at least add a comment here that specifies that it will not return services that are matched by the wildcard specifier. That could be potentially confusing.

**Comment by crhino** [comment]
💯 on updating all of the other places that also panic in the `xds` package!

Testing this out and looking through the code everything seems nice to me, I just had one comment about the potential of allowing `IG http -> svc tcp` targets.

File: agent/consul/state/config_entry.go (hunk 4 above)
Comment (rboyer) [reply agent/consul/state/config_entry.go:504]: Ah right I think this was not my intent. Let me stare at this part a bit more.

Comment (rboyer) [reply agent/consul/state/config_entry.go:504]: Fixed with a test.

File: agent/structs/config_entry_gateways.go (hunk 2 above)
Comment (rboyer) [reply agent/structs/config_entry_gateways.go:207]: done
