### PR TITLE
config: drop advertise_addrs

### LINKED ISSUE #3516: advertise_addrs in the config doesn't work
When investigating https://github.com/hashicorp/consul/issues/3436, I found that in 0.9.3 we expect the [advertise_addrs](https://www.consul.io/docs/agent/options.html#advertise_addrs) config option to include host and port, and it also incorrectly wants the RPC port to be an address. If the config sets all this, it uses the  rpc port from inside advertise_addrs, but ignores the serf_lan/serf_wan ports. 

In the 1.0 beta branch, it throws an error when any sub elements in advertise_addrs contain both an IP and port, and only accepts IPs. So people using advertise_addrs in 0.9.3's configs will break during an upgrade (albeit a partially working thing)

Discussed with @slackpad and it definitely looks like advertise_addrs never worked properly. We should remove support for it (and make sure one can override both the advertise address and the serf lan/wan ports via other config options), and update the documentation to remove references to it. 

Here's the config file I used for testing

```
 {
"bind_addr": "127.0.0.1",
"advertise_addr":"127.0.0.1",
"node_id":"ac5ec7af-5238-4c18-988a-0385d0a0f477",
"data_dir":"/tmp/consultest",
"ports":        {
                "https":-1,
                "dns":-1,
                "serf_lan":9301 //if this line is removed, it uses the default port and not 9302 though its configured according to what the documentation says
        },
"advertise_addrs": {"serf_lan": "127.0.0.1:9302", "serf_wan": "127.0.0.1:9302", "rpc": "127.0.0.1:9303"},
"datacenter":"mydc",
"ui":true,
"server":true
}
```

### PR DESCRIPTION
**Pull request by magiconair**
This patch removes the `advertise_addrs` config option since that was not working as expected before 1.0.

Fixes #3516

### CODE REVIEW

File: agent/config/builder.go [hunk 1]
```diff
@@ -371,9 +371,9 @@ func (b *Builder) Build() (rt RuntimeConfig, err error) {
 	// derive other advertise addresses from the advertise address
 	advertiseAddrLAN := b.makeIPAddr(b.expandFirstIP("advertise_addr", c.AdvertiseAddrLAN), advertiseAddr)
 	advertiseAddrWAN := b.makeIPAddr(b.expandFirstIP("advertise_addr_wan", c.AdvertiseAddrWAN), advertiseAddrLAN)
-	rpcAdvertiseAddr := b.makeTCPAddr(b.expandFirstIP("advertise_addresses.rpc", c.AdvertiseAddrs.RPC), advertiseAddrLAN, serverPort)
-	serfAdvertiseAddrLAN := b.makeTCPAddr(b.expandFirstIP("advertise_addresses.serf_lan", c.AdvertiseAddrs.SerfLAN), advertiseAddrLAN, serfPortLAN)
-	serfAdvertiseAddrWAN := b.makeTCPAddr(b.expandFirstIP("advertise_addresses.serf_wan", c.AdvertiseAddrs.SerfWAN), advertiseAddrWAN, serfPortWAN)
+	rpcAdvertiseAddr := &net.TCPAddr{IP: advertiseAddrLAN.IP, Port: serverPort}
+	serfAdvertiseAddrLAN := &net.TCPAddr{IP: advertiseAddrLAN.IP, Port: serfPortLAN}
+	serfAdvertiseAddrWAN := &net.TCPAddr{IP: advertiseAddrWAN.IP, Port: serfPortWAN}
```
Comment (preetapan) [inline agent/config/builder.go]: If am right, we still need to reconcile this part - https://github.com/hashicorp/consul/blob/bfa70a10cac3876960cbe0e3d7a7bb482fe2876a/agent/agent.go#L606 

In the above, when setting up memberlist we use `config.SerfPortLAN` and `config.SerfPortWAN` as the port memberlist actually uses to bind to. Since you've already ensured that serfAdvertiseAddrLAN/WAN has the right port, its less confusing to use that directly in that line, instead of assuming that serfPortLAN and serfAdvertiseAddrLAN.Port will end up being the same value because of these lines.

Comment (magiconair) [reply agent/config/builder.go]: I thought I had already fixed this. The `SerfPortLAN/WAN` fields are somewhat leftovers from when we were getting things to work and the addresses weren't `*net.TCPAddr` fields yet. They are used in `command/agent.go` and `agent/agent_endpoint_test.go`

Comment (magiconair) [reply agent/config/builder.go]: I've changed the code in `agent/agent.go` to use the ports from the derived addresses. Getting rid of the other port values means to get rid of the notion that there is only one port per protocol.

Comment (preetapan) [reply agent/config/builder.go]: I

Comment (preetapan) [reply agent/config/builder.go]: would be great if we could remove serfportlan/wan from the runtime config entirely but that might be even more invasive, feel free to discard this suggestion if that's not feasible

Comment (magiconair) [reply agent/config/builder.go]: I've started and stopped this a couple of times. Lets do this in a separate commit. There is nothing stopping us to do this at a later stage.
