### PR TITLE
Fixes panic in tombstone GC.

### LINKED ISSUE #2087: Panic in tombstone_gc.go
If you have a question, please direct it to the
[consul mailing list](https://www.consul.io/community.html) if it hasn't been
addressed in either the [FAQ](https://www.consul.io/docs/faq.html) or in one
of the [Consul Guides](https://www.consul.io/docs/guides/index.html).

When filing a bug, please include the following:
### `consul version` for both Client and Server

Client: `Consul v0.6.4`
Server: `Consul v0.6.4`
### `consul info` for both Client and Server

Client:

```
Vault 0.5.2 - internal consul client.
```

Server:

```
agent:
    check_monitors = 0
    check_ttls = 1
    checks = 1
    services = 2
build:
    prerelease =
    revision = 26a0ef8c
    version = 0.6.4
consul:
    bootstrap = false
    known_datacenters = 1
    leader = true
    server = true
raft:
    applied_index = 2774
    commit_index = 2774
    fsm_pending = 0
    last_contact = 0
    last_log_index = 2774
    last_log_term = 17
    last_snapshot_index = 0
    last_snapshot_term = 0
    num_peers = 3
    state = Leader
    term = 17
runtime:
    arch = amd64
    cpu_count = 4
    goroutines = 80
    max_procs = 4
    os = linux
    version = go1.6
serf_lan:
    encrypted = true
    event_queue = 0
    event_time = 12
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 2
    members = 3
    query_queue = 0
    query_time = 1
serf_wan:
    encrypted = true
    event_queue = 0
    event_time = 1
    failed = 0
    intent_queue = 0
    left = 0
    member_time = 1
    members = 1
    query_queue = 0
    query_time = 1
```
### Operating system and Environment details

OS X `10.11.5 (15F34)`
Docker Version `1.11.1-beta13.1 (build: 8193)`
Image: `library/consul:v0.6.4 7c41a9d97d38`
### Description of the Issue (and unexpected/desired result)

Panic on one node out of a 3-node cluster. All nodes are running locally in Docker using the official image. The networking errors may be due to machine sleeping at one point.
### Reproduction steps

None at this time.
### Log Fragments or Link to [gist](https://gist.github.com/)

```
consul0    |     2016/06/02 17:38:47 [WARN] raft: Failed to contact quorum of nodes, stepping down
consul0    |     2016/06/02 17:38:47 [INFO] raft: Node at 172.18.0.2:8300 [Follower] entering Follower state
consul0    |     2016/06/02 17:38:47 [INFO] consul: cluster leadership lost
consul0    |     2016/06/02 17:38:47 [WARN] agent: Check 'vault-sealed-check' missed TTL, is now critical
consul0    |     2016/06/02 17:38:47 [ERR] agent: failed to sync changes: No cluster leader
consul0    |     2016/06/02 17:38:47 [ERR] agent: failed to sync changes: No cluster leader
consul0    |     2016/06/02 17:38:47 [INFO] raft: aborting pipeline replication to peer 172.18.0.4:8300
consul0    |     2016/06/02 17:38:47 [ERR] agent: coordinate update error: No cluster leader
consul0    |     2016/06/02 17:38:47 [INFO] raft: aborting pipeline replication to peer 172.18.0.3:8300
consul0    |     2016/06/02 17:38:47 [ERR] http: Request GET /v1/kv/vault/core/lock?index=1274&token=<hidden>&wait=15000ms, error: No cluster leader from=172.18.0.6:58450
consul0    |     2016/06/02 17:38:47 [ERR] http: Request PUT /v1/session/destroy/2ac34feb-989f-bc05-ec93-618106445b19?token=<hidden>, error: No cluster leader from=172.18.0.6:58456
consul0    | panic: runtime error: invalid memory address or nil pointer dereference
consul0    | [signal 0xb code=0x1 addr=0x0 pc=0x73a459]
consul0    |
consul0    | goroutine 944 [running]:
consul0    | panic(0xcb9ec0, 0xc820010070)
consul0    |     /goroot/src/runtime/panic.go:464 +0x3e6
consul0    | github.com/hashicorp/consul/consul/state.(*TombstoneGC).expireTime(0xc8201eda10, 0xecee26616, 0x0, 0x12cce40)
consul0    |     /gopath/src/github.com/hashicorp/consul/consul/state/tombstone_gc.go:149 +0x119
consul0    | github.com/hashicorp/consul/consul/state.(*TombstoneGC).Hint.func1()
consul0    |     /gopath/src/github.com/hashicorp/consul/consul/state/tombstone_gc.go:120 +0x3f
consul0    | created by time.goFunc
consul0    |     /goroot/src/time/sleep.go:129 +0x3a
```

### PR DESCRIPTION
**Pull request by slackpad**
This fixes #2087 and closes #2582.

### CODE REVIEW

File: consul/state/tombstone_gc_test.go [hunk 1]
```diff
@@ -102,3 +102,18 @@ func TestTombstoneGC_Expire(t *testing.T) {
...
+
+func TestTombstoneGC_TimerAfterShutdown(t *testing.T) {
+	ttl := 2 * time.Microsecond
+	gran := 1 * time.Microsecond
+	gc, err := NewTombstoneGC(ttl, gran)
+	if err != nil {
+		t.Fatalf("err: %v", err)
+	}
+
+	for i := 0; i < 1000; i++ {
```
Comment (magiconair) [inline consul/state/tombstone_gc_test.go]: What does this test? Why `1000`? What is the failure condition?

File: consul/state/tombstone_gc.go [hunk 2]
```diff
@@ -6,49 +6,52 @@ import (
...
+	// expires maps the time of expiration to the highest tombstone value
+	// that should be expired.
 	expires map[time.Time]*expireInterval
 
-	// expireCh is used to stream expiration
+	// expireCh is used to stream expiration to the leader for processing.
 	expireCh chan uint64
 
-	// lock is used to ensure safe access to all the fields
+	// lock is used to ensure safe access to all the fields.
```
Comment (magiconair) [inline consul/state/tombstone_gc.go]: If `lock` guards everything then you can embed `sync.Mutex`

Comment (slackpad) [inline consul/state/tombstone_gc.go]: Done.

File: consul/state/tombstone_gc_test.go (hunk 1 above)
Comment (slackpad) [inline consul/state/tombstone_gc_test.go]: This would repro the panic, but probably isn't useful as an ongoing unit test since it's not super deterministic (I had to push it up to 1000 to get it to fail). I'll remove it.

**Comment by magiconair** [comment]
I think you can also drop the `enabled: false` from the constructor func but other than that it LGTM.
