### PR TITLE
Kill check processes after the timeout is reached

### LINKED ISSUE #3565: Script checks can overlap
To my surprise Consul runs script [checks](https://www.consul.io/docs/agent/checks.html) in an overlapping fashion instead of serially.

This can lead to lots of processes and memory leakage if the script check is short or the `timeout` is long.

It also means that an older script check can overwrite the result written by a younger script check.

For example, assume you put `date` into the script check. Then, it can theoretically happen that the date output captured by the script and show time going backwards (for example, if the first `date` was CPU-scheduled unluckily).

I would have assumed that consul runs no more than 1 instance of a script check at any given time.

At least not unless some special flag is set.

### `consul version` for both Client and Server
Client: irrelevant
Server: `Consul v0.9.3`

### `consul info` for both Client and Server
Client: irrelevant

Server:
```
# consul info
agent:
	check_monitors = 1
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease = 
	revision = 
	version = 0.9.3
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.0.0.2:8300
	server = true
raft:
	applied_index = 95568
	commit_index = 95568
	fsm_pending = 0
	last_contact = 0
	last_log_index = 95568
	last_log_term = 495
	last_snapshot_index = 90278
	last_snapshot_term = 479
	latest_configuration = [{Suffrage:Voter ID:10.0.0.3:8300 Address:10.0.0.3:8300} {Suffrage:Voter ID:10.0.0.1:8300 Address:10.0.0.1:8300} {Suffrage:Voter ID:10.0.0.2:8300 Address:10.0.0.2:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 2
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 495
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 231
	max_procs = 1
	os = linux
	version = go1.9
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 165
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 468
	members = 5
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 231
	members = 3
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

NixOS

### Description of the Issue (and unexpected/desired result)

Consul runs script checks in an overlapping fashion instead of serially.

### Reproduction steps

Define a check with `interval` `1s`, make it `sleep 10` seconds. Observe processes in `ps` or `htop`.

### PR DESCRIPTION
**Pull request by kyhavlov**
Kill the subprocess spawned by a script check once the timeout is reached. Previously Consul just marked the check critical and left the subprocess around.

Fixes #3565.

### CODE REVIEW

File: agent/check.go [hunk 1]
```diff
@@ -128,19 +128,27 @@ func (c *CheckMonitor) check() {
...
+		if err := cmd.Process.Kill(); err != nil {
+			c.Logger.Printf("[WARN] Timed out running check '%s': error killing process: %v", c.Script, err)
 		} else {
-			time.Sleep(30 * time.Second)
+			c.Logger.Printf("[WARN] Timed out running check '%s'", c.Script)
 		}
-		errCh <- fmt.Errorf("Timed out running check '%s'", c.Script)
-	}()
-	err = <-errCh
+		err = <-waitCh
```
Comment (slackpad) [inline agent/check.go]: We should set `err` to `fmt.Errorf("Timed out running check '%s'", c.Script)` to make sure the check gets set to critical (otherwise if the wait returns `nil` it can go passing, and then we just block on the `waitCh` but don't set `err`, so:

```
err = fmt.Errorf("Timed out running check '%s'", c.Script)
<-waitCh
```

File: agent/util_windows.go [hunk 2]
```diff
@@ -22,3 +22,9 @@ func ExecScript(script string) (*exec.Cmd, error) {
 	}
 	return cmd, nil
 }
+
+func SetSysProcAttr(cmd *exec.Cmd) {}
+
+func KillCommandSubtree(cmd *exec.Cmd) error {
```
Comment (slackpad) [inline agent/util_windows.go]: Can you document this behavior difference on https://www.consul.io/docs/agent/checks.html.

File: agent/check.go [hunk 3]
```diff
@@ -119,28 +122,39 @@ func (c *CheckMonitor) check() {
...
+	waitCh := make(chan error, 1)
 	go func() {
-		errCh <- cmd.Wait()
+		waitCh <- cmd.Wait()
 	}()
-	go func() {
-		if c.Timeout > 0 {
-			time.Sleep(c.Timeout)
+
+	timeout := 30 * time.Second
```
Comment (slackpad) [inline agent/check.go]: Would be good to have test for this - I thought  saw it here a little while ago.

Comment (kyhavlov) [reply agent/check.go]: That was an existing test, I just ended up not having to modify it at all

**Comment by nh2** [comment]
@slackpad @kyhavlov I'm a bit late to the party/review, but first, thanks for the quick fix, and then a couple questions:

* I think it would be useful to document how the processes are getting killed, e.g. that you're using a process group kill, and which signal you use. That'd be good so that users don't try to do graceful exit on sigterm just to notice that they can't actually do it
* Does this really fix #3565? What I reported there was that script checks can overlap (the fact that no killing happened was just a side observation). It seems to me that if you don't use `timeout` and use a fast interval, scripts can still overlap and the same issues as I described in the bug can occur. Or did I miss a change to that regard in the commit messages?

**Comment by slackpad** [comment]
Hi @nh2 we added a wait in the timeout path so the `check()` function will block, preventing another run of that health check until the `Wait()` call comes back - https://github.com/hashicorp/consul/blob/master/agent/check.go#L153. That will prevent that particular check from overlapping itself. The docs were updated as part of this change but haven't been pushed out yet.

**Comment by nh2** [comment]
> we added a wait in the timeout path so the check() function will block, preventing another run of that health check until the Wait() call comes back

Ah, great.

> The docs were updated as part of this change but haven't been pushed out yet.

@slackpad I can see this docs change https://github.com/hashicorp/consul/pull/3567/files#diff-736ca63f9e217827ea7d70758c40cedeR28 but it doesn't really explain to the user how their scripts will be killed.

**Comment by slackpad** [comment]
> @slackpad I can see this docs change https://github.com/hashicorp/consul/pull/3567/files#diff-736ca63f9e217827ea7d70758c40cedeR28 but it doesn't really explain to the user how their scripts will be killed.

That's fair - it says "processes" but should be clearer about process groups and which signal is sent. @kyhavlov can you update the docs to make that more clear?
