### PR TITLE
ca: improve test coverage for RenewIntermediate

### LINKED ISSUE #7520: flaky test: agent/consul TestLeader_SecondaryCA_IntermediateRenew
Seen [here](https://app.circleci.com/pipelines/github/hashicorp/consul/8089/workflows/6b2127b2-c983-45f2-85f5-55ecdff47268/jobs/146766)

```
=== Failed
=== FAIL: agent/consul TestLeader_SecondaryCA_IntermediateRenew (1.06s)
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:02.745Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:774b6a4c-dfb2-d3ef-c25e-2d28e715361c Address:127.0.0.1:29524}]"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:02.745Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: entering follower state: follower="Node at 127.0.0.1:29524 [Follower]" leader=
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:02.746Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: EventMemberJoin: TestLeader_SecondaryCA_IntermediateRenew-node-10.dc1 127.0.0.1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:02.746Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.lan: serf: EventMemberJoin: TestLeader_SecondaryCA_IntermediateRenew-node-10 127.0.0.1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:02.747Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Adding LAN server: server="TestLeader_SecondaryCA_IntermediateRenew-node-10 (Addr: tcp/127.0.0.1:29524) (DC: dc1)"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:02.747Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Handled event for server in area: event=member-join server=TestLeader_SecondaryCA_IntermediateRenew-node-10.dc1 area=wan
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.087Z [WARN]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: heartbeat timeout reached, starting election: last-leader=
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.087Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: entering candidate state: node="Node at 127.0.0.1:29524 [Candidate]" term=2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.113Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: votes: needed=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.113Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: vote granted: from=774b6a4c-dfb2-d3ef-c25e-2d28e715361c term=2 tally=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.113Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: election won: tally=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.113Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.raft: entering leader state: leader="Node at 127.0.0.1:29524 [Leader]"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.113Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: cluster leadership acquired
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.113Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: New leader elected: payload=TestLeader_SecondaryCA_IntermediateRenew-node-10
Processing server acl mode for: TestLeader_SecondaryCA_IntermediateRenew-node-10 - 0
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.123Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Cannot upgrade to new ACLs: leaderMode=0 mode=0 found=true leader=127.0.0.1:29524
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.126Z [DEBUG] connect.ca.consul: consul CA provider configured: id=07:80:c8:de:f6:41:86:29:8f:9c:b8:17:d6:48:c2:d5:c5:5c:7f:0c:03:f7:cf:97:5a:a7:c1:68:aa:23:ae:81 is_primary=true
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.129Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.connect: initialized primary datacenter CA with provider: provider=consul
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.129Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: started routine: routine="federation state anti-entropy"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.129Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: started routine: routine="federation state pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.129Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: started routine: routine="CA root pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.129Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Skipping self join check for node since the cluster is too small: node=TestLeader_SecondaryCA_IntermediateRenew-node-10
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.129Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: member joined, marking health alive: member=TestLeader_SecondaryCA_IntermediateRenew-node-10
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.139Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: federation state anti-entropy synced
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.161Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:448cf652-2354-93b2-069e-c9f2ccbeebe4 Address:127.0.0.1:29527}]"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.161Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: entering follower state: follower="Node at 127.0.0.1:29527 [Follower]" leader=
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.161Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: EventMemberJoin: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2 127.0.0.1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.162Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.lan: serf: EventMemberJoin: TestLeader_SecondaryCA_IntermediateRenew-node-11 127.0.0.1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.164Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.memberlist.wan: memberlist: Initiating push/pull sync with: TestLeader_SecondaryCA_IntermediateRenew-node-10.dc1 127.0.0.1:29526
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.165Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.memberlist.wan: memberlist: Stream connection from=127.0.0.1:41546
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.166Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: EventMemberJoin: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2 127.0.0.1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.166Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Handled event for server in area: event=member-join server=TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2 area=wan
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.166Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: EventMemberJoin: TestLeader_SecondaryCA_IntermediateRenew-node-10.dc1 127.0.0.1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.167Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: Adding LAN server: server="TestLeader_SecondaryCA_IntermediateRenew-node-11 (Addr: tcp/127.0.0.1:29527) (DC: dc2)"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.168Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: Handled event for server in area: event=member-join server=TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2 area=wan
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.168Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: Handled event for server in area: event=member-join server=TestLeader_SecondaryCA_IntermediateRenew-node-10.dc1 area=wan
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.247Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.262Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.262Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.262Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.347Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.364Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.429Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Skipping self join check for node since the cluster is too small: node=TestLeader_SecondaryCA_IntermediateRenew-node-10
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.447Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.447Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: messageJoinType: TestLeader_SecondaryCA_IntermediateRenew-node-11.dc2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.503Z [WARN]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: heartbeat timeout reached, starting election: last-leader=
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.503Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: entering candidate state: node="Node at 127.0.0.1:29527 [Candidate]" term=2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.522Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: votes: needed=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.522Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: vote granted: from=448cf652-2354-93b2-069e-c9f2ccbeebe4 term=2 tally=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.522Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: election won: tally=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.522Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.raft: entering leader state: leader="Node at 127.0.0.1:29527 [Leader]"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.522Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: cluster leadership acquired
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.522Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: New leader elected: payload=TestLeader_SecondaryCA_IntermediateRenew-node-11
Processing server acl mode for: TestLeader_SecondaryCA_IntermediateRenew-node-10.dc1 - 0
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.544Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: Cannot upgrade to new ACLs, servers in acl datacenter are not yet upgraded: ACLDatacenter=dc1 mode=0 found=true
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.571Z [DEBUG] connect.ca.consul: consul CA provider configured: id=ad:4a:c6:ab:ef:63:c9:60:1a:51:7f:19:62:e3:e9:d9:0e:76:55:10:6e:74:24:69:28:a1:6c:b8:b9:8f:fd:89 is_primary=false
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.617Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: received new intermediate certificate from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: updated root certificates from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: initialized secondary datacenter CA with provider: provider=consul
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="config entry replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="federation state replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="federation state anti-entropy"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="secondary CA roots watch"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="intention replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="secondary cert renew watch"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.639Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: started routine: routine="CA root pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.640Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: Skipping self join check for node since the cluster is too small: node=TestLeader_SecondaryCA_IntermediateRenew-node-11
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.641Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: member joined, marking health alive: member=TestLeader_SecondaryCA_IntermediateRenew-node-11
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.643Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: starting Connect CA root replication from primary datacenter: primary=dc1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.replication.config_entry: finished fetching config entries: amount=0
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: starting Connect intention replication from primary datacenter: primary=dc1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.replication.config_entry: Config Entry replication: local=0 remote=0
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.replication.config_entry: Config Entry replication: deletions=0 updates=0
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.replication.config_entry: replication completed through remote index: index=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: finished fetching remote objects: amount=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: diffing replication state: local_amount=0 remote_amount=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: diffed replication state: deletions=0 updates=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.644Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: performing updates: updates=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.653Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: federation state anti-entropy synced
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.654Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: finished updates
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.654Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.replication.federation_state: replication completed through remote index: index=11
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.655Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: finished fetching remote objects: amount=2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.655Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: diffing replication state: local_amount=1 remote_amount=2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.655Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: diffed replication state: deletions=0 updates=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.655Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: performing updates: updates=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.655Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: finished updates
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.655Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.replication.federation_state: replication completed through remote index: index=14
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: federation state anti-entropy synced
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: finished fetching remote objects: amount=2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: diffing replication state: local_amount=2 remote_amount=2
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: diffed replication state: deletions=0 updates=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: performing updates: updates=1
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.server: finished updates
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.656Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.replication.federation_state: replication completed through remote index: index=16
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.657Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: received new intermediate certificate from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.657Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: updated root certificates from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.660Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: received new intermediate certificate from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.661Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: updated root certificates from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.663Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: received new intermediate certificate from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.664Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: updated root certificates from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.667Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: received new intermediate certificate from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.668Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: updated root certificates from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: received new intermediate certificate from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: leader_connect_test.go:301: 
        	Error Trace:	leader_connect_test.go:301
        	Error:      	Received unexpected error:
        	            	x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "sec-7g5cz2yh.consul.ca.3364da0c.consul")
        	Test:       	TestLeader_SecondaryCA_IntermediateRenew
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server: shutting down server
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="secondary CA roots watch"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="intention replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="secondary cert renew watch"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="CA root pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="config entry replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="federation state replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopping routine: routine="federation state anti-entropy"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [WARN]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.lan: serf: Shutdown without a Leave
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.709Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopped routine: routine="CA root pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.721Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.server: Skipping self join check for node since the cluster is too small: node=TestLeader_SecondaryCA_IntermediateRenew-node-10
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.725Z [WARN]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.serf.wan: serf: Shutdown without a Leave
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.725Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: updated root certificates from primary datacenter
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.router.manager: shutting down
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.router.manager: shutting down
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [ERROR] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.rpc: RPC failed to server in DC: server=127.0.0.1:29524 datacenter=dc1 method=FederationState.List error="rpc error making call: EOF"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.replication.federation_state: stopped replication
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopped routine: routine="federation state replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [ERROR] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.rpc: RPC failed to server in DC: server=127.0.0.1:29524 datacenter=dc1 method=ConfigEntry.ListAll error="rpc error making call: EOF"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-11.server.replication.config_entry: stopped replication
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-11.leader: stopped routine: routine="config entry replication"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [ERROR] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.rpc: RPC failed to server in DC: server=127.0.0.1:29524 datacenter=dc1 method=Intention.List error="rpc error making call: EOF"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [ERROR] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: error replicating intentions: routine="intention replication" error="rpc error making call: EOF"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [ERROR] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.rpc: RPC failed to server in DC: server=127.0.0.1:29524 datacenter=dc1 method=ConnectCA.Roots error="rpc error making call: EOF"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [ERROR] TestLeader_SecondaryCA_IntermediateRenew-node-11.server.connect: CA root replication failed, will retry: routine="secondary CA roots watch" error="Error retrieving the primary datacenter's roots: rpc error making call: EOF"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server: shutting down server
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: stopping routine: routine="federation state anti-entropy"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: stopping routine: routine="federation state pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: stopping routine: routine="CA root pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.727Z [WARN]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.lan: serf: Shutdown without a Leave
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.728Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: stopped routine: routine="federation state pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.728Z [DEBUG] TestLeader_SecondaryCA_IntermediateRenew-node-10.leader: stopped routine: routine="CA root pruning"
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.734Z [WARN]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.serf.wan: serf: Shutdown without a Leave
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.736Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.router.manager: shutting down
    TestLeader_SecondaryCA_IntermediateRenew: writer.go:29: 2020-03-26T19:39:03.736Z [INFO]  TestLeader_SecondaryCA_IntermediateRenew-node-10.server.router.manager: shutting down
```

### PR DESCRIPTION
**Pull request by dnephin**
There's a bunch of stuff here, so probably best viewed by individual commit. I'll try to comment on any interesting lines. I've been running the tests with `-count=100` in a loop and the flakes appear to be fixed now.

Primarily this PR:
1. adds a test for using the Vault provider in a secondary PR (previously we mostly only tested with Vault provider in the primary)
2. improves some existing RenewIntermediate tests to be less flaky (hopefully not flaky at all!) and to be less verbose, so easier to read.

Other changes made:
* adds an `Active()` method to both the `IndexedCARoots` (the RPC response) and `CARoots` (the state store result) so that we can stop repeating the "lookup active root" loop in dozens of places.

I'm planning on back porting to reduce conflicts when I back port other fixes.

Fixes #7520 (hopefully for real this time)

You can see [a recent flake of this on main here](https://app.circleci.com/pipelines/github/hashicorp/consul/24678/workflows/b21eb48c-e96e-4a2f-933e-a13dce677ab9/jobs/521497).

### CODE REVIEW

File: agent/consul/leader_connect_ca_test.go [hunk 1]
```diff
@@ -56,8 +56,6 @@ func TestCAManager_Initialize_Vault_Secondary_SharedVault(t *testing.T) {
 		testrpc.WaitForTestAgent(t, serverDC1.RPC, "dc1")
 
 		codec := rpcClient(t, serverDC1)
-		defer codec.Close()
```
Comment (dnephin) [inline agent/consul/leader_connect_ca_test.go]: The `rpcClient` function already does this with `t.Cleanup`

File: agent/consul/leader_connect_test.go [hunk 2]
```diff
@@ -420,8 +420,13 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
 		intermediatePEM = newIntermediatePEM
 	})
 
-	_, activeRoot, err = store.CARootActive(nil)
+	codec := rpcClient(t, s1)
+	roots := structs.IndexedCARoots{}
+	err = msgpackrpc.CallWithCodec(codec, "ConnectCA.Roots", &structs.DCSpecificRequest{}, &roots)
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:384]: I changed from a direct state store call to an RPC call because we need the `TrustDomain` below to create a valid spiffe ID.

I'm attempting to move where we store this value (see #11687) so I prefer fetching it from a public interface instead of reaching into the state store config.

File: agent/consul/leader_connect_test.go [hunk 3]
```diff
@@ -431,36 +436,18 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
...
-	raw, _ := connect.TestCSR(t, spiffeService)
-
-	leafCsr, err := connect.ParseCSR(raw)
-	require.NoError(err)
-
-	leafPEM, err := provider.Sign(leafCsr)
-	require.NoError(err)
-
-	cert, err := connect.ParseCert(leafPEM)
-	require.NoError(err)
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go]: Replaced the direct call to `provider.Sign` with an RPC to `ConenctCA.Sign` because those two things return different data. The RPC call returns a pem that includes intermediate certs, which is required to verify the cert. 

In general using public interfaces in tests is preferable, so this felt like a good change.

File: agent/consul/leader_connect_test.go [hunk 4]
```diff
@@ -431,36 +436,18 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
...
-	// TODO: do not explicitly add the intermediatePEM, we should have it available
-	// from leafPEM. Use connect.ParseLeafCerts to do the right thing.
-	intermediatePool.AppendCertsFromPEM([]byte(intermediatePEM))
-	rootPool := x509.NewCertPool()
-	rootPool.AppendCertsFromPEM([]byte(caRoot.RootCert))
-
-	_, err = cert.Verify(x509.VerifyOptions{
-		Intermediates: intermediatePool,
-		Roots:         rootPool,
-	})
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go]: This is now done in `verifyLeafCert`, which will prevent bugs like #11671 because `verifyLeafCert` checks the cert with intermediates from both locations (leafCertPEM and `Root.IntermediateCerts`)

File: agent/structs/connect_ca.go [hunk 5]
```diff
@@ -55,6 +55,15 @@ type IndexedCARoots struct {
...
 }
 
+func (r IndexedCARoots) Active() *CARoot {
+	for _, root := range r.Roots {
+		if root.ID == r.ActiveRootID {
+			return root
+		}
+	}
+	return nil
+}
```
Comment (dnephin) [inline agent/structs/connect_ca.go:65]: I will be slowly replacing the many places we do this with this new method in future PRs.

File: agent/consul/leader_connect_ca.go [hunk 6]
```diff
@@ -1111,8 +1111,8 @@ func setLeafSigningCert(caRoot *structs.CARoot, pem string) error {
 	return nil
 }
 
-// intermediateCertRenewalWatch periodically attempts to renew the intermediate cert.
-func (c *CAManager) intermediateCertRenewalWatch(ctx context.Context) error {
+// runRenewIntermediate periodically attempts to renew the intermediate cert.
+func (c *CAManager) runRenewIntermediate(ctx context.Context) error {
```
Comment (dnephin) [inline agent/consul/leader_connect_ca.go:1115]: This method was not really a "watch". Generally our watch functions block on a channel close, but this is polling at some interval, so I thought a rename would be appropriate.

File: agent/consul/leader_connect_ca.go [hunk 7]
```diff
@@ -1180,8 +1180,7 @@ func (c *CAManager) RenewIntermediate(ctx context.Context, isPrimary bool) error
 		return fmt.Errorf("error parsing active intermediate cert: %v", err)
 	}
 
-	if lessThanHalfTimePassed(c.timeNow(), intermediateCert.NotBefore.Add(ca.CertificateTimeDriftBuffer),
-		intermediateCert.NotAfter) {
+	if lessThanHalfTimePassed(c.timeNow(), intermediateCert.NotBefore, intermediateCert.NotAfter) {
```
Comment (dnephin) [inline agent/consul/leader_connect_ca.go:1183]: This was added in #8702 in an attempt to fix this flaky test, but I don't think it accomplished that goal.

I found it much harder to reason about this logic with the extra `.Add()` call, and I think conceptually it's not correct. We really only care about the half time.

I believe the other fixes in this PR will address the flakes.

File: agent/consul/leader_connect_test.go [hunk 8]
```diff
@@ -450,21 +440,26 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
 	verifyLeafCert(t, caRoot, cert.CertPEM)
 }
 
+func patchIntermediateCertRenewInterval(t *testing.T) {
+	origInterval := structs.IntermediateCertRenewInterval
+	origMinTTL := structs.MinLeafCertTTL
+
+	structs.IntermediateCertRenewInterval = 200 * time.Millisecond
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:412]: I think this is one of the two fixes that should resolve the flakes. Previously we only waited 1ms, which I think meant that in some cases the renew goroutine could run before we got a reference to the "original" certificate.  The test does not run any slower with this 200ms. I believe it actually runs faster than it does on `main` because of other changes in this PR.

File: agent/consul/leader_connect_test.go [hunk 9]
```diff
@@ -539,22 +533,18 @@ func TestCAManager_RenewIntermediate_Secondary(t *testing.T) {
...
-		secondaryProvider, _ = getCAProviderWithLock(s2)
-		intermediatePEM, err = secondaryProvider.ActiveIntermediate()
-		r.Check(err)
-		cert, err := connect.ParseCert(intermediatePEM)
+		store := s2.caManager.delegate.State()
+		_, storedRoot, err := store.CARootActive(nil)
 		r.Check(err)
-		if cert.SerialNumber.Cmp(currentCertSerialNumber) == 0 || !reflect.DeepEqual(cert.AuthorityKeyId, currentCertAuthorityKeyId) {
-			currentCertSerialNumber = cert.SerialNumber
-			currentCertAuthorityKeyId = cert.AuthorityKeyId
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:567]: I made this more consistent with the other test by comparing the certificate instead of the serial. There are a few values we could use, but comparing the certificate seemed fine.

File: agent/consul/leader_connect_test.go [hunk 10]
```diff
@@ -565,8 +555,8 @@ func TestCAManager_RenewIntermediate_Secondary(t *testing.T) {
 
 	_, activeRoot, err = store.CARootActive(nil)
 	require.NoError(err)
-	require.Equal(intermediatePEM, s2.caManager.getLeafSigningCertFromRoot(activeRoot))
 	require.Equal(connect.HexString(intermediateCert.SubjectKeyId), activeRoot.SigningKeyID)
+	require.Equal(intermediatePEM, s2.caManager.getLeafSigningCertFromRoot(activeRoot))
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go]: I flipped these because when the test fails it is a lot easier for humans to compare two relative short hex values, than a multi-line PEM encoded certificate.

The `t.Log` I added above in these tests allows us to easily see if the problem is that it was not rotated, or something else.

File: agent/consul/leader_connect_test.go [hunk 11]
```diff
@@ -314,18 +314,6 @@ func TestCAManager_Initialize_Secondary(t *testing.T) {
 	}
 }
 
-func waitForActiveCARoot(t *testing.T, srv *Server, expect *structs.CARoot) {
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:317]: This was basically a dupe of `testrpc.WaitForActiveCARoot`, so I removed this one.

File: agent/consul/leader_connect_test.go [hunk 12]
```diff
@@ -330,10 +330,8 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
 	require := require.New(t)
 
 	testVault := ca.NewTestVaultServer(t)
-	defer testVault.Stop()
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:357]: already done by `NewTestVaultServer` using `t.Cleanup`.

File: agent/consul/leader_connect_test.go [hunk 13]
```diff
@@ -330,10 +330,8 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
...
 
-	dir1, s1 := testServerWithConfig(t, func(c *Config) {
-		c.Build = "1.6.0"
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:360]: I think these were copy/paste from other tests where they were relevant. The build number does not matter for these tests.

File: agent/consul/leader_connect_test.go [hunk 14]
```diff
@@ -342,43 +340,27 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
 				"Token":               testVault.RootToken,
 				"RootPKIPath":         "pki-root/",
 				"IntermediatePKIPath": "pki-intermediate/",
-				"LeafCertTTL":         "1s",
-				// The retry loop only retries for 7sec max and
-				// the ttl needs to be below so that it
-				// triggers definitely.
-				"IntermediateCertTTL": "5s",
+				"LeafCertTTL":         "2s",
+				"IntermediateCertTTL": "7s",
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:344]: This was another source of flakes. The leaf cert could expire before we got to checking if it was valid.

Increasing these values does not actually slow down the test at all , because we use a "NotBefore" date for the cert that is a full minute in the past, so we only end up waiting on the "renew interval", which is 200ms.

File: agent/consul/leader_connect_test.go [hunk 15]
```diff
@@ -342,43 +340,27 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
...
-		rootList, activeRoot, err := getTestRoots(s1, "dc1")
-		require.NoError(err)
-		require.Len(rootList.Roots, 1)
-		originalRoot = activeRoot
-	}
-	t.Log("original SigningKeyID", originalRoot.SigningKeyID)
-
-	// Get the original intermediate.
-	provider, _ := getCAProviderWithLock(s1)
-	intermediatePEM, err := provider.ActiveIntermediate()
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:397]: Reading the cert from the provider directly was another possible source of flakes, because that value will be updated before the state store. 

I've tried to change these tests to always use either the RPC interface (preferred) or the state store (backs the RPC interface). That should make the tests less flaky.

I think we should make a similar change in other tests, but that is for a future PR.

File: agent/connect/ca/testing.go [hunk 16]
```diff
@@ -162,7 +163,7 @@ func runTestVault(t testing.T) (*TestVaultServer, error) {
 	}
 	t.Cleanup(func() {
 		if err := testVault.Stop(); err != nil {
-			t.Log("failed to stop vault server: %w", err)
+			t.Logf("failed to stop vault server: %v", err)
```
Comment (dnephin) [inline agent/connect/ca/testing.go:166]: not sure why `%w` was not working here, but it was not formatting correctly, so `%v` should be fine. Maybe `%w` only works in `fmt.Errorf` ?

File: agent/consul/leader_connect_test.go [hunk 17]
```diff
@@ -366,52 +340,37 @@ func TestCAManager_RenewIntermediate_Vault_Primary(t *testing.T) {
...
 	require.Equal(connect.HexString(intermediateCert.SubjectKeyId), activeRoot.SigningKeyID)
+	require.Equal(intermediatePEM, s1.caManager.getLeafSigningCertFromRoot(activeRoot))
 
 	// Wait for dc1's intermediate to be refreshed.
-	// It is possible that test fails when the blocking query doesn't return.
 	retry.Run(t, func(r *retry.R) {
-		provider, _ = getCAProviderWithLock(s1)
-		newIntermediatePEM, err := provider.ActiveIntermediate()
+		store := s1.caManager.delegate.State()
+		_, storedRoot, err := store.CARootActive(nil)
```
Comment (dnephin) [inline agent/consul/leader_connect_test.go:370]: This is another cause of flakes. Mentioned in another comment maybe, but it relates to [this flake](https://app.circleci.com/pipelines/github/hashicorp/consul/24678/workflows/b21eb48c-e96e-4a2f-933e-a13dce677ab9/jobs/521497) so I'll mention it here as well.

We poll checking the provider, which is updated first, but it is the state store that backs RPC requests, so we need to poll the state store (or RPC) not the provider.

The provider is updated before the state store, which causes a race in tests.

**Review by freddygv — APPROVED** [review]

File: agent/consul/leader_connect_ca.go (hunk 6 above)
Comment (FFMMM) [reply agent/consul/leader_connect_ca.go:1115]: [nit + i'm bad at naming, so maybe disregard]: could we somehow capture the "retry"-ness of the func in its name? Something like `renewIntermediateWithRetries` or `retryRenewIntermediate` or `runRetryRenewIntermediate`?

File: agent/consul/leader_connect_ca_test.go [hunk 18]
```diff
@@ -31,6 +33,103 @@ import (
...
+		err := msgpackrpc.CallWithCodec(codec, "ConnectCA.Roots", &structs.DCSpecificRequest{}, &roots)
+		require.NoError(t, err)
+		require.Len(t, roots.Roots, 1)
+
+		leafPEM := getLeafCert(t, codec, roots.TrustDomain, "dc2")
+		verifyLeafCert(t, roots.Roots[0], leafPEM)
+	})
+}
+
+func verifyLeafCert(t *testing.T, root *structs.CARoot, leafCertPEM string) {
```
Comment (FFMMM) [inline agent/consul/leader_connect_ca_test.go:98]: this looks super useful -- we don't have to do it with this PR but curious how we can propagate/ export this across server/ agent wherever we deal w certs.

**Review by FFMMM — APPROVED** [review]
Thanks for all the comments! It made reviewing easier -- LGTM! 🚀

File: agent/consul/leader_connect_ca_test.go (hunk 1 above)
Comment (boxofrad) [reply agent/consul/leader_connect_ca_test.go]: TIL about [`t.Cleanup`](https://pkg.go.dev/testing#T.Cleanup). Thanks! 🙌🏻

File: agent/consul/leader_connect_ca.go (hunk 6 above)
Comment (dnephin) [reply agent/consul/leader_connect_ca.go:1115]: Good idea! The function does both poll and retry if one of the ticks fails. In generally try to call any long running functions `Run` (or `Run<Something>`). 

Maybe `runPeriodicIntermediateCertRotation` ?  If that sounds good I'll probably opt to do the rename in a follow up and rename a couple other things at the same time.

File: agent/consul/leader_connect_ca_test.go (hunk 18 above)
Comment (dnephin) [reply agent/consul/leader_connect_ca_test.go:98]: If we find a use for it outside of this package, I generally like to export test helpers in their own `internal` packages ([ref](https://go.dev/doc/go1.4#internalpackages)).

So maybe `internal/catest` or `internal/pkitest`.

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit f9647ece05dc348445a09a053238081a9e952b28 onto `release/1.11.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/522605)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit f9647ece05dc348445a09a053238081a9e952b28 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/522605)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit f9647ece05dc348445a09a053238081a9e952b28 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/522605)

**Comment by dnephin** [comment]
I'll batch up a few changes to manually cherry-pick at the same time.

**Comment by kisunji** [comment]
@dnephin Have these been cherry-picked? I think 1.11.x is [failing](https://app.circleci.com/pipelines/github/hashicorp/consul-enterprise/14479/workflows/0f11d093-4189-4bde-a7b6-5b8205acdbf4/jobs/259078) on CA tests related to this change

**Comment by dnephin** [comment]
Nope, was still on my list. I'll do that now along with #11721. Thanks for the reminder!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/549495.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f9647ece05dc348445a09a053238081a9e952b28 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit f9647ece05dc348445a09a053238081a9e952b28 onto `release/1.10.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/549495)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit f9647ece05dc348445a09a053238081a9e952b28 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/549495)

**Comment by dnephin** [comment]
I managed to get this auto-backported into 1.11 by backporting #11721.

I'll do the other two release branches manually now.
