### PR TITLE
ca: fix a bug that caused a non blocking leaf cert query after a blocking leaf cert query to block

### LINKED ISSUE #12048: ca/ leaf cert: non blocking queries issued after blocking queries may block
#### Overview of the Issue

[This commit](https://github.com/hashicorp/consul/commit/384d497f267aefbcd173e7b1fd7fca9f762a82fe) introduces a new bug.

The intent of the original commit was to fix situations where expired certs or invalid certs (after a root rotation) were returned.

Now, however, a non blocking query issued after a blocking query can an end up blocking on the former blocking query's completion or timeout.
 
#### Reproduction Steps

```
1. set up a CA provider
2. curl {CONSUL_HTTP_ADDR}/v1/agent/connect/ca/leaf/something\?index\={MODIFY_INDEX} -k
3. cancel the query
4. curl {CONSUL_HTTP_ADDR}/v1/agent/connect/ca/leaf/something -k
```
The last query will be blocking but it shouldn't! 

#### Explanation

The blocking query sets up a Waiter. If that query is cancelled by the client, then the following non-blocking query needs to wait on that existing Waiter for the cache key because of `MustRevalidate` being set for all non-blocking queries. But that Waiter channel won't close until the previous blocking query's Fetch returns, and that won't happen until a new cert needs to be generated.

#### Workaround

A possible workaround was suggested to use `wait=N` where n is << small.

Another way was to modify the QueryOptions prior to kicking off the watch go routines::

```
	leafCert, _, err := c.consul.Agent().ConnectCALeaf(c.service, &api.QueryOptions{
		WaitTime:  1 * time.Second,
	})
	if err != nil {
		return err
	}
	c.handleLeafWatch(nil, leafCert)
```

#### Possible solutions

1. A solution that Daniel mentioned before was to rethink this cache type.

```
We'd need a LeafCertStore that is basically a map[key]LeafCert . We'd pass the LeafCertStore to the cache-type, so that it can store the leaf cert after creating it. Then we'd need some way to expire the entries in the LeafCertStore , either by using a separate TTL, or we could have the cache entry clear out the LeafCertStore.

The HTTPHandler would only use the cache for blocking queries. Non-blocking queries would go directly to the LeafCertStore, so would avoid the problem entirely.
```

2. Freddy suggested we think about supporting cancellation in the cache

```
1. Get a context and cancel func on calls to fetch from the cache
2. Plumb the context through the calls to Fetch the cache types
3. Store the cancel func in the cacheEntry
4. When a non-blocking query comes in we call the cancel func in the entry, and make the old Fetch return to close the corresponding Waiter (triggering a re-fetch from the cache)
```

#### Other thoughts

* This is the only cache-type that uses refresh=false, blocking=true. So it's likely that combo doesn't work right. Anecdotally, bugs in the leaf cert or coming from the leaf cert cache type seem to be a recurring hit for us. Maybe now is the time to invest more time/ resources to weed this source of bugs out for good.

* TDD! Anyone picking this up, please first make this fail in a unit test by following the repro steps above.

##### Acks
Thanks andrew for reporting and diagnosis this. As well as paul, daniel, freddy and chris for chiming in.

##### TODOs

* [ ] more code links

### LINKED ISSUE #12319: consul builtin sidecar proxy takes 10 minutes to start working
#### Overview of the Issue

When starting the builtin sidecar proxy to enable Consul Connect for a service registered in Consul, the proxy process starts immediately but only after 10 minutes it starts working and accepting Consul Connect requests. This used to work immediately in older versions of Consul. I've found out that Consul version 1.9.13 seems to work and in version 1.9.14 it takes 10 minutes. The release notes don't hint at any changes to the Consul connect proxy though. I have not done an exhaustive search to check if this happens with all versions from 1.9.4 and later or that all versions from 1.9.3 and earlier do not have this bug.

#### Reproduction Steps

Steps to reproduce this issue:
Download the latest consul version (1.11.2 at this moment)

1. Run a consul server in dev mode: consul agent -dev
2. Start any service, for example an nginx container: docker run -p 8000:80 -d nginx:alpine
3. Write a service file for a Consul service registration: 
```
service {
    name = "nginx-service"
    port = 8000
    connect {
        sidecar_service { }
    }
}
```
4. Register the service in Consul: consul services register nginx-service.hcl
5. Start the sidecar proxy: consul connect proxy --sidecar-for nginx-service

Now the sidecar proxy should start and open a socket on port 21000. For consul versions 1.9.13 and older this works nearly instant, for newer versions it takes 10 minutes to work. The first message in the log that appears is 
```[INFO]  proxy: Proxy loaded config and ready to serve```

This is immediately followed by:
```
[INFO]  proxy: Parsed TLS identity: uri=spiffe://b00fb169-c137-8254-a07e-ba340abd0e1c.consul/ns/default/dc/dc1/svc/nginx-service roots=[pri-9lo97id.consul.ca.b00fb169.consul]
[INFO]  proxy: Starting listener: listener="public listener" bind_addr=0.0.0.0:21000
```

6. curl http://localhost:8000 after seeing above message to verify that the sidecar proxy is working

### Consul info for both Client and Server
This happens on a consul cluster in dev modus, as well as a multi-node consul cluster setup with ACL's and TLS.

### Operating system and Environment details
This is reproducible on Linux (Ubuntu 20.04) as well as Windows 10 and WSL. 

### Log Fragments
logs from the consul agent:
```
==> Starting Consul agent...
           Version: '1.11.2'
           Node ID: '5b94a58e-4e44-d381-37ce-f053c6177bb5'
         Node name: 'NB-XPS111'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [127.0.0.1] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

2022-02-11T16:25:16.761+0100 [INFO]  agent.server.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:5b94a58e-4e44-d381-37ce-f053c6177bb5 Address:127.0.0.1:8300}]"
2022-02-11T16:25:16.762+0100 [INFO]  agent.server.raft: entering follower state: follower="Node at 127.0.0.1:8300 [Follower]" leader=
2022-02-11T16:25:16.762+0100 [INFO]  agent.server.serf.wan: serf: EventMemberJoin: NB-XPS111.dc1 127.0.0.1
2022-02-11T16:25:16.763+0100 [INFO]  agent.server.serf.lan: serf: EventMemberJoin: NB-XPS111 127.0.0.1
2022-02-11T16:25:16.763+0100 [INFO]  agent.router: Initializing LAN area manager
2022-02-11T16:25:16.763+0100 [INFO]  agent.server: Adding LAN server: server="NB-XPS111 (Addr: tcp/127.0.0.1:8300) (DC: dc1)"
2022-02-11T16:25:16.763+0100 [WARN]  agent: grpc: addrConn.createTransport failed to connect to {dc1-127.0.0.1:8300 0 NB-XPS111 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:0->127.0.0.1:8300: operation was canceled". Reconnecting...
2022-02-11T16:25:16.763+0100 [INFO]  agent.server: Handled event for server in area: event=member-join server=NB-XPS111.dc1 area=wan
2022-02-11T16:25:16.763+0100 [WARN]  agent: grpc: addrConn.createTransport failed to connect to {dc1-127.0.0.1:8300 0 NB-XPS111.dc1 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:0->127.0.0.1:8300: operation was canceled". Reconnecting...
2022-02-11T16:25:16.763+0100 [INFO]  agent: Started DNS server: address=127.0.0.1:8600 network=tcp
2022-02-11T16:25:16.763+0100 [INFO]  agent: Started DNS server: address=127.0.0.1:8600 network=udp
2022-02-11T16:25:16.763+0100 [INFO]  agent: Starting server: address=127.0.0.1:8500 network=tcp protocol=http
2022-02-11T16:25:16.763+0100 [WARN]  agent: DEPRECATED Backwards compatibility with pre-1.9 metrics enabled. These metrics will be removed in a future version of Consul. Set `telemetry { disable_compat_1.9 = true }` to disable them.
2022-02-11T16:25:16.763+0100 [INFO]  agent: Started gRPC server: address=127.0.0.1:8502 network=tcp
2022-02-11T16:25:16.764+0100 [INFO]  agent: started state syncer
2022-02-11T16:25:16.764+0100 [INFO]  agent: Consul agent running!
2022-02-11T16:25:16.808+0100 [WARN]  agent.server.raft: heartbeat timeout reached, starting election: last-leader=
2022-02-11T16:25:16.808+0100 [INFO]  agent.server.raft: entering candidate state: node="Node at 127.0.0.1:8300 [Candidate]" term=2
2022-02-11T16:25:16.808+0100 [DEBUG] agent.server.raft: votes: needed=1
2022-02-11T16:25:16.808+0100 [DEBUG] agent.server.raft: vote granted: from=5b94a58e-4e44-d381-37ce-f053c6177bb5 term=2 tally=1
2022-02-11T16:25:16.808+0100 [INFO]  agent.server.raft: election won: tally=1
2022-02-11T16:25:16.808+0100 [INFO]  agent.server.raft: entering leader state: leader="Node at 127.0.0.1:8300 [Leader]"
2022-02-11T16:25:16.808+0100 [INFO]  agent.server: cluster leadership acquired
2022-02-11T16:25:16.808+0100 [INFO]  agent.server: New leader elected: payload=NB-XPS111
2022-02-11T16:25:16.809+0100 [INFO]  agent.leader: started routine: routine="federation state anti-entropy"
2022-02-11T16:25:16.809+0100 [INFO]  agent.leader: started routine: routine="federation state pruning"
2022-02-11T16:25:16.809+0100 [DEBUG] agent.server.autopilot: autopilot is now running
2022-02-11T16:25:16.809+0100 [DEBUG] agent.server.autopilot: state update routine is now running
2022-02-11T16:25:16.809+0100 [DEBUG] connect.ca.consul: consul CA provider configured: id=fb:50:9b:45:1a:65:15:c1:68:57:73:5f:da:cd:b8:0d:0f:e2:26:eb:68:66:43:11:85:9d:67:a9:7a:56:9c:b9 is_primary=true
2022-02-11T16:25:16.810+0100 [INFO]  connect.ca: initialized primary datacenter CA with provider: provider=consul
2022-02-11T16:25:16.810+0100 [INFO]  agent.leader: started routine: routine="intermediate cert renew watch"
2022-02-11T16:25:16.810+0100 [INFO]  agent.leader: started routine: routine="CA root pruning"
2022-02-11T16:25:16.810+0100 [INFO]  agent.leader: started routine: routine="CA root expiration metric"
2022-02-11T16:25:16.810+0100 [INFO]  agent.leader: started routine: routine="CA signing expiration metric"
2022-02-11T16:25:16.810+0100 [INFO]  agent.leader: started routine: routine="virtual IP version check"
2022-02-11T16:25:16.810+0100 [DEBUG] agent.server: successfully established leadership: duration=1.6918ms
2022-02-11T16:25:16.810+0100 [INFO]  agent.server: member joined, marking health alive: member=NB-XPS111 partition=default
2022-02-11T16:25:16.810+0100 [DEBUG] agent.leader: stopping routine: routine="virtual IP version check"
2022-02-11T16:25:16.810+0100 [DEBUG] agent.leader: stopped routine: routine="virtual IP version check"
2022-02-11T16:25:16.924+0100 [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-02-11T16:25:16.925+0100 [INFO]  agent: Synced node info
2022-02-11T16:25:17.087+0100 [INFO]  agent.server: federation state anti-entropy synced
2022-02-11T16:25:17.390+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/internal/ui/services?dc=dc1&index=1 from=127.0.0.1:59810 latency=168.9µs
2022-02-11T16:25:19.751+0100 [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-02-11T16:25:19.752+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:19.752+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:29.890+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:29.890+0100 [INFO]  agent: Synced service: service=nginx-service
2022-02-11T16:25:29.890+0100 [DEBUG] agent: added local registration for service: service=nginx-service-sidecar-proxy
2022-02-11T16:25:29.890+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:29.890+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:25:29.890+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/internal/ui/services?dc=dc1&index=14 from=127.0.0.1:59810 latency=10.482508s
2022-02-11T16:25:29.891+0100 [INFO]  agent: Synced service: service=nginx-service-sidecar-proxy
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Service in sync: service=nginx-service-sidecar-proxy
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:25:29.891+0100 [INFO]  agent: Synced check: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:25:29.891+0100 [DEBUG] agent.http: Request finished: method=PUT url=/v1/agent/service/register from=127.0.0.1:59814 latency=1.6597ms
2022-02-11T16:25:29.891+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Service in sync: service=nginx-service-sidecar-proxy
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Service in sync: service=nginx-service-sidecar-proxy
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:25:29.892+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:25:31.915+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/internal/ui/services?dc=dc1&index=16 from=127.0.0.1:59810 latency=150.5µs
2022-02-11T16:25:36.752+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:25:36.752+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:25:46.752+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:25:46.752+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:25:56.753+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:25:56.753+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:26:06.755+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:26:06.755+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:26:16.756+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:26:16.756+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:26:23.258+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/services from=127.0.0.1:59826 latency=257.3µs
2022-02-11T16:26:23.259+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/service/nginx-service-sidecar-proxy from=127.0.0.1:59826 latency=67.9µs
2022-02-11T16:26:23.261+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/connect/ca/roots from=127.0.0.1:59828 latency=902.1µs
2022-02-11T16:26:26.757+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:26:26.757+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:26:36.758+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:26:36.758+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:26:40.158+0100 [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-02-11T16:26:40.159+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:26:40.159+0100 [DEBUG] agent: Service in sync: service=nginx-service-sidecar-proxy
2022-02-11T16:26:40.159+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:26:40.159+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:26:40.159+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:26:46.759+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
...
...lines removed that repeat same message until the sidecar starts working
...
2022-02-11T16:35:26.827+0100 [WARN]  agent: Check socket connection failed: check=service:nginx-service-sidecar-proxy:1 error="dial tcp 127.0.0.1:21000: connect: connection refused"
2022-02-11T16:35:26.827+0100 [WARN]  agent: Check is now critical: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:35:29.894+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/connect/ca/leaf/nginx-service from=127.0.0.1:59830 latency=9m6.6334955s
2022-02-11T16:35:36.828+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:35:36.829+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:35:36.829+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:35:36.829+0100 [DEBUG] agent: Service in sync: service=nginx-service-sidecar-proxy
2022-02-11T16:35:36.829+0100 [INFO]  agent: Synced check: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:35:36.829+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:35:36.829+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/internal/ui/services?dc=dc1&index=32 from=127.0.0.1:59810 latency=2m8.2864218s
2022-02-11T16:35:37.869+0100 [DEBUG] agent: Skipping remote check since it is managed automatically: check=serfHealth
2022-02-11T16:35:37.869+0100 [DEBUG] agent: Node info in sync
2022-02-11T16:35:37.869+0100 [DEBUG] agent: Service in sync: service=nginx-service
2022-02-11T16:35:37.869+0100 [DEBUG] agent: Service in sync: service=nginx-service-sidecar-proxy
2022-02-11T16:35:37.869+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:1
2022-02-11T16:35:37.869+0100 [DEBUG] agent: Check in sync: check=service:nginx-service-sidecar-proxy:2
2022-02-11T16:35:46.830+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:35:56.832+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:06.834+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:16.836+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:26.838+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:36.840+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:46.841+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:56.803+0100 [DEBUG] agent.http: Request finished: method=GET url=/v1/agent/service/nginx-service-sidecar-proxy?hash=144ca5fb9647b9e5 from=127.0.0.1:59826 latency=5m15.2379944s
2022-02-11T16:36:56.842+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:36:56.887+0100 [DEBUG] agent.router.manager: Rebalanced servers, new active server: number_of_servers=1 active_server="NB-XPS111 (Addr: tcp/127.0.0.1:8300) (DC: dc1)"
2022-02-11T16:37:06.844+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
2022-02-11T16:37:16.845+0100 [DEBUG] agent: Check status updated: check=service:nginx-service-sidecar-proxy:1 status=passing
```

=======================
logs from the sidecar proxy (please not the date output and the timestamps of the logs):

```
[root@devlaptop:~$] date
Fri Feb 11 16:26:19 CET 2022
[root@devlaptop:~$] consul connect proxy --sidecar-for nginx-service
==> Consul Connect proxy starting...
    Configuration mode: Agent API
        Sidecar for ID: nginx-service
              Proxy ID: nginx-service-sidecar-proxy

==> Log data will now stream in as it occurs:

    2022-02-11T16:35:29.896+0100 [INFO]  proxy: Proxy loaded config and ready to serve
    2022-02-11T16:35:29.897+0100 [INFO]  proxy: Parsed TLS identity: uri=spiffe://b00fb169-c137-8254-a07e-ba340abd0e1c.consul/ns/default/dc/dc1/svc/nginx-service roots=[pri-9lo97id.consul.ca.b00fb169.consul]
    2022-02-11T16:35:29.897+0100 [INFO]  proxy: Starting listener: listener="public listener" bind_addr=0.0.0.0:21000
```

### PR DESCRIPTION
**Pull request by rboyer**
Fixes #12048

Fixes #12319

Regression introduced in #11693

Local reproduction steps:
1. `consul agent -dev`
2. `curl -sLiv 'localhost:8500/v1/agent/connect/ca/leaf/web'`
3. make note of the `X-Consul-Index` header returned 
4. `curl -sLi 'localhost:8500/v1/agent/connect/ca/leaf/web?index=<VALUE_FROM_STEP_3>'`
5. Kill the above curl when it hangs with Ctrl-C
6. Repeat (2) and it should not hang.

### CODE REVIEW

File: agent/cache/cache.go [hunk 1]
```diff
@@ -554,9 +554,15 @@ func (c *Cache) fetch(key string, r getOptions, allowNew bool, attempt uint, ign
 		return ch
 	}
 
-	// If we already have an entry and it is actively fetching, then return
-	// the currently active waiter.
+	// If we already have an entry, it is actively fetching, and we don't need
+	// to revalidate the cache, then return the currently active waiter.
 	if ok && entry.Fetching {
+		// If we need to revalidate, return immediately
```
Comment (kisunji) [inline agent/cache/cache.go:560]:
```suggestion
		// If we need to revalidate, return with a closed channel
		// so the caller will immediately retry the cache
```

Comment (kisunji) [reply agent/cache/cache.go:560]: Not sure if `fetch` has more than one caller but felt like the closed channel required some extra justification

File: agent/agent_endpoint_test.go [hunk 2]
```diff
@@ -6202,6 +6202,104 @@ func TestAgentConnectCALeafCert_goodNotLocal(t *testing.T) {
...
+	}
+
+	var (
+		serialNumber string
+		index        string
+		issued       structs.IssuedCert
+	)
+	runStep(t, "do initial non-blocking query", func(t *testing.T) {
+		req, err := http.NewRequest("GET", "/v1/agent/connect/ca/leaf/test", nil)
+		require.NoError(t, err)
```
Comment (boxofrad) [inline agent/agent_endpoint_test.go:6252]: Tip: `httptest` has a convenience method for this too, so you don't need to handle the error.

```suggestion
		req := httptest.NewRequest("GET", "/v1/agent/connect/ca/leaf/test", nil)
```

File: agent/agent_endpoint_test.go [hunk 3]
```diff
@@ -6202,6 +6202,104 @@ func TestAgentConnectCALeafCert_goodNotLocal(t *testing.T) {
...
+			return
+		}
+		a.srv.h.ServeHTTP(resp, req)
+	}()
+
+	// We just need to ensure that the above blocking query is in-flight before
+	// the next step, so do a little sleep.
+	time.Sleep(50 * time.Millisecond)
+
+	runStep(t, "do a non-blocking query that should not block", func(t *testing.T) {
```
Comment (boxofrad) [inline agent/agent_endpoint_test.go:6282]: For those of us less familiar with this code-path, does this test assume that the waiter won't have been cleared because leaf certificates are generated infrequently? Would it be worth calling out in a comment?

**Review by boxofrad — APPROVED** [review]
Looks great, left a couple of small comments/questions 🎉

File: agent/cache/cache.go [hunk 4]
```diff
@@ -554,9 +554,16 @@ func (c *Cache) fetch(key string, r getOptions, allowNew bool, attempt uint, ign
 		return ch
 	}
 
-	// If we already have an entry and it is actively fetching, then return
-	// the currently active waiter.
+	// If we already have an entry, it is actively fetching, and we don't need
+	// to revalidate the cache, then return the currently active waiter.
```
Comment (FFMMM) [inline agent/cache/cache.go:558]: at least to me, this comment doesn't make sense anymore since we say that `If we need to revalidate, ... ` below. Could we re-write it as ?

```suggestion
	// We have an entry that is actively fetching
	// If we need to revalidate, return with a closed channel
	// so the caller will immediately retry the cache.
	// Otherwise, return the currently active waiter.
```

File: agent/cache/cache.go [hunk 5]
```diff
@@ -554,9 +554,16 @@ func (c *Cache) fetch(key string, r getOptions, allowNew bool, attempt uint, ign
...
 	if ok && entry.Fetching {
+		// If we need to revalidate, return with a closed channel
+		// so the caller will immediately retry the cache
+		if r.Info.MustRevalidate {
+			ch := make(chan struct{})
+			close(ch)
+			return ch
+		}
```
Comment (FFMMM) [inline agent/cache/cache.go:566]: something that I am still unsure about with this is how it affects other cache types 🤔

File: agent/agent_endpoint_test.go (hunk 3 above)
Comment (rboyer) [reply agent/agent_endpoint_test.go:6282]: I could add it here I guess. A lot of the API-side endpoint tests that test something about caching implicitly rely upon caching behavior where the cache takes longer than the execution of a test suite to prune.

So in this case the original non-blocking query implicitly populated the cache for this leaf entry. Also the initial non-blocking internal query used by the still-running goroutine up from line 6270 also refreshed that entry again. This new non-blocking query will see that the cache entry is present and usable/valid and return without blocking for the life of the above blocking query (as is the errant behavior we're fixing).

**Review by kisunji — APPROVED** [review]

File: agent/cache/cache.go [hunk 6]
```diff
@@ -376,6 +376,13 @@ func (c *Cache) getEntryLocked(
 	// Check if re-validate is requested. If so the first time round the
 	// loop is not a hit but subsequent ones should be treated normally.
 	if !tEntry.Opts.Refresh && info.MustRevalidate {
+		if entry.Fetching {
```
Comment (FFMMM) [inline agent/cache/cache.go:379]: Ah, this is one of those lines that I hope doesn't surface code that was relying on side effects here.

AFAIK, (and I don't know much)  there's not a lot of cache types that actually use `MustRevalidate`.

So my gut tells me that this should work beautifully for the bug in https://github.com/hashicorp/consul/issues/12048 🤞🏼 

But it would feel good to check in with @banks or @freddygv if they have more context here to get a third/ forth pair of eyes 💯

File: agent/agent_endpoint_test.go [hunk 7]
```diff
@@ -6202,6 +6202,101 @@ func TestAgentConnectCALeafCert_goodNotLocal(t *testing.T) {
...
+		serialNumber = issued.SerialNumber
+
+		require.Equal(t, "MISS", resp.Header().Get("X-Cache"),
+			"for the leaf cert cache type these are always MISS")
+		index = resp.Header().Get("X-Consul-Index")
+	})
+
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	go func() {
```
Comment (FFMMM) [inline agent/agent_endpoint_test.go:6265]: this is a non actionable comment:

for any of y'all wondering about testing that the blocking query does what we want for the leaf cert, that use case is here: https://github.com/hashicorp/consul/blob/main/agent/agent_endpoint_test.go#L6016-L6033

**Comment by FFMMM** [comment]
hey @rboyer thanks loads for taking this on 🥇  💯 ; that bug has been in the back of my mind 🪨 

i see the `backport/1.12` tag; I'll leave it up to you if you want to check this in for `1.12` or wait to chat with folks more familiar with the cache layer and have it in  `1.12.1`. Regardless, I made a milestone tag for `1.12.1` fyi .

File: agent/agent_endpoint_test.go [hunk 8]
```diff
@@ -6202,6 +6202,101 @@ func TestAgentConnectCALeafCert_goodNotLocal(t *testing.T) {
...
+		// launch goroutine for blocking query
+		req := httptest.NewRequest("GET", "/v1/agent/connect/ca/leaf/test?index="+index, nil).Clone(ctx)
+		resp := httptest.NewRecorder()
+		a.srv.h.ServeHTTP(resp, req)
+	}()
+
+	// We just need to ensure that the above blocking query is in-flight before
+	// the next step, so do a little sleep.
+	time.Sleep(50 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (rboyer) [reply agent/agent_endpoint_test.go:6274]: Much like all of the other blocking query tests, the trick is figuring out how to initiate a blocking query that does not return, know it has reached the important part, and only THEN issue your followup query. We don't have any signaling mechanism to know exactly when something is actually blocking.

**Review by boxofrad — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/645590.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f3ce353a87e2aae6b82bc6ebcea947d726352284 onto `release/1.12.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f3ce353a87e2aae6b82bc6ebcea947d726352284 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit f3ce353a87e2aae6b82bc6ebcea947d726352284 onto `release/1.10.x` succeeded!
