### PR TITLE
Agent anti-entropy test fixes

### LINKED ISSUE #1974: Track down TestClient_RPC_TLS failure...
```
--- FAIL: TestClient_RPC (0.01s)
	client_test.go:183: bad len
```

### LINKED ISSUE #2050: Track down TestAgentAntiEntropy_EnableTagOverride
```
--- FAIL: TestAgentAntiEntropy_EnableTagOverride (0.45s)
    local_test.go:253: bad: &{svc_id1 svc1 [tag1_mod]  7100 true {0 0}} &{svc_id1 svc1 [tag1_mod]  6100 true {0 0}}
```

### LINKED ISSUE #2052: Track down TestAgentAntiEntropy_NodeInfo failure
```
--- FAIL: TestAgentAntiEntropy_NodeInfo (4.00s)
	local_test.go:896: bad: map[]
```

### PR DESCRIPTION
**Pull request by kyhavlov**
Fixes #2050 
Fixes #2052
Fixes #1974

### CODE REVIEW

File: command/agent/local_test.go [hunk 1]
```diff
@@ -99,139 +107,144 @@ func TestAgentAntiEntropy_Services(t *testing.T) {
...
+			if !status.inSync {
+				t.Fatalf("should be in sync: %v %v", name, status)
+			}
 		}
+
+		return true, nil
 	}
 
+	testutil.WaitForResult(verifyServices, func(err error) {
+		t.Fatalf("failed to get sorted service nodes: %v", err)
```
Comment (slackpad) [inline command/agent/local_test.go]: This looks like a stale message.

File: command/agent/local_test.go [hunk 2]
```diff
@@ -99,139 +107,144 @@ func TestAgentAntiEntropy_Services(t *testing.T) {
...
+			if !status.inSync {
+				t.Fatalf("should be in sync: %v %v", name, status)
+			}
+		}
+
+		return true, nil
 	}
+
+	testutil.WaitForResult(verifyServicesAfterRemove, func(err error) {
+		t.Fatalf("failed to get sorted service nodes: %v", err)
```
Comment (slackpad) [inline command/agent/local_test.go]: Same for this one.

File: command/agent/local_test.go [hunk 3]
```diff
@@ -287,48 +300,55 @@ func TestAgentAntiEntropy_EnableTagOverride(t *testing.T) {
...
+			if !status.inSync {
+				return false, fmt.Errorf("should be in sync: %v %v", name, status)
+			}
 		}
+
+		return true, nil
 	}
+
+	testutil.WaitForResult(verifyServices, func(err error) {
+		t.Fatalf("failed to get sorted service nodes: %v", err)
```
Comment (slackpad) [inline command/agent/local_test.go]: Same for this one.

**Comment by slackpad** [comment]
LGTM
