### PR TITLE
watch: fix script watches with single arg

### LINKED ISSUE #8284: [1.8.0] watch config fails when args length is 1
#### Overview of the Issue

When we upgrade consul from 1.7.2 to 1.8.0, we found watches's args paramater can't accept one dimensional string array .

#### Reproduction Steps

1. Our watch defination is
```
{
  "watches":[
    {
      "type": "key",
      "key": "haas/whitelist/common",
      "handler_type": "script",
      "args": ["/etc/consul.d/watcher.py"]
    }]
}
```
In 1.7.2, it works good.
2. After Upgrade to 1.8.0, we always got 
Jul 10 16:44:07 haas-api-2 consul: 2020-07-10T16:44:07.534+0800 [ERROR] agent: Error starting agent: error="Watch args must be a list of strings"
Jul 10 16:44:07 haas-api-2 consul: 2020-07-10T16:44:07.534+0800 [INFO]  agent: Exit code: code=1
Then consul client failed to start
3. If we change the defination as below, 
```
{
  "watches":[
    {
      "type": "key",
      "key": "haas/whitelist/common",
      "handler_type": "script",
      "args": ["/etc/consul.d/watcher.py"**,""]**
    }]
}
```
It works.

### Consul info for both Client and Server
Both Client & Server are

Consul v1.8.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

### Operating system and Environment details

OS is CentOS 7.6, 64bit.

### Log Fragments
Just as above.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #8284

First commit extracts a function to make it possible to test the fix. Second commit contains the fix.

Draft for now until I finish off the additional test cases.

### CODE REVIEW

**Comment by dnephin** [comment]
`TestAgent_Monitor` test failure is a flake, it passes locally.

File: agent/watch_handler.go [hunk 1]
```diff
@@ -225,3 +218,25 @@ func makeWatchPlan(logger hclog.Logger, params map[string]interface{}) (*watch.P
 	}
 	return wp, nil
 }
+
+func parseWatchArgs(args interface{}) ([]string, error) {
+	switch args := args.(type) {
+	case string:
+		return []string{args}, nil
+	case []string:
```
Comment (i0rek) [inline agent/watch_handler.go:226]: Are both cases require to fix this bug?

Comment (dnephin) [reply agent/watch_handler.go:226]: Ah, good question. No I think only the first case is, but I added this additional case because it seems wrong to error if the input is already the desired type.
