### PR TITLE
fix monitor to only start the monitor in json format when requested

### LINKED ISSUE #10357: consul monitor log-json do not produce json format logs
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue
When starting `consul monitor  -log-json` the logs are not in json format

#### Reproduction Steps
- `consul agent` in tab1
- `consul monitor  -log-json`  in another tab
- notice the logs are not in json

### Operating system and Environment details

The bug is os independant

### Log Fragments

```
consul monitor -log-level=DEBUG  -log-json
2021-06-07T10:43:01.061-0400 [INFO]  agent: Caught: signal=interrupt
2021-06-07T10:43:01.061-0400 [INFO]  agent: Graceful shutdown disabled. Exiting
2021-06-07T10:43:01.061-0400 [INFO]  agent: Requesting shutdown
2021-06-07T10:43:01.061-0400 [INFO]  agent.server: shutting down server
2021-06-07T10:43:01.061-0400 [DEBUG] agent.leader: stopping routine: routine="federation state anti-entropy"
2021-06-07T10:43:01.061-0400 [DEBUG] agent.leader: stopping routine: routine="federation state pruning"
2021-06-07T10:43:01.061-0400 [DEBUG] agent.leader: stopping routine: routine="intermediate cert renew watch"
2021-06-07T10:43:01.061-0400 [DEBUG] agent.server.usage_metrics: usage metrics reporter shutting down
2021-06-07T10:43:01.061-0400 [DEBUG] agent.leader: stopped routine: routine="federation state pruning"
2021-06-07T10:43:01.061-0400 [DEBUG] agent.leader: stopping routine: routine="CA root pruning"
2021-06-07T10:43:01.062-0400 [DEBUG] agent.leader: stopped routine: routine="intermediate cert renew watch"
2021-06-07T10:43:01.062-0400 [WARN]  agent.server.serf.lan: serf: Shutdown without a Leave
2021-06-07T10:43:01.062-0400 [DEBUG] agent.leader: stopped routine: routine="CA root pruning"
2021-06-07T10:43:01.062-0400 [ERROR] agent.server: error performing anti-entropy sync of federation state: error="context canceled"
2021-06-07T10:43:01.062-0400 [DEBUG] agent.leader: stopped routine: routine="federation state anti-entropy"
2021-06-07T10:43:01.062-0400 [DEBUG] agent.server.autopilot: state update routine is now stopped
2021-06-07T10:43:01.062-0400 [DEBUG] agent.server.autopilot: autopilot is now stopped
2021-06-07T10:43:01.062-0400 [WARN]  agent.server.serf.wan: serf: Shutdown without a Leave
2021-06-07T10:43:01.062-0400 [INFO]  agent.router.manager: shutting down
2021-06-07T10:43:01.063-0400 [INFO]  agent.router.manager: shutting down
2021-06-07T10:43:01.063-0400 [INFO]  agent: consul server down
2021-06-07T10:43:01.063-0400 [INFO]  agent: shutdown complete
2021-06-07T10:43:01.063-0400 [INFO]  agent: Stopping server: protocol=DNS address=127.0.0.1:8600 network=tcp
2021-06-07T10:43:01.063-0400 [INFO]  agent: Stopping server: protocol=DNS address=127.0.0.1:8600 network=udp
2021-06-07T10:43:01.064-0400 [INFO]  agent: Stopping server: address=127.0.0.1:8500 network=tcp protocol=http
2021-06-07T10:43:02.069-0400 [WARN]  agent: Failed to stop server: address=127.0.0.1:8500 network=tcp protocol=http
2021-06-07T10:43:02.069-0400 [INFO]  agent: Waiting for endpoints to shut down
2021-06-07T10:43:02.069-0400 [INFO]  agent: Endpoints down
```

### PR DESCRIPTION
**Pull request by dhiaayachi**
when starting a new monitor we were starting (in case of json monitor) a json monitor and then overwrite it with a line monitor.
This will start one or the other.
Fix #10357

### CODE REVIEW

**Review by dnephin — APPROVED** [review]
LGTM!

File: command/monitor/monitor_test.go [hunk 1]
```diff
@@ -120,3 +122,66 @@ func TestMonitorCommand_LogJSONValidFlag(t *testing.T) {
...
+				}
+			}
+		}
+		shutdownCh <- struct{}{}
+
+	}()
+
+	select {
+	case ret := <-exitCode:
+		if ret != 0 {
```
Comment (dnephin) [inline command/monitor/monitor_test.go:180]: There are two goroutines sending to this chan, but this only checks the return value once, which seems like it could easily pass even when one of the goroutines fails.

Instead of running the assertion in a goroutine, could we use a `bufio.Scanner` in the main thread? We could then read lines, and assert some number of log lines is json encoded. Once it successfully we can shutdown the agent and goroutines.

Maybe we'll need to run another goroutine to perform a couple operations to ensure that the agent is producing logs.

File: command/monitor/monitor_test.go [hunk 2]
```diff
@@ -120,3 +122,66 @@ func TestMonitorCommand_LogJSONValidFlag(t *testing.T) {
...
+		wg.Done() // Signal that this goroutine is at least running now
+		exitCode <- c.Run(args)
+	}()
+
+	// Wait for that routine to at least be running
+	wg.Wait()
+
+	// Read the logs and try to json marshall it
+	go func() {
+		time.Sleep(1 * time.Second)
```
Comment (dnephin) [inline command/monitor/monitor_test.go:160]: Generally I try to avoid any sleeps in a test, and 1 second is a pretty long sleep. I think with the suggestion below we can remove this sleep.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/381703.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dda3e6879146adac2ab992f60510e023aa6b7a2c onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dda3e6879146adac2ab992f60510e023aa6b7a2c onto `release/1.9.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit dda3e6879146adac2ab992f60510e023aa6b7a2c onto `release/1.8.x` succeeded!
