### PR TITLE
xds: emit a labeled gauge of connected xDS streams by version

### LINKED ISSUE #10099: add simple gauge metric in the xds.Server for number of attached xds streams broken down by v2/v3
This should help with tracking down un-upgraded envoys.

### PR DESCRIPTION
**Pull request by rboyer**
Fixes #10099

### CODE REVIEW

File: agent/xds/xds_protocol_helpers_test.go [hunk 1]
```diff
@@ -155,6 +157,16 @@ func newTestServerScenarioInner(
 		envoy.Close()
 	})
 
+	sink := metrics.NewInmemSink(1*time.Minute, 1*time.Minute)
+	cfg := metrics.DefaultConfig("consul.xds.test")
+	cfg.EnableHostname = false
```
Comment (dnephin) [inline agent/xds/xds_protocol_helpers_test.go:162]:
```suggestion
	cfg := metrics.DefaultConfig("consul.xds.test")
	cfg.EnableHostname = false
	cfg.EnableRuntimeMetrics = false
```

minor: I'd suggest setting `EnableRuntimeMetrics` to false as well, to prevent the unnecessary background goroutine from starting.

File: agent/xds/xds_protocol_helpers_test.go [hunk 2]
```diff
@@ -647,3 +660,23 @@ func runStep(t *testing.T, name string, fn func(t *testing.T)) {
 		t.FailNow()
 	}
 }
+
+func requireProtocolVersionGauge(
```
Comment (dnephin) [inline agent/xds/xds_protocol_helpers_test.go:664]: Do you expect that we will call this from other places? Right now it's only called from one place so it might be good to keep it next to the one call site.

File: agent/xds/server.go [hunk 3]
```diff
@@ -141,6 +150,36 @@ type Server struct {
...
+		return func() {}
+	}
+
+	count := atomic.AddUint64(counter, 1)
+	metrics.SetGaugeWithLabels([]string{"xds", "server", "streams"}, float32(count),
+		[]metrics.Label{{Name: "version", Value: xdsVersion}})
+	return func() {
+		count := atomic.AddUint64(counter, ^uint64(0))
+		metrics.SetGaugeWithLabels([]string{"xds", "server", "streams"}, float32(count),
+			[]metrics.Label{{Name: "version", Value: xdsVersion}})
```
Comment (dnephin) [inline agent/xds/server.go:181]: Minor: could define the labels once and use them in both calls to set gauges to shrink the line lengths a bit.

**Review by dnephin — APPROVED** [review]
LGTM, couple small some suggestions, nothing blocking

File: agent/xds/xds_protocol_helpers_test.go (hunk 2 above)
Comment (rboyer) [reply agent/xds/xds_protocol_helpers_test.go:664]: It's called in two places: `server_test.go` and `delta_test.go` for v2 and v3 respectively.

File: agent/xds/xds_protocol_helpers_test.go (hunk 1 above)
Comment (rboyer) [reply agent/xds/xds_protocol_helpers_test.go:162]: :+1:

File: agent/xds/server.go (hunk 3 above)
Comment (rboyer) [reply agent/xds/server.go]: :+1:

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/369442.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit ede14b7c54cba42d9a1376544ba2474c0d95a290 onto `release/1.10.x` succeeded!

File: agent/xds/server.go [hunk 4]
```diff
@@ -141,6 +150,36 @@ type Server struct {
 	AuthCheckFrequency time.Duration
 
 	DisableV2Protocol bool
+
```
Comment (markan) [inline agent/xds/server.go:153]: Am I correct in assuming that there can only be one Server instance per host? Do we run multiple servers on different ports or anything like that?

**Review by markan — APPROVED** [review]
Other than that one question, looks good to me

File: agent/xds/server.go (hunk 4 above)
Comment (rboyer) [reply agent/xds/server.go:153]: There is exactly one xDS server per consul agent.
