### PR TITLE
xds: only try to create an ipv6 expose checks listener if ipv6 is supported by the kernel

### LINKED ISSUE #9311: consul connect fails to boot envoy when health checks are exposed and ipv6 is disabled
#### Overview of the Issue

Envoy refuses to create exposed health check listeners when ipv6 is disabled. Here’s a relevant line from the logs:
 
```
[2020-11-19 18:25:07.670][144682][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:101] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) exposed_path_grpchealthv1HealthCheck:0.0.0.0:51700: IPv6 addresses are not supported on this machine: [::1]:0
```
 
The only place that seems to use an IPv6 address in the listener config is in the source_prefix_ranges:

``` 
"filter_chain_match": {
"source_prefix_ranges": [
  {
   "address_prefix": "127.0.0.1",
   "prefix_len": 8
  },
  {
   "address_prefix": "::1",
   "prefix_len": 128
  },
  {
   "address_prefix": "45.32.96.231",
   "prefix_len": 32
  }
]
}
```
 
It looks like there’s currently not a way to skip including the IPv6 address in [listeners.go](https://github.com/hashicorp/consul/blob/v1.8.4/agent/xds/listeners.go#L538)

There are no workarounds.

#### Reproduction Steps

The problem should be reproducible within a CentOS7 container with [ipv6 disabled](https://linuxhint.com/disable_ipv6_centos7/)

### Operating system and Environment details

We are using Consul 1.8, Envoy 1.14.4, and RHEL7.

### PR DESCRIPTION
**Pull request by rboyer**
Fixes #9311 

This only fails if the kernel has ipv6 hard-disabled. It is not sufficient to merely not provide an ipv6 address for a network interface. For local testing I [disabled it in grub](https://itsfoss.com/disable-ipv6-ubuntu-linux/) on an ubuntu linux VM first.

Then register a service with connect locally with a config file like:
```
...
connect {
 sidecar_service {
  proxy {
   expose {
    checks = true
   }
  }
 }
}
...
```

Then try launching the sidecar and grep the envoy logs for the word `expose`

TODO
- [x] add expose checks envoy integration test

### CODE REVIEW

File: agent/xds/listeners.go [hunk 1]
```diff
@@ -690,12 +690,22 @@ func (s *Server) makeExposedCheckListener(cfgSnap *proxycfg.ConfigSnapshot, clus
 			advertiseLen = 128
 		}
 
+		ranges := make([]*envoycore.CidrRange, 0, 3)
+		ranges = append(ranges,
+			&envoycore.CidrRange{AddressPrefix: "127.0.0.1", PrefixLen: &wrappers.UInt32Value{Value: 8}},
+			&envoycore.CidrRange{AddressPrefix: advertise, PrefixLen: &wrappers.UInt32Value{Value: uint32(advertiseLen)}},
+		)
+
+		if ok, err := kernelSupportsIPv6(); err != nil {
```
Comment (markan) [inline agent/xds/listeners.go:699]: @rboyer and I had a chat about testing; it's kind of thorny. Mocking this gets us into trouble with parallel unit tests, as we risk changing an invariant under other tests noses.

**Review by markan — APPROVED** [review]
Looks good to me.

File: test/integration/connect/envoy/case-expose-checks/service_s2.hcl [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+        expose {
+          checks = true
+        }
+      }
+    }
+  }
+  checks = [
+    {
+      name     = "http"
+      http     = "http://127.0.0.1:8181/debug"
```
Comment (rboyer) [inline test/integration/connect/envoy/case-expose-checks/service_s2.hcl:16]: The fake workloads are usually copies of `fortio` which has a webserver builtin. One of the pages is `/debug` so that'll 200, hence why it's used here as the healthcheck standin.

File: test/integration/connect/envoy/helpers.bash [hunk 3]
```diff
@@ -152,6 +152,37 @@ function assert_envoy_version {
...
+  HCM_NAME=$(echo "$HCM" | jq -r '.name')
+  HCM_PATH=$(echo "$HCM" | jq -r '.config.route_config.virtual_hosts[0].routes[0].match.path')
+  echo "HCM = $HCM"
+  [ "${HCM_NAME:-}" == "envoy.http_connection_manager" ]
+  [ "${HCM_PATH:-}" == "${EXPECT_PATH}" ]
+}
+
+function get_envoy_expose_checks_listener_once {
+  local HOSTPORT=$1
+  run curl -s -f $HOSTPORT/config_dump
```
Comment (rboyer) [inline test/integration/connect/envoy/helpers.bash:181]: Captured output from a run:
```
{
  "configs": [
    {
      "@type": "type.googleapis.com/envoy.admin.v3.BootstrapConfigDump",
      ...snip...
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.ClustersConfigDump",
      ...snip...
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.ListenersConfigDump",
      "version_info": "00000001",
      "dynamic_listeners": [
        {
          "name": "public_listener:0.0.0.0:21001",
          ...snip...
        },
        {
          "name": "exposed_path_debug:0.0.0.0:21500",
          "active_state": {
            "version_info": "00000001",
            "listener": {
              "@type": "type.googleapis.com/envoy.api.v2.Listener",
              "name": "exposed_path_debug:0.0.0.0:21500",
              "address": {
                "socket_address": {
                  "address": "0.0.0.0",
                  "port_value": 21500
                }
              },
              "filter_chains": [
                {
                  "filter_chain_match": {
                    "source_prefix_ranges": [
                      {
                        "address_prefix": "127.0.0.1",
                        "prefix_len": 8
                      },
                      {
                        "address_prefix": "127.0.0.1",
                        "prefix_len": 32
                      },
                      {
                        "address_prefix": "::1",
                        "prefix_len": 128
                      }
                    ]
                  },
                  "filters": [
                    {
                      "name": "envoy.http_connection_manager",
                      "config": {
                        "http_filters": [
                          {
                            "name": "envoy.router"
                          }
                        ],
                        "stat_prefix": "exposed_path_filter_debug_21500",
                        "route_config": {
                          "name": "exposed_path_filter_debug_21500",
                          "virtual_hosts": [
                            {
                              "routes": [
                                {
                                  "route": {
                                    "cluster": "local_app"
                                  },
                                  "match": {
                                    "path": "/debug"
                                  }
                                }
                              ],
                              "domains": [
                                "*"
                              ],
                              "name": "exposed_path_filter_debug_21500"
                            }
                          ]
                        },
                        "tracing": {
                          "random_sampling": {}
                        }
                      }
                    }
                  ]
                }
              ]
            },
            "last_updated": "2021-02-17T19:32:31.547Z"
          }
        }
      ]
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.ScopedRoutesConfigDump"
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.RoutesConfigDump",
      ...snip...
    },
    {
      "@type": "type.googleapis.com/envoy.admin.v3.SecretsConfigDump"
    }
  ]
}
```

File: test/integration/connect/envoy/helpers.bash [hunk 4]
```diff
@@ -152,6 +152,37 @@ function assert_envoy_version {
...
+  BODY=$(get_envoy_expose_checks_listener_once $HOSTPORT)
+  echo "BODY = $BODY"
+
+  CHAINS=$(echo "$BODY" | jq '.active_state.listener.filter_chains | length')
+  echo "CHAINS = $CHAINS (expect 1)"
+  [ "${CHAINS:-0}" -eq 1 ]
+
+  RANGES=$(echo "$BODY" | jq '.active_state.listener.filter_chains[0].filter_chain_match.source_prefix_ranges | length')
+  echo "RANGES = $RANGES (expect 3)"
+  [ "${RANGES:-0}" -eq 3 ]
```
Comment (markan) [inline test/integration/connect/envoy/helpers.bash:169]: Is this expected to be 2 on a IPv4 only system with `conf.all.disable_ipv6=1` ?

Comment (rboyer) [reply test/integration/connect/envoy/helpers.bash:169]: Yes. I believe our golden tests for `agent/xds` will fail on an ipv6-less machine so at least these two sets of tests would break at the same time?

Comment (markan) [reply test/integration/connect/envoy/helpers.bash:169]: Might be worth a comment at the head of the test explaining that for the future reader.

Comment (rboyer) [reply test/integration/connect/envoy/helpers.bash:169]: :+1:

File: test/integration/connect/envoy/case-expose-checks/verify.bats [hunk 5]
```diff
@@ -37,5 +37,6 @@ load helpers
 }
 
 @test "s2 exposes checks on a new listener" {
+exit 1
```
Comment (markan) [inline test/integration/connect/envoy/case-expose-checks/verify.bats:40]: This fails the test, right? Is that intended?

Comment (rboyer) [reply test/integration/connect/envoy/case-expose-checks/verify.bats]: Ha. I did not intend to commit it. Removed.

I did this because it triggers the `capture.sh` script to run when the test fails so all of the envoy information is written to the `workdir` along with the logs so I could figure out what was happening. I just forgot to remove it.

**Review by markan — APPROVED** [review]
