### PR TITLE
Changes remote exec KV read to call GetTokenForAgent().

### LINKED ISSUE #3160: consul exec is denied even though acl allows
Version 0.8.4 both on server and client.
I have acl turned on on this DC, and of course `"disable_remote_exec": false` on every server for this case.
I try to run `consul exec` both with token and without token and I get errors of `Permission denied`.
Attaching the ACL for anonymous and the exec command.
I have no idea what I'm doing wrong.
Anonymous ACL:
```
key "" {
  policy = "read"
}
event "" {
  policy = "write"
}
event "*" {
  policy = "write"
}
```
(Master ACL is similar)
the exec commands I tried:
```
[root@tr-test ~]$ consul exec -verbose -token="792c6304-772c-4672-a956-2e0aadbea205" -node visat ls /tmp/
Created remote execution session: 778caffa-d091-58a7-0116-14206a1854b3
Uploaded remote execution spec
Fired remote execution event: c790aa4d-cbc2-eb82-c24a-2123553aa30b
0 / 0 node(s) completed / acknowledged
Completed in 2.00 seconds
[root@tr-test ~]$ consul exec -verbose -node viast ls /tmp/
Created remote execution session: 377be95b-02f0-928a-b9bf-7efcba1c8851
Failed to create job file: Unexpected response code: 403 (rpc error: Permission denied)
```
consul monitor on visat (the node I want to exec on)
```
2017/06/19 07:41:13 [ERR] consul: RPC failed to server 10.2.1.185:8300: rpc error: rpc error: Permission denied
2017/06/19 07:41:13 [ERR] agent: failed to ack remote exec job: rpc error: rpc error: Permission denied
```
Note that the first exec with the token produces the access denied message on the node consul monitor, while the exec without the token just exits on spot and doesn't prompt log message on the node.

### PR DESCRIPTION
**Pull request by slackpad**
This lets it use the `acl_agent_token` instead of just the `acl_token`. Docs were also updated accordingly.

Fixes #3160.

### CODE REVIEW

File: agent/remote_exec_test.go [hunk 1]
```diff
@@ -107,6 +107,15 @@ func TestRemoteExecGetSpec_ACLToken(t *testing.T) {
 	testRemoteExecGetSpec(t, cfg)
 }
 
+func TestRemoteExecGetSpec_ACLAgentToken(t *testing.T) {
+	t.Parallel()
+	cfg := TestConfig()
+	cfg.ACLDatacenter = "dc1"
+	cfg.ACLAgentToken = "root"
+	cfg.ACLDefaultPolicy = "deny"
+	testRemoteExecGetSpec(t, cfg)
```
Comment (preetapan) [inline agent/remote_exec_test.go]: I am not sure if this this testing anything here. It is passing this config struct to `testRemoteExecGetSpec`, but that doesn't seem to get passed to the test agent it creates there. What exactly is the intention of this `TestRemoteExecGetSpec_ACLAgentToken` test case?

File: agent/remote_exec_test.go [hunk 2]
```diff
@@ -107,6 +107,15 @@ func TestRemoteExecGetSpec_ACLToken(t *testing.T) {
...
+}
+
 func testRemoteExecGetSpec(t *testing.T, c *Config) {
 	a := NewTestAgent(t.Name(), nil)
```
Comment (preetapan) [inline agent/remote_exec_test.go]: Ah, maybe the second arg is not supposed to be nil but c instead?

Comment (slackpad) [inline agent/remote_exec_test.go]: Oh good catch - yeah this must be working because ACLs aren't getting enabled for either case. This is supposed to make sure we can get the token from the ACL agent token, and the other test checks the ACL token. I'll pass that through and make sure it looks like it's properly using ACLs.

**Comment by slackpad** [comment]
@preetapan did a rebase and updated that unit test, can you please take another look?

**Comment by slackpad** [comment]
The unhappy path test found a similar `nil` getting passed in for the config, so I fixed that as well.
