### PR TITLE
Make RPC limits reloadable

### LINKED ISSUE #4012: Make limits a reloadable configuration
### Description of the Issue (and unexpected/desired result)
Right now it's not possible to apply [limit](https://www.consul.io/docs/agent/options.html#limits) changes without a restart. It could be nice make them a reloadable configuration.
 
### Reproduction steps
- edit `limits` in the config
- send a `SIGHUP` to consul
- `limits` are not refreshed at runtime

### PR DESCRIPTION
**Pull request by mkeeler**
Fixes #4012 
Supersedes #4019 

Thanks @jwasinger for the start to this. I went ahead and took it the rest of the way.

The rpc rate limiter is now stored as an atomic.Value. Unfortunately the rate.Limiter has no method for updating the burst so the only option is to recreate the limiter all together and them atomically set the new one. There are only a handful of places this is used so now they just load the atomic val and call the Allow function on the Limiter.

This PR also updates the website to mention that rpc limits are reloadable and implements some additional tests to verify the Client structure is properly reloading the limiter.

### CODE REVIEW

File: agent/consul/client_test.go [hunk 1]
```diff
@@ -665,3 +667,25 @@ func TestClient_Encrypted(t *testing.T) {
...
+	defer c.Shutdown()
+
+	limiter := c.rpcLimiter.Load().(*rate.Limiter)
+	require.Equal(t, rate.Limit(500), limiter.Limit())
+	require.Equal(t, 5000, limiter.Burst())
+
+	c.config.RPCRate = 1000
+	c.config.RPCMaxBurst = 10000
+
+	require.NoError(t, c.ReloadConfig(c.config))
```
Comment (banks) [inline agent/consul/client_test.go]: This all looks good to me but I wonder if we should have 3 different goroutines all spawn and run this in a loop and verify that `go test -race` doesn't pick up any concurrency issues?

Comment (mkeeler) [reply agent/consul/client_test.go]: ReloadConfig can't be called concurrently. At least as the code stands today.

Client.ReloadConfig is only called from Agent.ReloadConfig which in turn is only called from cmd.handleReload (command/agent/agent.go) and finally handleReload is only called from a loop in cmd.run which is processing the chan of signals. As it can only handle 1 signal at a time, ReloadConfig can therefore not be called concurrently so there can be no race. I have no doubt that if it was called concurrently there would be several problems (like watches, services etc could be loaded multiple times)

Comment (banks) [reply agent/consul/client_test.go]: Oh OK. Maybe I confused the calls, I was mostly wanting to validate the `atomic.Value` stuff - I guess that is about calling this concurrently with RPC client reading the values so perhaps the valid test would be to start a goroutine (or 10) making RPCs while calling this in a loop or something.

It's not a blocker, it just might be an extra sanity check that there aren't any obvious concurrency issues.

Comment (mkeeler) [reply agent/consul/client_test.go]: What would that really test? To me it looks like that would be testing that atomc.Value.(Load/Store) do what they say they do. And since that is an upstream library (and builtin to the language) I would say that testing that is outside the scope of Consul testing and would only serve to lengthen test times. We should be able to assume that those atomic primitives work as expected. Because the whole limiter is now stored within the value it is impossible to access it without a load/store and since we don't do any write operations into an existing limiter during reload (but rather create a new limiter) there can be no race. Additionally the limiter looks to be thread safe in that if you did set new limits or perform other operations it will lock itself internally (which is how we can use one limiter with multiple go routines). Looks to be = I read through the code. I don't think they expressly say in the package documentation that this is the case.

Comment (banks) [reply agent/consul/client_test.go]: > We should be able to assume that those atomic primitives work as expected. 

It's often the case that atomic values are misused. My suggestion was to guard against any of the common pitfalls of using them!

I don't think it's critical so merge away but in general go's race detector is easy to use and can often catch subtle and common mistakes/bad assumptions in how `sync` primitives are used. 😄 .
