### PR TITLE
agent: tolerate more failure scenarios during service registration with central config enabled

### LINKED ISSUE #6323: central service config resolution can be disregarded in restart and failure conditions
There are several ways a service can end up registered locally on an agent:

1. Registered via HTTP API.
2. Registered via Config File HCL/JSON snippet.
3. Agent cold restart that reloads from persisted copy of (1).
4. Agent hot reload that reloads from (2) and a persisted copy of (1).

Of these, (1) and (4) happen when the agent is fully operational and (2) and (3) happen while the agent is still wiring itself up. Notably config file and persistent reloads _must_ happen before the Agent API is available and anti-entropy starts happening. If that is violated then there may be catalog registration flaps or local uses of the API that see things vanish and come back into existence.

If central service config is enabled any attempt by the agent to register a service locally is diverted through the ServiceManager. This applies equally to (1), (2), (3), and (4). The point of central service config is to only ever surface the _merged config_ in the Agent API and sent to the catalog. The original user-provided (incomplete) service registration should never be seen outside of the agent process. It would be easy to have ServiceManager hard-wait for the necessary RPCs to complete to flatten `proxy-defaults` and `service-defaults` down for use, and that would totally be ok for (1) and (4) but it is impossible for (2) and (3).

Both of those happen while the agent is still wiring itself up and it may not even be able to execute RPCs yet, so the service manager today assumes that errors during the _first_ central service config fetch are acceptable and it just leaks the incomplete registration out into the world. Very quickly after the rest of startup completes the actual central config comes back and the state is corrected.

If anything polls the Agent API during this window of time they'll see the wrong config. This definitely can happen with `consul connect envoy` during bootstrap generation. If you quickly sequence:

1. `consul agent` start
2. `consul services register`
3. `consul agent` restart
4. `consul services (re-)register`
5. `consul connect envoy`

The resulting envoy config randomly will omit things like observability settings from central config. And because the consul binary exec'd away nothing will fix that lack in the envoy without a restart.

### PR DESCRIPTION
**Pull request by rboyer**
Also:

* Finished threading `replaceExistingChecks` setting (from GH-4905) through service manager.

* Respected the original `configSource` value that was used to register a service or a check when restoring persisted data.

* Run several existing tests with and without central config enabled (not exhaustive yet).

* Switch to `ioutil.ReadFile` for all types of agent persistence.

Fixes #6323

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -1984,13 +2017,116 @@ func (a *Agent) purgeCheck(checkID types.CheckID) error {
...
+		if err := json.Unmarshal(buf, &p); err != nil {
+			a.logger.Printf("[ERR] agent: Failed decoding service config file %q: %s", file, err)
+			continue
+		}
+		out[p.ServiceID] = p.Defaults.ToResponse()
+	}
+
+	return out, nil
+}
+
```
Comment (banks) [inline agent/agent.go]: Thought: I realise this is following the existing pattern, but do you think it would be worth factoring this out into a separate file? This file being big doesn't cause too many practical issues for me so maybe not worth the effort now but I wonder if all the persistence stuff in here would be better as a separate package at some point or at least a separate file in this one?

File: agent/agent.go [hunk 2]
```diff
@@ -1984,13 +2017,116 @@ func (a *Agent) purgeCheck(checkID types.CheckID) error {
...
+// feeds into the ServiceManager at registration time so that it may be
+// restored later on.
+type persistedServiceConfig struct {
+	ServiceID string
+	Defaults  *persistedServiceConfigResponse
+}
+
+// persistedServiceConfigResponse is a mirror image of
+// *structs.ServiceConfigResponse without QueryMeta fields. These should be
+// kept in sync.
```
Comment (banks) [inline agent/agent.go]: Why can't we use the existing struct? Does it add empty QueryMeta fields to the JSON we persist? I'm OK with this just not super sure why it's important.

File: agent/agent.go [hunk 3]
```diff
@@ -1999,25 +2135,80 @@ func (a *Agent) AddServiceAndReplaceChecks(service *structs.NodeService, chkType
...
+type addServiceRequest struct {
+	service               *structs.NodeService
+	chkTypes              []*structs.CheckType
+	persistService        *structs.NodeService
+	persistDefaults       *structs.ServiceConfigResponse
+	persist               bool
+	persistServiceConfig  bool
+	token                 string
+	replaceExistingChecks bool
+	source                configSource
```
Comment (banks) [inline agent/agent.go]: I was going to comment on the number of arguments in `addServiceLocked` growing then saw this. Is there a reason we can't re-use this across the other `[aA]ddService(Locked)` methods? I don't feel super strongly just seems more consistent if we are bothering to define a struct in this case etc.

File: agent/service_manager.go [hunk 4]
```diff
@@ -18,100 +18,200 @@ import (
...
+	if updating {
+		s.agent.logger.Printf("[DEBUG] agent.manager: updated local registration for service %q", service.ID)
+	} else {
 		s.agent.logger.Printf("[DEBUG] agent.manager: added local registration for service %q", service.ID)
 	}
 
 	return nil
 }
 
+// NOTE: must hold the Agent.stateLock!
```
Comment (banks) [inline agent/service_manager.go]: This confuses me - the method holds the manager's `servicesLock`. Do you mean the caller must hold the state lock when calling?

File: agent/agent.go (hunk 2 above)
Comment (rboyer) [reply agent/agent.go]: We could use the existing struct, it just seemed a little weird to persist all of that metadata with the original values. I can revert this section and fixup the tests.

File: agent/agent.go (hunk 3 above)
Comment (rboyer) [reply agent/agent.go]: The function signatures are not entirely the same. There is enough  overlap that I could just add the union of fields to the struct and just document with comments which fields are only meant for one or the other

File: agent/service_manager.go (hunk 4 above)
Comment (rboyer) [reply agent/service_manager.go]: Yeah i meant that the caller should hold the lock.

File: agent/agent.go (hunk 1 above)
Comment (rboyer) [reply agent/agent.go]: I can move it out into its own file.

File: agent/agent.go [hunk 5]
```diff
@@ -2135,68 +2124,77 @@ func (a *Agent) AddServiceAndReplaceChecks(service *structs.NodeService, chkType
...
+// addServiceRequest is the union of arguments for calling both
+// addServiceLocked and addServiceInternal. The overlap was significant enough
+// to warrant merging them and indicating which fields are meant to be set only
+// in one of the two contexts.
+//
+// Before using the request struct one of the fixupFor*() methods should be
+// invoked to clear irrelevant fields.
+//
+// The ServiceManager.AddService signature is largely just a passthrough for
+// addServiceLocked and should be treated as such.
```
Comment (banks) [inline agent/agent.go]: 🤔 my initial reaction to this was that is seems uglier than the massive argument lists it replaced and maybe the smell indicated that we should have just built this whole registration pipeline differently.

But after thinking some I'm not sure it's too bad and the alternatives don't seem obviously cleaner. I think it's OK as it is.

Comment (rboyer) [reply agent/agent.go]: If we start really using central service config more it might be worth the investment to rethink this whole `Agent` structure. It's not a quick fix.
