### PR TITLE
command: fix Windows build

### LINKED ISSUE #636: build failure on windows
`syscall.Kill` was introduced in f2f980f5bc5baf7187a63edfb9f6248770a38c71, which is platform dependent.

Since `syscall.Kill` is not defined on Windows it results in a build failure on all Windows systems.

### PR DESCRIPTION
**Pull request by ceh**
Add a per GOOS implementation to send signals to PIDs
since syscall.Kill does not exist on Windows.

It will always send a SIGKILL on Windows since there
seems to be no POSIX compatible notion.

Fixes #636

### CODE REVIEW

**Comment by ryanuber** [comment]
This looks good! I think this method is more generally useful, and I can see us running into these kinds of issues in the future. Maybe we can have a `util_unix.go` and `util_windows.go` instead of naming them specifically for the `lock` command.

File: command/lock_windows.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+package command
+
+import (
+	"os"
+	"syscall"
+)
+
+func signalChild(child *os.Process, sig syscall.Signal) error {
+	// Interrupts et al not implemented on Windows. Always signal SIGKILL.
+	_ = sig
```
Comment (ryanuber) [inline command/lock_windows.go]: Minor, but I think you can even just ignore this in the function signature.

**Comment by ceh** [comment]
@ryanuber 

Moved the implementation into util_GOOS.go and made the function take an integer pid instead of a `os.Process` to make it more useful.

Kept `syscall.Signal` in the Windows function signature to keep 'em identical, plus, Go might add support for interrupts on Windows in the future.

Please take another look.

**Comment by ryanuber** [comment]
LGTM, thanks!
