### PR TITLE
UI: Fixes healthy node listing resize on large portrait screens

### LINKED ISSUE #4368: List of healthy nodes not wrapped vertical
On vertical-align monitors, when all nodes are healthy and there is more than 20 nodes scroll apear on the right and field with nodes don't wrap down. See screenshot.

Also this concept of tile is good for users and extreamly unusable for administrating. The concept of lines with details is preferably.
ui-bug3

### PR DESCRIPTION
**Pull request by johncowen**
Fixes #4368 

Split the resizing functionality of into a separate mixin to be shared across components

### CODE REVIEW

File: ui-v2/app/components/list-collection.js [hunk 1]
```diff
@@ -1,6 +1,32 @@
...
+    };
+  }),
+  resize: function(e) {
+    const $self = this.element;
+    const $appContent = [...$$('main > div')][0];
+    if ($appContent) {
+      const rect = $self.getBoundingClientRect();
+      const $footer = [...$$('footer[role="contentinfo"]')][0];
+      const space = rect.top + $footer.clientHeight;
+      const height = new Number(e.detail.height - space);
```
Comment (DingoEatingFuzz) [inline ui-v2/app/components/list-collection.js]: Why use the Number constructor here?

File: ui-v2/app/mixins/with-resizing.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+    this.didAppear();
+  },
+  didAppear: function() {
+    this.handler({ target: get(this, 'win') });
+  },
+  willDestroyElement: function() {
+    get(this, 'win').removeEventListener('resize', this.handler);
+    this._super(...arguments);
+  },
+});
```
Comment (DingoEatingFuzz) [inline ui-v2/app/mixins/with-resizing.js]: Nice mixin. One suggestion I have is to put emphasis on resize in some manner to make it obvious that that is the interesting part for a consumer of this mixin. This could be as simple as moving `resize` to the first thing in the file so it's hard to overlook, or something more aggressive [like this](https://github.com/hashicorp/nomad/blob/280d6a3f5536b98f52b7c44cffda82a41305b77d/ui/app/mixins/window-resizable.js#L7-L9), which throws an error if a component/controller/whatever is mixing in the mixin without overriding the expected method.

File: ui-v2/tests/integration/mixins/with-resizing-test.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+import EmberObject from '@ember/object';
+import Mixin from 'consul-ui/mixins/with-resizing';
+module('Integration | Mixin | with-resizing', function(hooks) {
+  setupTest(hooks);
+  test('window.addEventListener, resize and window.removeEventListener are called once each through the entire lifecycle', function(assert) {
+    const win = {
+      innerWidth: 0,
+      innerHeight: 0,
+      addEventListener: this.stub(),
+      removeEventListener: this.stub(),
```
Comment (DingoEatingFuzz) [inline ui-v2/tests/integration/mixins/with-resizing-test.js]: Neat. I need to look into `ember-sinon-qunit`. I'm just using plain `sinon` right now, but I love spies.

File: ui-v2/app/mixins/with-resizing.js (hunk 2 above)
Comment (johncowen) [reply ui-v2/app/mixins/with-resizing.js]: Done
