### PR TITLE
connect: Fix an issue with updating CA config in a secondary datacenter

### LINKED ISSUE #7009: connect: cannot update CA configuration in secondary datacenter
On `master@43ab78fe5` attempts to reconfigure the builtin connect ca in a secondary with provided key material does not work:

```
$ cat body.json
{
  "Provider": "consul",
  "Config": {
    "PrivateKey": "-----BEGIN EC PRIVATE KEY-----  ...(snip)..."
  }
}
$ consul connect ca set-config -config-file body.json
Error setting CA configuration: Unexpected response code: 500 (error generating CA root certificate: provider is not the root certificate authority)
```

From what I can tell the RPC handler for updating the ca configuration has no plumbing in place to properly do the CSR dance to actually update a secondary.

### PR DESCRIPTION
**Pull request by kyhavlov**
This PR fixes a case where updating the CA config in a secondary datacenter would cause an error when it should trigger the creation of a new intermediate certificate. 

The test passes but I think this still needs some extra logic to prevent races between the RPC endpoint and `secondaryCARootWatch`/`intermediateCertRenewalWatch`. Currently `secondaryCARootWatch` will set things right on its next iteration if there's a race where it gets overwritten by a call to the RPC endpoint, but since it spends most of its time waiting on a blocking query that could be up to 5-10 minutes with the wrong intermediate/root, which is a pretty long time to wait for things to converge.

Fixes #7009.

### CODE REVIEW

**Comment by kyhavlov** [comment]
Discussed fixing the racey parts of the secondary logic with @rboyer and decided a good solution is to pull some of the intermediate update code out into a separate struct to manage the different states (ready/signing/reconfig) in a safer/more understandable way.

**Comment by kyhavlov** [comment]
I've updated the PR with the refactored CA logic - it still needs some test updates/fixes and a writeup of how the state machine logic avoids race conditions in specific situations.

File: agent/consul/leader_connect_ca.go [hunk 1]
```diff
@@ -0,0 +1,821 @@
...
+}
+
+// setState attempts to update the CA state to the given state.
+// If the current state is not READY, this will fail. The only exception is when
+// the current state is UNINITIALIZED, and the function is called with CAStateInitializing.
+func (c *CAManager) setState(newState CAState) error {
+	c.stateLock.RLock()
+	state := c.state
+	c.stateLock.RUnlock()
+
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:72]: You have a minor bug here with the double checked locking implementation. Usually you would do a cheap lock (the read lock) first to short circuit doing the expensive lock (write lock) to do the real work. In that case the first check is purely a perf optimization so the rest has to function correctly even if the first block were erased. But in this implementation you don't re-check the conditionals from line 73 again with the write lock held, since the state could've drifted in the intervening clock ticks.

Practically speaking would it be easier here to change this to be:
```
c.stateLock.Lock()
defer c.stateLock.Unlock()
// your if conditional, error returns, and state update code
```
Usually the read/write lock split makes sense only if you expect a high degree of "no-op" writes, but given the body of this function that seems less likely

File: agent/consul/leader_connect_ca.go [hunk 2]
```diff
@@ -0,0 +1,821 @@
...
+		c.stateLock.Unlock()
+	} else {
+		return fmt.Errorf("CA is already in %s state", state)
+	}
+	return nil
+}
+
+// setReady sets the CA state back to READY. This should only be called by a function
+// that has successfully called setState beforehand.
+func (c *CAManager) setReady() {
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:85]: Why does this not just call `setState()`?

File: agent/consul/leader_connect_ca.go [hunk 3]
```diff
@@ -0,0 +1,821 @@
...
+	conf, err := c.initializeCAConfig()
+	if err != nil {
+		return err
+	}
+	provider, err := c.srv.createCAProvider(conf)
+	if err != nil {
+		return err
+	}
+
+	c.setCAProvider(provider, nil)
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:224]: The state lock is not held when this is called here, should it be? Or is the comment on the function more like "the state lock is sometimes held" vs "the state lock is always held"?

I recall things going poorly with multiple locks involved and them not always being invoked serially in the right way.

File: agent/consul/leader_connect_ca.go [hunk 4]
```diff
@@ -0,0 +1,821 @@
...
+		Datacenter: c.srv.config.Datacenter,
+		IsPrimary:  false,
+		RawConfig:  conf.Config,
+		State:      conf.State,
+	}
+	if err := provider.Configure(pCfg); err != nil {
+		return fmt.Errorf("error configuring provider: %v", err)
+	}
+
+	c.actingSecondaryCA = true
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:811]: The `stateLock` is not held when updating this value.

File: agent/consul/connect_ca_endpoint.go [hunk 5]
```diff
@@ -163,6 +163,22 @@ func (s *ConnectCA) ConfigurationSet(
 		}
 	}()
 
+	// If this is a secondary, check if the intermediate needs to be regenerated.
+	if s.srv.config.Datacenter != s.srv.config.PrimaryDatacenter {
+		// Attempt to take the CA lock in order to update the config.
+		if err := s.srv.caManager.setState(CAStateReconfig); err != nil {
+			return err
+		}
+		defer s.srv.caManager.setReady()
```
Comment (rboyer) [inline agent/consul/connect_ca_endpoint.go:172]: So if the init function call fails, you'll still revert to READY. Is that correct? Is there any other cleanup required?

File: agent/consul/leader.go [hunk 6]
```diff
@@ -375,7 +375,7 @@ func (s *Server) revokeLeadership() {
 
 	s.stopConnectLeader()
 
-	s.setCAProvider(nil, nil)
+	s.caManager.setCAProvider(nil, nil)
```
Comment (rboyer) [inline agent/consul/leader.go:378]: Should you reset the rest of the internal state of the CAManager on step-down?

File: agent/consul/server.go [hunk 7]
```diff
@@ -137,17 +136,11 @@ type Server struct {
...
-	// only non-nil when we are the leader.
-	caProvider ca.Provider
-	// caProviderRoot is the CARoot that was stored along with the ca.Provider
-	// active. It's only updated in lock-step with the caProvider. This prevents
-	// races between state updates to active roots and the fetch of the provider
-	// instance.
-	caProviderRoot *structs.CARoot
-	caProviderLock sync.RWMutex
+	// autopilotWaitGroup is used to block until Autopilot shuts down.
+	autopilotWaitGroup sync.WaitGroup
```
Comment (rboyer) [inline agent/consul/server.go:140]: if you rebase the PR on current master i believe this autopilot change vanishes

File: agent/consul/connect_ca_endpoint.go (hunk 5 above)
Comment (kyhavlov) [reply agent/consul/connect_ca_endpoint.go]: There shouldn't be any cleanup required since nothing is persisted until the very end, i.e. `persistNewRootAndConfig`, so if that succeeds then there's noithing to error after it, and if something before that fails then there's no changes to worry about.

File: agent/consul/leader_connect_ca.go [hunk 8]
```diff
@@ -0,0 +1,1082 @@
...
+		NotBefore:           rootCert.NotBefore,
+		NotAfter:            rootCert.NotAfter,
+		RootCert:            pemValue,
+		PrivateKeyType:      keyType,
+		PrivateKeyBits:      keyBits,
+		Active:              true,
+	}, nil
+}
+
+// getCAProvider is being called while holding caProviderReconfigurationLock
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:169]: I think this comment is stale now, since it references `caProviderReconfigurationLock`

File: agent/consul/leader_connect_ca.go [hunk 9]
```diff
@@ -0,0 +1,1082 @@
...
+
+func (c *CAManager) getPrimaryRoots() structs.IndexedCARoots {
+	c.stateLock.Lock()
+	defer c.stateLock.Unlock()
+	return c.primaryRoots
+}
+
+// initializeCAConfig is used to initialize the CA config if necessary
+// when setting up the CA during establishLeadership
+func (c *CAManager) initializeCAConfig() (*structs.CAConfiguration, error) {
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:99]: maybe add a comment about how you should hold the state "meta lock" before calling this.

File: agent/consul/leader_connect_ca.go [hunk 10]
```diff
@@ -0,0 +1,1082 @@
...
+	}
+	provider, err := c.srv.createCAProvider(conf)
+	if err != nil {
+		return err
+	}
+
+	c.setCAProvider(provider, nil)
+
+	// If this isn't the primary DC, run the secondary DC routine if the primary has already been upgraded to at least 1.6.0
+	if c.srv.config.PrimaryDatacenter != c.srv.config.Datacenter {
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:234]: Maybe it would make this even clearer if we switched this to:
```
if c.srv.config.PrimaryDatacenter == c.srv.config.Datacenter {
	return c.initializeRootCA(provider, conf)
}
// .. all of the secondary code outdented
```

File: agent/consul/leader_connect_ca.go [hunk 11]
```diff
@@ -0,0 +1,1082 @@
...
+
+		c.logger.Info("initialized secondary datacenter CA with provider", "provider", conf.Provider)
+		return nil
+	}
+
+	return c.initializeRootCA(provider, conf)
+}
+
+// initializeRootCA runs the initialization logic for a root CA.
+// It is being called while holding caProviderReconfigurationLock
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:276]: stale comment should be updated for the meta lock instead

File: agent/consul/leader_connect_ca.go [hunk 12]
```diff
@@ -0,0 +1,1082 @@
...
+
+	c.logger.Info("initialized primary datacenter CA with provider", "provider", conf.Provider)
+
+	return nil
+}
+
+// initializeSecondaryCA runs the routine for generating an intermediate CA CSR and getting
+// it signed by the primary DC if the root CA of the primary DC has changed since the last
+// intermediate.
+// It is being called while holding caProviderReconfigurationLock
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:384]: stale comment should be updated for the meta lock instead

File: agent/consul/leader_connect_ca.go [hunk 13]
```diff
@@ -0,0 +1,1082 @@
...
+	}
+	if err := c.persistNewRootAndConfig(provider, newRoot, config); err != nil {
+		return err
+	}
+
+	c.setCAProvider(provider, newActiveRoot)
+	return nil
+}
+
+// persistNewRootAndConfig is being called while holding caProviderReconfigurationLock
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:496]: stale comment should be updated for the meta lock instead

File: agent/consul/leader_connect_ca.go [hunk 14]
```diff
@@ -0,0 +1,1082 @@
...
+	}
+
+	c.logger.Info("CA rotated to new root under provider", "provider", args.Config.Provider)
+
+	return nil
+}
+
+// getIntermediateCAPrimary regenerates the intermediate cert in the primary datacenter.
+// This is only run for CAs that require an intermediary in the primary DC, such as Vault.
+// This function is being called while holding caProviderReconfigurationLock
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:801]: stale comment should be updated for the meta lock instead

File: agent/consul/leader_connect_ca.go [hunk 15]
```diff
@@ -0,0 +1,1082 @@
...
+	// Append the new intermediate to our local active root entry. This is
+	// where the root representations start to diverge.
+	newActiveRoot.IntermediateCerts = append(newActiveRoot.IntermediateCerts, intermediatePEM)
+	newActiveRoot.SigningKeyID = connect.EncodeSigningKeyID(intermediateCert.SubjectKeyId)
+
+	c.logger.Info("generated new intermediate certificate for primary datacenter")
+	return nil
+}
+
+// getIntermediateCASigned is being called while holding caProviderReconfigurationLock
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:824]: stale comment should be updated for the meta lock instead

File: agent/consul/leader_connect_ca.go [hunk 16]
```diff
@@ -0,0 +1,1082 @@
...
+		// this happens when leadership is being revoked and this go routine will be stopped
+		return nil
+	}
+	// If this isn't the primary, make sure the CA has been initialized.
+	if !isPrimary && !c.configuredSecondaryCA() {
+		return fmt.Errorf("secondary CA is not yet configured.")
+	}
+
+	state := c.srv.fsm.State()
+	_, activeRoot, err := state.CARootActive(nil)
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:900]: we should deep-copy `activeRoot` here as `newActiveRoot` and use that to mutate. I think we're currently mutating the memdb copy which is usually a bad sign

File: agent/consul/leader_connect_ca.go [hunk 17]
```diff
@@ -0,0 +1,1082 @@
...
+	}
+
+	// Enough time has passed, go ahead with getting a new intermediate.
+	renewalFunc := c.getIntermediateCAPrimary
+	if !isPrimary {
+		renewalFunc = c.getIntermediateCASigned
+	}
+	if err := renewalFunc(provider, activeRoot); err != nil {
+		return err
+	}
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:944]: In a secondary this is going to do an RPC over the wan which may take a long time. From the perspective of the secondary, this operation itself doesn't do any local writes so you could do the following to mitigate:

1. pass the `ctx` in to this function
2. use another goroutine to invoke `renewalFunc`, shipping back the err/no-err via a `chan error`
3. here do a select on the `ctx.Done()` and (2)'s error channel so the leader routine here can cancel and get out of this locked section quickly

File: agent/consul/leader_connect_ca.go [hunk 18]
```diff
@@ -0,0 +1,1082 @@
...
+
+	c.logger.Debug("starting Connect CA root replication from primary datacenter", "primary", c.srv.config.PrimaryDatacenter)
+
+	retryLoopBackoff(ctx, func() error {
+		var roots structs.IndexedCARoots
+		if err := c.srv.forwardDC("ConnectCA.Roots", c.srv.config.PrimaryDatacenter, &args, &roots); err != nil {
+			return fmt.Errorf("Error retrieving the primary datacenter's roots: %v", err)
+		}
+
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:973]: safety:
if the wan read above takes a long time, the context may be canceled when it next wakes up so it might be beneficial to add a quick:
```
select {
  case <-ctx.Done():
    return ctx.Err()
  default:
}
```

File: agent/consul/leader_connect_ca.go [hunk 19]
```diff
@@ -0,0 +1,1082 @@
...
+		return nil
+	}
+	if !c.configuredSecondaryCA() {
+		versionOk, primaryFound := ServersInDCMeetMinimumVersion(c.srv, c.srv.config.PrimaryDatacenter, minMultiDCConnectVersion)
+		if !primaryFound {
+			return fmt.Errorf("Primary datacenter is unreachable - deferring secondary CA initialization")
+		}
+
+		if versionOk {
+			if err := c.initializeSecondaryProvider(provider, roots); err != nil {
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:1018]: if this errors, what mechanism attempts to re-execute it? We already updated the stored roots above

File: agent/consul/leader_connect_ca.go [hunk 20]
```diff
@@ -0,0 +1,1082 @@
...
+		if err := c.initializeSecondaryCA(provider, nil); err != nil {
+			return fmt.Errorf("Failed to initialize the secondary CA: %v", err)
+		}
+	}
+
+	return nil
+}
+
+// initializeSecondaryProvider configures the given provider for a secondary, non-root datacenter.
+// It is being called while holding the stateLock in order to update actingSecondaryCA, which means
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:1036]: this comment also seems out of date

File: agent/consul/leader_connect_ca.go [hunk 21]
```diff
@@ -0,0 +1,1082 @@
...
+	}
+	if err := provider.Configure(pCfg); err != nil {
+		return fmt.Errorf("error configuring provider: %v", err)
+	}
+
+	return c.setSecondaryCA()
+}
+
+// setSecondaryCA sets the flag for acting as a secondary CA to true.
+func (c *CAManager) setSecondaryCA() error {
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:1064]: Should this also pick up a `validate bool` arg like the `setState` function did?

File: agent/consul/leader_connect_ca.go (hunk 19 above)
Comment (kyhavlov) [reply agent/consul/leader_connect_ca.go:1018]: It won't be reattempted currently until the next run of the root watch routine returns, Do you think we need a separate retry backoff loop here even when this function (UpdateRoots) is being called periodically?

File: agent/consul/leader_connect_ca.go (hunk 21 above)
Comment (kyhavlov) [reply agent/consul/leader_connect_ca.go:1064]: I don't think it needs one yet, since there's no place that wants to bypass the validation currently

File: agent/structs/connect_ca.go [hunk 22]
```diff
@@ -122,6 +122,16 @@ type CARoot struct {
 	RaftIndex
 }
 
+func (c *CARoot) Clone() *CARoot {
+	if c == nil {
+		return nil
+	}
+
+	newCopy := *c
+	copy(c.IntermediateCerts, newCopy.IntermediateCerts)
```
Comment (rboyer) [inline agent/structs/connect_ca.go:131]: This doesn't do what you think it does: https://play.golang.org/p/sKpXLoemIyf

You could use the convenience function i wrote in `agent/structs` for this: `cloneStringSlice`

File: agent/consul/leader_connect_ca.go (hunk 19 above)
Comment (rboyer) [reply agent/consul/leader_connect_ca.go:1025]: I think as long as the system does something reasonable to recover from a temporary failure here that would be sufficient.

File: agent/consul/leader.go (hunk 6 above)
Comment (kyhavlov) [reply agent/consul/leader.go:377]: I think nil-ing out the provider/root and setting the state back to uninitialized is enough, since that will block anything from getting the provider or doing any operations that aren't InitializeCA (which only gets called on establishLeadership).

File: agent/consul/leader_connect_ca.go [hunk 23]
```diff
@@ -0,0 +1,1142 @@
...
+		intermediateCert.NotAfter) {
+		return nil
+	}
+
+	// Enough time has passed, go ahead with getting a new intermediate.
+	renewalFunc := c.getIntermediateCAPrimary
+	if !isPrimary {
+		renewalFunc = c.getIntermediateCASigned
+	}
+	errCh := make(chan error)
```
Comment (rboyer) [inline agent/consul/leader_connect_ca.go:986]:
```suggestion
	errCh := make(chan error, 1)
```
By making this a 1-buffered channel then you let each goroutine use the channel on its own timeline, rather than forcing them to wait on the other one. This is important when the context is canceled and the main goroutine leaves and stops receiving (forever). I think the Go GC will detect that nothing will ever read from the channel and stop the sending goutine, but best to make is more obvious how their lifecycles should go.

File: agent/consul/leader_connect_ca_test.go [hunk 24]
```diff
@@ -0,0 +1,256 @@
...
+func (m *mockCAServerDelegate) forwardDC(method, dc string, args interface{}, reply interface{}) error {
+	switch method {
+	case "ConnectCA.Roots":
+		roots := reply.(*structs.IndexedCARoots)
+		roots.TrustDomain = connect.TestClusterID
+		roots.Roots = []*structs.CARoot{m.primaryRoot}
+		roots.ActiveRootID = m.primaryRoot.ID
+	case "ConnectCA.SignIntermediate":
+		r := reply.(*string)
+		*r = m.primaryRoot.RootCert
```
Comment (rboyer) [inline agent/consul/leader_connect_ca_test.go:79]: Might want a `default` branch that just returns an obvious error to avoid future test headaches.

File: agent/consul/leader_connect_ca_test.go [hunk 25]
```diff
@@ -0,0 +1,256 @@
...
+	if t == structs.ConnectCARequestType {
+		req := msg.(*structs.CARequest)
+		act, err := m.store.CARootSetCAS(1, req.Index, req.Roots)
+		require.NoError(m.t, err)
+		require.True(m.t, act)
+
+		act, err = m.store.CACheckAndSetConfig(1, req.Config.ModifyIndex, req.Config)
+		require.NoError(m.t, err)
+		require.True(m.t, act)
+	}
```
Comment (rboyer) [inline agent/consul/leader_connect_ca_test.go:104]: Might want an `else` here that just returns an obvious error to avoid future test headaches.

File: agent/consul/leader_connect_ca_test.go [hunk 26]
```diff
@@ -0,0 +1,256 @@
...
+func (m *mockCAProvider) SupportsCrossSigning() (bool, error)                       { return false, nil }
+func (m *mockCAProvider) Cleanup() error                                            { return nil }
+
+func waitForCh(t *testing.T, ch chan string, expected string) {
+	select {
+	case op := <-ch:
+		if op != expected {
+			t.Fatalf("got unexpected op %q, wanted %q", op, expected)
+		}
+	case <-time.After(3 * time.Second):
```
Comment (rboyer) [inline agent/consul/leader_connect_ca_test.go:142]: You could instead use the current time and the time portion of `(*testing.T).Deadline()` instead to compute remaining test time instead of using a made up "not forever" number here and several other places

File: agent/consul/leader_connect_ca_test.go [hunk 27]
```diff
@@ -0,0 +1,256 @@
...
+	conf.ConnectEnabled = true
+	conf.PrimaryDatacenter = "dc1"
+	conf.Datacenter = "dc2"
+	delegate := NewMockCAServerDelegate(t, conf)
+	manager := NewCAManager(delegate, testutil.Logger(t), conf)
+
+	// Call InitializeCA and then confirm the RPCs and provider calls
+	// happen in the expected order.
+	go func() {
+		require.EqualValues(t, CAStateUninitialized, manager.state)
```
Comment (rboyer) [inline agent/consul/leader_connect_ca_test.go:199]: IIRC it's not usually a good idea to use `testing.T` from goroutines. The alternative would be using a `chan error` to pass the assertion results back up to the body of the test function for assertion.

Also would it make sense to do lines 199 and 201 outside of the goroutine and just use the goroutine to handles the `initializeCA` call?

File: agent/consul/leader_connect_ca_test.go [hunk 28]
```diff
@@ -0,0 +1,256 @@
...
+	manager := NewCAManager(delegate, testutil.Logger(t), conf)
+	initTestManager(t, manager, delegate)
+
+	// Wait half the TTL for the cert to need renewing.
+	time.Sleep(500 * time.Millisecond)
+
+	// Call RenewIntermediate and then confirm the RPCs and provider calls
+	// happen in the expected order.
+	go func() {
+		require.NoError(t, manager.RenewIntermediate(context.TODO(), false))
```
Comment (rboyer) [inline agent/consul/leader_connect_ca_test.go:239]: Similar comment about assertions in goroutines.

File: agent/consul/leader_connect_ca_test.go [hunk 29]
```diff
@@ -0,0 +1,256 @@
...
+		require.EqualValues(t, CAStateReady, manager.state)
+	}()
+
+	waitForCh(t, delegate.callbackCh, "provider/GenerateIntermediateCSR")
+
+	// Call UpdateConfiguration while RenewIntermediate is still in-flight to
+	// make sure we get an error about the state being occupied.
+	go func() {
+		require.EqualValues(t, CAStateRenewIntermediate, manager.state)
```
Comment (rboyer) [inline agent/consul/leader_connect_ca_test.go:248]: Similar comment about assertions in goroutines.

**Review by rboyer — APPROVED** [review]
LGTM assuming CI passes.

Further tests can come in a followup.
