### PR TITLE
replace filename with inline_bytes.

### LINKED ISSUE #6360: `consul connect envoy` should have the ability to inline the TLS certificates necessary for gRPC
#### Overview of the Issue

I want to run Envoy within a container and provide it the bootstrap configuration generated in the container/machine that the Consul agent managing it resides. When HTTPs is enabled TLS also gets enabled for the gRPC connection. Therefore the bootstrap configuration also needs to setup TLS. Right now it inserts the path to the CA certificate file on disk. This path is only valid on the agent itself. Envoy supports inlining the PEM files I think that the CLI should read the ca file and dump the pem into the bootstrap config instead of providing the path.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Run a consul agent on the host with HTTPs enabled.
2. Run `consul connect envoy -bootstrap <other args>`. Either set the env vars so that the CLI will know TLS should be used or manually set the gRPC addr to `https://<consul agent ip>:<consul agent grpc port>`
3. Run an envoy container, map in the bootstrap config.

Envoy will not be able to validate the TLS cert because its filesystem doesn't contain the path where we told it the CA cert lives.

### PR DESCRIPTION
**Pull request by i0rek**
Fixes #6360.

> I want to run Envoy within a container and provide it the bootstrap configuration generated in the container/machine that the Consul agent managing it resides. When HTTPs is enabled TLS also gets enabled for the gRPC connection. Therefore the bootstrap configuration also needs to setup TLS. Right now it inserts the path to the CA certificate file on disk. This path is only valid on the agent itself. Envoy supports inlining the PEM files I think that the CLI should read the ca file and dump the pem into the bootstrap config instead of providing the path.

 This PR does exactly what was asked for by using `inline_bytes` instead of `filename`.

### CODE REVIEW

File: command/connect/envoy/envoy.go [hunk 1]
```diff
@@ -493,14 +494,24 @@ func (c *cmd) templateArgs() (*BootstrapTplArgs, error) {
 		adminAccessLogPath = DefaultAdminAccessLogPath
 	}
 
+	var ca []byte
+	if httpCfg.TLSConfig.CAFile != "" {
```
Comment (i0rek) [inline command/connect/envoy/envoy.go]: I noticed that we don't have CAPath support and I wonder if envoy can deal with multiple CAs and if we should add it.

File: command/connect/envoy/envoy.go [hunk 2]
```diff
@@ -422,7 +423,7 @@ func (c *cmd) templateArgs() (*BootstrapTplArgs, error) {
 	if strings.HasPrefix(strings.ToLower(c.grpcAddr), "https://") {
 		useTLS = true
 	} else if useSSLEnv := os.Getenv(api.HTTPSSLEnvName); useSSLEnv != "" {
-		if enabled, err := strconv.ParseBool(useSSLEnv); err != nil {
+		if enabled, err := strconv.ParseBool(useSSLEnv); err == nil {
```
Comment (i0rek) [inline command/connect/envoy/envoy.go]: Found a little bug as well.

File: command/connect/envoy/bootstrap_tpl.go [hunk 3]
```diff
@@ -23,9 +23,9 @@ type BootstrapTplArgs struct {
 	// TLS.
 	AgentTLS bool
 
-	// AgentCAFile is the CA file to use to verify the local agent gRPC service if
+	// AgentCA is the CA to use to verify the local agent gRPC service if
 	// TLS is enabled.
-	AgentCAFile string
+	AgentCA []byte
```
Comment (banks) [inline command/connect/envoy/bootstrap_tpl.go]: nit: if this is the raw certificate PEM I'd name it `AgentCAPEM` to be clear as it could be anything from the path to PEM to raw ASN1 etc...

File: command/connect/envoy/envoy.go (hunk 2 above)
Comment (banks) [reply command/connect/envoy/envoy.go]: Good catch. I still thought this was wrong for a second but you're right...

**Comment by banks** [comment]
> Would be useful if the PR description could include the rationale for why this change is necessary for history/context.

I went and read the ticket and now it's obvious so maybe not a big deal. My personal preference is to be descriptive in PRs with links if necessary where there is a well-described context issue but at least a short summary of the change's intent 🤷‍♂

**Comment by i0rek** [comment]
Thanks for the review @bannks!
I added more context to this PR and am using `AgentCAPEM` now.
