### PR TITLE
UI Bugfix - kv trailing slashes

### LINKED ISSUE #4324: Can't list keys in new UI with limited ACL token
#### Overview of the Issue

Given an ACL with limited access (such as write access to `foo/bar/`, but no access to `foo/`), the user can't list their own keys.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a new cluster running 1.2.0
2. Create the folders `foo/` and `foo/bar/` and a key called `foo/bar/data`
3. Create an ACL with the following rules:
```
key "" {
  policy = "deny"
}

key "foo/bar/" {
  policy = "write"
}
```
4. Using the test ACL, you will see nothing on the key/value page (which is unfortunate, but identical to the old UI). But if you visit https://192.168.99.100:8500/ui/dc1/kv/foo/bar/, you should see the `data` key, but instead, we get a blank page. (And even using the master token, if you go to this URL, you're redirected to the top level prefix, which I think is a separate issue.)

It's worth noting that this does work with the API:

```
jodawill: docker-consul-cluster (master)$ curl "https://192.168.99.100:8500/v1/kv/foo/bar/?keys&seperator=/&dc=dc1&token=e6864d20-00e6-1ae2-0075-e60823e1037e" --insecure
["foo/bar/","foo/bar/data"]
```

### Consul info for Server

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 28141971
	version = 1.2.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 10.0.0.8:8300
	server = true
raft:
	applied_index = 471
	commit_index = 471
	fsm_pending = 0
	last_contact = 54.356352ms
	last_log_index = 471
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:f1bfbe28-c5e5-78f3-7afc-05ab730b5a96 Address:10.0.0.8:8300} {Suffrage:Voter ID:ea9e588c-b984-7e32-2b4b-de23dc29383a Address:10.0.0.7:8300} {Suffrage:Voter ID:035f2dcc-eaa6-87f8-8ae2-3d5345de3971 Address:10.0.0.6:8300}]
	latest_configuration_index = 1
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 84
	max_procs = 1
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 3
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Running in Docker Swarm with docker-machine on MacOS 10.13.4.

### Log Fragments

No relevant log entries.

### PR DESCRIPTION
**Pull request by johncowen**
Fixes #4324 

This PR addresses the fact that the UI has a redirect to remove trailing slashes off any URLs, which causes problems with KV 'folders'. So if you hand type a URL with a trailing slash it will redirect you to possibly a inaccessible URL (whereas if you are navigating there using the UI/javascript, it won't).

It goes by the basic premise that if you request the `index` or `folder` route you must be asking for a 'folder' therefore if the URL/Keyname has no trailing slash, then add one when calling the API.

Also, I made sure I added a failing test as a separate first commit on this branch instead of bundling it up with the fix, so if you want see it breaking easily you can checkout one commit back and run `make test-view`, filtering by 'trailing' will take you to the broken test, re-checking out this branch will fix it. Will try and make this easier to do this moving forwards.

### CODE REVIEW

File: ui-v2/app/routes/dc/kv/index.js [hunk 1]
```diff
@@ -13,7 +14,12 @@ export default Route.extend(WithKvActions, {
   },
   repo: service('kv'),
   model: function(params) {
-    const key = params.key || '/';
+    let key = params.key || '/';
+    // we are index or folder, so if the key doesn't have a trailing slash
+    // add one to force a fake findBySlug
+    if (!isFolder(key)) {
+      key = key + '/';
+    }
```
Comment (meirish) [inline ui-v2/app/routes/dc/kv/index.js]: Thinking about this some more - this solves the data fetching problem, but now you have 2 URLs that show the same thing which seems odd to me. What would you think about doing a `this.replaceWith` in the `beforeModel` hook that passes in a key with the slash on the end so that you always have a 1:1 mapping of URL to UI state?

Comment (johncowen) [reply ui-v2/app/routes/dc/kv/index.js]: Took me a while to follow this, but this morning just had another look at that PR you sent over and I had a lightbulb moment! _ah ha, thats what matt was talking about in that comment!_ :smile: 

I thought I couldn't add the trailing slash because it would redirect again, but of course we are in ember by this point so we can redirect to a trailing slash using the history API and it won't be 301'ed

Good call, will sort in a bit hopefully be here by the time you are in 👍
