### PR TITLE
[Streaming] Predictable order for results of /health/service/:serviceName to mimic memdb

### LINKED ISSUE #9239: [Streaming] Order of results in /health is modified when streaming is enabled for cached queries
#### Overview of the Issue

While testing streaming on Consul 1.9.0-beta2, we encountered the following issue:

When streaming is enabled, results on /health endpoint are not sorted in a deterministic way

#### Reproduction Steps

Steps to reproduce this issue, eg:

Register 100 instances for a service
Run ` curl '127.0.0.1:8500/v1/health/service/my-fake-service?pretty&cached' | jq '.[].Node.Node' -r | head`

##### With streaming disabled

The results are sorted the same way as any non cached query:

```
$ curl '127.0.0.1:8500/v1/health/service/my-fake-service?pretty&cached' | jq '.[].Node.Node' -r | head
agent-1
agent-10
agent-100
agent-1000
agent-10000
agent-10001
agent-10002
agent-10003
```

##### With streaming enabled

The results are not sorted the same way for cached queries:

```
$ curl '127.0.0.1:8500/v1/health/service/my-fake-service?pretty&cached' | jq '.[].Node.Node' -r | head
agent-813
agent-11431
agent-12555
agent-2092
agent-7112
agent-8042
agent-1093
agent-17152
agent-18740
agent-763
```

### Consul info for both Client and Server

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease = beta2
        revision = db08bdc1
        version = 1.9.0
consul:
        acl = disabled
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 66
        max_procs = 2
        os = linux
        version = go1.14.9
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 15
        members = 6
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details

Linux

### PR DESCRIPTION
**Pull request by pierresouchay**
This ensures the result is consitent with/witout streaming

Will partially fix #9239

### CODE REVIEW

File: agent/cache-types/streaming_health_services.go [hunk 1]
```diff
@@ -206,6 +208,21 @@ func (noopFilterEvaluator) Evaluate(_ interface{}) (bool, error) {
...
+func cachedHealResultSorter(serviceNodes *structs.IndexedCheckServiceNodes) {
+	sort.SliceStable(serviceNodes.Nodes, func(i, j int) bool {
+		left := serviceNodes.Nodes[i]
+		right := serviceNodes.Nodes[j]
+		res := strings.Compare(left.Node.Node, right.Node.Node)
+		if res != 0 {
+			return res < 0
+		}
+		return strings.Compare(left.Service.ID, right.Service.ID) < 0
+	})
```
Comment (dnephin) [inline agent/cache-types/streaming_health_services.go:223]: According to https://golang.org/pkg/strings/#Compare, "strings.Compare is included only for symmetry with package bytes. It is usually clearer and always faster to use the built-in string comparison operators ==, <, >, and so on."

So I guess this should use `<` instead of `strings.Compare`.

```go
left := serviceNodes.Nodes[i]
right := serviceNodes.Nodes[j]
if left == right {
    return left.Service.ID < right.Service.ID
}
return left.Node.Node < right.Node.Node
```

File: agent/cache-types/streaming_health_services.go [hunk 2]
```diff
@@ -206,6 +208,21 @@ func (noopFilterEvaluator) Evaluate(_ interface{}) (bool, error) {
 	return true, nil
 }
 
+// cachedHealResultSorter sorts the results to match memdb semantics
+// Sort results by Node.Node, if 2 instances match, order by Service.ID
+// Will allow result to be stable sorted and match queries without cache
+func cachedHealResultSorter(serviceNodes *structs.IndexedCheckServiceNodes) {
```
Comment (dnephin) [inline agent/cache-types/streaming_health_services.go:214]: minor: maybe `sortCheckServiceNodes` ?

File: agent/cache-types/streaming_health_services_test.go [hunk 3]
```diff
@@ -226,6 +228,58 @@ func getNamespace(ns string) string {
...
+		},
+		QueryMeta: structs.QueryMeta{
+			Index: index,
+		},
+	}
+	cachedHealResultSorter(&result)
+	require.Equal(t, result.Nodes[0], zero)
+	require.Equal(t, result.Nodes[1], one)
+	require.Equal(t, result.Nodes[2], two)
+	require.Equal(t, result.Nodes[3], three)
```
Comment (dnephin) [inline agent/cache-types/streaming_health_services_test.go:280]: If one of these fails it can be hard to see exactly why it is broken because all we know is that one element is different. I generally try to keep the number of assertions in a test to as few as possible, ideally only 1 for each return value.

I think something like this should work and would give more context on a failure:

```go
expected := structs.CheckServiceNodes{zero, one, two, three}
require.Equal(t, expected, result.Nodes)
```

**Review by dnephin — COMMENTED** [review]
Thank you for the PR! 

I agree this should fix the problem. Just a couple minor suggestions for the implementation.

**Comment by pierresouchay** [comment]
@dnephin All done, thank you for the review

**Review by dnephin — APPROVED** [review]
Thank you! Looks great!
