### PR TITLE
Fixes #3891: agent monitor no longer unresponsive before logs stream.

### LINKED ISSUE #3891: consul monitor doesn't respond to SIGINT/TERM until initial log lines come in
When running `consul monitor` on machines with acl tokens without enough privileges, it blocks forever and doesn't respond to SIGINT or SIGTERM signals. 

### Reproduction steps
1. Provision a Consul cluster with ACLs enabled
2. Create an ACL token without permissions to see other nodes
3. Run a client agent with token created in 2.
4. Run `consul monitor`

### Expected behavior
Exit immediately with a message indicating the lack of permissions.

### `consul version` for both Client and Server
Client: `v1.0.6`
Server: `v1.0.6`

### PR DESCRIPTION
**Pull request by banks**
The root cause is actually that the agent's streaming HTTP API didn't flush until the first log line was found which commonly was pretty soon since the default level is INFO. In cases where there were no logs immediately due to level for instance, the client gets stuck in the HTTP code waiting on a response packet from the server before we enter the loop that checks the shutdown channel from the signal handler.

This fix flushes the initial status immediately on the streaming endpoint which lets the client code get into it's expected state where it's listening for shutdown or log lines.

This is the only streaming API we have in the code base (only used of `http.Flusher`) so no other places with the same issue to fix.

**Before:**

```
$ curl -v 'localhost:8500/v1/agent/monitor?loglevel=ERR'
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8500 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/agent/monitor?loglevel=ERR HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.54.0
> Accept: */*
>
^C⏎
```

**After:**
```
$ curl -v 'localhost:8500/v1/agent/monitor?loglevel=ERR'
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8500 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8500 (#0)
> GET /v1/agent/monitor?loglevel=ERR HTTP/1.1
> Host: localhost:8500
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 19 Feb 2018 21:18:44 GMT
< Transfer-Encoding: chunked
<
^C⏎
```

### CODE REVIEW

File: command/monitor/monitor_test.go [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+	// to write to unbuffered shutdownCh. We don't just buffer it because then it
+	// doesn't model the real shutdownCh we use for signal watching and could mask
+	// bugs in the handling.
+	select {
+	case ret := <-exitCode:
+		if ret != 0 {
+			t.Fatal("command returned with non-zero code")
+		}
+		// OK!
+	case <-time.After(1 * time.Second):
```
Comment (preetapan) [inline command/monitor/monitor_test.go]: Will this timeout be enough in Travis?

Comment (banks) [reply command/monitor/monitor_test.go]: I think so it only has to be long enough for the chan send to happen, the other goroutine to be scheduled and then exit.

It passed in this PR anyway, we can always bump it up if it does flake out.

Comment (banks) [reply command/monitor/monitor_test.go]: Sorry saw this after kyle approved and I merged.
