### PR TITLE
Docker check flaps with "connection reset by peer"

### LINKED ISSUE #3576: Docker script checks flappiness
Discovered when regression testing the 1.0 release. Docker script healthchecks sometimes fail with a `connection reset by peer` error which causes it to flap unnecessarily. 

Reproduction steps:
Create a service with a docker script healthcheck. For my testing, I used a ubuntu container and configured the check to run `ls -l \` as the check. 

Agent logs:
```
 2017/10/13 15:49:38 [WARN] agent: Check 'service:bar' is now critical
    2017/10/13 15:49:38 [INFO] agent: Synced check 'service:bar'
    2017/10/13 15:49:58 [INFO] agent: Synced check 'service:bar'
    2017/10/13 15:50:37 [WARN] agent: Check 'service:foo' is now critical
    2017/10/13 15:50:37 [INFO] agent: Synced check 'service:foo'
    2017/10/13 15:50:57 [INFO] agent: Synced check 'service:foo'
    2017/10/13 15:51:37 [WARN] agent: Check 'service:foo' is now critical
```

Check output when it flaps to critical above: 
```
 "service:foo": {
    "Node": "preetha-work",
    "CheckID": "service:foo",
    "Name": "bar",
    "Status": "critical",
    "Notes": "",
    "Output": "start exec failed for container cefd3f7f5cd4: read unix @->/var/run/docker.sock: read: connection reset by peer",
    "ServiceID": "foo",
    "ServiceName": "foo",
    "ServiceTags": [],
    "CreateIndex": 0,
    "ModifyIndex": 0
  }
```

It seems to happen every few minutes and recover on its own, and then happen again. Needs further investigation.

### PR DESCRIPTION
**Pull request by magiconair**
Issue #3576 describes a behavior where the docker script check flaps because during the read of the body the docker agent closes the connection prematurely. This causes an error which is bubbled up and causes the check to fail even though the status code and response body have been received.

This patch checks for a "connection reset by peer" error and ignores it if the status code is still `200`. 

It also adds some more cleanup for the docker check by closing idle connections when stopping the check and stopping a previous check when replacing a check.

Fixes #3576

### CODE REVIEW

**Comment by magiconair** [comment]
This feels like a band-aid but I can't spot the place where my client is behaving differently from the docker.io client. During `io.Copy` we just get a `connection reset by peer` error after having read the response body and the status code. If someone has more insight then I'm all ears.

File: agent/checks/docker.go [hunk 1]
```diff
@@ -151,11 +158,17 @@ func (c *DockerClient) CreateExec(containerID string, cmd []string) (string, err
...
 	b, code, err := c.call("POST", uri, data)
 	switch {
-	case err != nil:
+	// todo(fs): https://github.com/hashicorp/consul/pull/3621
+	// todo(fs): for some reason the docker agent closes the connection during the
+	// todo(fs): io.Copy call in c.call which causes a "connection reset by peer" error
+	// todo(fs): even though both body and status code have been received. My current is
+	// todo(fs): that the docker agent closes this prematurely but I don't understand why.
+	// todo(fs): the code below ignores this error.
+	case err != nil && !strings.Contains(err.Error(), "connection reset by peer"):
```
Comment (preetapan) [inline agent/checks/docker.go]: If the container is shut down this is still a valid error condition and should fail the healthcheck. I would watch for this error and do a retry (maybe limit to 3 retries) rather than ignoring it altogether.

Comment (magiconair) [reply agent/checks/docker.go]: The error comes from the docker agent and not the container. You can shut down the container and the check will go critical. I've tried that.

Comment (preetapan) [reply agent/checks/docker.go]: What about if the docker agent daemon is shutdown and restarted after several minutes. Does the check still go critical? I believe it would because then this code will see 'connection refused' errors, not 'reset by peer' but want to confirm

Comment (magiconair) [reply agent/checks/docker.go]: Good point. I'll test that

Comment (magiconair) [reply agent/checks/docker.go]: I've tried this:

```
# run docker container
docker run -it ubuntu

# run consul
sudo /vagrant/consul agent -dev -config-dir /vagrant/conf.d/

$ cat conf.json
{
	"bind_addr": "127.0.0.1",
	"advertise_addr":"127.0.0.1",
	"bootstrap": true,
	"disable_remote_exec":false,
	"enable_script_checks":true,
	"node_id":"ac5ec7af-5238-4c18-988a-0385d0a0f477",
	"data_dir":"/tmp/consultest",
	"ports":{
		"https":-1,
		"serf_lan":9301
	},
	"datacenter":"mydc",
	"ui":true,
	"server":true
}
$ cat svc.json
{
	"service":{
		"name":"foo",
		"Check": {
			"name":"bar",
			"docker_container_id":"8afaa5f28703",
			"script":"echo hey",
			"interval":"2s"
		}
	}
}

# check healthy, no flaps

docker pause <id> -> check goes critical
docker unpause <id> -> check goes OK
docker kill <id> -> check goes critical and stays there

# start new container, update svc.json and pkill -HUP -f consul to reload
# check goes OK again

# stop docker agent
sudo service docker stop

# check goes critical "conn refused" since it never 
# gets to `StartExec` but fails one step before
```

Comment (magiconair) [reply agent/checks/docker.go]:
```ruby
$ cat Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.hostname = "docker"
    c.vm.box_check_update = false
    c.vm.provision "shell", inline: <<-SHELL
	  apt-get install -y apt-transport-https ca-certificates curl software-properties-common
	  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

	  apt-key fingerprint 0EBFCD88
	  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
	  apt-get update

	  apt-get install -y docker-ce=17.03.1~ce-0~ubuntu-xenial
	  docker run hello-world
	  systemctl enable docker

	  groupadd docker
	  usermod -aG docker $USER
	  docker run hello-world

	  apt-get install -y unzip
	  wget -q https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
	  unzip -f consul_1.0.0_linux_amd64.zip
	  rm *.zip
    SHELL
  end
end
```

Comment (magiconair) [reply agent/checks/docker.go]: I've built the consul binary with 

```sh
$ make linux && cp pkg/linux_amd64/consul ~/vagrant/ubuntu-docker
```

Comment (preetapan) [reply agent/checks/docker.go]: :+1:

File: agent/checks/docker.go [hunk 2]
```diff
@@ -151,11 +158,17 @@ func (c *DockerClient) CreateExec(containerID string, cmd []string) (string, err
 }
 
 func (c *DockerClient) StartExec(containerID, execID string) (*circbuf.Buffer, error) {
-	data := struct{ Detach, Tty bool }{Detach: false, Tty: true}
+	data := struct{ Detach, Tty bool }{Detach: false, Tty: false}
```
Comment (preetapan) [inline agent/checks/docker.go]: why did tty change?

Comment (preetapan) [reply agent/checks/docker.go]: never mind i just saw the commit message

Comment (magiconair) [reply agent/checks/docker.go]: The main reason was that the older client was using `Tty: false`. I *think* pseudo-terminals are required for interactive sessions but I'll double check.

Comment (magiconair) [reply agent/checks/docker.go]: Looks like my assumptions was correct. Will merge.

**Comment by magiconair** [comment]
Updated CHANGELOG as well
