### PR TITLE
agent: shutdown if the http server goroutine exits

### LINKED ISSUE #6677: consul may continue running without a working HTTP server
#### Overview of the Issue

We configure consul to run the HTTP API on port 8500. However, we found that sometimes we had a running consul process that wasn't listening on that port anymore.

After digging through logs we found the following:

```
2019/10/14 12:43:38 accept tcp 127.0.0.1:8500: accept4: too many open files in system
```

This corresponds to ENFILE (not EMFILE). The server had run out of file descriptors, and this aborted the HTTP accept loop:

https://github.com/hashicorp/consul/blob/60f6ec0/agent/agent.go#L935-L937

However the consul process kept running. Should the process abort instead under these circumstances?

I've filed https://github.com/golang/go/issues/35131 with Go to maybe treat ENFILE as a temporary error as well.

#### Reproduction Steps

1. Exhaust files available to the OS
2. Try to connect to the consul RPC port

### Operating system and Environment details

Linux

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #6677 

[x/sync/errgroup](https://golang.org/x/sync/errgroup) is designed to handle exactly this problem. I have used it in the past and found that it handled the problem well.

Eventually we may be able to use a single `errgroup.Group` as the core of the agent. That would require that every goroutine shutdown on a cancelled context (instead of calling `Shutdown`). Until that is possible I've put it into a new `apiServers` struct and exposed the channel so that `command` can be notified when one of them exits, and proceed with the shutdown.

As a follow up to this PR I think we can move at least the `dnsServers` into `apiServers`, which should further shrink `agent.Agent`. Maybe it would be appropriate to move the `grpcServers` in as well?

The retryJoiner for Lan/Wan pools also works the same way. So using this errgroup for them would help shrink the Agent even further.

### CODE REVIEW

File: agent/agent.go [hunk 1]
```diff
@@ -1134,14 +1141,16 @@ func (a *Agent) startListeners(addrs []net.Addr) ([]net.Listener, error) {
...
 	var ln []net.Listener
-	var servers []*HTTPServer
+	var servers []apiServer
+
 	start := func(proto string, addrs []net.Addr) error {
 		listeners, err := a.startListeners(addrs)
 		if err != nil {
 			return err
 		}
+		ln = append(ln, listeners...)
```
Comment (dnephin) [inline agent/agent.go:1153]: This was moved up from line 1178. I believe the old code would not properly close the listener that caused the error because it was not appended to the list until after an error is returned.

File: agent/agent.go [hunk 2]
```diff
@@ -1257,43 +1275,6 @@ func (a *Agent) listenSocket(path string) (net.Listener, error) {
...
-		defer a.wgServers.Done()
-		notif <- srv.ln.Addr()
-		err := srv.Server.Serve(srv.ln)
-		if err != nil && err != http.ErrServerClosed {
-			a.logger.Error("error closing server", "error", err)
-		}
-	}()
-
-	select {
-	case addr := <-notif:
```
Comment (dnephin) [inline agent/agent.go:1279]: This select/case no longer exists. All this was doing was waiting for a goroutine to start. The server would not actually be started when the addr is sent on the channel.

With this change, a failure to server will cause a shutdown, so we now properly handle the case without the need for the `notif` channel.

**Comment by dnephin** [comment]
I amended the last commit to fix a merge conflict and added more godoc to `apiServers`.
