### PR TITLE
agent: fix bug with multiple listeners

### LINKED ISSUE #9214: API listener regression Consul 1.9.0-RC
#### Overview of the Issue

After updating to Consul 1.9.0-rc Consul does no longer listen to more than one IP address for API requests (http/https)

#### Reproduction Steps

With the following in the config The http, dns and GRPC should all listen on both localhost and the lan IP.  The logs say this is what is happening but looking at open ports show http does not. (DNS and GRPC is fine)

```
addresses {
  dns  = "127.0.0.1 {{GetPrivateIP}}"
  http = "127.0.0.1 {{GetPrivateIP}}"
  grpc = "127.0.0.1 {{GetPrivateIP}}"
}
```

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = rc1
	revision = 35d3e629
	version = 1.9.0
consul:
	acl = enabled
	bootstrap = true
	known_datacenters = 1
	leader = true
	leader_addr = 10.10.10.13:8300
	server = true
raft:
	applied_index = 4162
	commit_index = 4162
	fsm_pending = 0
	last_contact = 0
	last_log_index = 4162
	last_log_term = 8
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:f5410285-86da-aaab-2188-a5c9853d584e Address:10.10.10.13:8300}]
	latest_configuration_index = 0
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 8
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 94
	max_procs = 8
	os = darwin
	version = go1.15.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 7
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 7
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

macOS 11.0.1, amd64.

### Log Fragments

From the Logs...
```
    2020-11-18T13:15:45.512+1100 [INFO]  agent: Started DNS server: address=127.0.0.1:8600 network=tcp
    2020-11-18T13:15:45.512+1100 [INFO]  agent: Started DNS server: address=10.10.10.13:8600 network=tcp
    2020-11-18T13:15:45.512+1100 [INFO]  agent: Started DNS server: address=10.10.10.13:8600 network=udp
    2020-11-18T13:15:45.512+1100 [INFO]  agent: Started DNS server: address=127.0.0.1:8600 network=udp
    2020-11-18T13:15:45.514+1100 [INFO]  agent: Starting server: address=127.0.0.1:8500 network=tcp protocol=http
    2020-11-18T13:15:45.514+1100 [INFO]  agent: Starting server: address=10.10.10.13:8500 network=tcp protocol=http
    2020-11-18T13:15:45.514+1100 [INFO]  agent: Started gRPC server: address=127.0.0.1:8502 network=tcp
    2020-11-18T13:15:45.514+1100 [INFO]  agent: Started gRPC server: address=10.10.10.13:8502 network=tcp
```
 But verifying with lsof -nPi
```
consul    6765 consul   17u  IPv4 0x95d9fe19e8a08813      0t0  TCP 127.0.0.1:8600 (LISTEN)
consul    6765 consul   18u  IPv4 0x95d9fe19ec98065b      0t0  TCP 10.10.10.13:8600 (LISTEN)
consul    6765 consul   19u  IPv4 0x95d9fe19e04b5a13      0t0  UDP 127.0.0.1:8600
consul    6765 consul   20u  IPv4 0x95d9fe19e04b5443      0t0  UDP 10.10.10.13:8600
consul    6765 consul   21u  IPv4 0x95d9fe19e939c8d3      0t0  TCP 10.10.10.13:52422->10.10.10.13:8300 (ESTABLISHED)
consul    6765 consul   22u  IPv4 0x95d9fe19eba7022b      0t0  TCP 10.10.10.13:8500 (LISTEN)
consul    6765 consul   23u  IPv4 0x95d9fe19eba734a3      0t0  TCP 127.0.0.1:8502 (LISTEN)
consul    6765 consul   24u  IPv4 0x95d9fe19eba752eb      0t0  TCP 10.10.10.13:8502 (LISTEN)
```

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #9214

Previously the listener was being passed to a closure in a loop without capturing the loop variable. The result is only the last listener is used, so the http/https servers only listen on one address.

This problem is fixed by capturing the variable by passing it into a function.

There was a fix for this in https://github.com/hashicorp/consul/pull/8623/files#diff-62b6ad581fe3a3059ae8c85ef0f31dde4092bfdecfa7d6857c470bcacaa8cc8bR765, but that PR has not merged yet.

### CODE REVIEW

File: agent/agent_test.go [hunk 1]
```diff
@@ -4705,3 +4712,64 @@ func TestSharedRPCRouter(t *testing.T) {
...
+	bd := BaseDeps{
+		Deps: consul.Deps{
+			Logger:          hclog.NewInterceptLogger(nil),
+			Tokens:          new(token.Store),
+			TLSConfigurator: tlsConf,
+		},
+		RuntimeConfig: &config.RuntimeConfig{
+			HTTPAddrs: []net.Addr{
+				&net.TCPAddr{IP: net.ParseIP("127.0.0.1")},
+				&net.TCPAddr{IP: net.ParseIP("127.0.0.1")},
```
Comment (rboyer) [inline agent/agent_test.go:4729]: why aren't these different ip addresses?

Comment (dnephin) [reply agent/agent_test.go:4729]: I guess I could use another 127.0.0.0/24 address? The IP is the same, but the port is different (because it is set to 0 and the OS will choose one), so we end up with two different listener addresses. I could also add `Port: 0` to make that more explicit.

Comment (rboyer) [reply agent/agent_test.go:4729]: Actually if that's the case you should probably use freeport to grab two ports officially at the top of the test and use them here. Unit tests cannot actually ever rely upon `:0` port grabbing because that invalidates some tests that rely upon a particular port being reserved _and not listening_ for a portion of those tests.

**Review by rboyer — APPROVED** [review]
LGTM
