### PR TITLE
Sensible keyring error

### LINKED ISSUE #7231: Not possible to use gossip encryption without a warning in the logs
#### Overview of the Issue

First time I start consul with a blank slate, I have `encrypt = "key"` in my config file and I get `Encrypt: Gossip: true` in the output. If I restart consul, it warns me that I supplied "encrypt" again, but there is a keyring and it's going to use that instead. So I remove the "encrypt" option from my config, to get rid of the warning, assuming it will just use the keyring. Instead after restarting, I just get `Encrypt: Gossip: false` - It seems like the only option is to leave "encrypt" in the config and ignore the warning. It's like you can't have encrypted gossip without also having this warning.

#### Reproduction Steps

Steps to reproduce this issue:

Do as I described in the overview

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease =
	revision = 7f3b5f34
	version = 1.6.3
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 10.150.0.13:8300
	server = true
raft:
	applied_index = 45
	commit_index = 45
	fsm_pending = 0
	last_contact = 0
	last_log_index = 45
	last_log_term = 3
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:4cb7c3a4-097d-2ece-a4b0-7efba281f21d Address:10.150.0.13:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 3
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 84
	max_procs = 1
	os = linux
	version = go1.12.13
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 1
	event_time = 3
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
</details>

### Operating system and Environment details

CentOS 7

### PR DESCRIPTION
**Pull request by i0rek**
Fixes #7231. Before an agent would always emit a warning when there is
an encrypt key in the configuration and an existing keyring stored,
which is happening on restart.

Now it only emits that warning when the encrypt key from the
configuration is not part of the keyring.

I feel a little bad, because `setupBaseKeyrings` is not pretty and I would like to make it better. But that would mean more changes that don't contribute to the fix at hand. Will leave that for later.

### CODE REVIEW

**Comment by i0rek** [comment]
test failures are related. will fix.

File: agent/agent.go [hunk 1]
```diff
@@ -1617,6 +1622,26 @@ LOAD:
...
+	// Only perform the following checks if there was an encrypt_key
+	// provided in the configuration.
+	if a.config.EncryptKey != "" {
+		msg := " keyring doesn't include key provided with -encrypt, using keyring"
+		if existingLANKeyring &&
+			keyringIsMissingKey(
+				config.SerfLANConfig.MemberlistConfig.Keyring,
+				a.config.EncryptKey,
+			) {
+			a.logger.Warn("LAN" + msg)
```
Comment (mkeeler) [inline agent/agent.go]: nit:

I think this would be more consistent with existing logs if it were:

```
a.logger.Warn(msg, "keyring", "WAN")
```

During the hclog refactor it looked like most of the places that we had previously formatted a log message we turned into having a constant string message and passing the other data to the logger as kv pairs.

The same thing goes for the log for the "LAN" case too. If you really prefer this form, then thats fine with me too. My opinions on the subject are not very strong either way.

Comment (i0rek) [reply agent/agent.go]: Thank you Matt! This was actually a thing I kept wondering how to do with the new logger! I like your suggestion and will go with it!

Comment (mkeeler) [reply agent/agent.go]: :thumbsup:
