### PR TITLE
server: partly fix config entry replication issue that prevents replication in some circumstances

### LINKED ISSUE #9319: Config Entry replication of ingress-gateway entries fails validation in secondary datacenter
#### Overview of the Issue

Config Entry replication fails to apply properly in the secondary datacenter, blocking replication from finishing. This is caused by `ingress-gateway` config validation being dependent on an existing `proxy-defaults` entry.

I could imagine that this is an issue with any config entry that is dependent on another entry for setting properties like the `protocol` of the service.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create 2 datacenters
1. Create an ingress gateway config entry with an `http` listener for a service defined, and a `proxy-defaults` entry that sets everything to `http` protocol
1. Watch the secondary DC to see the replication of config entries

This does not reproduce all of the time, I think because sometimes the secondary DC will replicate the `proxy-defaults` entry before the `ingress-gateway` entry is added in my setup.

##### My Config Entries:

Created via `consul config write` CLI command:
```
{
  "kind": "ingress-gateway",
  "name": "ingress1",
  "listeners": [
    {
      "protocol": "http",
      "port": 443,
      "services": [
        {
          "name": "*"
        }
      ]
    },
    {
      "protocol": "http",
      "port": 444,
      "services": [
        {
          "name": "virtual"
        }
      ]
    }
  ]
}
```

Set in the config of the primary servers:
```
  "config_entries": {
    "bootstrap": [
      {
        "kind": "proxy-defaults",
        "name": "global",
        "config": {
          "protocol": "http"
        }
      },
      {
        "kind": "service-router",
        "name": "counting",
        "routes": [
          {
            "destination": {
              "NumRetries": 3,
              "RetryOnConnectFailure": true
            }
          }
        ]
      }
    ]
  },
```
### Log Fragments

```
    2020-12-03T16:33:52.006Z [DEBUG] agent.server.replication.config_entry: finished fetching config entries: amount=3
    2020-12-03T16:33:52.007Z [DEBUG] agent.server.replication.config_entry: Config Entry replication: local=0 remote=3
    2020-12-03T16:33:52.007Z [DEBUG] agent.server.replication.config_entry: Config Entry replication: deletions=0 updates=3
    2020-12-03T16:33:52.007Z [DEBUG] agent.server.replication.config_entry: Updating local config entries: updates=3
    2020-12-03T16:33:52.008Z [WARN]  agent.server.replication.config_entry: replication error (will retry if still leader): error="failed to update local config entries: Failed to apply config upsert: service "virtual" has protocol "tcp", which does not match defined listener protocol "http""
```

### PR DESCRIPTION
**Pull request by rboyer**
There are some cross-config-entry relationships that are enforced during
"graph validation" at persistence time that are required to be
maintained. This means that config entries may form a digraph at times.

Config entry replication proceeds in a particular sorted order by kind
and name.

Occasionally there are some fixups to these digraphs that end up
replicating in the wrong order and replicating the leaves
(ingress-gateway) before the roots (service-defaults) leading to
replication halting due to a graph validation error related to things
like mismatched service protocol requirements.

This PR changes replication to give each computed change (upsert/delete)
a fair shot at being applied before deciding to terminate that round of
replication in error. In the case where we've simply tried to do the
operations in the wrong order at least ONE of the outstanding requests
will complete in the right order, leading the subsequent round to have
fewer operations to do, with a smaller likelihood of graph validation
errors.

This does not address all scenarios, but for scenarios where the edits
are being applied in the wrong order this should avoid replication
halting.

Fixes #9319

The scenario that is NOT ADDRESSED by this PR is as follows:

1. create: service-defaults: name=new-web, protocol=http
2. create: service-defaults: name=old-web, protocol=http
3. create: service-resolver: name=old-web, redirect-to=new-web
4. delete: service-resolver: name=old-web
5. update: service-defaults: name=old-web, protocol=grpc
6. update: service-defaults: name=new-web, protocol=grpc
7. create: service-resolver: name=old-web, redirect-to=new-web

If you shutdown dc2 just before (4) and turn it back on after (7)
replication is impossible as there is no single edit you can make to
make forward progress.

### CODE REVIEW

File: agent/consul/config_replication.go [hunk 1]
```diff
@@ -214,9 +217,10 @@ func (s *Server) replicateConfig(ctx context.Context, lastRemoteIndex uint64, lo
 			return 0, true, nil
 		}
 		if err != nil {
-			return 0, false, fmt.Errorf("failed to delete local config entries: %v", err)
+			merr = multierror.Append(merr, err)
```
Comment (kisunji) [inline agent/consul/config_replication.go:220]: do we want to preserve the error message here?

File: agent/consul/config_replication.go [hunk 2]
```diff
@@ -228,9 +232,14 @@ func (s *Server) replicateConfig(ctx context.Context, lastRemoteIndex uint64, lo
 			return 0, true, nil
 		}
 		if err != nil {
-			return 0, false, fmt.Errorf("failed to update local config entries: %v", err)
+			merr = multierror.Append(merr, err)
```
Comment (kisunji) [inline agent/consul/config_replication.go:235]: do we want to preserve the error message here?

File: agent/consul/config_replication_test.go [hunk 3]
```diff
@@ -247,3 +247,106 @@ func TestReplication_ConfigEntries(t *testing.T) {
...
+
+	t.Parallel()
+	dir1, s1 := testServerWithConfig(t, func(c *Config) {
+		c.PrimaryDatacenter = "dc1"
+	})
+	defer os.RemoveAll(dir1)
+	defer s1.Shutdown()
+	testrpc.WaitForLeader(t, s1.RPC, "dc1")
+	client := rpcClient(t, s1)
+	defer client.Close()
```
Comment (kisunji) [inline agent/consul/config_replication_test.go:264]: I think all the `defer`s are unnecessary here (and the `defer os.RemoveAll(dir1)` conflicts with testDir flag behavior)

File: agent/consul/config_replication_test.go [hunk 4]
```diff
@@ -247,3 +247,106 @@ func TestReplication_ConfigEntries(t *testing.T) {
...
+	dir2, s2 := testServerWithConfig(t, func(c *Config) {
+		c.Datacenter = "dc2"
+		c.PrimaryDatacenter = "dc1"
+		c.ConfigReplicationRate = 100
+		c.ConfigReplicationBurst = 100
+		c.ConfigReplicationApplyLimit = 1000000
+	})
+	testrpc.WaitForLeader(t, s2.RPC, "dc2")
+	defer os.RemoveAll(dir2)
+	defer s2.Shutdown()
```
Comment (kisunji) [inline agent/consul/config_replication_test.go:275]: Can be removed

File: agent/consul/config_replication_test.go [hunk 5]
```diff
@@ -247,3 +247,106 @@ func TestReplication_ConfigEntries(t *testing.T) {
...
+		out := false
+		require.NoError(t, s1.RPC("ConfigEntry.Apply", &arg, &out))
+	}
+
+	// Try to join which should kick off replication.
+	joinWAN(t, s2, s1)
+	testrpc.WaitForLeader(t, s1.RPC, "dc1")
+	testrpc.WaitForLeader(t, s1.RPC, "dc2")
+
+	checkSame := func(t *retry.R) error {
```
Comment (kisunji) [inline agent/consul/config_replication_test.go:316]:
```suggestion
	checkSame := func(t *require.TestingT) error {
```

File: agent/consul/config_replication.go (hunk 1 above)
Comment (rboyer) [reply agent/consul/config_replication.go:220]: the inner errors will be of the form `Failed to apply config entry <delete|upsert>: <error with details>` so since the delete/update portion was already present I didn't see the value.

File: agent/consul/config_replication.go (hunk 2 above)
Comment (rboyer) [reply agent/consul/config_replication.go:235]: same

File: agent/consul/config_replication_test.go (hunk 5 above)
Comment (rboyer) [reply agent/consul/config_replication_test.go]: Doing this, but not as a pointer-to-an-interface because that's probably not what you meant.

**Review by freddygv — APPROVED** [review]

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/594115.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 64271289ec3c3b6c00a8685b7822eafcf472bcb6 onto `release/1.11.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit 64271289ec3c3b6c00a8685b7822eafcf472bcb6 onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit 64271289ec3c3b6c00a8685b7822eafcf472bcb6 onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/594115)
