### PR TITLE
fix: add tls config to unix socket when https is used

### LINKED ISSUE #16252: Consul HTTPS unix socket binds HTTP instead
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

In testing using unix sockets for connect envoy and consul I have come across that entering a unix socket for https results in a http socket instead.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a consul config supplying all the TLS goodies and add the https address section pointing to a unix socket.  In my case I am using the consul docker container 1.14.4
```JSON
    "addresses": {
        "grpc_tls" : "unix://consul/consul_grpc.sock",
        "http" : "unix://consul/consul_http.sock",
        "https" : "unix://consul/consul_https.sock"
    },
```
2. Configure consul connect to connect to the socket using environment vars
```
      - CONSUL_HTTP_ADDR=unix://consul/consul_https.sock
      - CONSUL_HTTP_SSL=true
```
3. View error
`us-consul-gateway  | Error registering service "gateway-us": Put "https://consul%2Fconsul_https.sock/v1/agent/service/register": http: server gave HTTP response to HTTPS client`
### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
# consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease =
	revision = dae670fe
	version = 1.14.4
	version_metadata =
consul:
	acl = enabled
	known_servers = 1
	server = false
runtime:
	arch = arm64
	cpu_count = 2
	goroutines = 98
	max_procs = 2
	os = linux
	version = go1.19.4
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 25
	members = 2
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Mac OS using docker

### PR DESCRIPTION
**Pull request by huikang**
### Description
Add tls config to unix socket when https is used

### Testing & Reproduction steps
Manually tested with the following agent config

```
"addresses": {
        "grpc_tls" : "unix://consul/consul_grpc.sock",
        "http" : "unix://consul/consul_http.sock",
        "https" : "unix://consul/consul_https.sock"
    },
```

```
export CONSUL_HTTP_ADDR=unix://consul/consul_https.sock
CONSUL_HTTP_SSL=true consul connect 
```

### Links

fix #16252 

### PR Checklist

* [ ] updated test coverage
* [ ] external facing docs updated
* [x] not a security concern

### CODE REVIEW

**Review by mkeeler — COMMENTED** [review]
To not be surprising this fix is necessary (although in this case TLS isn't really providing any extra security).

Should we have a test somewhere that starts a unix https listener and attempts to connect via TLS to ensure its working?

**Comment by huikang** [comment]
> To not be surprising this fix is necessary (although in this case TLS isn't really providing any extra security).
> 
> Should we have a test somewhere that starts a unix https listener and attempts to connect via TLS to ensure its working?

Thanks for the prompt response.

Agreed that we need some form of test on this agent configuration. The closet example I can find is https://github.com/hashicorp/consul/blob/2460ac99c95aa9177d0ae4e527ee6d8d2fbac062/agent/agent_test.go#L3905-L3908
Or do you have any recommendation on which example I shall follow? Thanks.

**Comment by mkeeler** [comment]
@huikang You could probably copy/paste + modify this test: https://github.com/hashicorp/consul/blob/8dab825c36406e8dd9222e857b486f139072c45a/agent/http_test.go#L39-L99

File: agent/http_test.go [hunk 1]
```diff
@@ -151,9 +241,13 @@ func TestSetupHTTPServer_HTTP2(t *testing.T) {
 	a := StartTestAgent(t, TestAgent{
 		UseHTTPS: true,
 		HCL: `
-			key_file = "../test/client_certs/server.key"
```
Comment (huikang) [inline agent/http_test.go:154]: deprecated

**Comment by huikang** [comment]
@mkeeler , the unit test is added. Please take a look whenever you have a chance. Thanks.

**Review by boxofrad — APPROVED** [review]
