### PR TITLE
Fix envoy 1.10 exec

### LINKED ISSUE #5960: Envoy 1.10 not supported by `consul connect envoy`
While investigating a "flaky" integration test today, I realised that one specific integration test (the one that verifies our exec trick works) was actually buggy and ran against a non-deterministic version of Envoy!

I have a fix for the test locally and can now confirm that Envoy 1.10 is broken when used with `consul connect envoy` (the execing form, not the bootstrapping form).

It's broken because:
 1. `--v2-config-only` arg was removed. This is easy to fix since it wasn't actually necessary for the old versions and we can just remove it.
 2. Our FD trick with `/dev/fd/<fd>` is broken in 1.10 due to them being stricter about "sensiteive" paths. I've [filed an issue](https://github.com/envoyproxy/envoy/issues/7258).

We can't release 1.5.2 like this so we need to do one of:
 - revert the 1.10 PR and wait for a later release to support it
 - come up with a work-around for now for 1.10 exec. We could go back to writing the bootstrap file to disk but it's pretty gross from a security POV.
 - make `consul connect envoy` fail for Envoy 1.10 (somehow) with an error saying it only supports the `-bootstrap` method or something.

CC @i0rek FYI. Lets work out the best solution here.

### LINKED ISSUE #5962: ACL API no-merge support
#### Feature Description

The Consul Agent CLI supports the no-merge feature when executing an UPDATE command on an existing ACL policy. (https://www.consul.io/docs/commands/acl/policy/update.html#no-merge)
I'd like to have that feature also available on the API of Consul.

#### Use Case(s)

We're provisioning policies through the API and wanted to update policies in place but overwriting the old rules.
Currently, we have to:

1. check if we have a policy existing with our naming convention
2. delete it
3. recreate it with the new rules

We'd just like to avoid having to delete an existing policy when we only want to overwrite rules.

### PR DESCRIPTION
**Pull request by banks**
Potentially fixes #5960 

This replaces our exec mechanism that relied on CLOEXEC and inherited file descriptors and the magic `/dev/fd/<num>` to pass a file to Envoy that didn't actually appear in the file system since it contains secrets.

Since [envoy 1.10] sanitises the path so that doesn't work any more, this falls back to an alternative mechanism that does - at least on macOS and linux in my testing so far.

The strategy now is to:
 - create a named pipe (fifo)
 - spawn a detached child process that will cat STDIN to the fifo. (we need this since writing to fifo will block until Envoy is ready to read but we want the main process to exec Envoy directly)
 - write the bootstrap the STDIN of the child
 - exec Envoy with the named pipe as the config file path
 - Envoy reads it and starts as normal in foreground
 - child process deletes the named pipe again and exits (will be left in a Zombie state)

The child is launched still attached to the parent's TTY. I'm not sure if this is the best thing to do - it's nice in that if you run the command from a terminal, then the child is cleaned up once you Ctrl-C rather than becoming a Zombie forever.

## Questions

 - ~Is the TTY behaviour right?~ changed to be non-special child with same TTY.
 - ~I'm using `/bin/bash` but is there a more portable way to invoke a bash-like shell?~ Changed to use `cp` from $PATH.
 - ~Will deleting the fifo right after writing cause a race? I think not because the write can't complete until Envoy starts reading at which point it has the file descriptor so rm will just unlink and the file will only really be removed once Envoy closes it but I could be wrong. It works fine in my few tests on maxOS and linux (via the integration test/docker).~ It will not. Confirmed.
 - ~Any other downsides I'm not thinking of?~ Loads, but this seems the best option

### CODE REVIEW

File: command/connect/envoy/exec_unix.go [hunk 1]
```diff
@@ -43,126 +43,94 @@ func hasHotRestartOption(argSets ...[]string) bool {
...
+		Dir: ".",
+		Env: os.Environ(),
+		Files: []*os.File{
+			pr,
+			nil,
+			nil,
+		},
+	}
+	process, err := os.StartProcess("/bin/bash",
+		[]string{"bash", "-c", "cat > " + pipeFile + "; rm -rf " + pipeFile},
```
Comment (rboyer) [inline command/connect/envoy/exec_unix.go]: You could also add an consul subcommand that did this operation rather than doing a blob of inline shell. That subcommand could be omitted from the general help listings as it isn't terribly useful on its own.

As is you make the assumption here that `/bin/bash` is valid and that `cat & rm` are both on the `PATH`. These are all reasonable assumptions, but new here.

Another bit of awfulness here, with inline shell (via `bash -c`) you now have to think a bit harder about whether `pipeFile` could have spaces in the full path. Normally no, but what if someone set `TMPDIR` to an absolute path with spaces in the name?  If you could manage this as a single subprocess invocation with the `pipeFile` value only manifesting in a single positional argument you wouldn't have to worry (like some mythical app named `cp_and_rm`).

Comment (rboyer) [reply command/connect/envoy/exec_unix.go]: This pretty much amounts to code golf, but you can use `cp` instead of `cat` if that seems better:
```
$ echo foo | cp /dev/stdin my.out
$ cat my.out
foo
```

**Comment by rboyer** [comment]
Another optimization would be to [adjust the size of the named pipe](https://unix.stackexchange.com/questions/439196/change-buffer-size-of-named-pipe) to hold the full bootstrap file and then write it all from the consul subcommand before running envoy, but you still run into the issue of preferring to garbage collect the named pipe anyway so it doesn't gain you much.

**Comment by rboyer** [comment]
> Will deleting the fifo right after writing cause a race? I think not because the write can't complete until Envoy starts reading at which point it has the file descriptor so rm will just unlink and the file will only really be removed once Envoy closes it but I could be wrong. It works fine in my few tests on maxOS and linux (via the integration test/docker).

If the fifo buffer is big enough the write won't block. You'll merrily write the entire JSON blob into the fifo and immediately erase it before envoy has read any of it back out again.

File: command/connect/envoy/exec_unix.go (hunk 1 above)
Comment (banks) [reply command/connect/envoy/exec_unix.go]: Hmm yeah I considered a custom command. Requiring bash and cat seemed _ok_ to me but I don't really want to go handling issues for this on arcane minimal setups etc.

**Comment by banks** [comment]
> Another optimization would be to adjust the size of the named pipe to hold the full bootstrap file and then write it all from the consul subcommand before running envoy, but you still run into the issue of preferring to garbage collect the named pipe anyway so it doesn't gain you much.

Well the file is a temp file anyway so should be garbage collected by the system. But I'm not sure this is true. The bootstrap is only just over 1kb and most things I've seen say the default pipe buffer on macOS is usually larger than that.

For example:

```bash
$ mkfifo /tmp/pipe
~/s/h/consul (fix-envoy-1.10-exec+) echo "foo" > /tmp/pipe
# blocks even though there are only 4 bytes being written until something opens fifo for reading.
```

So my understanding is that until Envoy opens the other end, the buffer size doesn't matter and the write will always block but I'm still not sure about that. https://stackoverflow.com/questions/21223703/block-until-a-reader-has-connected-to-named-pipe indicates that named pipe writes block until a corresponding `open` call on the pipe which matches my example above. So sadly we can't dispense with the child process it seems.

This is not the same as un-named pipes it would seem which is why writing the whole bootstrap to STDIN pipe passed to the child works OK before starting the child. I guess technically if the bootstrap got big enough then we'd end up hanging on the STDIN write too which is another possible issue here in the future.

**Comment by rboyer** [comment]
> Well the file is a temp file anyway so should be garbage collected by the system.

If it's created in `/tmp` and the operator has arranged for that to be periodically cleared then yes. If it's created anywhere else then nothing will clean it up. There's no bit on the file saying "I'm a temp file".

**Comment by rboyer** [comment]
> If the fifo buffer is big enough the write won't block. You'll merrily write the entire JSON blob into the fifo and immediately erase it before envoy has read any of it back out again.

Oops I skimmed over what `exec 3<> fifo` was doing in the example (setting up the listener side). If I just do a `mkfifo` + `dd` yeah even 1 byte blocks. 

Ignore this.

**Comment by rboyer** [comment]
FYI the anonymous pipe buffer size by default is limited to 65536.
https://unix.stackexchange.com/questions/343302/anonymous-pipe-kernel-buffer-size

I experimentally showed this:
```
$ go run main.go -size 65536
PARENT: 2019/06/14 10:57:48 starting
PARENT: 2019/06/14 10:57:48 sample data is 65536 bytes
PARENT: 2019/06/14 10:57:48 created pipe "my.pipe"
PARENT: 2019/06/14 10:57:48 created anonymous pipe
PARENT: 2019/06/14 10:57:48 wrote data to anonymous pipe
PARENT: 2019/06/14 10:57:48 launching child proc
PARENT: 2019/06/14 10:57:48 releasing child proc
PARENT: 2019/06/14 10:57:48 exec-ing fake envoy (wc)
CHILD: 2019/06/14 10:57:48 starting
CHILD: 2019/06/14 10:57:48 reading data from STDIN
CHILD: 2019/06/14 10:57:48 writing data from "my.pipe"
CHILD: 2019/06/14 10:57:48 opening output file
CHILD: 2019/06/14 10:57:48 copied 65536 bytes from stdin to output file
65536 my.pipe   # fake envoy was 'wc -c'
```
vs
```
$ go run main.go -size 65537
PARENT: 2019/06/14 10:58:19 starting
PARENT: 2019/06/14 10:58:19 sample data is 65537 bytes
PARENT: 2019/06/14 10:58:19 created pipe "my.pipe"
PARENT: 2019/06/14 10:58:19 created anonymous pipe
< hangs forever>
```

**Comment by banks** [comment]
Incoming updates get to a satisfactory (I think) place to merge.

 - Uses internal shim command to sidestep shell/portability issues
 - Makes tests pass again
 - Shim command self-destructs after 10 seconds in case Envoy crashed before it opened the file or similar.
 - Somehow on my machine, this method doesn't even seem to leave the shim command as a Zombie waiting to be reaped by its parent. I don't fully understand that but it seems better!

Works under darwin and linux which are the only two OSes we support in build tags anyway.

File: command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap.go [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+func (c *cmd) init() {
+	c.help = flags.Usage(help, c.flags)
+}
+
+func (c *cmd) Run(args []string) int {
+	// This should never be alive for very long. In case bad things happen and
+	// Envoy never starts limit how long we live before just exiting so we can't
+	// accumulate tons of these zombie children.
+	time.AfterFunc(10*time.Second, func() { os.Exit(99) })
```
Comment (rboyer) [inline command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap.go]: Maybe this time bomb should also erase the pipe file?

File: command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap.go [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+		return 1
+	}
+
+	_, err = io.Copy(f, os.Stdin)
+	if err != nil {
+		c.UI.Error(err.Error())
+		return 1
+	}
+
+	f.Close()
```
Comment (rboyer) [inline command/connect/envoy/pipe-bootstrap/connect_envoy_pipe-bootstrap.go]: Since you were doing writes through this file descriptor you should probably explicitly check the error returned from `Close`. I know sometimes for normal files opened for writing some errors only manifest when you close the file descriptor and the rest of the working state is flushed. I know this is a named pipe but it wouldn't hurt to just explicitly check the error.

File: go.mod [hunk 4]
```diff
@@ -88,7 +87,6 @@ require (
 	github.com/kr/pretty v0.1.0 // indirect
 	github.com/kr/text v0.1.0
 	github.com/lib/pq v0.0.0-20180523175426-90697d60dd84 // indirect
-	github.com/lyft/protoc-gen-validate v0.0.0-20180911180927-64fcb82c878e // indirect
```
Comment (rboyer) [inline go.mod]: unrelated?

File: command/connect/envoy/exec_test.go [hunk 5]
```diff
@@ -193,6 +186,11 @@ func TestHelperProcess(t *testing.T) {
 
 		limitProcessLifetime(2 * time.Minute)
 
+		// This is another level of gross - we are relying on `consul` being on path
+		// and being the correct version but in general that is true under `make
+		// test`. We already make the same assumption for API package tests.
+		testSelfExecOverride = "consul"
```
Comment (mkeeler) [inline command/connect/envoy/exec_test.go]: I have thought about this numerous times too. Couldn't we during testing look in ./bin within the source directory for the binary instead of assuming the one on the path is the correct one.

Thats probabably a future task and not something to overhaul with this PR though.
