### PR TITLE
Fix high cpu usage with IPv6 recursor address. Closes #6120

### LINKED ISSUE #6120: 100% CPU after upgrade to consul 1.5.2
After upgrading to 1.5.2 our consul agents where taking all available CPU.

I traced the issue to PR #5468

We specify our IPv6 recursor on startup with the flag `-recursor [2001:db8:85a3:8d3:1319:8a2e:370:7348]` but without a port (which should use the default port 53)

This PR introduced a tight loop on that port 53 check in: https://github.com/hashicorp/consul/blob/a82e6a7fd33a0d05b9b871bcaf1d7595c9b8dedc/agent/dns.go#L271-L275 which results in an every increasing bracket adding `[[[2001:db8:85a3:8d3:1319:8a2e:370:7348]]:53]:53` etc and taking all the CPU

According to https://github.com/golang/go/issues/20470 the "[]" are only allowed when specifying a port with an ipv6 address.

But the `-recursor 2001:db8:85a3:8d3:1319:8a2e:370:7348` fails with `too many colons in address`

So a possible fix would be to check for that error as below:

```
START:
	_, _, err := net.SplitHostPort(recursor)
	if ae, ok := err.(*net.AddrError); ok && (ae.Err == "missing port in address" ||  ae.Err == "too many colons in address") {
		recursor = ipaddr.FormatAddressPort(recursor, 53)
		goto START
```

ping @pierresouchay 

Simple workaround for this bug is specifying the port `-recursor [2001:db8:85a3:8d3:1319:8a2e:370:7348]:53`

### PR DESCRIPTION
**Pull request by 42wim**

### CODE REVIEW

File: agent/dns.go [hunk 1]
```diff
@@ -270,7 +270,7 @@ func recursorAddr(recursor string) (string, error) {
 	// Add the port if none
 START:
 	_, _, err := net.SplitHostPort(recursor)
-	if ae, ok := err.(*net.AddrError); ok && ae.Err == "missing port in address" {
+	if ae, ok := err.(*net.AddrError); ok && (ae.Err == "missing port in address" || ae.Err == "too many colons in address") {
```
Comment (mkeeler) [inline agent/dns.go]: I took a quick look at the implementation of `SplitHostPort` and there are several other real error cases where the `too many colons in address` can be returned. In those cases we would not want to use the `FormatAddressPort` logic with the default port but rather return the error.

I think something like the following should be sufficient to only assume a non-bracketed IPv6 address when we get that error.

```
if ae, ok := err.(*net.AddrError); ok {
  if ae.Err == "missing port in address" {
    recursor = ipaddr.FormatAddressPort(recursor, 53)
    goto START
  } else if ae.Err == "too many colons in address" {
    if ip := net.ParseIp(recursor); ip != nil && ip.To4() == nil {
      recursor = ipaddr.FormatAddressPort(recursor, 53)
      goto START
    }
  }
}
```

I haven't tested that myself but basically it just ensures that in the case of the too many colons error that the address is a valid IPv6 address and we didn't get that error for any other reason.

In addition, it would be great to also add a test for `foo::53` as that should return with the `too many colons in address` error but we should not attempt to turn it into an actual recursor.

**Comment by swills** [comment]
What is the status of this? I'm hitting this error too.

**Comment by i0rek** [comment]
@42wim This looks like something we would like to fix. Any updates on this one?

**Comment by 42wim** [comment]
@i0rek seems like I forgot about this issue, I'll try to fix this soon.

**Comment by i0rek** [comment]
Thank you!

**Comment by 42wim** [comment]
changes pushed
