### PR TITLE
Use bind address as source for outgoing connections (#2822)

### LINKED ISSUE #2822: Consul does not initiate RPC connections from the 'bind' address or support 'source' address
### `consul version` for both Client and Server
Server: Consul v0.7.5
Client: NA

### `consul info` for Server
Server:
```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 1
build:
        prerelease =
        revision = '21f2d5a
        version = 0.7.5
consul:
        bootstrap = false
        known_datacenters = 3
        leader = false
        leader_addr = 172.18.1.69:8300
        server = true
raft:
        applied_index = 11568
        commit_index = 11568
        fsm_pending = 0
        last_contact = 56.345518ms
        last_log_index = 11568
        last_log_term = 2
        last_snapshot_index = 8192
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:172.18.1.69:8300 Address:172.18.1.69:8300} {Suffrage:Voter ID:172.18.1.133:8300 Address:172.18.1.133:8300} {Suffrage:Voter ID:172.18.1.5:8300 Address:172.18.1.5:8300}]
        latest_configuration_index = 1
        num_peers = 2
        protocol_version = 1
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 2
runtime:
        arch = amd64
        cpu_count = 8
        goroutines = 62
        max_procs = 8
        os = linux
        version = go1.7.5
serf_lan:
        encrypted = true
        event_queue = 0
        event_time = 4
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 3896
        members = 6
        query_queue = 0
        query_time = 1
serf_wan:
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 13
        members = 9
        query_queue = 0
        query_time = 1
```

### Operating system and Environment details
CentOS Linux release 7.3.1611 (Core)
Linux ip-172-18-1-175 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP qlen 1000
    link/ether 12:f6:c5:ab:61:f6 brd ff:ff:ff:ff:ff:ff
    inet 172.18.1.175/26 brd 172.18.1.191 scope global dynamic eth0
       valid_lft 3200sec preferred_lft 3200sec
    inet6 fe80::10f6:c5ff:feab:61f6/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP qlen 1000
    link/ether 12:63:ed:78:44:74 brd ff:ff:ff:ff:ff:ff
    inet 172.18.1.133/26 brd 172.18.1.191 scope global dynamic eth1
       valid_lft 2407sec preferred_lft 2407sec
    inet6 fe80::1063:edff:fe78:4474/64 scope link
       valid_lft forever preferred_lft forever
```

### Description of the Issue (and unexpected/desired result)
When the `-bind ip_addr` argument is passed to Consul, Consul still creates RPC connections to other servers from the default host address. For multi-homed hosts behind firewalls, especially if the default interface is dynamically configured, it would be useful if Consul initiated connections from the 'bind' address or supported a 'source' address option.

### Reproduction steps
Create a multi-server Consul cluster where at least one Consul server has multiple IP addresses on the same subnet. Pass Consul the '-bind ip_addr' argument where ip_addr is the second/non-default host address. On a non-leader server, query local Consul agent and observe network traffic to leader from default IP.

Command line:
```
consul agent -bind 172.18.1.133 -node ip-172-18-1-133 -config-dir /opt/consul/consul.d -datacenter aws-us-east-1
```
Config:
```
{
  "data_dir": "/opt/consul/data",
  "disable_update_check": true,
  "dns_config": {
    "allow_stale": true,
    "max_stale": "5s"
  },
  "log_level": "warn"
  "server": true,
  "bootstrap_expect": 3,
  "telemetry": {
    "dogstatsd_addr": "127.0.0.1:8125"
  }
  "encrypt": "<consul keygen>"
}
```

```
[centos@ip-172-18-1-175 ~]$ sudo ss -tulna |grep 8300
tcp    LISTEN     0      128    172.18.1.133:8300                  *:*
tcp    ESTAB      0      0      172.18.1.175:38012              172.18.1.69:8300
tcp    ESTAB      0      0      172.18.1.133:8300               172.18.1.94:48244
tcp    ESTAB      0      0      172.18.1.133:8300               172.18.1.122:53730
tcp    ESTAB      0      0      172.18.1.133:8300               172.18.1.122:53736
```

### PR DESCRIPTION
**Pull request by magiconair**
This patch configures consul to use the bind address as the
source address for outgoing RPC connections.

Fixes #2822

### CODE REVIEW

File: consul/pool.go [hunk 1]
```diff
@@ -265,7 +269,8 @@ type HalfCloser interface {
 // given connection timeout.
 func (p *ConnPool) DialTimeout(dc string, addr net.Addr, timeout time.Duration) (net.Conn, HalfCloser, error) {
 	// Try to dial the conn
-	conn, err := net.DialTimeout("tcp", addr.String(), defaultDialTimeout)
+	d := &net.Dialer{LocalAddr: p.src, Timeout: timeout}
```
Comment (magiconair) [inline consul/pool.go]: Pls note that this code uses the `timeout` value passed into the function instead of `defaultDialTimeout` as before.

File: command/agent/agent.go [hunk 2]
```diff
@@ -440,6 +440,14 @@ func (a *Agent) consulConfig() *consul.Config {
 		base.AutopilotConfig.DisableUpgradeMigration = *a.config.Autopilot.DisableUpgradeMigration
 	}
 
+	// set the src address for outgoing rpc connections
+	// to RPCAdvertise with port 0 so that outgoing
+	// connections use a random port.
+	// todo(fs): can base.RPCAdvertise be nil ?
+	base.RPCSrcAddr = new(net.TCPAddr)
```
Comment (magiconair) [inline command/agent/agent.go]: If `base.RPCAdvertise` can be `nil` then I need to wrap this.

File: consul/pool.go (hunk 1 above)
Comment (slackpad) [inline consul/pool.go]: Good catch - that was a mistake from when this got refactored for network areas.

File: command/agent/agent.go (hunk 2 above)
Comment (slackpad) [inline command/agent/agent.go]: Hmm - there's this logic downstream that looks like the config item can be left `nil` and it pulls the address from the listener (at least for servers) - https://github.com/hashicorp/consul/blob/master/consul/server.go#L607-L612. Looking at agent.go it's not clear that this can't be `nil` either - this might be a good case for a helper fn (maybe customized for agent/server modes) to put the logic in one spot.

Comment (magiconair) [inline command/agent/agent.go]: I think this is just a convoluted way to say that the advertise address is either the rpc address or the overwritten one. I'll double check but I think we can drop that if statement. There should be one place where we configure the configuration and then it needs to be immutable.

Comment (magiconair) [inline command/agent/agent.go]: This is another place where the configuration gets modified: https://github.com/hashicorp/consul/blob/master/consul/server.go#L228-L230

Comment (slackpad) [inline command/agent/agent.go]: Makes sense - if we can set the config early on that's better than a helper fn.

Comment (magiconair) [inline command/agent/agent.go]: More config mutation code: https://github.com/hashicorp/consul/blob/c63f44a58891275088e29b44f6ff437f157cb85f/command/agent/agent.go#L143-L197

Comment (magiconair) [inline command/agent/agent.go]: I'll try https://github.com/lukechampine/freeze to find the places and refactor. I'll split the patch into two

**Comment by ziggythehamster** [comment]
This change broke us. We launch `consul-agent` on boot in AWS user data and we launch the Docker image.

Here's a snippet from our Terraform template that builds the user data:

```sh
# Get our internal IPv4 address
INTERNAL_IPV4="$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)"

# Get our instance ID
INSTANCE_ID="$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"

# Get the VPC's DNS server (see: <https://gist.github.com/cpswan/59ece85a1f7c231d5cb2>)
MAC="$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/)"
VPCCIDR="$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/"$MAC"/vpc-ipv4-cidr-block)"
VPCNET="$${VPCCIDR%%/*}"
VPCBASE="$(echo "$VPCNET" | cut -d"." -f1-3)"
VPCDNS="$VPCBASE"'.2'

# Write Consul configuration
cat > /opt/consul/config/consul-agent.json <<EOF
{
  "advertise_addr": "$INTERNAL_IPV4",
  "bind_addr": "0.0.0.0",
  "client_addr": "0.0.0.0",
  "datacenter": "${datacenter}",
  "leave_on_terminate": true,
  "recursors": [
    "$VPCDNS"
  ]
}
EOF

# --- snip ---

# Run the Consul docker image
docker run -d --restart=always -v /opt/consul:/consul -h $INSTANCE_ID \
  -p 8301:8301 -p 8301:8301/udp -p 8400:8400 -p 8500:8500 -p 53:8600 -p 53:8600/udp --name consul-agent --env-file /opt/consul/.env \
  ${consul_docker_image} agent \
  ${replace(join(" ", formatlist("-retry-join %s", split(",", join_servers))), "-retry-join none", "")}
```

So, in other words, it does the wrong thing when we ask it to bind on all interfaces.

We get errors like this:

```
2017/05/09 23:50:18 [ERR] http: Request GET /v1/health/service/public-transcoder?passing=1&stale=&wait=60000ms, error: rpc error: failed to get conn: dial tcp 10.20.0.119:0->10.20.5.10:8300: bind: cannot assign requested address from=172.17.0.1:36476
    2017/05/09 23:50:20 [ERR] consul: RPC failed to server 10.20.132.10:8300: rpc error: failed to get conn: dial tcp 10.20.0.119:0->10.20.132.10:8300: bind: cannot assign requested address
```

**Comment by magiconair** [comment]
Looking

**Comment by magiconair** [comment]
I think the problem is that the advertise address is used as the source address for outgoing connections. 

https://github.com/hashicorp/consul/blob/master/command/agent/agent.go#L442-L445

Since your advertise address is not in the network of the docker container this can't work. I think we should use the bind address as src unless it is `ANY`.

**Comment by magiconair** [comment]
Actually, the comment and the branch name say the same thing. I just did not implement it this way :(

**Comment by magiconair** [comment]
https://github.com/hashicorp/consul/pull/3028 should fix this.
