### PR TITLE
cli: forward SIGTERM to child process of 'lock' and 'watch' subcommands

### LINKED ISSUE #3754: lock command is not stop child on SIGTERM
### `consul version` for both Client and Server
Client: `v1.0.1`
Server: `v1.0.1`

### `consul info` for both Client and Server
Client:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 1
	services = 1
build:
	prerelease = 
	revision = 9564c29
	version = 1.0.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 172.21.0.5:8300
	server = true
raft:
	applied_index = 74
	commit_index = 74
	fsm_pending = 0
	last_contact = 0
	last_log_index = 74
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:b3bc687e-d34d-3482-6cc4-5db5b4a933d6 Address:172.21.0.5:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 78
	max_procs = 8
	os = linux
	version = go1.9.2
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 9564c29
	version = 1.0.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 6
	commit_index = 6
	fsm_pending = 0
	last_contact = 0
	last_log_index = 6
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:ec0d5310-1da8-19af-6f9e-91df70675889 Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 71
	max_procs = 8
	os = linux
	version = go1.9.2
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details
Gentoo Linux.
Server is running in docker 17.06.2-ce, using `consul:latest`.
Client is running in docker 17.06.2-ce, using alpine-based image and https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_amd64.zip.

### Description of the Issue (and unexpected/desired result)
I expect when `consul lock` get SIGTERM it should deliver it to the child - it looks like this was implemented in #827 - but this isn't happens (SIGINT works).

### Reproduction steps
Acquiring lock and starting child:
```
/ # consul lock l1 exec sleep 600 &
/ # ps ax
PID   USER     TIME   COMMAND
   64 root       0:00 sh
  121 root       0:00 consul lock l1 exec sleep 600
  132 root       0:00 sleep 600
  133 root       0:00 ps ax
```

Trying to stop child by sending SIGTERM to consul:
```
/ # kill 121; sleep 3; ps ax
PID   USER     TIME   COMMAND
   64 root       0:00 sh
  121 root       0:00 consul lock l1 exec sleep 600
  132 root       0:00 sleep 600
  135 root       0:00 ps ax
```
This doesn't work.

Trying to stop child by sending SIGINT to consul:
```
/ # kill -INT 121; sleep 3; ps ax
Error running handler: signal: interrupt
PID   USER     TIME   COMMAND
   64 root       0:00 sh
  137 root       0:00 ps ax
[1]+  Done                       consul lock l1 exec sleep 600
```
This works.

### Log Fragments or Link to [gist](https://gist.github.com/)

N/A

### PR DESCRIPTION
**Pull request by rboyer**
This PR ensures that the `consul lock` and `consul watch` subcommands forward the SIGTERM signal to the child process that they supervise.

This also removes the existing forwarding logic for SIGKILL as it's impossible to receive these signals.

Fixes #3754

### CODE REVIEW

File: agent/util_test.go [hunk 1]
```diff
@@ -119,3 +123,166 @@ func TestDurationFixer(t *testing.T) {
...
+// may spawn them.
+func limitProcessLifetime(dur time.Duration) {
+	go time.AfterFunc(dur, func() {
+		os.Exit(99)
+	})
+}
+
+func TestForwardSignals(t *testing.T) {
+	for _, s := range forwardSignals {
+		testForwardSignal(t, s)
```
Comment (mitchellh) [inline agent/util_test.go]: I would wrap each one of these in a subtest `t.Run()` with the signal name/number.

File: agent/signal_unix.go [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// +build !windows
+
+package agent
+
+import (
+	"os"
+	"syscall"
+)
+
+var forwardSignals []os.Signal = []os.Signal{os.Interrupt, syscall.SIGTERM}
```
Comment (mitchellh) [inline agent/signal_unix.go]: nitpick but I don't think you need the first `[]os.Signal` here. Surprised `fmt` doesn't remove this actually.

**Comment by banks** [comment]
This looks good to me although the test fail was 3 consecutive 8/9min timeouts which I've never seen before. I've restarted that job to see if there was just a bad moment for CPUs on Travis when that ran but it's possible that one of these tests actually blocks now because something is not being sent the right signal etc.

Did you see agent package to pass locally?

**Comment by banks** [comment]
Nevermind it passed on a retry 🎉 🤦‍♂️

File: agent/util_test.go (hunk 1 above)
Comment (rboyer) [reply agent/util_test.go]: I totally forgot about `t.Run`. I'll also remove the `testname` log prefix stuff as it's not needed to understand the failures now.

**Comment by rboyer** [comment]
Updated PR with feedback.

**Comment by i0rek** [comment]
😍
