### PR TITLE
Remove failed nodes from serfWAN

### LINKED ISSUE #3361: recurring log "serf: attempting reconnect" to left server
### `consul version`

Server: `0.9.0`

### `consul info`

Server:
```
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = b79d951
	version = 0.9.0
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 172.31.1.83:8300
	server = true
raft:
	applied_index = 182734
	commit_index = 182734
	fsm_pending = 0
	last_contact = 0
	last_log_index = 182734
	last_log_term = 4
	last_snapshot_index = 180231
	last_snapshot_term = 4
	latest_configuration = [{Suffrage:Voter ID:61567a07-7122-5ebd-677b-e5f437e9558c Address:172.31.3.20:8300} {Suffrage:Voter ID:c95cdd96-f493-3c9e-35d7-c9b0370ccbf9 Address:172.31.1.83:8300} {Suffrage:Voter ID:bbcbad42-a097-0fd0-f813-7e68c46d7178 Address:172.31.7.163:8300}]
	latest_configuration_index = 174747
	num_peers = 2
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 4
runtime:
	arch = amd64
	cpu_count = 1
	goroutines = 102
	max_procs = 1
	os = linux
	version = go1.8.3
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 4
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 4
	member_time = 34
	members = 10
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 1
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 12
	members = 4
	query_queue = 0
	query_time = 1
```

### Operating system and Environment details

Amazon AMI 2017.03.1

### Description of the Issue (and unexpected/desired result)

`consul members`:

```
[ec2-user@ip-172-31-1-83 ~]$ consul members
Node              Address             Status  Type    Build  Protocol  DC
ip-172-31-1-151   172.31.1.151:8301   left    server  0.9.0  2         eu-west-1
ip-172-31-1-83    172.31.1.83:8301    alive   server  0.9.0  2         eu-west-1
ip-172-31-10-77   172.31.10.77:8301   alive   client  0.9.0  2         eu-west-1
ip-172-31-11-106  172.31.11.106:8301  left    client  0.9.0  2         eu-west-1
ip-172-31-11-9    172.31.11.9:8301    alive   client  0.9.0  2         eu-west-1
ip-172-31-2-237   172.31.2.237:8301   left    client  0.9.0  2         eu-west-1
ip-172-31-3-20    172.31.3.20:8301    alive   server  0.9.0  2         eu-west-1
ip-172-31-4-153   172.31.4.153:8301   alive   client  0.9.0  2         eu-west-1
ip-172-31-7-163   172.31.7.163:8301   alive   server  0.9.0  2         eu-west-1
ip-172-31-7-176   172.31.7.176:8301   left    client  0.9.0  2         eu-west-1
```

I am seeing recurring logs of:

```
2017/08/04 12:00:41 [INFO] serf: attempting reconnect to ip-172-31-1-151.eu-west-1 172.31.1.151:8302
2017/08/04 12:02:44 [INFO] serf: attempting reconnect to ip-172-31-1-151.eu-west-1 172.31.1.151:8302
2017/08/04 12:03:17 [INFO] serf: attempting reconnect to ip-172-31-1-151.eu-west-1 172.31.1.151:8302
2017/08/04 12:03:50 [INFO] serf: attempting reconnect to ip-172-31-1-151.eu-west-1 172.31.1.151:8302
2017/08/04 12:06:23 [INFO] serf: attempting reconnect to ip-172-31-1-151.eu-west-1 172.31.1.151:8302
```

However, the server has left.

### Reproduction steps

I have a AWS Autoscaling Group (Desired Count 3) with the following consul config:
```
{
  "server": true,
  "datacenter": "${AWS::Region}",
  "data_dir": "/var/consul",
  "encrypt": "${EncryptionKey}",
  "bootstrap_expect": 3,
  "retry_join_ec2": {
    "region": "${AWS::Region}",
    "tag_key": "consul",
    "tag_value": "server"
  },
  "raft_protocol": 3,
  "disable_update_check": true
}
```

I then increase the desired count to 4 and then back to 3. After that the then terminated consul server has left the cluster but the logs "serf: attempting reconnect" keep coming.

### PR DESCRIPTION
**Pull request by s-christoff**
Autopilot primarily focuses on serfLAN and places failed servers into a left state in that gossip pool, but does not do this for serfWAN. 
Whenever serfWAN is in use, we should be removing any failed node from the gossip pool to create consistency between serfWAN and serfLAN.

In the `force-leave` command it is important to check if when passing nodenames to serfWAN it is formatted in the proper way (nodename.datacenter) or it will not properly be removed. 

Fixes #3361

### CODE REVIEW

**Comment by freddygv** [comment]
For added context, the reason why nodes aren't removed from the WAN pool right when they're removed from the LAN pool is that they take a little longer to be marked as failed in WAN.

One option was to block until the WAN member was marked as failed, but instead opted to wait until another autopilot run to avoid blocking autopilot's other tasks.

File: agent/consul/autopilot/autopilot.go [hunk 1]
```diff
@@ -22,7 +22,8 @@ type Delegate interface {
 	NotifyHealth(OperatorHealthReply)
 	PromoteNonVoters(*Config, OperatorHealthReply) ([]raft.Server, error)
 	Raft() *raft.Raft
-	Serf() *serf.Serf
+	SerfLAN() *serf.Serf
```
Comment (adams-sarah) [inline agent/consul/autopilot/autopilot.go]: Who implements this interface? I can't find much in the codebase with grep, which makes me think it's the customer or external user who implements this?
I think this looks like an API-breaking change, since the type is exported we're changing the interface definition. Is that acceptable? How do you guys usually handle breaking changes to public interfaces?

Apologies if this comment seems irrelevant! Still gaining project context.

File: agent/consul/autopilot/autopilot.go [hunk 2]
```diff
@@ -520,3 +528,27 @@ func IsPotentialVoter(suffrage raft.ServerSuffrage) bool {
 		return false
 	}
 }
+
+//For each member in serfWAN check to see if it
+//is failed - then check to see if it is a serfLAN
+//member, remove it.
+func (a *Autopilot) pruneSerfWAN(serfWAN *serf.Serf, serfLAN *serf.Serf) {
+	for _, memberWAN := range serfWAN.Members() {
```
Comment (adams-sarah) [inline agent/consul/autopilot/autopilot.go]: I have very limited context about what this code is doing, so totally ignore this if it seems inappropriate or not important!

This looks like it could potentially be an expensive operation with the 2 nested for loops. Maybe this isn't super important, but maybe we can make the algorithm more efficient? Perhaps by caching something from the first or second for loop, and then just having 2 side-by-side loops? Maybe first iterating through either the serfLAN or serfWAN members and caching our findings in a way that is easy to look up (like in a map)? (making the algorithm go from O(n^2) => O(2n)). 

Let me know if I’m not making sense.

File: agent/consul/autopilot/autopilot.go [hunk 3]
```diff
@@ -215,7 +216,8 @@ func (a *Autopilot) pruneDeadServers() error {
 					a.logger.Printf("[INFO] autopilot: Attempting removal of failed server node %q", member.Name)
 					go serfLAN.RemoveFailedNode(member.Name)
```
Comment (freddygv) [inline agent/consul/autopilot/autopilot.go]: This is another spot to remove from serfWAN, since non-voting servers are still servers in the WAN pool.

File: agent/consul/autopilot/autopilot.go (hunk 2 above)
Comment (s-christoff) [reply agent/consul/autopilot/autopilot.go]: Hey -
It *was* super expensive (I whined about this function and it's complexity, as well as it's poor readability imo) - I wouldn't want to cache anything for Serf due to the possibility of harming our results. 
What this is s'posed to be doing is retrieving all the Serf members from WAN and LAN, comparing the results, and removing any failed members. The reason we did it like this was because we wanted to find any members in LAN after they have been removed, and if we find one then we need to remove it from WAN. We were trying to not do the calculation for Raft twice (where we make sure we can still maintain a consensus). 

Luckily the new implementation gets rid of this function entirely. :)

File: agent/consul/server.go [hunk 4]
```diff
@@ -958,6 +959,11 @@ func (s *Server) RemoveFailedNode(node string) error {
 	if err := s.serfLAN.RemoveFailedNode(node); err != nil {
 		return err
 	}
+	// The Serf WAN pool stors members as node.datacenter
```
Comment (banks) [inline agent/consul/server.go]:
```suggestion
	// The Serf WAN pool stores members as node.datacenter
```

**Comment by i0rek** [comment]
I happened to look at it again, and it looks great! 👍
