### PR TITLE
Ensure a blank/empty token is sent if the localStorage kv doesn't exist

### LINKED ISSUE #4246: [bug] Clients browsing new UI are getting 403 due to non-existent ACL set
1.1.0 Beta UI 

**Describe the problem you're having**
I apologize in advance, this is going to be a **terrible** bug report.

I've gotten several reports, and have encountered the behavior myself of users going to the new UI for the first time (having been to the old one) and getting a permission denied.

screen shot 2018-06-18 at 3 46 11 pm

The User has to go to the ACL tab and clear their token to get the page to load correctly. Sometimes this clearing has to be done twice (the first time it shows a 4 character '****' instead). All users have used the old ui before. Likely haven't cleared their browser caches. I _believe_ some never used ACLs on the old sites.

My gut is telling me theres something off about how the new Beta site is reading the ACL token from the old site (if there is a difference).

I've had reports of it from at least two other users not including experiencing it myself.

### PR DESCRIPTION
**Pull request by johncowen**
This PR fixes a bug where a value of `null` would be sent as a string to in the `X-Consul-Token` header if the token had never been set using the UI settings page or the user hadn't used the old UI (which sets the `token` value in localStorage to `''` on first load)

Fixes #4246

### CODE REVIEW

File: ui-v2/app/services/settings.js [hunk 1]
```diff
@@ -7,19 +7,27 @@ export default Service.extend({
   storage: window.localStorage,
   findHeaders: function() {
     // TODO: if possible this should be a promise
+    const token = get(this, 'storage').getItem('token');
+    // TODO: The old UI always sent ?token=
+    // replicate the old functionality here
```
Comment (pearkes) [inline ui-v2/app/services/settings.js]: FWIW `X-Consul-Token` is the right way to do it in this scenario, instead of passing `?token`.

Comment (johncowen) [reply ui-v2/app/services/settings.js]: Hey, sorry yeah should have explained that comment a bit better, right now I'm replicating the fact that the old UI used to send the `?token` with *every single request*. So I'm doing the same currently but with `X-Consul-Token` instead of `?token` (so replicating the fact that we send it with every single request). I was going to look at whether that is necessary to send it with every single request further down the line, the more I think about it though we probably do.
