### PR TITLE
Fix some data races

### LINKED ISSUE #9457: data race in lib/serf.UpdateTag
There are actually 2 races here.

1. `Serf.SetTags` can race with itself. The godoc for the `Serf` struct claims that all methods should be safe for concurrent use, but there is no lock around `SetTags`, so this is not the case. I'm not sure if it should be the responsibility of serf or the caller to handle that locking.
2. Even if the above is fixed, the logic in `lib/serf.UpdateTag` is to first get the tags from `Serf.GetTags`, mutate the map, then set the tags. But there is no lock! So if two goroutines attempt to update the tags at the same time, the second `SetTags` may not include all the tags from the first, and some tags would have effectively been removed.

```
Write at 0x00c000e2a590 by goroutine 29:
  github.com/hashicorp/serf/serf.(*Serf).SetTags()
      /home/daniel/go/pkg/mod/github.com/hashicorp/serf@v0.9.5/serf/serf.go:620 +0xa4
  github.com/hashicorp/consul/lib/serf.UpdateTag()
      /home/daniel/pers/code/consul/lib/serf/serf.go:48 +0xbb
  github.com/hashicorp/consul/agent/consul.(*Server).updateSerfTags()
      /home/daniel/pers/code/consul/agent/consul/acl_server.go:89 +0x84
  github.com/hashicorp/consul/agent/consul.(*Server).updateACLAdvertisement()
      /home/daniel/pers/code/consul/agent/consul/acl_server.go:102 +0x709
  github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership()
      /home/daniel/pers/code/consul/agent/consul/leader.go:125 +0x6ce

Previous write at 0x00c000e2a590 by goroutine 387:
  github.com/hashicorp/serf/serf.(*Serf).SetTags()
      /home/daniel/go/pkg/mod/github.com/hashicorp/serf@v0.9.5/serf/serf.go:620 +0xa4
  github.com/hashicorp/consul/lib/serf.UpdateTag()
      /home/daniel/pers/code/consul/lib/serf/serf.go:48 +0xbb
  github.com/hashicorp/consul/agent/consul.(*Server).updateSerfTags()
      /home/daniel/pers/code/consul/agent/consul/acl_server.go:89 +0x84
  github.com/hashicorp/consul/agent/consul.(*Server).updateACLAdvertisement()
      /home/daniel/pers/code/consul/agent/consul/acl_server.go:102 +0x113
  github.com/hashicorp/consul/agent/consul.(*Server).establishLeadership()
      /home/daniel/pers/code/consul/agent/consul/leader.go:314 +0xd8
  github.com/hashicorp/consul/agent/consul.(*Server).leaderLoop()
      /home/daniel/pers/code/consul/agent/consul/leader.go:199 +0x10af
  github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership.func1()
      /home/daniel/pers/code/consul/agent/consul/leader.go:91 +0x79

Goroutine 29 (running) created at:
  github.com/hashicorp/consul/agent/consul.NewServer()
      /home/daniel/pers/code/consul/agent/consul/server.go:585 +0x3029
  github.com/hashicorp/consul/agent/consul.newServer()
      /home/daniel/pers/code/consul/agent/consul/server_test.go:296 +0x204
  github.com/hashicorp/consul/agent/consul.testServerWithConfig.func1()
      /home/daniel/pers/code/consul/agent/consul/server_test.go:262 +0xf3
  github.com/hashicorp/consul/sdk/testutil/retry.run.func2()
      /home/daniel/pers/code/consul/sdk/testutil/retry/retry.go:133 +0x71

Goroutine 387 (running) created at:
  github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership()
      /home/daniel/pers/code/consul/agent/consul/leader.go:89 +0x38b
```

### LINKED ISSUE #9458: data race: TestLeader_Vault_PrimaryCA_IntermediateRenew modifies a global without a lock
```
Write at 0x000003e9b868 by goroutine 167:
  github.com/hashicorp/consul/agent/consul.TestLeader_Vault_PrimaryCA_IntermediateRenew.func1()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_test.go:194 +0x3e
  github.com/hashicorp/consul/agent/consul.TestLeader_Vault_PrimaryCA_IntermediateRenew()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_test.go:297 +0xf71
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1123 +0x202

Previous read at 0x000003e9b868 by goroutine 339:
  github.com/hashicorp/consul/agent/consul.(*CAManager).intermediateCertRenewalWatch()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_ca.go:908 +0x1d8
  github.com/hashicorp/consul/agent/consul.(*CAManager).intermediateCertRenewalWatch-fm()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_ca.go:901 +0x55
  github.com/hashicorp/consul/agent/consul.(*LeaderRoutineManager).StartWithContext.func1()
      /home/daniel/pers/code/consul/agent/consul/leader_routine_manager.go:86 +0xa4

Goroutine 167 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:1007 +0x236

Goroutine 339 (finished) created at:
  github.com/hashicorp/consul/agent/consul.(*LeaderRoutineManager).StartWithContext()
      /home/daniel/pers/code/consul/agent/consul/leader_routine_manager.go:81 +0x284
  github.com/hashicorp/consul/agent/consul.(*LeaderRoutineManager).Start()
      /home/daniel/pers/code/consul/agent/consul/leader_routine_manager.go:60 +0x39d
  github.com/hashicorp/consul/agent/consul.(*Server).startConnectLeader()
      /home/daniel/pers/code/consul/agent/consul/leader_connect.go:42 +0x272
  github.com/hashicorp/consul/agent/consul.(*Server).establishLeadership()
      /home/daniel/pers/code/consul/agent/consul/leader.go:356 +0x2cc
  github.com/hashicorp/consul/agent/consul.(*Server).leaderLoop()
      /home/daniel/pers/code/consul/agent/consul/leader.go:199 +0x10af
  github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership.func1()
      /home/daniel/pers/code/consul/agent/consul/leader.go:91 +0x79
==================
==================
WARNING: DATA RACE
Write at 0x000003e9b838 by goroutine 167:
  github.com/hashicorp/consul/agent/consul.TestLeader_Vault_PrimaryCA_IntermediateRenew.func1()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_test.go:196 +0x76
  github.com/hashicorp/consul/agent/consul.TestLeader_Vault_PrimaryCA_IntermediateRenew()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_test.go:297 +0xf71
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1123 +0x202

Previous read at 0x000003e9b838 by goroutine 339:
  github.com/hashicorp/consul/agent/consul.(*CAManager).RenewIntermediate()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_ca.go:976 +0x419
  github.com/hashicorp/consul/agent/consul.(*CAManager).intermediateCertRenewalWatch.func1()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_ca.go:910 +0x64
  github.com/hashicorp/consul/agent/consul.retryLoopBackoffHandleSuccess()
      /home/daniel/pers/code/consul/agent/consul/leader_connect.go:180 +0x19c
  github.com/hashicorp/consul/agent/consul.retryLoopBackoffAbortOnSuccess()
      /home/daniel/pers/code/consul/agent/consul/leader_connect.go:161 +0x1a4
  github.com/hashicorp/consul/agent/consul.(*CAManager).intermediateCertRenewalWatch()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_ca.go:909 +0xf5
  github.com/hashicorp/consul/agent/consul.(*CAManager).intermediateCertRenewalWatch-fm()
      /home/daniel/pers/code/consul/agent/consul/leader_connect_ca.go:901 +0x55
  github.com/hashicorp/consul/agent/consul.(*LeaderRoutineManager).StartWithContext.func1()
      /home/daniel/pers/code/consul/agent/consul/leader_routine_manager.go:86 +0xa4

Goroutine 167 (running) created at:
  testing.(*T).Run()
      /usr/lib/go/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /usr/lib/go/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /usr/lib/go/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /usr/lib/go/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:1007 +0x236

Goroutine 339 (finished) created at:
  github.com/hashicorp/consul/agent/consul.(*LeaderRoutineManager).StartWithContext()
      /home/daniel/pers/code/consul/agent/consul/leader_routine_manager.go:81 +0x284
  github.com/hashicorp/consul/agent/consul.(*LeaderRoutineManager).Start()
      /home/daniel/pers/code/consul/agent/consul/leader_routine_manager.go:60 +0x39d
  github.com/hashicorp/consul/agent/consul.(*Server).startConnectLeader()
      /home/daniel/pers/code/consul/agent/consul/leader_connect.go:42 +0x272
  github.com/hashicorp/consul/agent/consul.(*Server).establishLeadership()
      /home/daniel/pers/code/consul/agent/consul/leader.go:356 +0x2cc
  github.com/hashicorp/consul/agent/consul.(*Server).leaderLoop()
      /home/daniel/pers/code/consul/agent/consul/leader.go:199 +0x10af
  github.com/hashicorp/consul/agent/consul.(*Server).monitorLeadership.func1()
      /home/daniel/pers/code/consul/agent/consul/leader.go:91 +0x79
```

### PR DESCRIPTION
**Pull request by dnephin**
Related to #8329
Fixes #9458

These commits are extracted from #10341. There's still a lot more work required to properly solve #9457 (ex: https://github.com/hashicorp/memberlist/pull/238), so I'd like to get some of the data race fixes merged to prevent them from rotting, and so that contributors can run the race detector locally with much less noise.

### CODE REVIEW

File: agent/consul/acl_test.go [hunk 1]
```diff
@@ -346,15 +348,17 @@ func testPolicyForID(policyID string) (bool, *structs.ACLPolicy, error) {
...
 			ID:          "node-wr",
 			Name:        "node-wr",
 			Description: "node-wr",
 			Rules:       `node_prefix "" { policy = "write"}`,
 			Syntax:      acl.SyntaxCurrent,
 			Datacenters: []string{"dc1"},
 			RaftIndex:   structs.RaftIndex{CreateIndex: 1, ModifyIndex: 2},
-		}, nil
+		}
+		p.SetHash(false)
```
Comment (dnephin) [inline agent/consul/acl_test.go:360]: I'm wondering about this fix. Why does the ACL resolver need to call `SetHash` ? Shouldn't that be done when the policy is created instead of when it is read?

File: agent/service_manager_test.go [hunk 2]
```diff
@@ -385,6 +387,7 @@ func TestServiceManager_PersistService_API(t *testing.T) {
 		EnterpriseMeta: *structs.DefaultEnterpriseMeta(),
 	}
 
+	svc := newNodeService()
```
Comment (freddygv) [inline agent/service_manager_test.go:390]: How is there a race here?

File: agent/consul/acl_test.go [hunk 3]
```diff
@@ -319,14 +319,16 @@ func testPolicyForID(policyID string) (bool, *structs.ACLPolicy, error) {
 			RaftIndex:   structs.RaftIndex{CreateIndex: 1, ModifyIndex: 2},
 		}, nil
 	case "acl-wr":
-		return true, &structs.ACLPolicy{
+		p := &structs.ACLPolicy{
```
Comment (freddygv) [inline agent/consul/acl_test.go:322]: How come this change was only needed for a subset of the cases?

File: agent/consul/acl_test.go (hunk 1 above)
Comment (freddygv) [reply agent/consul/acl_test.go:360]: We do set the hash on creation in the PolicySet endpoint: https://github.com/hashicorp/consul/blob/main/agent/consul/acl_endpoint.go#L1204

testPolicyForID is used by a test resolver delegate, so I think it's necessary to do it on reads here because there is no write beyond the policy existing in this function. It resolves these hard coded policies as if they had been created by some other process. (But maybe I'm misunderstanding your question)

File: agent/consul/acl_test.go (hunk 3 above)
Comment (dnephin) [reply agent/consul/acl_test.go:322]: I believe it is because only the "Concurrent-Token-Resolve" test cases  has a race on `SetHash`, and only these two cases are used by the "Concurrent-Token-Resolve" test case.

File: agent/consul/acl_test.go (hunk 1 above)
Comment (dnephin) [reply agent/consul/acl_test.go:360]: Thanks! I think that suggests that this fix is reasonable (because it better matches a production flow), which is reassuring.

I think my broader question is about the call to `SetHash` that caused the data race. The call in `resolveWithCache` ([here](https://github.com/hashicorp/consul/blob/v1.10.0/agent/structs/acl.go#L779)).

That seems like a very strange place to be calling `SetHash`. From my reading of the code this method is called in read flows, which should already have a hash set from when the policy was written. And if not, why would `SetHash` be called here, and not in a more core place (like the state store or RPC handler) ? My thinking is that if this `SetHash` call is misplaced, it has the potentially to cause or hide bugs, either now or in the future. I guess maybe it was done defensively because we are about to read the hash, but I think sometimes this kind of defense can actually introduce other problems.

I think answering that question isn't a blocker for this PR, but it may be worth exploring further to see if we can rationalize where `SetHash` is called.

**Review by dnephin — COMMENTED** [review]
Thank you for reviewing this PR! I think those are excellent questions, I've replied below.

File: agent/consul/acl_test.go (hunk 3 above)
Comment (freddygv) [reply agent/consul/acl_test.go:322]: I think adding it to all of them would be nice for that reason. Would also avoid that confusion when someone looks at this again later.

File: agent/consul/acl_test.go (hunk 1 above)
Comment (freddygv) [reply agent/consul/acl_test.go:360]: Yeah that's a good point about `resolveWithCache`. I'm not sure why it's done there. At first I thought it could have been a new field, where policies before some version doesn't have it, but the Hash field has existed since the [New ACLs PR](https://github.com/hashicorp/consul/pull/4791).

It also doesn't seem to be used for ACL compatibility, since the function to extract policies from embedded tokens sets the hash itself:
https://github.com/hashicorp/consul/blob/0527dcff5753ddf2943581c73e1284ea81f66e3c/agent/structs/acl.go#L475

Same with these other synthetic policy extractors:
https://github.com/hashicorp/consul/blob/0527dcff5753ddf2943581c73e1284ea81f66e3c/agent/structs/acl.go#L189
https://github.com/hashicorp/consul/blob/0527dcff5753ddf2943581c73e1284ea81f66e3c/agent/structs/acl.go#L233

My sense is that it was there for tests like this one that don't set the hash in advance. I don't see a non-test use for it.

Agreed that it doesn't need to be handled in this PR.

File: agent/service_manager_test.go (hunk 2 above)
Comment (freddygv) [reply agent/service_manager_test.go:390]: Got it, that makes sense, thanks! I hadn't looked by commit.

**Review by freddygv — APPROVED** [review]
Have one request below about calling SetHash for all of the test policies, but will approve the PR anyways

**Comment by dnephin** [comment]
The one test failure (`TestConnectCAConfig_GetSetForceNoCrossSigning`) is a known flake and passed locally, so going to merge.

File: agent/consul/acl_test.go (hunk 3 above)
Comment (dnephin) [reply agent/consul/acl_test.go:324]: Sounds good! Added those in the latest commit

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/412138.
