### PR TITLE
command/envoy: enable TLS when CONSUL_HTTP_ADDR=https://...

### LINKED ISSUE #7473: Connect with Envoy: gRPC over HTTPS in a new cluster only works when CONSUL_HTTP_SSL is true
#### Overview of the Issue

When using Connect with Envoy, Envoy uses HTTPS to connect to the Consul agent for the first time only when `CONSUL_HTTP_SSL` is true, even if `CONSUL_HTTP_ADDR` is set to use HTTPS. After it has connected for the first time (with `CONSUL_HTTP_SSL` enabled), it is able to connect again even without setting `CONSUL_HTTP_SSL`.

#### Reproduction Steps

1. Create a cluster with HTTP (8500), HTTPS (8501), and GRPC (8502) ports enabled, and with Connect enabled
1. Define a service with a sidecar proxy configured to use `CONSUL_HTTP_ADDR=https://127.0.0.1:8501` (without setting `CONSUL_HTTP_SSL`)
1. Envoy fails to connect to the Consul agent:

    Agent log:

        agent: grpc: Server.Serve failed to complete security handshake from "127.0.0.1:50030": tls: first record does not look like a TLS handshake

    Envoy log:

        router decoding headers:
        ':method', 'POST'
        ':path', '/envoy.service.discovery.v2.AggregatedDiscoveryService/StreamAggregatedResources'
        ':authority', 'local_agent'
        ':scheme', 'http'
        'te', 'trailers'
        'content-type', 'application/grpc'
        'x-consul-token', ''
        'x-envoy-internal', 'true'
        'x-forwarded-for', '192.168.121.186'
        ...
        Unknown error code 104 details Connection reset by peer

When `CONSUL_HTTP_SSL` is set to true, the `':scheme', 'http'` line becomes `':scheme', 'https'`.

Here is a full Ansible playbook that reproduces this problem:
https://gist.github.com/akhayyat/4a6a5718425ac4addfef3fa9bb932c65

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 2
        services = 2
build:  
        prerelease =
        revision = 2cf0a3c8
        version = 1.7.1
consul: 
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 192.168.121.170:8300
        server = true
raft:   
        applied_index = 61
        commit_index = 61
        fsm_pending = 0
        last_contact = 21.84253ms
        last_log_index = 61
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:61915f30-6707-76d2-8ab2-d8f5ab82e1be Address:192.168.121.186:8300} {Suffrage:Voter ID:3919f158-7d07-ddfd-530e-8b048e5aff4f Address:192.168.121.170:8300} {Suffrage:Voter ID:41f37e2a-bda7-f15a-b714-2cfbd8193f72 Address:192.168.121.134:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 2
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 104
        max_procs = 1
        os = linux  
        version = go1.13.7
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 2
        failed = 0  
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6
        members = 3 
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0  
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5
        members = 3 
        query_queue = 0
        query_time = 1
```

</details>

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 2  
        services = 2
build:
        prerelease =
        revision = 2cf0a3c8
        version = 1.7.1
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 192.168.121.170:8300
        server = true
raft:
        applied_index = 73
        commit_index = 73
        fsm_pending = 0
        last_contact = 38.422636ms
        last_log_index = 74
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:61915f30-6707-76d2-8ab2-d8f5ab82e1be Address:192.168.121.186:8300} {Suffrage:Voter ID:3919f158-7d07-ddfd-530e-8b048e5aff4f Address:192.168.121.170:8300} {Suffrage:Voter ID:41f37e2a-bda7-f15a-b714-2cfbd8193f72 Address:192.168.121.134:8300}]
        latest_configuration_index = 0
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 2
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 104
        max_procs = 1
        os = linux
        version = go1.13.7
serf_lan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 6
        members = 3 
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = true
        event_queue = 0
        event_time = 1
        failed = 0  
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 5
        members = 3 
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

Debian 10, amd64.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #7473

The documentation for [CONSUL_HTTP_ADDR](https://www.consul.io/docs/commands/index.html#consul_http_addr) and [CONSUL_GRPC_ADDR](https://www.consul.io/docs/commands/index.html#consul_grpc_addr) suggest that 

> If the https:// scheme is used, CONSUL_HTTP_SSL is implied to be true.

> As with CONSUL_HTTP_ADDR, if TLS is enabled either the https:// scheme should be used, or CONSUL_HTTP_SSL set.

It appears that the code was attempting to do this, however the call to `api.NewClient` was stripping the `https` scheme from `Config.Address`, which prevented it from working.

To test and fix this properly I had to make some substantial changes. I've split up the changes into a few commits to hopefully make it easier to review and show the process.

There are a few new TODOs to be resolved. I was thinking of leaving those for a follow up PR as this is already relatively large, but I could do them here if that is desirable.

### CODE REVIEW

File: api/api.go [hunk 1]
```diff
@@ -599,7 +599,7 @@ func NewClient(config *Config) (*Client, error) {
 	if len(parts) == 2 {
 		switch parts[0] {
 		case "http":
-			config.Scheme = "http"
+			// Never revert to http if TLS was explicitly requested.
```
Comment (dnephin) [inline api/api.go:602]: This looks like it was introduced in 12216583a124e25de630fb8d3e96ed0c7b431142 which is a shockingly large change, and I have to assume was not intended. Disabling TLS based on the URL is not safe.

File: command/connect/envoy/envoy_test.go [hunk 2]
```diff
@@ -555,20 +611,24 @@ func TestGenerateConfig(t *testing.T) {
...
-			// Set the agent HTTP address in ENV to be our mock
-			tc.Env = append(tc.Env, "CONSUL_HTTP_ADDR="+srv.URL)
 			testDirPrefix := testDir + string(filepath.Separator)
 			myEnv := copyAndReplaceAll(tc.Env, "@@TEMPDIR@@", testDirPrefix)
 			defer testSetAndResetEnv(t, myEnv)()
 
 			ui := cli.NewMockUi()
 			c := New(ui)
+			// explicitly set the client to one which can connect to the httptest.Server
+			c.client = client
```
Comment (dnephin) [inline command/connect/envoy/envoy_test.go:624]: Without this change it was impossible to test any settings that enabled TLS. It is possible to start a TLS `httptest` server, but we would still need to inject the TLSConfig into the client.

I think the structure of `Run` could be further improved to make this easier to test, but that would be a much larger change, so I deferred it for now.

File: command/connect/envoy/envoy.go [hunk 3]
```diff
@@ -406,58 +393,14 @@ func (c *cmd) templateArgs() (*BootstrapTplArgs, error) {
 	httpCfg := api.DefaultConfig()
 	c.http.MergeOntoConfig(httpCfg)
 
-	// Trigger the Client init to do any last-minute updates to the Config.
+	// api.NewClient normalizes some values (Token, Scheme) on the Config.
 	if _, err := api.NewClient(httpCfg); err != nil {
```
Comment (dnephin) [inline command/connect/envoy/envoy.go:397]: This call to `api.NewClient` still feels very brittle to me. I suspect some portion of the logic in `NewClient` either belongs in `DefaultConfig()`, or as methods on `Config`. I deferred making larger changes here for now, but I think it will be necessary soon.

**Comment by i0rek** [comment]
I like the scope of this PR and appreciate your effort to keep it small.
