### PR TITLE
acl: acl replication routine to report the last error message

### LINKED ISSUE #10521: ensure replication routines can report what the last error message was
Namely when the acl replication routines fail, they set `LastError` on the [acl replication status endpoint](https://www.consul.io/api-docs/acl#check-acl-replication). It would be nice to include something like `LastErrorMessage` captured the content of the `error` that caused the `LastError` field to be updated.

Possibly worth also including giving any replication routines their own replication status endpoints if they don't currently have one (like federation states, config entries, etc).

### PR DESCRIPTION
**Pull request by bigmikes**
This PR adds the new field `LastErrorMessage` to the `ACLReplicationStatus` endpoint. Whenever the Goroutine executing the `runACLReplicator` encounters an error, both `LastError` and `LastErrorMessage` field in the endpoint are updated. 

Test `TestACLReplication_TokensRedacted` is updated to check also the `LastErrorMessage` field.

Fixes #10521.

### CODE REVIEW

File: agent/consul/acl_replication.go [hunk 1]
```diff
@@ -484,11 +484,12 @@ func (s *Server) IsACLReplicationEnabled() bool {
 		s.config.ACLTokenReplication
 }
 
-func (s *Server) updateACLReplicationStatusError() {
+func (s *Server) updateACLReplicationStatusError(errorMsg error) {
```
Comment (dnephin) [inline agent/consul/acl_replication.go:487]: Since we are already doing a `err != nil` check in the caller, we were thinking it would be safer to accept a string here instead of an error. That way no new callers can accidentally pass a `nil` error.

```suggestion
func (s *Server) updateACLReplicationStatusError(errorMsg string) {
```

which I guess will requires a change to the line below that uses `errorMsg`.

File: agent/structs/acl.go [hunk 2]
```diff
@@ -1269,6 +1269,7 @@ type ACLReplicationStatus struct {
 	ReplicatedTokenIndex uint64
 	LastSuccess          time.Time
 	LastError            time.Time
+	LastErrorMessage     string
```
Comment (dnephin) [inline agent/structs/acl.go:1272]: There is unfortunately another copy of this struct in `api/acl.go` which will need this field added to it as well. That copy of `ACLReplicationStatus` is used by the `api` client library package to deserialize the API response.

**Review by dnephin — COMMENTED** [review]
Thank you for the PR! This looks really good. I left a couple comments below for a couple small improvements.

It would also be great to include a changelog entry. A changelog entry can be added in a file named `.changelog/10612.txt` (named using the PR number). You can see some other examples in that directory for the exact syntax to use.

File: agent/structs/acl.go (hunk 2 above)
Comment (bigmikes) [reply agent/structs/acl.go:1272]: Done.

File: agent/consul/acl_replication.go (hunk 1 above)
Comment (bigmikes) [reply agent/consul/acl_replication.go]: Done.

**Review by dnephin — APPROVED** [review]
LGTM, thank you!

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/423688.
