### PR TITLE
connect: fix failover through a mesh gateway to a remote datacenter

### LINKED ISSUE #6161: service resolver failover to alternate datacenters through a mesh gateway does not work
The service resolver config entry offers a failover option. This allows you to have envoy serve one cluster of endpoints normally, but after too many endpoints become unhealthy it can start load balancing from another backup pool of endpoints within that cluster.

This is currently implemented using priority groupings of endpoints under a single cluster load assignment. The cluster and the `priority=0` grouping represent the happy path configuration (e.g. the cluster named "api.default.dc1" has `priority=0` filled with endpoints for `api` in `dc1` in the `default` namespace. The other priority groupings will have other endpoints (such as `api.default.dc4` or `new-api.default.dc1`).

When we need to use a mesh gateway to access the failover groupings (priority>0) of endpoints we run into a problem. Mesh gateways work by sniffing the SNI value passed in unencrypted as part of the TLS protocol. Envoy only lets you currently configure SNI as part of the cluster not per grouping of endpoints or at the individual endpoint level. This means that dialing the remote endpoints through a gateway will never succeed because it will send an incorrect SNI value.

Probably the best way to fix this for now will be to handle failover involving mesh gateways entirely within the consul agent (by reconfiguring envoy) rather than being able to push all of the logic for failover down into the data plane.

This comes with a downside: by doing failover within consul we can only make use of control plane signals (explicit healthcheck statuses) and lose out on data plane signals like envoy outlier detection.  The reason this isn't that bad is that outlier detection signals are already going to be scrambled when passing through a mesh gateway in the first place.

### PR DESCRIPTION
**Pull request by rboyer**
_(NOTE: This is a simpler variation of a solution to #6161 than was proposed in PR #6254)_

Failover is pushed entirely down to the data plane by creating envoy
clusters and putting each successive destination in a different load
assignment priority band. For example this shows that normally requests
go to 1.2.3.4:8080 but when that fails they go to 6.7.8.9:8080:

```
- name: foo
  load_assignment:
    cluster_name: foo
    policy:
      overprovisioning_factor: 100000
    endpoints:
    - priority: 0
      lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 1.2.3.4
              port_value: 8080
    - priority: 1
      lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 6.7.8.9
              port_value: 8080
```

Mesh gateways route requests based solely on the SNI header tacked onto
the TLS layer. Envoy currently only lets you configure the outbound SNI
header at the cluster layer.

If you try to failover through a mesh gateway you ideally would
configure the SNI value per endpoint, but that's not possible in envoy
today.

This PR introduces a simpler way around the problem for now:

1. We identify any target of failover that will use mesh gateway mode local or
   remote and then further isolate any resolver node in the compiled discovery
   chain that has a failover destination set to one of those targets.

2. For each of these resolvers we will perform a small measurement of
   comparative healths of the endpoints that come back from the health API for the
   set of primary target and serial failover targets. We walk the list of targets
   in order and if any endpoint is healthy we return that target, otherwise we
   move on to the next target.

3. The CDS and EDS endpoints both perform the measurements in (2) for the
   affected resolver nodes.

4. For CDS this measurement selects which TLS SNI field to use for the cluster
   (note the cluster is always going to be named for the primary target)

5. For EDS this measurement selects which set of endpoints will populate the
   cluster. Priority tiered failover is ignored.

One of the big downsides to this approach to failover is that the failover
detection and correction is going to be controlled by consul rather than
deferring that entirely to the data plane as with the prior version. This also
means that we are bound to only failover using official health signals and
cannot make use of data plane signals like outlier detection to affect
failover.

In this specific scenario the lack of data plane signals is ok because the
effectiveness is already muted by the fact that the ultimate destination
endpoints will have their data plane signals scrambled when they pass through
the mesh gateway wrapper anyway so we're not losing much.

Fixes #6161

### CODE REVIEW

File: agent/consul/discoverychain/compile.go [hunk 1]
```diff
@@ -12,8 +12,9 @@ import (
 
 type CompileRequest struct {
 	ServiceName       string
-	CurrentNamespace  string
-	CurrentDatacenter string
+	CurrentNamespace  string // TODO(rb): rename to EvaluateInDatacenter
+	CurrentDatacenter string // TODO(rb): rename to EvaluateInNamespace
```
Comment (banks) [inline agent/consul/discoverychain/compile.go]: UberNit: TODO Comments are reversed 😄

File: agent/xds/failover_math.go [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+		}
+		for _, ep := range endpoints {
+			healthStatus, _ := calculateEndpointHealthAndWeight(ep, targetConfig.Subset.OnlyPassing)
+			if healthStatus == envoycore.HealthStatus_HEALTHY {
+				return target
+			}
+		}
+	}
+
+	return primary // if everything is broken just use the primary for now
```
Comment (banks) [inline agent/xds/failover_math.go]: What do you think about making the healthy threshold configurable? That was what we talked about in the original domain model RFC (i.e. failover if some percentage of nodes is unhealthy).

It seems simple to built here, I think the big downside is that Envoy doesn't exactly support that model so if it does fix weighted clusters to be able to set separate SNI per leg or similar we won't be able to use it as it won't exactly provide "healthy threshold" semantics.

Given that no other proxies work exactly like Envoy in this sliding failover case, what do you think about introducing a `healthy_threshold_percent` now which is the percentage of services that must be healthy to keep traffic flowing to them and not failover. Then if we want to re-introduce more complex "sliding" mechanism for Envoy later we could be explicit and add it as a separate mutually exclusive option like `sliding_failover_overprovision_factor`.

I think that's OK UX esp. given that this mode is one we can always implement for any proxy as we are in control and most other proxies are more likely to be able to do something like this than they are to do something with same semantics as Envoy over provisioning/weighting?

If the answer is that we'd rather ship like this I think that's OK but I feel like "wait til every single instance is dead" although that's what prepared queries do is not really an ideal strategy in a modern Service Mesh. It basically only works with extremely low numbers of replicas and low request volume. Everything else is just a prolonged cascading failure until at last the remaining nodes are overwhelmed and fail health checks and traffic shifts but then the overwhelmed nodes catch up and get "healthy" and traffic flaps back etc...

File: agent/consul/discoverychain/compile.go (hunk 1 above)
Comment (rboyer) [reply agent/consul/discoverychain/compile.go]: fixed

File: agent/xds/failover_math.go (hunk 2 above)
Comment (rboyer) [reply agent/xds/failover_math.go]: Moving this to a new issue as it's purely additive: https://github.com/hashicorp/consul/issues/6276

File: agent/discovery_chain_endpoint_test.go [hunk 3]
```diff
@@ -188,6 +189,11 @@ func TestDiscoveryChainRead(t *testing.T) {
 				Kind:           structs.ServiceResolver,
 				Name:           "web",
 				ConnectTimeout: 33 * time.Second,
+				Failover: map[string]structs.ServiceResolverFailover{
```
Comment (rboyer) [inline agent/discovery_chain_endpoint_test.go]: After the compiler patch above the gateway customization is now correctly ignored so this test wasn't testing one of the customizations. Adding a dc2 failover causes it to continue being customized by gateway mode.

File: agent/consul/discoverychain/compile.go [hunk 4]
```diff
@@ -12,8 +12,9 @@ import (
 
 type CompileRequest struct {
 	ServiceName       string
-	CurrentNamespace  string
-	CurrentDatacenter string
+	CurrentNamespace  string // TODO(rb): rename to EvaluateInNamespace
```
Comment (mkeeler) [inline agent/consul/discoverychain/compile.go]: Didn't you do this in one of your other PRs? Was it one of those that is being shelved for now?

File: agent/xds/clusters_test.go [hunk 5]
```diff
@@ -115,6 +115,26 @@ func TestClustersFromSnapshot(t *testing.T) {
 			create: proxycfg.TestConfigSnapshotDiscoveryChainWithFailover,
 			setup:  nil,
 		},
+		{
```
Comment (mkeeler) [inline agent/xds/clusters_test.go]: Should there be cases here to failover through a local gateway?

File: agent/xds/endpoints_test.go [hunk 6]
```diff
@@ -253,6 +253,26 @@ func Test_endpointsFromSnapshot(t *testing.T) {
 			create: proxycfg.TestConfigSnapshotDiscoveryChainWithFailover,
 			setup:  nil,
 		},
+		{
```
Comment (mkeeler) [inline agent/xds/endpoints_test.go]: Same as before. Do we need tests with local gateways?

File: agent/xds/listeners_test.go [hunk 7]
```diff
@@ -189,6 +189,11 @@ func TestListenersFromSnapshot(t *testing.T) {
 			create: proxycfg.TestConfigSnapshotDiscoveryChainWithOverrides,
 			setup:  nil,
 		},
+		{
```
Comment (mkeeler) [inline agent/xds/listeners_test.go]: Ditto

File: agent/consul/discoverychain/compile.go (hunk 4 above)
Comment (rboyer) [reply agent/consul/discoverychain/compile.go]: I can do it here before merging. I just noticed in the middle of this PR that it made more sense to use the more descriptive names here since there are now 2 datacenter values involved, and the API already uses the more descriptive names.

File: agent/xds/endpoints_test.go (hunk 6 above)
Comment (rboyer) [reply agent/xds/endpoints_test.go]: Done.

File: agent/xds/clusters_test.go (hunk 5 above)
Comment (rboyer) [reply agent/xds/clusters_test.go]: Done.

File: agent/xds/listeners_test.go (hunk 7 above)
Comment (rboyer) [reply agent/xds/listeners_test.go]: Done.

File: agent/consul/discoverychain/compile.go (hunk 4 above)
Comment (rboyer) [reply agent/consul/discoverychain/compile.go]: done
