### PR TITLE
server: don't activate federation state replication or anti-entropy until all servers are running 1.8.0+

### LINKED ISSUE #8004: Consul 1.7.x to 1.8 Upgrade scenario - WAN Federation
#### Overview of the Issue

When upgrading a DC from 1.7.3 to 1.8 the following errors would show in the server logs. The errors in the 1.7.3 DC will persist until 1.8 upgrade is completed. The 1.8.0 server is trying to query another DC for the replication states but that DC isn’t aware of replication states yet. We could do more to at runtime prevent using those wan fed RPCs until the version of the remote DC servers are all 1.8.0+ Regardless the upgrade scenario is one we want to support and don’t want to alarm users with spurious errors that we can predict when they will occur and suppress them (or not issue the RPC doomed to fail

```
agent.server: error performing anti-entropy sync of federation state: error="error performing 
federation state anti-entropy sync: rpc error making call: rpc: can't find service 
FederationState.Apply"
```

### PR DESCRIPTION
**Pull request by rboyer**
Fixes #8004

### CODE REVIEW

File: agent/consul/federation_state_endpoint.go [hunk 1]
```diff
@@ -11,6 +12,14 @@ import (
 	memdb "github.com/hashicorp/go-memdb"
 )
 
+const (
+	federationStatesNotEnabledMessage = "Federation states are currently disabled until all servers in the datacenter support the feature"
+)
+
+var (
+	federationStatesNotEnabled = errors.New(federationStatesNotEnabledMessage)
```
Comment (dnephin) [inline agent/consul/federation_state_endpoint.go:20]: I believe there is a convention to name error constants with an `err` (or `Err`) prefix (https://github.com/golang/go/wiki/Errors#naming), making this `errFederationStatesNotEnabled`

File: agent/consul/federation_state_replication.go [hunk 2]
```diff
@@ -4,11 +4,28 @@ import (
...
+	"strings"
 	"time"
 
 	"github.com/hashicorp/consul/agent/structs"
 )
 
+const federationStatsNotSupportedMessage = "Not all servers in the datacenter support federation states - preventing replication"
+
+var (
+	federationStatesNotSupported = federationStatesNotSupportedError{}
```
Comment (dnephin) [inline agent/consul/federation_state_replication.go:16]: same recommendation on this one, `errFederationStatesNotSupported`

File: agent/consul/federation_state_replication.go [hunk 3]
```diff
@@ -4,11 +4,28 @@ import (
...
+)
+
+type federationStatesNotSupportedError struct{}
+
+func (e federationStatesNotSupportedError) Error() string {
+	return federationStatsNotSupportedMessage
```
Comment (dnephin) [inline agent/consul/federation_state_replication.go:22]: Is this type being created so that it can be compared? For constant errors I believe the `==` operator works (https://play.golang.org/p/N945vkiTk5S) and is the usual way of comparing them.  https://golang.org/pkg/errors/#Is also works with constants and uses the `==` to compare them.

File: agent/consul/federation_state_replication.go [hunk 4]
```diff
@@ -4,11 +4,28 @@ import (
...
+}
+
+func areFederationStatesNotSupportedError(err error) bool {
+	return strings.Contains(err.Error(), federationStatsNotSupportedMessage)
```
Comment (dnephin) [inline agent/consul/federation_state_replication.go:26]: `isErrFederationStatesNotSupported` ? The states are plural, but the thing thing being compared is a single error

File: agent/consul/leader.go [hunk 5]
```diff
@@ -1529,3 +1529,68 @@ func (s *Server) reapTombstones(index uint64) {
...
+		// the version requirement
+		return true
+	}
+
+	// mark that we processed at least one server
+	s.found = true
+
+	if srv.Build.GreaterThanOrEqual(minFederationStatesVersion) {
+		return true
+	}
```
Comment (dnephin) [inline agent/consul/leader.go:1589]: I guess we don't have any way for these servers to publish their capabilities? Version checks can sometimes be a bit brittle for this type of thing. Allowing a server to explicitly say they support a specific feature would make this quite a bit more future-proof. If we ever wanted to allow some features to be turned off a capability check would continue to work, where as a version check would fail.

This `metadata.Server` struct has a `FeatureFlags` field. Could that be used? Or could we add a similar one for capabilities?

File: agent/consul/federation_state_endpoint.go (hunk 1 above)
Comment (rboyer) [reply agent/consul/federation_state_endpoint.go:20]: Ah yeah this is from me duplicating a similar aspect of namespaces and not reevaluating the naming for what I referenced.

File: agent/consul/leader.go (hunk 5 above)
Comment (rboyer) [reply agent/consul/leader.go:1589]: It's tricky. The advertisement of features and build info is done with serf tags. Serf messages have to fit into single UDP packets so there's an upper limit on how much data you can put in there. The Network Segment feature can cause `O(num_segments)` growth in the metadata today. This means that for folks using the current maximum number of segments any time we increase the metadata going into those packets we effectively reduce the number of segments they can use which is not great.

If something changed recently (@i0rek ?) to make this not as bad then I can certainly switch.

Comment (dnephin) [reply agent/consul/leader.go:1589]: That is quite a severe restriction, good to know. I wonder if capabilities could be done with a single bit per capability to keep the size small (assuming the encoding doesn't add a lot more for each key). I'll have to read more about serf to understand how these are encoded.

Comment (rboyer) [reply agent/consul/leader.go:1589]: @mkeeler reminded me that segments stopped using this mechanism in consul enterprise 1.7.3 so we don't have to worry as much about that. I'll update the PR to do it using feature flags instead of build numbers.

File: agent/consul/federation_state_replication.go (hunk 3 above)
Comment (rboyer) [reply agent/consul/federation_state_replication.go]: I found the lone caller between the error being created and the error being inspected and swapped the `fmt.Errorf` directive from `%v` to `%w` so that `errors.Is()` actually works now.

File: agent/consul/replication.go [hunk 6]
```diff
@@ -183,7 +183,7 @@ func (r *IndexReplicator) Replicate(ctx context.Context, lastRemoteIndex uint64,
 	metrics.MeasureSince([]string{"leader", "replication", r.Delegate.MetricName(), "fetch"}, fetchStart)
 
 	if err != nil {
-		return 0, false, fmt.Errorf("failed to retrieve %s: %v", r.Delegate.PluralNoun(), err)
+		return 0, false, fmt.Errorf("failed to retrieve %s: %w", r.Delegate.PluralNoun(), err)
```
Comment (rboyer) [inline agent/consul/replication.go:186]: This is to support the `errors.Is()` usage up the call stack.
