### PR TITLE
Fixes deadlock between barrier write and leader notify channel read .…

### LINKED ISSUE #3230: Deadlock in consul server between leadership reconcile channel and barrier write
### `consul version` for both Client and Server
Client: `0.8.5`
Server: `0.8.5`

### Operating system and Environment details
Tested in Linux, but should be reproducible in other environments
### Reproduction steps
I found this when working on #1744.

Run consul server with bootstrap-expect=1, and make it lose leadership by filling up disk (although this can be any resource, not just disk). After a few iterations, leader election messages stop being logged, and going to debug/pprof/goroutine?debug=1 should show the deadlocked go-routines. When the node gives up leadership because of a disk write error, Raft's [runLeader](https://github.com/hashicorp/raft/blob/library-v2-stage-one/raft.go#L386)  is waiting for the reconcile channel to be free to write to it, but consul's [monitorLeadership method](https://github.com/hashicorp/consul/blob/44f5086873f165d60eacdddf4f9e3fdf6c6608bb/agent/consul/leader.go#L56) is unable to read from the reconcile channel to drain it because its waiting for the [barrier write](https://github.com/hashicorp/consul/blob/44f5086873f165d60eacdddf4f9e3fdf6c6608bb/agent/consul/leader.go#L99) to finish. The barrier write blocks because even though the node's state is set to be a follower, it waits till the runLeader loop finishes so that the [runFollower](https://github.com/hashicorp/raft/blob/library-v2-stage-one/raft.go#L156) goroutine can process the apply channel containing the barrier write. Thus the deadlock!

Discussed solution ideas with @slackpad, and simplest thing to do is to not make the barrier write block forever. It should timeout after a conservative time period, and return rather than waiting if there is a barrier error. 
### Log Fragments or Link to [gist](https://gist.github.com/)
(see goroutine dump attachment) 
Include appropriate Client or Server log fragments.  If the log is longer
than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/).

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

### PR DESCRIPTION
**Pull request by preetapan**
… Fixes #3230

### CODE REVIEW

File: agent/consul/server.go [hunk 1]
```diff
@@ -601,9 +601,9 @@ func (s *Server) setupRaft() error {
 	}
 
 	// Set up a channel for reliable leader notifications.
-	leaderCh := make(chan bool, 1)
-	s.config.RaftConfig.NotifyCh = leaderCh
-	s.leaderCh = leaderCh
+	raftReconcileChannel := make(chan bool, 1)
```
Comment (slackpad) [inline agent/consul/server.go]: The name "reconcile" has a special meaning where we sync the leader's Serf members with the catalog, so I'd avoid that and change `raftReconcileCh` to `raftNotifyCh` for the local variable here, or you could do:

```
s.raftNotifyCh = make(chan bool, 1)
s.config.RaftConfig.NotifyCh = s.raftNotifyCh
```

File: agent/consul/leader.go [hunk 2]
```diff
@@ -35,13 +36,13 @@ func (s *Server) monitorLeadership() {
 	// leaderCh, which is only notified best-effort. Doing this ensures
 	// that we get all notifications in order, which is required for
 	// cleanup and to ensure we never run multiple leader loops.
-	leaderCh := s.leaderCh
+	raftNotifyCh := s.raftNotifyChanel
```
Comment (slackpad) [inline agent/consul/leader.go]: sp. "Chanel"
