### PR TITLE
Move the watch package into the api module

### LINKED ISSUE #5604: consul/watch doesn´t exists
#### Overview of the Issue

When compiling micro package I received the error:

../go-micro/registry/consul/watcher.go:8:2: cannot find package "github.com/hashicorp/consul/watch" in any of:
	/usr/local/go/src/github.com/hashicorp/consul/watch (from $GOROOT)
	/Users/jleyba/go/src/github.com/hashicorp/consul/watch (from $GOPATH)

When checking into hasicorp consul/watch I realized it is importing 

	consulwatch "github.com/hashicorp/consul/watch"
	"github.com/mitchellh/cli"

That do not exists.

#### Reproduction Steps

1. Try to compile micro package or check consul code

### LINKED ISSUE #5713: Consul vendoring itself is causing panics on type assertions
#### Overview of the Issue

I have a module that uses the `consul/watch` module, `watch` in turn imports `consul/api`; however this import appears to use the vendored files under `consul/vendor/github.com/hashicorp/consul/api`. Later I attempt to do a type assertion on an `interface{}` such as:

```
i.(api.KVPairs)
``` 

which causes a runtime panic:

`panic: interface conversion: interface {} is api.KVPairs, not api.KVPairs (types from different packages)`

Before the panic occurs I added a println which prints out the `reflect.TypeOf(i).PkgPath()` that shows that the pkgpath of the interface{} is `github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api`

whereas the command:

`fmt.Println("Local Path =", reflect.TypeOf(api.KVPair{}).PkgPath())`

yields 

`github.com/hashicorp/consul/api`

It appears as though Go will give first priority to vendored code, even if the library itself being vendored: https://github.com/golang/go/blob/a16dcc00526dbb5ff411004c987a4182a8d68e7c/src/cmd/go/internal/load/pkg.go#L845

#### Reproduction Steps

Start a local consul "cluster"

Create the following module `test0`
```
package test0

import "github.com/hashicorp/consul/watch"

type Handler func(data interface{})

func TestWatch(h Handler) {
	params := map[string]interface{}{
		"type":   "keyprefix",
		"token":  "sometoken",
		"prefix": "foo/",
	}

	wp, err := watch.Parse(params)
	if err != nil {
		panic(err)
	}

	wp.Handler = func(idx uint64, data interface{}) {
		h(data)
	}

	wp.Run("localhost:8500")
}
```

The run 
```
package main

import (
	"fmt"

	"github.com/hashicorp/consul/api"
	"github.com/pod/test0"
)

func main() {
	test0.TestWatch(test0.Handler(func(i interface{}) {
		a := i.(api.KVPairs)
		fmt.Println(a)
	}))
}
```

### Operating system and Environment details
GO Version: 1.11.5
OS: Darwin and Linux
Architecture: amd64

### PR DESCRIPTION
**Pull request by mkeeler**
It was already just a thin wrapper around the API anyways. The biggest change was to the testing. Instead of using a test agent directly from the agent package it now uses the binary on the PATH just like the other API tests. In order for this to happen with minimal duplicated code the API package now has a few exported MakeTestClient* functions to handle spawning a test agent to run against.

The other big changes were to fix up the connect based watch tests so that we didn’t need to pull in the connect package (and therefore all of Consul)

Either this or an alternative solution will need to be put in before the next release.

This also fixes the makefile so that we run all the tests not just ones in the main module (`go list ./...` doesn't seem to traverse into nested submodules)

The dependencies of the API package remain unchanged and the code included for the watching is minimal. The oddest part is that the API package needed to export some additional functions to allow setting up the agent for the watch tests to execute against. I tried exporting them in api_test.go but then the api/watch package couldn’t see them. So the two options were to move them out of a *_test.go file or get rid of the subpackage all together and move the watch code into the api package. If there are other ways to do that please let me know.

Fixes #5604 
Fixes #5713

### CODE REVIEW

File: api/watch/funcs_test.go [hunk 1]
```diff
@@ -29,19 +35,68 @@ func makeInvokeCh() chan error {
...
+	t.Helper()
+
+	connect := client.Connect()
+	cfg, _, err := connect.CAGetConfig(nil)
+	require.NoError(t, err)
+	require.NotNil(t, cfg.Config)
+
+	// update the cert
+	// Create the private key we'll use for this CA cert.
+	pk, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
```
Comment (rboyer) [inline api/watch/funcs_test.go]: Maybe you could just create some 10-year certs and commit them as test-fixtures like vault does: https://github.com/hashicorp/vault/tree/master/api/test-fixtures/keys

Comment (mkeeler) [reply api/watch/funcs_test.go]: hmm, that certainly would work. This is just to get those watches to trigger a second time anyways.

Comment (banks) [reply api/watch/funcs_test.go]: FYI we already have certs in a test fixture committed in `test/ca` as matt said though this is just triggering rotation as part of the test so generating a new key seems reasonable. All the Connect tests generate keys live during each test case for example.

**Comment by banks** [comment]
The elephant in the room is that this will break all pre-go-modules dependent builds.

The counter argument is that per #5604 it is already broken.

While this has prospect of fixing it longer term and doesn't really make it _more_ broken. Is there any way we can make this cleaner so that the existing import path doesn't just stop existing (e.g. symlink) that actually makes anything better?

And what are the pros and cons vs fixing up the vendor dir to not include the api package? That seems relatively easy too. It seems to only do so because `go mod vendor` doesn't respect the local replace rules which may or may not be a bug in itself.

I think overall this may well be the best solution - it's a better fit there. But would be good to see the alternatives discussed here so we can remember why we choose this path later! It feels like every move we've made in go mod realm has resulted in consequences we didn't foresee which makes me wonder what effects this might have that we've not figured out yet. For example did you test that this imports from a separate project and builds correctly with and without go modules after the PR is applied?

What does a dependent project that relies on the old path see? (presumably just a 404 or similar)?

**Comment by banks** [comment]
Also, cf. #5636 - an argument for the move.

**Comment by mkeeler** [comment]
@banks This definitely does break compatibility but in a way that its just a few imports that need to be rewritten. Users could always use my [`goimport-rewrite`](https://github.com/mkeeler/goimport-rewrite) to fix up the paths across their entire codebase if they don't want to manually update all the import paths.

One other idea I considered that probably wouldn't break anything would be to have the watch package be its own submodule. This should fix the existing problems. When discussing this yesterday there was some push back against creating more nested modules as a way to fix our nested modules issue.

We also could go down the route of creating separate repos for the api, watch and sdk submodules and then simply pushing to those repos nightly or during releases. Anyone currently using the watch package wouldn't have to change but they could start using something like github.com/hashicorp/consul-watch or something like that to get their transitive dependencies greatly reduced.

Lastly, I wouldn't rely on symlinks. Especially because not all filesystems support symlinks (NTFS on Windows). Additionally the various go tooling do not usually handle symlinks (which is why I had to bind mount things into the GOPATH for building pre-modules instead of just symlinking).

**Comment by mkeeler** [comment]
Verified that a non-module go 1.11.5 build using the watch package in the updated location now builds properly.

**Comment by mkeeler** [comment]
The repro in #5713 was very helpful. Without getting rid of the vendoring of our own code no amount of moving things around will let it compile.

I also tested the same example outside of the GOPATH with go 1.12.1 and it built/ran as expected.

File: GNUmakefile [hunk 2]
```diff
@@ -143,14 +144,22 @@ dev-tree:
...
 
 test-install-deps:
 	go test -tags '$(GOTAGS)' -i $(GOTEST_PKGS)
 
+update-vendor:
+	@echo "--> Running go mod vendor"
+	@go mod vendor
+	@echo "--> Removing vendoring of our own nested modules"
+	@rm -rf vendor/github.com/hashicorp/consul
+	@grep -v "hashicorp/consul/" < vendor/modules.txt > vendor/modules.txt.new
```
Comment (rboyer) [inline GNUmakefile]: In one line:
```
sed -i '/github.com\/hashicorp\/consul\//d' vendor/modules.txt 
```

File: api/testing_api.go [hunk 3]
```diff
@@ -0,0 +1,57 @@
+package api
+
+import (
+	"testing"
+
+	"github.com/hashicorp/consul/sdk/testutil"
+)
+
+type ConfigCallback func(c *Config)
```
Comment (rboyer) [inline api/testing_api.go]: It might not be worth publicly exporting this named symbol. `ConfigCallback` and `func(c *Config)` only differ in length by 1 character. It might be sufficient to inline it and omit the named type.

File: api/watch/funcs_test.go [hunk 4]
```diff
@@ -666,31 +709,22 @@ func TestConnectLeafWatch(t *testing.T) {
 
 func TestConnectProxyConfigWatch(t *testing.T) {
 	t.Parallel()
-	a := agent.NewTestAgent(t, t.Name(), `
-	connect {
-		enabled = true
-		proxy {
-			allow_managed_api_registration = true
```
Comment (rboyer) [inline api/watch/funcs_test.go]: is this test still testing what it used to without this line?

File: GNUmakefile (hunk 2 above)
Comment (mkeeler) [reply GNUmakefile]: But `sed -i` operates differently on linux vs bsd/macos so when there is an easy way to do the same thing without it I take that route.

Comment (mkeeler) [reply GNUmakefile]: There is a `sed_i` function in our build scripts to abstract away the platform differences.

File: api/testing_api.go (hunk 3 above)
Comment (mkeeler) [reply api/testing_api.go]: It doesn't save much typing but I think its easier to grok having the typedef like:

```
type MyStruct struct {
  ...
  Fn ConfigCallback
  ...
}

func doSomething(fn ConfigCallback) error {
...
}
```

Instead of

```
type MyStruct struct {
   ...
   Fn func(c *Config)
   ...
}

func doSomething(fn func(c *Config)) {

}
```

Especially in the case of a function definition its easier to read without all the extra parens necessary.

File: api/watch/funcs_test.go (hunk 4 above)
Comment (mkeeler) [reply api/watch/funcs_test.go]: Yep, MakeTestClient defaults to connect on and managed api registrations allowed.

File: GNUmakefile (hunk 2 above)
Comment (rboyer) [reply GNUmakefile]: This is why we can't have nice things.

File: api/testing_api.go (hunk 3 above)
Comment (rboyer) [reply api/testing_api.go]: The symbol appears to be exclusively for tests, but in order to be used by `api/watch` needs to be public which isn't great from the perspective of someone skimming the godoc output for `api`.

Comment (mkeeler) [reply api/testing_api.go]: I see the argument there. To minimize what needs to be exported we could just inline the def to keep the godoc cleaner.
