### PR TITLE
DNS : Fixes recursors answering the DNS query to properly return the correct response.

### LINKED ISSUE #4426: Multiple recursors return SERVFAIL
#### Overview of the Issue

I'm running a local consul agent and specifying two recursor DNS servers. I want the ability to DNS query all 3 DNS servers in this order: consul, my internal data center DNS, and google's dns 8.8.8.8. My internal datacenter DNS returns SERVFAIL when querying `www.google.com` I then expect consul to query 8.8.8.8 but instead consul returns SERVFAIL. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Setup a DNS server that doesn't forward requests to a public DNS, mine is at `10.2.3.28`, I'm using [Triton CNS](https://github.com/joyent/triton-cns) for my DNS server.
2. Start consul locally (with one node `-dev`) and point to an internal (10.2.3.28) and external (8.8.8.8 google's) dns recursor
* `consul agent -dev -server -ui -recursor 10.2.3.28 -recursor 8.8.8.8`
3. Verify that querying the consul service DNS endpoint works. This is a valid response, see how the `ANSWER SECTION:` has an ip address
```
~> dig @127.0.0.1 -p 8600 consul.service.consul 
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @127.0.0.1 -p 8600 consul.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 877
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;consul.service.consul.		IN	A

;; ANSWER SECTION:
consul.service.consul.	0	IN	A	127.0.0.1

;; ADDITIONAL SECTION:
consul.service.consul.	0	IN	TXT	"consul-network-segment="

;; Query time: 2 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Fri Jul 20 10:29:44 CDT 2018
;; MSG SIZE  rcvd: 102
```
4. Next try and query via consul for an address that is in your internal DNS, notice how that works successfully
`dig @127.0.0.1 -p 8600 lb.svc.80d12....`
5. Finally try and query via consul for `www.google.com` and notice how it fails
``` 
~> dig @127.0.0.1 -p 8600 www.google.com
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @127.0.0.1 -p 8600 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 23010
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1470
;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 32 msec
;; SERVER: 127.0.0.1#8600(127.0.0.1)
;; WHEN: Fri Jul 20 10:35:37 CDT 2018
;; MSG SIZE  rcvd: 43
```
6. This is the same result I get when querying my internal DNS directly for www.google.com
```
~> dig @10.2.3.28 www.google.com           
; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> @10.2.3.28 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 51448
;; flags: qr rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1470
;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 31 msec
;; SERVER: 10.2.3.28#53(10.2.3.28)
;; WHEN: Fri Jul 20 10:36:23 CDT 2018
;; MSG SIZE  rcvd: 43
```
7. I would expect consul's DNS endpoint to look for `www.google.com` on 10.2.3.28, not find it, then go onto the next recursor which is 8.8.8.8 and 8.8.8.8 would be able to answer `www.google.com`

### Consul info for both Client and Server

<details>
  <summary>Consul info</summary>

```
~> consul info
agent:
	check_monitors = 0
	check_ttls = 0
	checks = 0
	services = 0
build:
	prerelease = 
	revision = 39f93f01
	version = 1.2.1
consul:
	bootstrap = false
	known_datacenters = 1
	leader = true
	leader_addr = 127.0.0.1:8300
	server = true
raft:
	applied_index = 10
	commit_index = 10
	fsm_pending = 0
	last_contact = 0
	last_log_index = 10
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:b262bd1a-d445-5196-f9ab-0a04d794df7a Address:127.0.0.1:8300}]
	latest_configuration_index = 1
	num_peers = 0
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Leader
	term = 2
runtime:
	arch = amd64
	cpu_count = 8
	goroutines = 75
	max_procs = 8
	os = linux
	version = go1.10.1
serf_lan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 1
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = false
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 1
	members = 1
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

```
~> uname -a
Linux bender 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments

```
    2018/07/20 10:29:03 [DEBUG] dns: recurse RTT for {www.google.com. 1 1} (31.716944ms)
    2018/07/20 10:29:03 [DEBUG] dns: request for {www.google.com. 1 1} (udp) (31.838467ms) from client 127.0.0.1:34702 (udp)
```

### PR DESCRIPTION
**Pull request by MagnumOpus21**
This PR addresses the fact that if multiple recursors are provided to the Consul agent, Consul tries to fetch the DNS query instead of prematurely returning the response received from the first known recursor. i.e If a recursor returns a response like _SERVFAIL_ or _REFUSED_ the previous behaviour was to return the DNS response, instead of moving onto the next recursor for getting the DNS query issued. 
Fixes #4426

### CODE REVIEW

File: agent/dns.go [hunk 1]
```diff
@@ -1300,22 +1300,36 @@ func (d *DNSServer) handleRecurse(resp dns.ResponseWriter, req *dns.Msg) {
...
-			r.Compress = !d.disableCompression.Load().(bool)
-
-			// Forward the response
-			d.logger.Printf("[DEBUG] dns: recurse RTT for %v (%v)", q, rtt)
-			if err := resp.WriteMsg(r); err != nil {
-				d.logger.Printf("[WARN] dns: failed to respond: %v", err)
+		// Check if the response is valid and has the desired Response code
+		if r != nil && (r.Rcode != dns.RcodeSuccess && r.Rcode != dns.RcodeNameError) {
+			d.logger.Printf("[DEBUG] dns: recurse RTT for %v (%v) Recursor queried: %v Status returned: %v", q, rtt, recursor, dns.RcodeToString[r.Rcode])
+			// This is so that if the last known recursor also throws an error
```
Comment (mkeeler) [inline agent/dns.go]: I dont think the body inside the `if {}` here is doing anything useful other than logging the recursor failure.

Condensed down this is the logic you have.

```
for ... {
   if ... {
      if last recursor {
         break
      }
      continue
   } else {
      if no error or truncated {
         write out the response
         return
      }
   }
}
```

The break if its the last recursor and continuing the loop will do the exact same thing which is to finish/exit the loop. This could be condensed into

```
for ... {
   if bad rcode {
      log
      continue
   }

   if no error or truncated {
      write out response
      return
   }
}
```

Comment (MagnumOpus21) [reply agent/dns.go]: Noted. I felt that the other if was totally unnecessary. Still wanted to get an opinion. Will add the test case and push it.

File: agent/dns.go [hunk 2]
```diff
@@ -1302,20 +1302,28 @@ func (d *DNSServer) handleRecurse(resp dns.ResponseWriter, req *dns.Msg) {
...
-			if err := resp.WriteMsg(r); err != nil {
-				d.logger.Printf("[WARN] dns: failed to respond: %v", err)
+		// Check if the response is valid and has the desired Response code
+		if r != nil && (r.Rcode != dns.RcodeSuccess && r.Rcode != dns.RcodeNameError) {
+			d.logger.Printf("[DEBUG] dns: recurse RTT for %v (%v) Recursor queried: %v Status returned: %v", q, rtt, recursor, dns.RcodeToString[r.Rcode])
+			// If we still have recursors to forward the query to,
+			// we move forward onto the next one else the loop ends
+			continue
+		} else {
+			if err == nil || err == dns.ErrTruncated {
```
Comment (mkeeler) [inline agent/dns.go]: Leaving the same conditions and body is fine but this really should be

```
} else if err == nil || err == dns.ErrTruncated {
<body>
}
```

There is no reason to have the extra indentation

Comment (MagnumOpus21) [reply agent/dns.go]: Gotcha
