### PR TITLE
Fix #4076 - Agent configured Watches now work with HTTPS only agents

### LINKED ISSUE #4076: Watch doesn't work, when Consul use only SSL
### Description of the Issue (and unexpected/desired result)
After switching Consul to HTTPS protocol, the watch service is not able to connect to the Consul anymore. Looks like that the watch service still expect only HTTP service.

When I remove config for SSL than all works fine.
In configuration of Consul I disabled the http and use only https.

```sh
May  2 10:47:21 sql8b-stg-1 consulID: 2018/05/02 10:47:21 [ERR] consul.watch: Watch (type: checks) errored: Get http://0.0.0.0:8500/v1/health/checks/shared1: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02", retry in 20s
May  2 10:47:22 sql8b-stg-1 consulID: 2018/05/02 10:47:22 [WARN] agent: Check "perconaservice" is now warning
May  2 10:47:22 sql8b-stg-1 consulID: 2018/05/02 10:47:22 [INFO] agent: Synced check "perconaservice"
```

#### Environment Variables 
```sh
export CONSUL_HTTP_ADDR="https://127.0.0.1:8500"
export CONSUL_HTTP_SSL="true"
export CONSUL_HTTP_SSL_VERIFY="false"
```
#### Watche config
```sh
  "watches":[
    {
        "type": "checks",
        "service": "shared1",
        "handler_type": "http",
        "http_handler_config": {
            "path":"https://salt01.tech.inet:4080/hook/percona",
            "method": "POST",
            "header": {"cluster": ["shared1"]},
            "timeout": "10s",
            "tls_skip_verify": true
        }
    }
  ]
```

#### Client config
```sh
{
  "advertise_addr": "10.202.24.8",
  "bind_addr": "10.202.24.8",
  "client_addr": "0.0.0.0",
  "log_level": "INFO",
  "datacenter": "eu-west-1",
  "node_name": "10.202.24.8",
  "retry_join": ["consul.tech.inet"],
  "server": false,
  "ui": false,
  "ports": {
    "http": -1,
    "https": 8500
  },
  "key_file": "/etc/pki/tls/private/consul.key",
  "cert_file": "/etc/pki/tls/certs/consul.crt",
  "domain": "consul",
  "enable_script_checks": true
}
```

### `consul version` for both Client and Server
Client: `Consul v1.0.7 Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)`
Server: `Consul v1.0.7 Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)`

### `consul info` for both Client and Server
Client:
```
consul info
agent:
        check_monitors = 2
        check_ttls = 0
        checks = 4
        services = 1
build:
        prerelease = 
        revision = fb848fc4
        version = 1.0.7
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 44
        max_procs = 2
        os = linux
        version = go1.10
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 150
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1583
        members = 6
        query_queue = 0
        query_time = 1
```

Server:
```
agent:
        check_monitors = 0
        check_ttls = 1
        checks = 1
        services = 1
build:
        prerelease = 
        revision = fb848fc4
        version = 1.0.7
consul:
        bootstrap = false
        known_datacenters = 1
        leader = false
        leader_addr = 10.200.22.20:8300
        server = true
raft:
        applied_index = 1529547
        commit_index = 1529547
        fsm_pending = 0
        last_contact = 48.192473ms
        last_log_index = 1529547
        last_log_term = 1701
        last_snapshot_index = 1521691
        last_snapshot_term = 1701
        latest_configuration = [{Suffrage:Voter ID:baf253c9-7a07-e8bf-2a16-4fdac5b8d779 Address:10.200.12.34:8300} {Suffrage:Voter ID:6458a929-bdf5-4bc1-e4b0-a966618c6749 Address:10.200.22.20:8300} {Suffrage:Voter ID:4725f550-8fe0-b75c-9a11-19417a14800f Address:10.200.32.22:8300}]
        latest_configuration_index = 1395152
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Follower
        term = 1701
runtime:
        arch = amd64
        cpu_count = 1
        goroutines = 81
        max_procs = 1
        os = linux
        version = go1.10
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 150
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 4
        member_time = 1583
        members = 10
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 202
        members = 3
        query_queue = 0
        query_time = 1

```

### Operating system and Environment details
```sh
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 ```
### Log Fragments or Link to [gist](https://gist.github.com/)
```sh
May  2 11:08:58 sql8b-stg-1 consulID: 2018/05/02 11:08:58 [ERR] consul.watch: Watch (type: checks) errored: Get http://0.0.0.0:8500/v1/health/checks/shared1: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02", retry in 3m0s
May  2 11:11:58 sql8b-stg-1 consulID: 2018/05/02 11:11:58 [ERR] consul.watch: Watch (type: checks) errored: Get http://0.0.0.0:8500/v1/health/checks/shared1: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02", retry in 3m0s
May  2 11:14:58 sql8b-stg-1 consulID: 2018/05/02 11:14:58 [ERR] consul.watch: Watch (type: checks) errored: Get http://0.0.0.0:8500/v1/health/checks/shared1: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02", retry in 3m0s
```

TIP: Use `-log-level=TRACE` on the client and server to capture the maximum log detail.

### PR DESCRIPTION
**Pull request by mkeeler**
Basically just needed to push the TLS setup into the Watch Plan Run method so when it generates the API Client it tries to use TLS.

Fixes #4076

### CODE REVIEW

File: watch/plan.go [hunk 1]
```diff
@@ -20,10 +20,12 @@ const (
 )
 
 // Run is used to run a watch plan
-func (p *Plan) Run(address string) error {
+func (p *Plan) Run(address string, conf *consulapi.Config) error {
```
Comment (kyhavlov) [inline watch/plan.go]: It might be worth keeping this signature the same and moving to a RunWithConfig method so we don't break tools that import this package. It is pretty small, though - what do you think?

Comment (mkeeler) [reply watch/plan.go]: Thats probably best. Nothing in our code does but I guess the api can be imported by other tools.
