### PR TITLE
server: remove config entry CAS in legacy intention API bridge code

### LINKED ISSUE #9143: creating intentions in parallel often result in http 500 CAS failure
#### Overview of the Issue

creating intentions in parallel often result in http 500

#### Reproduction Steps

use below terraform code and default setting (TF_PARALLELISM=10) will often reproduce the error, change it to 1 then the error goes away:

locals {
  rules = ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15"]
} 
resource "consul_intention" "intention" {
  count            = length(local.rules)
  source_name      = local.rules[count.index]
  destination_name = "foo"
  action           = "allow"
}

### Consul info for both Client and Server

Consul server is 1.9 beta-2

### Log Fragments

Error: Failed to create intention (dc: 'dc1'): Unexpected response code: 500 (config entry failed to persist due to CAS failure: kind="service-intentions", name="foo")

### PR DESCRIPTION
**Pull request by rboyer**
Change so line-item intention edits via the API are handled via the state store instead of via CAS operations.

Fixes #9143

### CODE REVIEW

File: agent/consul/intention_endpoint.go [hunk 1]
```diff
@@ -318,180 +243,132 @@ func (s *Intention) computeApplyChangesLegacyUpdate(
...
-		return nil
+	// Pre-flight to avoid pointless raft operations.
+	_, _, ixn, err := s.srv.fsm.State().IntentionGetExact(nil, args.Intention.ToExact())
+	if err != nil {
+		return nil, fmt.Errorf("Intention lookup failed: %v", err)
 	}
-	if prevEntry.LegacyIDFieldsAreAllSet() {
-		return nil
+	if ixn == nil {
+		return nil, nil
```
Comment (freddygv) [inline agent/consul/intention_endpoint.go:365]: How come this doesn't return the "can't delete non-existent intention" error?

File: agent/consul/state/intention.go [hunk 2]
```diff
@@ -207,6 +207,294 @@ func (s *Store) legacyIntentionsListTxn(tx ReadTxn, ws memdb.WatchSet, entMeta *
...
 
+func (s *Store) IntentionMutation(idx uint64, op structs.IntentionOp, mut *structs.IntentionMutation) error {
+	tx := s.db.WriteTxn(idx)
+	defer tx.Abort()
+
+	usingConfigEntries, err := areIntentionsInConfigEntries(tx, nil)
+	if err != nil {
+		return err
+	}
+	if !usingConfigEntries {
```
Comment (freddygv) [inline agent/consul/state/intention.go:218]: I'm not following why this error is being returned. Isn't `!usingConfigEntries` true before the migration? `ErrLegacyIntentionsAreDisabled` is about legacy intentions being disabled after the migration.

It seems like this error should be about not being able to mutate config intentions before intentions are migrated.

File: agent/consul/state/intention.go [hunk 3]
```diff
@@ -207,6 +207,294 @@ func (s *Store) legacyIntentionsListTxn(tx ReadTxn, ws memdb.WatchSet, entMeta *
...
+
+		if err := checkLegacyIntentionApplyAllowed(prevEntry); err != nil {
+			return err
+		}
+
+		upsertEntry = prevEntry.Clone()
+		upsertEntry.Sources = append(upsertEntry.Sources, value)
+	}
+
+	if err := upsertEntry.LegacyNormalize(); err != nil {
```
Comment (freddygv) [inline agent/consul/state/intention.go:286]: `LegacyNormalize` updates the `LegacyCreateTime` and `LegacyUpdateTime` for all sources in the config entry. That seems like an odd side-effect for mutations that only update one source.

File: agent/consul/intention_endpoint.go [hunk 4]
```diff
@@ -87,6 +73,8 @@ func (s *Intention) Apply(
 		return err
 	}
 
+	args.Mutation = nil // not something the user can control
```
[the remark this answers is not in the document]
Comment (rboyer) [reply agent/consul/intention_endpoint.go:76]: fixed

File: agent/consul/intention_endpoint.go [hunk 5]
```diff
@@ -240,73 +186,52 @@ func (s *Intention) computeApplyChangesLegacyCreate(
...
-	prevEntry := configEntry.(*structs.ServiceIntentionsConfigEntry)
-
-	if err := checkLegacyIntentionApplyAllowed(prevEntry); err != nil {
-		return "", nil, err
-	}
-
-	upsertEntry := prevEntry.Clone()
-	upsertEntry.Sources = append(upsertEntry.Sources, args.Intention.ToSourceIntention(true))
 
 	// NOTE: if the append of this source causes a duplicate source name the
```
[the remark this answers is not in the document]
Comment (rboyer) [reply agent/consul/intention_endpoint.go:204]: We still ultimately do execute config entry validation, it just happens inside of the FSM apply instead now.

File: agent/consul/intention_endpoint.go (hunk 1 above)
Comment (rboyer) [reply agent/consul/intention_endpoint.go:382]: The new endpoint variations that operate by name instead of by ID did not retain the bizarre behavior of their predecessors. Deletes the new way are idempotent so you can re-delete an infinite number of times and it'll say "sure!"

I suspect partly the ID-based deletes had to work the way they did because you couldn't enforce ACLs unless you could turn the ID into source+destination pairs, and if it doesn't exist it can't tell you if something is possible or not possible.

In the name-based endpoints all of the information necessary for the ACL check is part of the request.

File: agent/consul/state/intention.go (hunk 2 above)
Comment (rboyer) [reply agent/consul/state/intention.go:218]: Short answer is belt-and-suspenders checks upon checks.

None of the RPC endpoints will let you get far enough to write something into the raft log that would trigger `Store.IntentionMutation` until after the migration has happened.

This is just insurance so that even if we missed a spot it still wouldn't work.

File: agent/consul/state/intention.go (hunk 3 above)
Comment (rboyer) [reply agent/consul/state/intention.go:286]: In earlier PRs I thought about this, but ultimately decided that it wasn't worth the extra hoop jumping to figure out how to make this behave better.

BUT thank you for commenting here because it made me realize I'd done something terrible by moving Normalize calls on the other side of a memdb txn.

Most of the normalize operations would happen identically on sibling voting servers, but updating timestamps super duper would not so that would mean a raft log divergence. I'll have to correct this ... somehow.

Comment (rboyer) [reply agent/consul/state/intention.go:286]: Conveniently with the `IntentionMutation` refactor I now no longer need the standard config entry Apply RPC to do the normalize, so i think i can get times out of normalize now

Comment (rboyer) [reply agent/consul/state/intention.go:286]: OK. I think I managed that. I had to modify a bunch of the unit tests to BYO times now.

File: agent/consul/intention_endpoint.go [hunk 6]
```diff
@@ -245,258 +193,212 @@ func (s *Intention) computeApplyChangesLegacyCreate(
...
 
 	// Prior to v1.9.0 renames of the destination side of an intention were
 	// allowed, but that behavior doesn't work anymore.
 	if ixn.DestinationServiceName() != args.Intention.DestinationServiceName() {
-		return "", nil, fmt.Errorf("Cannot modify DestinationNS or DestinationName for an intention once it exists.")
+		return nil, fmt.Errorf("Cannot modify DestinationNS or DestinationName for an intention once it exists.")
 	}
 
-	// We always update the updatedat field.
-	args.Intention.UpdatedAt = time.Now().UTC()
```
Comment (rboyer) [inline agent/consul/intention_endpoint.go:318]: This was already a dead assignment given how `args.Intention.ToSourceIntention` worked.

File: agent/consul/state/intention_test.go [hunk 7]
```diff
@@ -258,6 +272,535 @@ func TestStore_LegacyIntentionDelete_failsAfterUpgrade(t *testing.T) {
...
+			err := s.IntentionMutation(1, structs.IntentionOpCreate, mut)
+			testutil.RequireErrorContains(t, err, ErrLegacyIntentionsAreDisabled.Error())
+		} else {
+			testStore_IntentionMutation(t, s)
+		}
+	})
+}
+
+func testStore_IntentionMutation(t *testing.T, s *Store) {
+	// TODO: namespaces
```
Comment (rboyer) [inline agent/consul/state/intention_test.go:288]: self note

File: agent/consul/state/intention.go (hunk 2 above)
Comment (freddygv) [reply agent/consul/state/intention.go:218]: Right, we should still have the check, I'm wondering if the error message should be different

Comment (rboyer) [reply agent/consul/state/intention.go:218]: Changing it.

**Review by freddygv — APPROVED** [review]
:shipit:
