### PR TITLE
Streaming filter tags + case insensitive lookups for Service Names

### LINKED ISSUE #9695: [DNS][Streaming] DNS service queries do not filter with tags anymore when streaming is enabled
### Overview of the Issue

When streaming is enabled, on Consul 1.9.x, the DNS queries do not filter on tags anymore.

#### In 1.9.x branch, start agent with streamig enabled:

```
$ consul agent -dev -hcl 'rpc{enable_streaming=true}' -hcl use_streaming_backend=true -hcl 'dns_config{ allow_stale=true, max_stale="3h", use_cache=true, "cache_max_age"="3h"}'

# Query on non-existing tag
$ dig @localhost -p 8600 wrongtag.consul.service.consul +short
127.0.0.1
$
```
=> There should be no result, because wrongtag does not exists.

#### Without streaming
```
$ consul agent -dev -hcl 'dns_config{ allow_stale=true, max_stale="3h", use_cache=true, "cache_max_age"="3h"}'

# Query on non-existing tag
dig @localhost -p 8600 wrongtag.consul.service.consul +short
$
```
=> Expected => not results => correct

### LINKED ISSUE #9702: [Streaming] Health lookups are not case-insensitive with Streaming enabled
Lookups in health are not case insensitive

#### Overview of the Issue

When doing some lookups on services, Consul is case sensitive when streaming is enabled

#### Reproduction Steps

Compare the output of those commands with Consul with streaming and without.

With streaming, lookups on health are not case insensitive, especially annoying for DNS.

#### To run Consul with streaming

```
consul agent -dev -hcl 'rpc{enable_streaming=true}' -hcl use_streaming_backend=true -hcl 'dns_config{ allow_stale=true, max_stale="3h", use_cache=true, "cache_max_age"="3h"}'
```

Test that should return 1 entry (notice the *ConsuL* case):
```
curl -fs --get "localhost:8500/v1/health/service/ConsuL?index=13&wait=5s&"
[]
```
=> BAD, should return 1 entry

### PR DESCRIPTION
**Pull request by pierresouchay**
Fixes #9695
Fixes #9702

This is also testing the 2 cases at once since I modified the DNS test:

* Will test both case insensitive and tags lookups

### CODE REVIEW

**Review by dnephin — COMMENTED** [review]
Thank you for the PR! This looks great.

I think the fix for case insensitivity is exactly right. I'm going to have a closer look at the tests, and also see if we can use https://github.com/hashicorp/go-bexpr  to implement the filtering. I need to look at how this relates to the filtering we do in the cache right now. Filtering in a separate place might be ok if these values are not part of the cache key.

I'll work on getting this merged early next week.

**Comment by pierresouchay** [comment]
We already deployed this on our clusters: https://github.com/criteo-forks/consul/commits/1.9.3-criteo  seems to work well for now

**Comment by pierresouchay** [comment]
@dnephin Also added node-meta filtering (see #9730) as it caused issues on our infra :-)

File: agent/rpcclient/health/health.go [hunk 1]
```diff
@@ -49,6 +50,7 @@ func (c *Client) getServiceNodes(
 ) (structs.IndexedCheckServiceNodes, cache.ResultMeta, error) {
 	var out structs.IndexedCheckServiceNodes
 
+	req.ServiceName = strings.ToLower(req.ServiceName)
```
Comment (dnephin) [inline agent/rpcclient/health/health.go:53]: Is this line necessary with the `strings.EqualFold` change to filtering?

Is this because the cache key uses this value? If that is the case I guess we should be normalizing this strings in the function which creates the cache key instead of here.

Comment (pierresouchay) [reply agent/rpcclient/health/health.go:53]: @dnephin This is not exactly mandatory (the only drawback would be having 2 separate entries when requesting /health/service/NAME vs /health/service/name), but works better as only 1 entry will be cached

The big advantage of doing it there is that we know we are handling a Service (with its case insensitive semantics), we could do it in:
```
(c *Cache) Get(ctx context.Context, t string, r Request)
```

But, we should in such case either:
* add a specific case for services
* add a new method to compute a key which is different for health than for kv values for instance (aka before calling  `key := makeEntryKey(r.TypeEntry.Name, r.Info.Datacenter, r.Info.Token, r.Info.Key)`

Those 2 solutions seem more complex to me and more error-prone. Do you have another idea?

Comment (dnephin) [reply agent/rpcclient/health/health.go:53]: Oh ya, I was thinking it would be good to put it here (https://github.com/hashicorp/consul/blob/master/agent/structs/structs.go#L605) where we build the key for this cache type.

Comment (pierresouchay) [reply agent/rpcclient/health/health.go:53]: @dnephin Done!

File: agent/rpcclient/health/health.go [hunk 2]
```diff
@@ -68,5 +70,74 @@ func (c *Client) getServiceNodes(
...
+func filterTags(out *structs.IndexedCheckServiceNodes, req structs.ServiceSpecificRequest) structs.IndexedCheckServiceNodes {
+	if len(req.ServiceTags) == 0 || len(out.Nodes) == 0 {
+		return *out
+	}
+	tags := make([]string, 0, len(req.ServiceTags))
+	for _, r := range req.ServiceTags {
+		// DNS has the bad habit to setting [""] for ServiceTags
+		if r != "" {
+			tags = append(tags, strings.ToLower(r))
+		}
```
Comment (dnephin) [inline agent/rpcclient/health/health.go:86]: Does this logic exist in the current server side implementation? I had a quick look but couldn't find it. Maybe we should fix this in `dns.go` instead to not send the empty tag?

It looks like the server code uses the `TagFilter` field to determine if the tags should be used or not. It seems strange to me to have separate a separate boolean field enable the filtering instead of checking the length of the slice of tags, but I guess that's how it works.

To keep this consistent I guess this will need to both check if `TagFilter` is true, and also include `req.ServiceTag` (although that's been deprecated for a while, so maybe we don't need to support it here).

File: agent/rpcclient/health/health.go (hunk 1 above)
Comment (dnephin) [reply agent/rpcclient/health/health.go:53]: Looks good! I guess we should also remove this line now as well, since it is done in the cache-type?

**Review by dnephin — COMMENTED** [review]
Thanks! Looking good, couple minor things I noticed.

I attempted to use the bexpr filters here: https://github.com/hashicorp/consul/commit/e2475cc2a768f245abdcbfc81d1661473c567323, but I ran into a problem with the ServiceTags filtering, because bexpr is not case insensitive. I'll see if there is a way to make that work tomorrow. Otherwise I think copying the existing code from the server as you have done here makes sense.

File: agent/rpcclient/health/health.go (hunk 2 above)
Comment (pierresouchay) [reply agent/rpcclient/health/health.go]: @dnephin Ok, DONE, I also fixed in DNS by sending `[]` instead of `[""]` when no tags are set in requests

**Comment by pierresouchay** [comment]
@dnephin All done

**Review by dnephin — APPROVED** [review]
Looks great! Thank you!

I pushed one commit which moves the filtering to where we call the current `req.Filter` in the `cache-type. With this change we keep all the filtering in the same place, and we can do fewer allocations since the values get filtered before we store them. I added some tests that I had written while experimenting with the `expr` option.

I'm going to ask someone to look over the changes I've made tomorrow, but I think this is ready to merge.

File: agent/cache-types/streaming_health_services.go [hunk 3]
```diff
@@ -240,3 +288,34 @@ func (s *healthView) Result(index uint64) (interface{}, error) {
...
+		if !serviceHasTag(csn.Service, tag) {
+			// If any one of the expected tags was not found, filter the service
+			return false, nil
+		}
+	}
+	return true, nil
+}
+
+func serviceHasTag(sn *structs.NodeService, tag string) bool {
+	for _, t := range sn.Tags {
```
Comment (banks) [inline agent/cache-types/streaming_health_services.go:315]: I'm pretty sure the answer is no, but do we ever need to handle the backcompat case where `sn.Tag` is set? I think not since this would have come from Consul's state store and every CSN from a version recent enough to support streaming would only use the plural field right?

**Review by banks — APPROVED** [review]
LGTM. Thanks Pierre and Daniel!

I had one Q inline but I'm sure enough that it's not an issue I've approved as-is anyway.

File: agent/cache-types/streaming_health_services.go (hunk 3 above)
Comment (dnephin) [reply agent/cache-types/streaming_health_services.go:315]: That case is handled in this PR, here: https://github.com/hashicorp/consul/pull/9703/files/d5cc206e3963ddd910ee34b8612658d85f370d38#diff-97d0de9c08776c4ff05f75254d7319f757e5b56f78b428d0b2574ee43b77bb9dR210
