### PR TITLE
fix: non-leader agents return 404 on Get Intention exact api

### LINKED ISSUE #12578: /v1/connect/intentions/exact endpoint returns 500 instead of 404?
#### Overview of the Issue

In previous versions of Consul, this `/v1/connect/intentions/exact` used to return a 404 if no matching ACL was found. In `Consul v1.11.4` (not sure exactly which version this change was introduced), it now returns a 500 with the error `rpc error making call: Intention not found`.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. Create a cluster with n client nodes n and n server nodes
1. Run `curl -v "localhost:8500/v1/connect/intentions/exact?source=foo&destination=bar`
1. View error

### Consul info for both Client and Server

<details>
  <summary>Client info</summary>

N/A

</details>

<details>
  <summary>Server info</summary>

```
agent:
	check_monitors = 2
	check_ttls = 0
	checks = 2
	services = 1
build:
	prerelease =
	revision = 944e8ce6
	version = 1.11.4
consul:
	acl = enabled
	bootstrap = false
	known_datacenters = 1
	leader = false
	leader_addr = 172.18.0.5:8300
	server = true
raft:
	applied_index = 231
	commit_index = 231
	fsm_pending = 0
	last_contact = 25.68533ms
	last_log_index = 231
	last_log_term = 2
	last_snapshot_index = 0
	last_snapshot_term = 0
	latest_configuration = [{Suffrage:Voter ID:f6dccc25-28f5-91eb-4616-885ed1810029 Address:172.18.0.5:8300} {Suffrage:Voter ID:a8380437-24ed-a44a-cc06-07d2b1bd2b44 Address:172.18.0.4:8300} {Suffrage:Voter ID:bfbd0d3a-e2ff-3f31-2cd3-5b93c6ed10e9 Address:172.18.0.6:8300} {Suffrage:Voter ID:887b0334-8c1e-89f0-ef15-c4c2e16e148e Address:172.18.0.7:8300}]
	latest_configuration_index = 0
	num_peers = 3
	protocol_version = 3
	protocol_version_max = 3
	protocol_version_min = 0
	snapshot_version_max = 1
	snapshot_version_min = 0
	state = Follower
	term = 2
runtime:
	arch = arm64
	cpu_count = 2
	goroutines = 111
	max_procs = 2
	os = linux
	version = go1.17.5
serf_lan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 2
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 5
	members = 4
	query_queue = 0
	query_time = 1
serf_wan:
	coordinate_resets = 0
	encrypted = true
	event_queue = 0
	event_time = 1
	failed = 0
	health_score = 0
	intent_queue = 0
	left = 0
	member_time = 4
	members = 4
	query_queue = 0
	query_time = 1
```

</details>

### Operating system and Environment details

Ubuntu 18.04 amd64

### Log Fragments

N/A as far as I know, happy to provide any if needed.

### PR DESCRIPTION
**Pull request by huikang**
###Description

- rpc call method appends extra error message, so change == to
  "Strings.Contains"

### Testing & Reproduction steps

Send http request to non-leader agent

### Links

fix #12578 

### PR Checklist

* [x] updated test coverage
* [ ] external facing docs updated
* [x] not a security concern
* [ ] checklist [folder](./../docs/config) consulted

### CODE REVIEW

File: agent/intentions_endpoint_test.go [hunk 1]
```diff
@@ -314,6 +319,93 @@ func TestIntentionCheck(t *testing.T) {
...
+	}
+
+	t.Run("not found locally", func(t *testing.T) {
+		notfound()
+	})
+
+	a.delegate = &testSrv{}
+	t.Run("not found by RPC", func(t *testing.T) {
+		notfound()
+	})
```
Comment (kisunji) [inline agent/intentions_endpoint_test.go:406]: These subtests should be able to pass independently (right now `"not found by RPC"` fails when run by itself).

From a design perspective, each subtest should clean up after itself to minimize side effects of shared state. But the scope of these tests are small so I don't consider it a blocker

```suggestion
	t.Run("not found locally", func(t *testing.T) {
		notfound()
	})

	
	t.Run("not found by RPC", func(t *testing.T) {
	        a.delegate = &testSrv{}
		notfound()
	})
```

**Review by kisunji — COMMENTED** [review]
Nice bugfix! Left a few comments for improvement
