### PR TITLE
connect: Switch the default gateway port from 443 to 8443

### LINKED ISSUE #8948: Generated envoy bootstrap config for IGs require envoy to run as root in official docker container
After playing with Nomad's new ability to run the latest version of envoy supported by Consul, we found ingress gateways do not work anymore when using Consul 1.9-beta1

I believe this is a _side effect_ of Envoy 1.15 no longer running the envoy binary as root inside the official container. 
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.15.0
> build: runs as non-root inside Docker containers. Existing behaviour can be restored by setting the environment variable ENVOY_UID to 0. ENVOY_UID and ENVOY_GID can be used to set the envoy user’s uid and gid respectively.

Reproducing using only Consul and Envoy's docker image:

```bash
$ consul version 
Consul v1.9.0-beta1
Revision 6e6e62767
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

```bash
$ consul connect envoy -bootstrap -gateway ingress -service myig -register > bootstrap.json
$ sed -i -n -e '2,$p' bootstrap.json  # remove consul output
```

```bash
$ docker run --rm -v $(pwd):/stuff envoyproxy/envoy:v1.15.0 -c /stuff/bootstrap.json 2>&1 | tail -n 5
[2020-10-13 23:44:29.516][7][warning][misc] [bazel-out/k8-opt/bin/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:66] Using deprecated extension name 'envoy.http_connection_manager' for 'envoy.filters.network.http_connection_manager'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.
[2020-10-13 23:44:29.518][7][warning][misc] [bazel-out/k8-opt/bin/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:66] Using deprecated extension name 'envoy.router' for 'envoy.filters.http.router'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.
[2020-10-13 23:44:29.518][7][critical][main] [source/server/server.cc:101] error initializing configuration '/stuff/bootstrap.json': cannot bind '127.0.0.1:443': Permission denied
[2020-10-13 23:44:29.519][7][info][main] [source/server/server.cc:704] exiting
cannot bind '127.0.0.1:443': Permission denied
```

Setting the suggested environment variable to run `envoy` as root inside the container.
```bash
$ docker run -e ENVOY_UID=0 --rm -v $(pwd):/stuff envoyproxy/envoy:v1.15.0 -c /stuff/bootstrap.json
<works>
```

Now, Nomad _could_ just set that environment variable and life would go on, but I'm wondering if the offending listener is supposed to exist in the first place.

```
 "listeners": [
      {
        "name": "envoy_ready_listener",
        "address": {
          "socket_address": {
            "address": "127.0.0.1",
            "port_value": 443
          }
        },
        "filter_chains": [
          {
            "filters": [
              {
                "name": "envoy.http_connection_manager",
                "config": {
                  "stat_prefix": "envoy_ready",
```

### PR DESCRIPTION
**Pull request by mikemorris**
To avoid assumption of Envoy running as root.

Fixes #8948

/cc @shoenig

### CODE REVIEW

**Comment by mikemorris** [comment]
I'm kinda surprised this didn't break any Envoy integration tests?

**Comment by rboyer** [comment]
We never use the default in the tests.

**Comment by mikemorris** [comment]
Would it be worthwhile to add a test using the defaults anywhere?

File: command/connect/envoy/flags_test.go [hunk 1]
```diff
@@ -31,12 +31,12 @@ func TestServiceAddressValue_Value(t *testing.T) {
...
 	t.Run("nil receiver", func(t *testing.T) {
 		var addr *ServiceAddressValue
-		require.Equal(t, addr.String(), ":443")
+        require.Equal(t, addr.String(), ":8443")
 	})
 
 	t.Run("default value", func(t *testing.T) {
 		addr := &ServiceAddressValue{}
-		require.Equal(t, addr.String(), ":443")
+        require.Equal(t, addr.String(), ":8443")
```
Comment (rboyer) [inline command/connect/envoy/flags_test.go:39]: I suspect the linter will fail because of formatting here.

Comment (mikemorris) [reply command/connect/envoy/flags_test.go:39]:
```suggestion
		require.Equal(t, addr.String(), ":8443")
```
Ugh, my vim config replacing tabs with spaces it looks like...

File: command/connect/envoy/flags_test.go [hunk 2]
```diff
@@ -31,12 +31,12 @@ func TestServiceAddressValue_Value(t *testing.T) {
 func TestServiceAddressValue_String(t *testing.T) {
 	t.Run("nil receiver", func(t *testing.T) {
 		var addr *ServiceAddressValue
-		require.Equal(t, addr.String(), ":443")
+        require.Equal(t, addr.String(), ":8443")
```
Comment (mikemorris) [inline command/connect/envoy/flags_test.go:34]:
```suggestion
		require.Equal(t, addr.String(), ":8443")
```

File: .changelog/9113.txt [hunk 3]
```diff
@@ -0,0 +1,3 @@
+```release-note:breaking-change
+connect: Switch the default gateway port from 443 to 8443 to avoid assumptiuon of Envoy running as root.
```
Comment (rboyer) [inline .changelog/9113.txt:2]:
```suggestion
connect: Switch the default gateway port from 443 to 8443 to avoid assumption of Envoy running as root.
```

**Comment by rboyer** [comment]
> Would it be worthwhile to add a test using the defaults anywhere?

Probably not at this time? If we started testing ALL of the defaults we'd need a lot more tests.
