### PR TITLE
Fix several ACL token/policy resolution issues.

### LINKED ISSUE #5219: 403 Permission denied error / 404 not found when submiting concurrent kv GET,PUT or DELETE / kv GET recurse with the same token/different tokens with the same policy from a non primary datacenter
#### Overview of the Issue

Given we have 2 consul clusters with ACL enabled and ACL replication
When we submit concurrent kv GET, PUT or DELETE with the same token or with different tokens with the same policy from the non primary datacenter
Then we have a Unexpected response code: 403 (Permission denied)
Or
Then we have a 404 when we submit a kv GET recurse

It seems when consul is resolving the policies of this token it get lost in some way.
The function resolvePoliciesForIdentity from agent/consul/acl.go flows different when have concurrent requests with the same token.

#### Reproduction Steps

1) 2 vagrant machines

➜  reproduce_it cat Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  (1..2).each do |index|
    config.vm.define "consul-dc#{index}" do |c|
      c.vm.box =  "ubuntu/trusty64"
      c.vm.hostname = "consul-dc#{index}"
      c.vm.network "private_network", ip: "192.168.56.10#{index}"
      #c.vm.provision "shell", path: "setup.sh"
      #c.vm.provider :virtualbox do |vb|
      #  vb.customize ["modifyvm", :id, "--memory", "2048"]
      #end
      #c.vm.synced_folder "./", "/home/vagrant/go/src/github.com/hashicorp/consul-replicate"
    end
  end
end
```

2) vagrant up
3) install unzip and download consul-1.4.0
4) dc1 run consul with the following command and config.json:
command: consul agent -server -config-dir=config.json
config.json:

```
{
  "server": true,
  "bind_addr": "0.0.0.0",
  "data_dir": "/tmp/consul",
  "datacenter": "dc1",
  "advertise_addr": "192.168.56.101",
  "log_level": "TRACE",
  "bootstrap_expect": 1,
  "primary_datacenter": "dc1",
  "acl" : {
    "enabled" : true,
    "default_policy" : "deny",
    "down_policy" : "extend-cache"
  }
}
```

5) wait for bootstrap the cluster
6) bootstrap the acl, create agent policy, create token policy, set token policy, restart consul server
7) dc2 run consul with the same command as dc1 and config.json:

```
{
  "server": true,
  "bind_addr": "0.0.0.0",
  "data_dir": "/tmp/consul",
  "datacenter": "dc2",
  "advertise_addr": "192.168.56.102",
  "log_level": "TRACE",
  "bootstrap_expect": 1,
  "primary_datacenter": "dc1",
  "retry_join_wan": ["192.168.56.101"],
  "acl" : {
    "enabled" : true,
    "default_policy" : "deny",
    "down_policy" : "extend-cache",
    "tokens": {
      "agent": "617539a8-5bf0-3b4a-4bbc-208cfdfae481"
    }
  }
}
```

8) Create a policy with key_prefix "" { policy: "write"}
9) Create a token or create two different tokens using the same policy

10) Start 2 loops from dc2 writing keys using that token:

```
export CONSUL_HTTP_TOKEN=96f33a23-c54d-e2bd-651b-893846c43242
for i in $(seq 1 100000); do consul kv put test/1 1; exit_status=$?; if [ $exit_status -eq 1 ]; then break; fi ; done
```

Eventually the 403 permission denied errors will come

or 
```
for i in $(seq 1 100000); do http_code=$(curl -s -o /dev/null -w "%{http_code}" -H "X-Consul-Token: $CONSUL_HTTP_TOKEN" localhost:8500/v1/kv/test?recurse=true); echo $http_code; if [ $http_code -eq 404 ]; then break; fi ; done
```
Eventually the 404 will come

Please notice on this POC I didn't test through an agent connected to DC2, but we had the issue on a production cluster even connected from local agent instead of communicating directly though the server.

You can reproduce the error with PUT, GET or DELETE.

As I mentioned before,
It seems when consul is resolving the policies of this token it get lost in some way.
The function resolvePoliciesForIdentity from agent/consul/acl.go flows different when have concurrent requests with the same token or different tokens with the same policy.

### PR DESCRIPTION
**Pull request by mkeeler**
Fixes #5219 

The main issue was that token specific issues (not able to access a particular policy or the token being deleted after initial fetching) were poisoning the policy cache.

A second issue was that for concurrent token resolutions, the first resolution to get started would go fetch all the policies. If before the policies were retrieved a second resolution request came in, the new request would register watchers for those policies but then never block waiting for them to complete. This resulted in using the default policy when it shouldn't have.

This PR fixes those issues. The second issue was simplest to fix. We were using the wrong value to determine the number of times to block on our wait channel for async policy resolution responses. Previously we looped newAsyncFetchIDs number of times which when other policy resolutions for required policies are already ongoing will be less than the total number of policies needed. This was changed to the number of policies that need to be fetched (regardless of which resolution request is the one to initiate the policy fetch)

The first issue required a few changes.

On the server side, the `ACL.PolicyResolve` endpoint was modified to return permission denied errors when trying to resolve a policy that the token is not linked with. This way we can differentiate between non-existent policies and policies the token just isn't allowed to retrieve.

On the client side token/policy got a little more complex. Token errors during policy resolution (both not found and permission denied) are now handled better. First they no longer modify the policy cache for these errors. Instead for a not found error, it overrides the identity used for the request in the local cache to nullify it and store the not found error. For a permission denied errors, the cached identity is just removed which will allow subsequent requests to be fetched again. For both token related errors it will cause policy resolution to stop. For permission denied errors and not found errors for other tokens, the request will be retried.

For example:

Token A is linked to policies 1, 2 and 3
Token B is linked to policies 2, 3 and 4

Then the following flow is how things will work:

1. ResolveToken('<token A secret>') is started
2. Token A's identity gets fetched and cached
3. ResolveToken('<token B secret>') is started
4. Token B's identity gets fetched and cached
5. Some external entity modifies Token A to unlink policy 3.
6. Async request to resolve policies 1,2 and 3 is started using Token A
7. Async request to resolve policy 4 is started using Token B
8. Request to resolve with Token A returns Permission Denied
9. Token A gets removed from the identity cache
9. Both policy resolution requests get stopped due to the token error for A
10. In the background the Token B policy resolution is still ongoing (or may have finished). This will populate the cache for policy 4.
11. Token A's identity must be re-fetched as it is no longer cached.
12. Token B's identity is cached and will be used for policy resolution.
13. Something external deletes Token B.
14. Policy resolution of policies 2 and 3 is started for Token B.
15. Policy resolution of policy 1 is started for Token A.
16. Policy resolution of 2 and 3 returns with a not found error.
17. Both policy resolution requests get stopped due to the token error for B.
18. In the background the Token A policy resolution of policy 1 is still ongoing (or may have finished). This will populate the cache for policy 1.
19. Because of the not found token error, token B resolution will stop and propagate the not found error as if the very first identity resolution requests had come up with the not found error.
20. The Token A resolution request will be retried.
21. Token A's identity will be retrieved from the cache.
22. Token A will start a policy resolution for policy 2.
23. The server returns policy 2
24. Token A policy resolution completes and policies 1 and 2 get compiled into the Authorizer and are cached/returned.

### CODE REVIEW

File: agent/consul/acl_test.go [hunk 1]
```diff
@@ -657,6 +682,100 @@ func TestACLResolver_DatacenterScoping(t *testing.T) {
...
+		require.NoError(t, err)
+		require.NotNil(t, authz)
+		require.True(t, authz.NodeWrite("foo", nil))
+		require.False(t, authz.ACLRead())
+		require.True(t, modified)
+		require.True(t, deleted)
+		require.Equal(t, int32(2), tokenReads)
+		require.Equal(t, int32(2), policyResolves)
+
+		// sleep long enough for the policy cache to expire cache to expire
```
Comment (banks) [inline agent/consul/acl_test.go]:
```suggestion
		// sleep long enough for the policy cache to expire
```

**Comment by mkeeler** [comment]
@banks The only potential for granting more access than desired is really an issue with caching tokens at all.

If for example you have two tokens that link the same policies and you resolve them both only 1 of them is going to be used to resolve policies. If between the original identity fetch/cache the second token gets modified to remove one of those policies the new state will not be detected until the identity cache expires. I don't see this as an issue. So long as we cache tokens/identities and policies we will have to deal with stale data which is what this scenario is.

**Comment by banks** [comment]
Gotcha sounds reasonable to me!
