### PR TITLE
config raft apply silent error

### LINKED ISSUE #10656: Applying Connect CA configuration to raft is silently failing when an invalid `ModifyIndex` is provided
#### Overview of the Issue
When applying a configuration and providing a `ModifyIndex`, if the provided `ModifyIndex` do not much the one stored in raft the new configuration will not be applied but the error is never reported back to the API call.

The issue is related to the fact that we return a `nil` error in [here](https://github.com/hashicorp/consul/blob/c271308473dd04e13567b894867547d8d76fd670/agent/consul/state/connect_ca.go#L159-L161)

### PR DESCRIPTION
**Pull request by dhiaayachi**
Fix #10656

### CODE REVIEW

File: agent/consul/leader_connect_ca.go [hunk 1]
```diff
@@ -909,6 +909,9 @@ func (c *CAManager) UpdateConfiguration(args *structs.CARequest) (reterr error)
 		if respErr, ok := resp.(error); ok {
 			return respErr
 		}
+		if respOk, ok := resp.(bool); ok && !respOk {
+			return errors.New("configuration not applied")
```
Comment (banks) [inline agent/consul/leader_connect_ca.go:913]: Perhaps we could make this more descriptive so operators understand why not?
```suggestion
			return errors.New("CA configuration not applied as the given ModifyIndex is older than the current one")
```

File: agent/consul/state/connect_ca.go [hunk 2]
```diff
@@ -157,7 +159,7 @@ func (s *Store) CACheckAndSetConfig(idx, cidx uint64, config *structs.CAConfigur
 	// return early here.
 	e, ok := existing.(*structs.CAConfiguration)
 	if (ok && e.ModifyIndex != cidx) || (!ok && cidx != 0) {
-		return false, nil
+		return false, errors.Errorf("invalid index")
```
Comment (banks) [inline agent/consul/state/connect_ca.go:162]: Hmm I prefer returning an explicit error although I think the wording could be a little different - this is somewhat 'expected' in that the user requested "Check and Set" so it's not that their index is _invalid_ so much as that their requested check has failed and their write may have conflicted with another one.

Perhaps a message like `CAS failure: ModifyIndex did not match existing` would be clearer and also easier for consumers to detect since their behviour in this case might be to retry the read-modify-write rather than this being a fatal error.

Comment (banks) [reply agent/consul/state/connect_ca.go:162]: Are there any other callers to this other than the `CAManager` one we modified above?

File: agent/consul/leader_connect_ca.go (hunk 1 above)
Comment (banks) [reply agent/consul/leader_connect_ca.go:913]: I wonder how this will affect the HTTP API - did you try it? I assume this error just gets returned to the user.

I notice that we don't document the Check-and-set behaviour at all in this specific API endpoint anyway (maybe another thing to fix) https://www.consul.io/api-docs/connect/ca#update-ca-configuration.

Could use something similar to the words in Config Entries: https://www.consul.io/api-docs/config#cas

Looking though all other endpoints that have optional CAS semantics do so with an explicit field like `cas` rather than just implicitly on the ModifyIndex. I wonder why we choose to do that in this case and then not document it?

Perhaps we should make it explicit instead and ignore `ModifyIndex` entirely which is probably what operators assume we would do and the same as other similar endpoints.

**Review by banks — COMMENTED** [review]
Some thoughts inline, what do you think @dhiaayachi ?

File: agent/consul/state/connect_ca_test.go [hunk 3]
```diff
@@ -59,8 +59,8 @@ func TestStore_CAConfigCAS(t *testing.T) {
 	ok, err := s.CACheckAndSetConfig(2, 0, &structs.CAConfiguration{
 		Provider: "static",
 	})
-	if ok || err != nil {
-		t.Fatalf("expected (false, nil), got: (%v, %#v)", ok, err)
+	if ok || err == nil {
+		t.Fatalf("expected (false, \"invalid index\"), got: (%v, %#v)", ok, err)
```
Comment (dnephin) [inline agent/consul/state/connect_ca_test.go:63]: I think it's always a good idea to at least check part of the error message. Otherwise when the code is changed the test could return an error for a different reason, and the code path that you expected to be testing is no longer covered.

```suggestion
require.False(t, ok)
testutil.RequireErrorContains(t, err, "ModifyIndex did not match existing")
```

File: agent/consul/leader_connect_ca.go [hunk 4]
```diff
@@ -909,6 +909,9 @@ func (c *CAManager) UpdateConfiguration(args *structs.CARequest) (reterr error)
 		if respErr, ok := resp.(error); ok {
 			return respErr
 		}
+		if respOk, ok := resp.(bool); ok && !respOk {
```
Comment (dnephin) [inline agent/consul/leader_connect_ca.go:912]: I think in practice this code path will not be hit because the FSM operation will return an error. Even during an upgrade this code probably won't be relevant because the leader handles both operations.

I think unnecessary code like this can be a distraction and can lead to other problems, so I suggest we do not add this handling.

**Review by dnephin — COMMENTED** [review]
Thanks for working on this fix!

File: agent/consul/leader_connect_ca.go (hunk 1 above)
Comment (dhiaayachi) [reply agent/consul/leader_connect_ca.go:913]: I'm not sure that the error should be specific to the `ModifyIndex` in here, by returning an error in connect_ca.go this will not be triggered and act as a fail safe/generic error in case another case happen where we return a nil error with a false. My understanding is in this case the false response mean that we did not modify the config and need to be associated with an error that state the reason, this is the case that we did not write the config but for no reason, which should never happen.

I agree on being explicit it will make it clear and easier to document. 
Is there any concern with retro compatibility if we decide to add a `cas` field?

File: agent/consul/state/connect_ca.go (hunk 2 above)
Comment (dhiaayachi) [reply agent/consul/state/connect_ca.go:162]: This is only triggered by leader_connect_ca.go in 3 places:
- UpdateConfiguration (the one we are fixing)
- initializeCAConfig which read the config from raft copy it and modify it and write it again
- initializeRootCA which add the root ca to the config and write it again

File: agent/consul/leader_connect_ca.go (hunk 4 above)
Comment (dhiaayachi) [reply agent/consul/leader_connect_ca.go:912]: The issue is that the FSM code is error prone, the fact that we return a flag and an error and the flag is not really used can lead to other errors as this one. 
Another possibility would be to return always false or true so it's explicit that the response is not used for that specific operation

File: agent/consul/state/connect_ca.go (hunk 2 above)
Comment (dnephin) [reply agent/consul/state/connect_ca.go:162]: Don't forget that `Store.CACheckAndSetConfig` is also called by the `CAOpSetRootsAndConfig` operation, which is called in two other places:
* a second place in `UpdateConfiguration`
* `CAManager.persistNewRootAndConfig` called by `initializeSecondaryCA` and `RenewIntermediate`, although `RenewIntermediate` will use a `nil` config, so should always use the existing stored config and not hit this bug.

File: agent/consul/leader_connect_ca.go (hunk 4 above)
Comment (dnephin) [reply agent/consul/leader_connect_ca.go:912]: I think the `bool` return value is the problem. The error should be able to indicate if it was success or not. The bool is a distraction that we should either remove or ignore.

Comment (dhiaayachi) [reply agent/consul/leader_connect_ca.go:912]: I will remove this from here and create another PR to refactor it to be less error prone.

File: agent/consul/leader_connect_ca.go (hunk 1 above)
Comment (dhiaayachi) [reply agent/consul/leader_connect_ca.go]: I ended up removing this, I opened #10660 to refactor and remove the bool response

**Review by dnephin — APPROVED** [review]
LGTM! Thanks for fixing this.

**Comment by hc-github-team-consul-core** [comment]
:cherries: If backport labels were added before merging, cherry-picking will start automatically.

To retroactively trigger a backport after merging, add backport labels and re-run https://circleci.com/gh/hashicorp/consul/414411.

**Comment by hc-github-team-consul-core** [comment]
:cherries::white_check_mark: Cherry pick of commit c6859b3fb07031e3ea1fcd0230bacb070315d93d onto `release/1.10.x` succeeded!

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit c6859b3fb07031e3ea1fcd0230bacb070315d93d onto `release/1.9.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/414411)

**Comment by hc-github-team-consul-core** [comment]
:cherries::x: Cherry pick of commit c6859b3fb07031e3ea1fcd0230bacb070315d93d onto `release/1.8.x` failed! [Build Log](https://circleci.com/gh/hashicorp/consul/414411)
