### PR TITLE
Fixes handling of stop channel and failed barrier attempts.

### LINKED ISSUE #3545: Barrier write timeout can cause permanently degraded leader
We encountered a user where the Consul leader ran into a network issue that lasted several minutes. Over the span of about 20 minutes there were errors queueing writes, with messages like `consul.coordinate: Batch update failed: timed out enqueuing operation`. Finally, one of these happened during a leader reconcile loop and we saw `consul: failed to wait for barrier: timed out enqueuing operation`.

Since the leader had been established for several days, this hit the `return` statement in the error handling logic here:

https://github.com/hashicorp/consul/blob/v1.0.0-beta2/agent/consul/leader.go#L97-L101

Which hit the `defer`-ed `revokeLeadership()` call here:

https://github.com/hashicorp/consul/blob/v1.0.0-beta2/agent/consul/leader.go#L111-L116

The result was that the leader loop exited and that the consistent read flag got reset, resulting in the application getting `Not ready to serve consistent reads`. Since the server never actually lost leadership it was stuck in this state. Restarting the leader fixed it. This was found in 0.9.2, but the code is the same in master today.

The change that added the `return` was #3230, which was working under the assumption that exiting the leader loop would cause the server to step down. In this unfortunate set of circumstances, the network errors were such that we hit the barrier write error, but we were able to service the Raft requirements to stay a leader. This is a bit of a manifestation of the separate path for pipelined Raft replication + a separate path for AE messages for maintaining leadership (I think), so that stems from our implementation.

In any case, the right thing to do here is to keep the timeout part of the deadlock fix from #3230, but do the old `goto WAIT` instead of the `return`. This would have let the leader make another attempt at the barrier later, and would have kept the leader tracking goroutine.

There's no good API now to ask Raft to step down, so later we might want to consider adding that, and if the leader tracking goroutine hasn't made progress then we could voluntarily step down, but the simple fix outlined above should be sufficient to defer to Raft's health checking. There are no other `return` statements of this type in `leaderLoop()`.

### PR DESCRIPTION
**Pull request by slackpad**
There were two issues here. First, we needed to not exit when there was a timeout trying to write the barrier, because Raft might not step down, so we'd be left as the leader but having run all the step down actions.

Second, we didn't close over the `stopCh` correctly, so it was possible to `nil` that out and have the `leaderLoop` never exit. We close over it properly AND sequence the `nil`-ing of it AFTER the `leaderLoop` exits for good measure, so the code is more robust.

We also added a pre-poll before we wait in the `leaderLoop`, since the exit condition is mixed in with a bunch of other stuff, so if we wait a long time for the barrier we will have hit the interval and may get kind of stuck waiting for the `select` to pick the `stopCh` case (making another failed attempt at doing a barrier could cost us another 2 minutes, for example).

Fixes #3545

### CODE REVIEW

File: agent/consul/leader.go [hunk 1]
```diff
@@ -33,25 +33,41 @@ func (s *Server) monitorLeadership() {
...
+	// running at any given time. We need to run that in a goroutine so we
+	// can look for other notifications (loss of leadership) which we pass
+	// along by closing the stopCh given to the current leader loop.
 	var wg sync.WaitGroup
 	var stopCh chan struct{}
 	for {
 		select {
 		case isLeader := <-raftNotifyCh:
 			if isLeader {
+				if stopCh != nil {
```
Comment (magiconair) [inline agent/consul/leader.go]: This looks correct. I have three small nitpicks:

1. I'd call `defer wg.Done` out of habit in case the function becomes more complex
2. I'd name go func arg different (e.g. `ch`) to avoid accidental future confusion
3. I think writing this as a switch statement may help readability since it gets rid of some brackets

```go
			switch {
			case isLeader:
				if stopCh != nil {
					s.logger.Printf("[ERR] consul: attempted to start the leader loop while running")
					continue
				}

				stopCh = make(chan struct{})
				wg.Add(1)
				go func(ch chan struct{}) {
					defer wg.Done()
					s.leaderLoop(ch)
				}(stopCh)
				s.logger.Printf("[INFO] consul: cluster leadership acquired")

			default:
				if stopCh == nil {
					s.logger.Printf("[ERR] consul: attempted to stop the leader loop while not running")
					continue
				}

				s.logger.Printf("[DEBUG] consul: shutting down leader loop")
				close(stopCh)
				wg.Wait()
				stopCh = nil
				s.logger.Printf("[INFO] consul: cluster leadership lost")
			}
```

Comment (slackpad) [reply agent/consul/leader.go]: Thanks @magiconair these are all good suggestions. PTAL at the last push.
