### PR TITLE
agent: fix 'consul leave' shutdown race (#2880)

### LINKED ISSUE #2880: 0.8.0 short-time till "leave" leads to EOF
The following issue did not affect 0.7.5, but it does affect 0.8.0 and HEAD.

The error is "Error leaving: Put http://127.0.0.1:8500/v1/agent/leave: EOF"

```
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v0.8.0-25-g3ef7dde6-dev (3ef7dde6+CHANGES)'
           Node ID: '0badd3ca-3553-380f-8a09-3b02ba961b45'
         Node name: 'iMac-TMP.local'
        Datacenter: 'dc1'
            Server: false (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 10.0.1.15 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2017/04/08 07:48:27 [INFO] serf: EventMemberJoin: iMac-TMP.local 10.0.1.15
    2017/04/08 07:48:27 [WARN] manager: No servers available
    2017/04/08 07:48:27 [ERR] agent: failed to sync remote state: No known Consul servers
==> /usr/local/Cellar/consul/HEAD-3ef7dde/bin/consul leave
    2017/04/08 07:48:28 [INFO] consul: client starting leave
    2017/04/08 07:48:28 [INFO] serf: EventMemberLeave: iMac-TMP.local 10.0.1.15
    2017/04/08 07:48:28 [INFO] agent: requesting shutdown
    2017/04/08 07:48:28 [INFO] consul: shutting down client
    2017/04/08 07:48:28 [INFO] manager: shutting down
    2017/04/08 07:48:28 [INFO] agent: shutdown complete
Error leaving: Put http://127.0.0.1:8500/v1/agent/leave: EOF
```

If I crank the sleep up to 30 seconds in the test before running `consul leave`, then it exits gracefully, as follows:

```
iMac-TMP:dir joe$ brew test consul -vd
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/consul.rb
Testing consul
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170408-30654-1xf5lmd.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/consul.rb -vd --HEAD
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/consul.rb
==> Starting Consul agent...
==> Consul agent running!
           Version: 'v0.8.0-25-g3ef7dde6-dev (3ef7dde6+CHANGES)'
           Node ID: '0badd3ca-3553-380f-8a09-3b02ba961b45'
         Node name: 'iMac-TMP.local'
        Datacenter: 'dc1'
            Server: false (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 10.0.1.15 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2017/04/08 07:49:26 [INFO] serf: EventMemberJoin: iMac-TMP.local 10.0.1.15
    2017/04/08 07:49:26 [WARN] manager: No servers available
    2017/04/08 07:49:26 [ERR] agent: failed to sync remote state: No known Consul servers
    2017/04/08 07:49:45 [WARN] manager: No servers available
    2017/04/08 07:49:45 [ERR] agent: failed to sync remote state: No known Consul servers
==> /usr/local/Cellar/consul/HEAD-3ef7dde/bin/consul leave
    2017/04/08 07:49:56 [INFO] consul: client starting leave
    2017/04/08 07:49:56 [INFO] serf: EventMemberLeave: iMac-TMP.local 10.0.1.15
    2017/04/08 07:49:56 [INFO] agent: requesting shutdown
    2017/04/08 07:49:56 [INFO] consul: shutting down client
    2017/04/08 07:49:56 [INFO] manager: shutting down
    2017/04/08 07:49:56 [INFO] agent: shutdown complete
Graceful leave complete
```

### PR DESCRIPTION
**Pull request by magiconair**
When the agent is triggered to shutdown via an external 'consul leave'
command delivered via the HTTP API then the client expects to receive a
response when the agent is down. This creates a race on when to shutdown
the agent itself like the RPC server, the checks and the state and the
external endpoints like DNS and HTTP. Ideally, the external endpoints
should be shutdown before the internal state but if the goal is to
respond reliably that the agent is down then this is not possible.

This patch splits the agent shutdown into two parts implemented in a
single method to keep it simple and unambiguos for the caller. The first
stage shuts down the internal state, checks, RPC server, ...
synchronously and then triggers the shutdown of the external endpoints
asychronously. This way the caller is guaranteed that the internal state
services are down when Shutdown returns and there remains enough time to
send a response.

Fixes #2880

### CODE REVIEW

**Comment by magiconair** [comment]
I'd appreciate some extra pair of eyes on this one. Please read the git commit comment and the comment in the code to evaluate the approach. I think this does what we want and that this is also how we want it. 

Also, this was the previous behavior when the HTTP and DNS servers were managed by the `Command` and not the `Agent`.

File: agent/agent.go [hunk 1]
```diff
@@ -1159,9 +1150,32 @@ func (a *Agent) Shutdown() error {
...
+			}
+		}
+		a.logger.Println("[INFO] agent: Waiting for endpoints to shut down")
+		a.wgServers.Wait()
+		a.logger.Print("[INFO] agent: Endpoints down")
+
+		a.logger.Println("[INFO] agent: shutdown complete")
+		close(a.shutdownCh)
+	}()
+
```
Comment (preetapan) [inline agent/agent.go]: If I understand this correctly, don't you also need another waitGroup to make sure this goroutine finishes before the return in line 1179? like a waitgroup with Add(1) called  around line 1154, and then make sure to call Done() after close(..) is called in the above go-routine.

Comment (kyhavlov) [inline agent/agent.go]: It looks like it has to be this way (not blocking on the http server shutdowns) so that in the Leave endpoint this function can return and finish serving the connection to the client, then shut down the http servers afterward (because they're doing a graceful shutdown and waiting for connections to finish being served). If we shut them down before Leave returns, we get the EOF.

Comment (magiconair) [inline agent/agent.go]: A shutdown can be triggered through a signal or through an http call. When we get a signal we can shutdown in any suitable order. If we get the shutdown signal via HTTP **and** want to return a response that the shutdown has completed successfully then we need to send that response before the HTTP server is down. The leave handler has to wait for some state change, then send the response and then the rest can terminate. The fully correct way of doing this would be to continue with the shutdown after the response has been sent but since I don't know how to accomplish this this is the next best thing. Everything else depends on a go routine which fires some time after the handler function returned.

Comment (preetapan) [inline agent/agent.go]: Understood now. I see how this fixes that specific race condition. 
However, if a sigquit/sigterm is sent, and with this implementation, if the go-routine doesn't get called before it gets terminated, won't it leave like an open socket to the http/dns ports? trying to start it again might lead to "connection refused" type errors?

Comment (magiconair) [inline agent/agent.go]: @preetapan you are quite thorough. :) The go routine closes the `shutdownCh` at the end which should prevent this. Let me double check.

Comment (magiconair) [inline agent/agent.go]: @preetapan you're right. Merged too soon.

**Comment by magiconair** [comment]
I've backed this out again. will try a different approach.

**Comment by magiconair** [comment]
Superseded by https://github.com/hashicorp/consul/pull/3163
