### PR TITLE
config: warn if a config file is being skipped because of its file extension

### LINKED ISSUE #7748: Consul services register silently does nothing when given file with unsupported file extension
#### Overview of the Issue

I tried to register a service but nothing happened. The problem turned out to be because the file extension was incorrect, but the need for the file extension to be from a supported list was not mentioned on the documentation page for the `consul services register` subcommand. Also, I believe at least one error or warning should have been printed: either a message about an ignored file, a message that no services were registered, or both.

#### Reproduction Steps

1. Create a service description file, calling it foo.service
1. Type `consul services register foo.service`

### Consul info for both Client and Server

<details>
  <summary>Client and server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 5
        services = 8
build:
        prerelease = 
        revision = 1200f25e
        version = 1.6.2
consul:
        acl = disabled
        bootstrap = true
        known_datacenters = 1
        leader = true
        leader_addr = 10.42.4.108:8300
        server = true
raft:
        applied_index = 49678
        commit_index = 49678
        fsm_pending = 0
        last_contact = 0
        last_log_index = 49678
        last_log_term = 2
        last_snapshot_index = 49177
        last_snapshot_term = 2
        latest_configuration = [{Suffrage:Voter ID:b6705d1a-a960-0c91-dba5-5e684c63face Address:10.42.4.108:8300}]
        latest_configuration_index = 1
        num_peers = 0
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 16
        goroutines = 91
        max_procs = 16
        os = linux
        version = go1.12.13
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 1
        event_time = 2
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 0
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 1
        members = 1
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

Alpine Linux 3.9 in Docker container

### Log Fragments

There are no relevant log fragments, because the API is never called.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #7748 

Adds a warning when config building skips files due to their file extension.

I found that `validate` and the `services` commands were not printing any warnings. I've made them print warnings as part of this change.

I did some cleanup, in separate commits, before making the change. To reduce the scope of `Builder`, and so that the two pieces of code which can produce this warning are much closer together.

Best viewed by individual commit. There is a lot more context in each commit message.

### CODE REVIEW

File: command/validate/validate.go [hunk 1]
```diff
@@ -60,6 +60,9 @@ func (c *cmd) Run(args []string) int {
 		c.UI.Error(fmt.Sprintf("Config validation failed: %v", err.Error()))
 		return 1
 	}
+	for _, w := range b.Warnings {
+		c.UI.Warn(w)
+	}
```
Comment (dnephin) [inline command/validate/validate.go:65]: I wonder if this should be inside the `!c.quiet` block.

File: agent/config/builder.go [hunk 2]
```diff
@@ -112,34 +105,34 @@ func NewBuilder(flags Flags) (*Builder, error) {
...
 }
 
-// ReadPath reads a single config file or all files in a directory (but
-// not its sub-directories) and appends them to the list of config
-// sources.
-func (b *Builder) ReadPath(path string) ([]Source, error) {
+// sourcesFromPath reads a single config file or all files in a directory (but
+// not its sub-directories) and returns Sources created from the
+// files.
+func (b *Builder) sourcesFromPath(path string, options BuilderOpts) ([]Source, error) {
```
Comment (crhino) [inline agent/config/builder.go:135]: Just curious if you have a philosophy on why to pass in `options BuilderOpts` to `b.sourcesFromPath`, but `newSourceFromFile` takes only the `format string`? One is a method on the `Builder` struct and the other a regular function?

File: agent/config/runtime_test.go [hunk 3]
```diff
@@ -5996,23 +5999,18 @@ func TestFullConfig(t *testing.T) {
 		t.Run(format, func(t *testing.T) {
 			// parse the flags since this is the only way we can set the
 			// DevMode flag
-			var flags Flags
+			var flags BuilderOpts
 			fs := flag.NewFlagSet("", flag.ContinueOnError)
 			AddFlags(fs, &flags)
 			if err := fs.Parse(flagSrc); err != nil {
 				t.Fatalf("ParseFlags: %s", err)
 			}
```
Comment (crhino) [inline agent/config/runtime_test.go:6008]: Should we add a check like `require.Len(t, fs.Args(), 0)` here as well? Since we no longer error for that in `NewBuilder`.

File: command/agent/agent.go [hunk 4]
```diff
@@ -174,14 +174,17 @@ func (c *cmd) startupJoinWan(agent *agent.Agent, cfg *config.RuntimeConfig) erro
...
 func (c *cmd) run(args []string) int {
-	// Parse our configs
 	if err := c.flags.Parse(args); err != nil {
 		if !strings.Contains(err.Error(), "help requested") {
 			c.UI.Error(fmt.Sprintf("error parsing flags: %v", err))
 		}
 		return 1
 	}
-	c.flagArgs.Args = c.flags.Args()
+	if len(c.flags.Args()) > 0 {
```
Comment (crhino) [inline command/agent/agent.go:183]: 👍  I like moving this check here instead of in `NewBuilder`

File: command/validate/validate.go (hunk 1 above)
Comment (crhino) [reply command/validate/validate.go:65]: Good question, although warnings do not constitute an error, they are still a potential misconfiguration. 🤔 

Perhaps the real question is: are warnings an error or not? If they are, they should cause a failure. If they are not, then they should be in the quiet block.

As a user, I would probably want `consul validate` to error on any warnings as well, since I am actively attempting to check my configuration. Changing those semantics now might be annoying to current users though, but perhaps helpful.

**Comment by crhino** [comment]
Ran through a bunch of the different commands and it looks great. I think the only remaining question is what to do about `consul validate`.

File: command/validate/validate.go (hunk 1 above)
Comment (dnephin) [reply command/validate/validate.go:65]: A new flag that exits non-zero if there are warnings would be a good idea. I'll add that as a follow up.

For the current behaviour it sounds like you agree this should only be printed when not `--quiet`, so I will make that change.

File: agent/config/builder.go (hunk 2 above)
Comment (dnephin) [reply agent/config/builder.go:135]: Ah, just an oversight. I forget if this changed while I was working on it, but you are correct this should take `format string`. I'll make that change.

**Comment by dnephin** [comment]
Thanks for the review! I've made those changes

File: command/validate/validate.go (hunk 1 above)
Comment (crhino) [reply command/validate/validate.go]: That makes sense to me. 👍

**Comment by dnephin** [comment]
I guess this should go into 1.8.x? I forgot to tag it for cherry-picking, I'll get it merged now
