### PR TITLE
Centralize command-line parsing part 2

### LINKED ISSUE #2566: consul kv command does not pass CONSUL_HTTP_TOKEN
### `consul version`
Client: `0.7.1`
Server: `n/a`

### Operating system and Environment details

Ubuntu 16.04

### Description of the Issue (and unexpected/desired result)

From `consul kv get --help`:

```
  -token=<value>          ACL token to use in the request. This can also be
                          specified via the CONSUL_HTTP_TOKEN environment
                          variable. If unspecified, the query will default to
                          the token of the Consul agent at the HTTP address.
```

So, I expect the following two commands to have equivalent behavior:

    $ consul kv get -token xyz config/test
    $ CONSUL_HTTP_TOKEN=xyz consul kv get config/test

However, the first command with `-token xyz` specified as a CLI option, passes the token to the API correctly, whereas the second command with the environment variable only does not pass the token to the API.

### Reproduction steps

Use netcat to verify, first, on a machine not running Consul, set netcat to listen to port 8500:

    $ nc -l 8500

Then in another window, run the first command above. It will hang, but in the netcat terminal you can see the HTTP request that is sent:

    GET /v1/kv/config/test HTTP/1.1
    Host: 127.0.0.1:8500
    User-Agent: Go-http-client/1.1
    X-Consul-Token: xyz
    Accept-Encoding: gzip

Hit Ctrl-C on the Consul command. This will also kill the netcat process. Restart netcat, and run the second command using the environment variable, and in the netcat window you will see:

    GET /v1/kv/config/test HTTP/1.1
    Host: 127.0.0.1:8500
    User-Agent: Go-http-client/1.1
    Accept-Encoding: gzip

In other words, `consul kv` command does not pass through the `CONSUL_HTTP_TOKEN` environment variable to the `X-Consul-Token` header as the documentation suggests.

### PR DESCRIPTION
**Pull request by kyhavlov**
This converts the commands up through `kv` to use the base.Command structure for parsing.

Fixes #2566

### CODE REVIEW

File: command/base/command.go [hunk 1]
```diff
@@ -198,6 +211,10 @@ func printTitle(w io.Writer, s string) {
 func printFlag(w io.Writer, f *flag.Flag) {
 	example, _ := flag.UnquoteUsage(f)
 	if example != "" {
+		// Change 'value' to 'string' for consistency
+		if example == "value" {
+			example = "string"
+		}
```
Comment (kyhavlov) [inline command/base/command.go]: This feels a little strange; having common flags show up as `-http-addr=<value>` looks weird, though

File: command/base/command.go [hunk 2]
```diff
@@ -130,6 +140,9 @@ func (c *Command) Parse(args []string) error {
 
 // Help returns the help for this flagSet.
 func (c *Command) Help() string {
+	if c.flagSet == nil {
+		return ""
+	}
```
Comment (kyhavlov) [inline command/base/command.go]: I wasn't sure if there was a better solution than this for cases where Help() gets called before anything is initialized, like with the kv command and the kv tests that check for no tabs.

File: command/base/command.go (hunk 1 above)
Comment (slackpad) [inline command/base/command.go]: Hmm - we should probably keep the default Go behavior here for consistency. Looking at `UnquoteUsage` you can fix `-http-addr` by putting `string` in backquotes in the help text:

```
The `address` to connect to...
```

This will make it do `-http-addr=<address>` and is probably a better way to customize. While in here I realized that the description for `-http-addr` doesn't address UNIX sockets at all, so we need to touch that up a bit.

File: command/event.go [hunk 3]
```diff
@@ -24,33 +23,25 @@ Usage: consul event [options] [payload]
...
-	if err := cmdFlags.Parse(args); err != nil {
+	var name, node, service, tag string
+
+	f := c.Command.NewFlagSet(c)
+	f.StringVar(&name, "name", "",
+		"Name of the event.")
+	f.StringVar(&node, "node", "",
+		"Regular expression to filter on node names.")
+	f.StringVar(&service, "service", "",
+		"Regular expression to filter on service instances")
```
Comment (slackpad) [inline command/event.go]: Missing period at the end of this one. We keep an eye out for this and try to make them all match (include the period).

File: command/event.go [hunk 4]
```diff
@@ -101,7 +92,7 @@ func (c *EventCommand) Run(args []string) int {
 	}
 
 	// Create and test the HTTP client
-	client, err := HTTPClient(*httpAddr)
```
Comment (slackpad) [inline command/event.go]: Note to self to make sure we delete this `HTTPClient` later.

File: command/keyring.go [hunk 5]
```diff
@@ -1,37 +1,46 @@
...
+		"Change the primary encryption key, which is used to encrypt "+
+			"messages. The key must already be installed before this operation "+
+			"can succeed.")
+	f.StringVar(&removeKey, "remove", "",
+		"Remove the given key from the cluster. This operation may only be "+
+			"performed on keys which are not currently the primary key.")
+	f.BoolVar(&listKeys, "list", false,
+		"List all keys currently in use within the cluster.")
+	f.IntVar(&relay, "relay-factor", 0,
+		"Added in Consul 0.7.4, setting this to a non-zero value will cause nodes "+
```
Comment (slackpad) [inline command/keyring.go]: I wonder if it makes sense to put these version notes in the actual command help, or just the web docs. If you are seeing this, then you have the right version :-)

File: command/kv_get.go [hunk 6]
```diff
@@ -51,54 +50,39 @@ Usage: consul kv get [options] [KEY_OR_PREFIX]
...
+	detailed := f.Bool("detailed", false,
+		"Provide additional metadata about the key in addition to the value such "+
+			"as the ModifyIndex and any flags that may have been set on the key. "+
+			"The default value is false.")
+	keys := f.Bool("keys", false,
+		"List keys which start with the given prefix, but not their values. "+
+			"This is especially useful if you only need the key names themselves. "+
+			"This option is commonly combined with the -separator option. The default "+
+			"value is false.")
+	base64encode := f.Bool("base64", false,
```
Comment (slackpad) [inline command/kv_get.go]: This should be moved up to keep them in sorted order.

File: command/kv_get.go [hunk 7]
```diff
@@ -51,54 +50,39 @@ Usage: consul kv get [options] [KEY_OR_PREFIX]
...
+		"Base64 encode the value. The default value is false.")
+	recurse := f.Bool("recurse", false,
+		"Recursively look at all keys prefixed with the given path. The default "+
+			"value is false.")
+	separator := f.String("separator", "/",
```
Comment (slackpad) [inline command/kv_get.go]: This ought to get a `-stale` option while we are in here.

File: website/source/layouts/docs.erb [hunk 8]
```diff
@@ -87,6 +87,10 @@
 					<a href="/docs/commands/force-leave.html">force-leave</a>
 					</li>
 
+					<li<%= sidebar_current("docs-commands-info") %>>
+                    <a href="/docs/commands/info.html">info</a>
```
Comment (slackpad) [inline website/source/layouts/docs.erb]: Looks like the whitespace got borked here.

File: command/keyring.go (hunk 5 above)
Comment (kyhavlov) [inline command/keyring.go]: Yeah, it's pretty redundant here, going to remove it.

File: command/kv_get.go (hunk 7 above)
Comment (kyhavlov) [inline command/kv_get.go]: Stale is one of the common http options, are you referring to something else?

Comment (slackpad) [inline command/kv_get.go]: Oh then we need to plumb it into the options below.

Comment (slackpad) [inline command/kv_get.go]: Or does the API client plumb that in?

Comment (kyhavlov) [inline command/kv_get.go]: It doesn't; it gets passed in through the QueryOptions like this: 
```go
AllowStale: c.Command.HTTPStale(),
```
