### PR TITLE
Set MinQuorum variable in Autopilot

### LINKED ISSUE #5922: Auto Pilot breaks Quorum Invariant
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

#### Overview of the Issue

Consul Auto Pilot Dead Server Cleanup allows consul to run reads, writes, etc without quorum.

#### Reproduction Steps

We are using a cluster of 5 nodes.
A cluster with 5 nodes requires at least 3 nodes to maintain quorum.

<details>
<summary>Create a docker file `docker-compose.yml` with this contents.</summary>
<pre>
version: "2"
services:
  consul_dc1:
    image: consul
    command: "agent -log-level debug -ui -server -client 0.0.0.0 -datacenter=dc1 -bootstrap-expect=5 -join consul_dc1"
  consul_nodes_dc1:
    image: consul
    command: "agent -log-level debug -server -bootstrap-expect=5 -datacenter=dc1 -join consul_dc1"
    depends_on:
      - consul_dc1
</pre>
</details>

Start docker:
```
docker-compose -p quorum up -d --scale consul_nodes_dc1=4
```

Wait until the cluster is fully operational and healthy.
```
docker-compose -p quorum exec consul_dc1 consul info
```

Remove 1 server by scaling down the followers to 3.
```
docker-compose -p quorum scale consul_nodes_dc1=3
```

The server will enter the `failed` status, but auto pilot Dead Server Cleanup will change this to the `left` status.
This can be observed by looking at the members:
```
docker-compose -p quorum exec consul_dc1 consul members
```

Once the server has entered the `left` status, remove another server by scaling the followers to 2.
```
docker-compose -p quorum scale consul_nodes_dc1=2
```

Once again, this removed server will enter the `failed` status, but auto pilot Dead Server Cleanup will change this to the `left` status.
This can be observed by looking at the members:
```
docker-compose -p quorum exec consul_dc1 consul members
```

Once again, we wait until the server has entered the `left` status.
At this moment, we're running with 3 servers, and with 2 `left` servers.
The consul members output will look something like this:

    Node          Address          Status  Type    Build  Protocol  DC   Segment
    0b6017669513  172.21.0.5:8301  left    server  1.4.4  2         dc1  <all>
    2602b8156afc  172.21.0.2:8301  alive   server  1.4.4  2         dc1  <all>
    4feed0909559  172.21.0.6:8301  left    server  1.4.4  2         dc1  <all>
    bedf4c26482a  172.21.0.4:8301  alive   server  1.4.4  2         dc1  <all>
    f9dde50de3b7  172.21.0.3:8301  alive   server  1.4.4  2         dc1  <all>

According to quorum rules, our 5 node cluster should have a failure tolerance of `0` and *we can no longer lose any servers without losing quorum*.
So let's remove another one. :)
```
docker-compose -p quorum scale consul_nodes_dc1=1
```

Our membership will look like this:
- 2 `alive` servers
- 2 `left` sersers
- 1 `failed` server

```
Node          Address          Status  Type    Build  Protocol  DC   Segment
0b6017669513  172.21.0.5:8301  left    server  1.4.4  2         dc1  <all>
2602b8156afc  172.21.0.2:8301  alive   server  1.4.4  2         dc1  <all>
4feed0909559  172.21.0.6:8301  left    server  1.4.4  2         dc1  <all>
bedf4c26482a  172.21.0.4:8301  alive   server  1.4.4  2         dc1  <all>
f9dde50de3b7  172.21.0.3:8301  failed  server  1.4.4  2         dc1  <all>
```

If we test setting and getting a value, this succeeds:

    [avandersteldt] ~/docker_img (1)# docker-compose -p quorum exec consul_dc1 consul kv put redis/config/connections 5
    Success! Data written to: redis/config/connections
    [avandersteldt] ~/docker_img (0)# docker-compose -p quorum exec consul_dc1 consul kv get redis/config/connections
    5

<details>
<summary>(Instructions on how to clean up the cluster under this fold.)</summary>
<pre>
docker-compose -p quorum stop
docker-compose -p quorum kill
docker-compose -p quorum rm -sf
</pre>
</details>

## Expected Behaviour

The last server loss would have caused quorum loss, stopped the leader being a leader, and the write operation would have failed.

### Consul info for both Client and Server

<details>
  <summary>Server info</summary>

```
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 0
        services = 0
build:
        prerelease = 
        revision = ea5210a3
        version = 1.4.4
consul:
        acl = disabled
        bootstrap = false
        known_datacenters = 1
        leader = true
        leader_addr = 172.21.0.2:8300
        server = true
raft:
        applied_index = 107
        commit_index = 107
        fsm_pending = 0
        last_contact = 0
        last_log_index = 107
        last_log_term = 2
        last_snapshot_index = 0
        last_snapshot_term = 0
        latest_configuration = [{Suffrage:Voter ID:a4ac8ce3-7f6f-0406-6ca8-1ccb3de9ea35 Address:172.21.0.2:8300} {Suffrage:Voter ID:aa7c826a-caa2-f091-4e40-6a4b6bcf060a Address:172.21.0.4:8300} {Suffrage:Voter ID:3f6bcd8b-f9b9-30eb-328e-f09c70556f04 Address:172.21.0.3:8300}]
        latest_configuration_index = 23
        num_peers = 2
        protocol_version = 3
        protocol_version_max = 3
        protocol_version_min = 0
        snapshot_version_max = 1
        snapshot_version_min = 0
        state = Leader
        term = 2
runtime:
        arch = amd64
        cpu_count = 4
        goroutines = 96
        max_procs = 4
        os = linux
        version = go1.11.4
serf_lan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 2
        failed = 1
        health_score = 0
        intent_queue = 0
        left = 2
        member_time = 9
        members = 5
        query_queue = 0
        query_time = 1
serf_wan:
        coordinate_resets = 0
        encrypted = false
        event_queue = 0
        event_time = 1
        failed = 3
        health_score = 0
        intent_queue = 0
        left = 0
        member_time = 12
        members = 5
        query_queue = 0
        query_time = 1
```

</details>

### Operating system and Environment details

uname -a says: `Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### Log Fragments

```
2019/06/05 15:32:37 [INFO] autopilot: Attempting removal of failed server node "4feed0909559"
2019/06/05 15:32:57 [INFO] autopilot: Attempting removal of failed server node "0b6017669513"
```

### Notes

The scenario requires servers to go away slowly enough for auto-pilot to transition one from the failed to the left state, before the next one fails.

We discovered this during testing of an upgrade script that tested both the `healthy` and `failure_tolerance` telemetry to ascertain if a cluster was healthy. Both these health indicators indicate that everthing is fine with servers in the `left` state.

Work-around is to turn off dead server removal and only enable it during brief windows where an upgrade happens.
I think the long term fix in code would be that dead server removal only occurs in cases where a `failed` server can be replaced by a newly joining server. Whereas a failed server that is not replaced would remain in the `failed` state indefinitely, or until a human operator has removed the server using force-leave.

I speculate the same scenario can occur with Dead Server Removal disabled, if the servers stay in the `failed` state for 3 days and the automatic cleanup kicks in to remove them.

### PR DESCRIPTION
**Pull request by s-christoff**
Fixes #5922 
`MinQuorum` allows users to pass in the number of servers needed in a cluster before pruning of dead servers in autopilot can occur.

### CODE REVIEW

File: agent/config/builder.go [hunk 1]
```diff
@@ -1089,6 +1090,10 @@ func (b *Builder) Validate(rt RuntimeConfig) error {
 		}
 	}
 
+	//MinQuorum is set to BootstrarpExpect if available
+	if rt.BootstrapExpect != 0 {
```
Comment (s-christoff) [inline agent/config/builder.go]: I'm sure there will be a time someone wants to set both BootstrapExpect and MinQuorum. Do we want them to be able to be different, or should it override MinQuorum if BootstrapExpect is set?
Open to discussion here.

Comment (mkeeler) [reply agent/config/builder.go]: I think we should allow bootstrap expect to be lower than MinQuorum but not the other way around

Comment (s-christoff) [reply agent/config/builder.go]: Hmm - okay, I can totally do that. Do you have an example of how they would be set that way/ why someone would use them that way? I'm curious because I cannot think of why someone would want MinQuorum and BootstrapExpect to be different, but I know there **has** to be users who would want it.

Comment (mkeeler) [reply agent/config/builder.go]: So thinking a little more my original answer I would alter to say that we shouldn't enforce any particular constraints the relationship of minquorum and bootstrap expect.

So first, the autopilot settings in the config are only ever used if no autopilot config exists (so only when bootstrapping a new datacenter). Otherwise you must manage it from the API/CLI.

When managing from the API/CLI we don't even have this question because the bootstrap expect value isn't persisted in the raft autopilot config. It could be that you originally wanted to use 5 servers but found you only needed 3 or maybe you are going the other way. Regardless whatever value you set in this fashion should be taken (unless its a value that is just bad like 0 or something which never makes sense).

So given that the only time when there may be a correlation between the bootstrap expect value and the min quorum size is during dc bootstrapping for the first time when deciding on the autopilot config to set in raft.

If MinQuorum is set we should use it as the user "knows what they are doing".

If its less than bootstrap expect maybe they want to wait for all 5 servers to come online before bootstrapping everything for the first time but once operational they want more availability so they will allow the min quorum to be 3.

On the other side, maybe they want to get to bootstrapping things and need to wait for 2 or 3 servers but eventually will have 5 and want that to be the minimum that autopilot will reduce things to.

Both cases seem plausible to me.

Comment (s-christoff) [reply agent/config/builder.go]: Right, I see. So would you rather remove the relationship between the two or keep it as is (if MinQuorum is not set, take on BootstrapExpect value) and also create a validator for 0 value inputs (ex: if users inputs 0, throw an err?)

Comment (mkeeler) [reply agent/config/builder.go]: I think leaving as is would be good. If MinQuorum isn't set then assume it should be the bootstrap expect value.

Does 0 indicate that the min quorum size calculations should be disabled?

Comment (s-christoff) [reply agent/config/builder.go]: I guess that would make sense, should people are the option to set MinQuorum to 0 and then set BootstrapExpect to 5 (or whatever)

Comment (mkeeler) [reply agent/config/builder.go]: I think so. If you want todays behavior then you need to disable the MinQuorum calculations but you may also want to still do bootstrap expect stuff.

Comment (s-christoff) [reply agent/config/builder.go]: I think this new update is much better. :)

File: agent/consul/autopilot_test.go [hunk 2]
```diff
@@ -369,3 +369,99 @@ func TestAutopilot_PromoteNonVoter(t *testing.T) {
...
+	})
+
+	delete(servers, dead.config.NodeName)
+	//Autopilot should not take this one into left
+	dead = findStatus(false)
+	dead.Shutdown()
+	<-closeMap[dead.config.NodeName]
+
+	//To allow for pruning to finish
+	time.Sleep(1 * time.Second)
```
Comment (mikemorris) [inline agent/consul/autopilot_test.go]: Is there any sort of helper method like `waitForPrune` or something we could use here? This could be prone to flapping.

Comment (s-christoff) [reply agent/consul/autopilot_test.go]: Thanks for the review! Do you mean just making a new func in this file called `waitforPrune` and the contents of that holding the sleep?

File: agent/consul/autopilot/structs.go [hunk 3]
```diff
@@ -20,6 +20,10 @@ type Config struct {
 	// be behind before being considered unhealthy.
 	MaxTrailingLogs uint64
 
+	// MinQuorum sets the minimum number of servers required in a cluster
+	// before autopilot can prune dead servers.
+	MinQuorum uint
```
Comment (freddygv) [inline agent/consul/autopilot/structs.go]: I think these should be ints instead, like with BootstrapExpect.

To avoid issues with someone providing a negative value you can do something like this:
https://github.com/hashicorp/consul/blob/e653583f698f4762f28535b251d0ec11910e65a8/agent/config/builder.go#L985

The issue with the uint is that is someone provides something like -1, then the config build fails with this error:
`cannot parse 'autopilot.min_quorum', -1 overflows uint`

That may seem cryptic to users, compared to how we validate other numbers that should always be positive.

File: agent/consul/autopilot_test.go (hunk 2 above)
Comment (freddygv) [reply agent/consul/autopilot_test.go]: I think this sleep can be removed, since you're using `retry.Run` below. Does it not pass without the sleep?

Comment (s-christoff) [reply agent/consul/autopilot_test.go]: It does not. :(

File: website/source/docs/agent/options.html.md [hunk 4]
```diff
@@ -782,6 +782,9 @@ default will automatically work with some tooling.
       the maximum number of log entries that a server can trail the leader by before being considered unhealthy. Defaults
       to 250.
 
+    * <a name="min_quorum"></a><a href="#min_quorum">`min_quorum`</a> - Sets the minimum number of servers allowed in a cluster
+      before autopilot can prune dead servers. Defaults to bootstrap expect if set.
```
Comment (freddygv) [inline website/source/docs/agent/options.html.md]: Should this be `Defaults to bootstrap expect if not set`? Also, where in the code  does it default to bootstrap expect? 

Maybe it would be useful to add a test to verify the behavior when bootstrap expect and minquorum aren't equal.

File: agent/consul/autopilot_test.go (hunk 2 above)
Comment (s-christoff) [reply agent/consul/autopilot_test.go]: Hmm - I was like 100% sure it didn't pass when I wrote it without the sleep, but it turns out I was wrong. It can totally go on without it.
Weird!

File: agent/consul/autopilot/structs.go (hunk 3 above)
Comment (s-christoff) [reply agent/consul/autopilot/structs.go]: Discussed privately.

File: website/source/api/operator/autopilot.html.md [hunk 5]
```diff
@@ -108,6 +108,9 @@ The table below shows this endpoint's support for
 - `MaxTrailingLogs` `(int: 250)` specifies the maximum number of log entries
   that a server can trail the leader by before being considered unhealthy.
 
+- `MinQuorum` `int: 0` - specifies the minimum amount of servers needed before
```
Comment (kaitlincarter-hc) [inline website/source/api/operator/autopilot.html.md]:
```suggestion
- `MinQuorum` `int: 0` - specifies the minimum number of servers needed before
```

File: website/source/api/operator/autopilot.html.md [hunk 6]
```diff
@@ -108,6 +108,9 @@ The table below shows this endpoint's support for
...
+  autopilot can prune dead servers
```
Comment (kaitlincarter-hc) [inline website/source/api/operator/autopilot.html.md]:
```suggestion
  Autopilot can prune dead servers.
```

File: website/source/docs/agent/options.html.md [hunk 7]
```diff
@@ -782,6 +782,9 @@ default will automatically work with some tooling.
       the maximum number of log entries that a server can trail the leader by before being considered unhealthy. Defaults
       to 250.
 
+    * <a name="min_quorum"></a><a href="#min_quorum">`min_quorum`</a> - Sets the minimum number of servers allowed in a cluster
```
Comment (kaitlincarter-hc) [inline website/source/docs/agent/options.html.md]: Allowed doesn't quite fit, maybe again use "needed" or "necessary". Is cluster the right term? Also is there a default? If there isn't a default, then you can say so.

Comment (s-christoff) [reply website/source/docs/agent/options.html.md]: This sound better?
```
Sets the minimum number of servers necessary in a cluster
      before autopilot can prune dead servers. There is no default.
```

Comment (s-christoff) [reply website/source/docs/agent/options.html.md]: I don't know the proper way to say there isn't a default, but I appreciate the "necessary" wording suggestion. It sounds way more clear then "allowed"
