### PR TITLE
Fix CA Replication when ACLs are enabled

### LINKED ISSUE #6192: CA replication not working 1.6beta2
#### Overview of the Issue

Consul 1.6beta2

The CA replication from the primary DC to the secondary DC does not work.

ACLs and Intentions are replicated but he Consul cluster in the secondary DC is not able to replicate the CA. 

#### Reproduction Steps

2 clusters of 3 nodes each in 2 different regions (tested in AWS: eu-west-1 and eu-west-3).
ACL, Connect, TLS are enabled. 
replication, agent, default and agent_master tokens are set with appropriate policies.

### Consul info for both Client and Server

Replication policy:
```
    acl = "write"

    operator = "write"

    service_prefix "" {
      policy = "read"
      intentions = "read"
    }
```

Part of the configuration in the secondary DC:
```
{
    "datacenter": "eu-west-1",
    "primary_datacenter": "eu-west-3",
    "connect": {
        "enabled": true
    },
    "acl": {
        "default_policy": "deny",
        "down_policy": "extend-cache",
        "enable_key_list_policy": true,
        "enable_token_persistence": true,
        "enable_token_replication": true,
        "enabled": true
    }
}
```

Part of the configuration in the primary DC:
```
{
    "datacenter": "eu-west-3",
    "primary_datacenter": "eu-west-3",
    "connect": {
        "enabled": true
    },
    "acl": {
        "default_policy": "deny",
        "down_policy": "extend-cache",
        "enable_key_list_policy": true,
        "enable_token_persistence": true,
        "enabled": true
    }
}
```

### Operating system and Environment details

debian 9 on t2.micro

### Log Fragments

In the primary DC:
```
22:05:49 root@ip-10-3-0-13 ~ [0]
> consul members 
Node             Address            Status  Type    Build       Protocol  DC         Segment
ip-10-3-0-13     10.3.0.13:8301     alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-29     10.3.0.29:8301     alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-37     10.3.0.37:8301     alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-4      10.3.0.4:8301      alive   client  1.6.0beta2  2         eu-west-3  <default>
ip-10-3-0-7      10.3.0.7:8301      alive   client  1.6.0beta2  2         eu-west-3  <default>

22:06:03 root@ip-10-3-0-13 ~ [0]
> consul members -wan
Node                    Address         Status  Type    Build       Protocol  DC         Segment
ip-10-1-0-10.eu-west-1  10.1.0.10:8302  alive   server  1.6.0beta2  2         eu-west-1  <all>
ip-10-1-0-22.eu-west-1  10.1.0.22:8302  alive   server  1.6.0beta2  2         eu-west-1  <all>
ip-10-1-0-41.eu-west-1  10.1.0.41:8302  alive   server  1.6.0beta2  2         eu-west-1  <all>
ip-10-3-0-13.eu-west-3  10.3.0.13:8302  alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-29.eu-west-3  10.3.0.29:8302  alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-37.eu-west-3  10.3.0.37:8302  alive   server  1.6.0beta2  2         eu-west-3  <all>
```

In the secondary DC:
```
22:07:37 root@ip-10-1-0-22 ~ [0]
> consul members -wan
Node                    Address         Status  Type    Build       Protocol  DC         Segment
ip-10-1-0-10.eu-west-1  10.1.0.10:8302  alive   server  1.6.0beta2  2         eu-west-1  <all>
ip-10-1-0-22.eu-west-1  10.1.0.22:8302  alive   server  1.6.0beta2  2         eu-west-1  <all>
ip-10-1-0-41.eu-west-1  10.1.0.41:8302  alive   server  1.6.0beta2  2         eu-west-1  <all>
ip-10-3-0-13.eu-west-3  10.3.0.13:8302  alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-29.eu-west-3  10.3.0.29:8302  alive   server  1.6.0beta2  2         eu-west-3  <all>
ip-10-3-0-37.eu-west-3  10.3.0.37:8302  alive   server  1.6.0beta2  2         eu-west-3  <all>
```

Here is the auto-generated CA in the primary DC:
```
22:07:12 root@ip-10-3-0-13 ~ [0]
> curl -sS http://127.0.0.1:8500/v1/connect/ca/roots | jq .
{
  "ActiveRootID": "9a:21:7a:e0:16:ae:19:58:bc:ca:b5:c4:97:3e:fe:d3:0c:8f:af:8e",
  "TrustDomain": "594d66d8-240c-260c-33d0-71589d845d99.consul",
  "Roots": [
    {
      "ID": "9a:21:7a:e0:16:ae:19:58:bc:ca:b5:c4:97:3e:fe:d3:0c:8f:af:8e",
      "Name": "Consul CA Root Cert",
      "SerialNumber": 7,
      "SigningKeyID": "37:63:3a:33:65:3a:39:38:3a:36:34:3a:30:36:3a:30:36:3a:30:61:3a:34:30:3a:33:61:3a:65:30:3a:64:31:3a:36:39:3a:31:61:3a:31:65:3a:31:38:3a:66:35:3a:37:34:3a:38:32:3a:65:63:3a:38:64:3a:33:65:3a:31:66:3a:32:66:3a:35:62:3a:38:31:3a:30:64:3a:65:33:3a:32:65:3a:38:64:3a:64:32:3a:33:39:3a:66:36",
      "ExternalTrustDomain": "594d66d8-240c-260c-33d0-71589d845d99",
      "NotBefore": "2019-07-22T21:47:11Z",
      "NotAfter": "2029-07-22T21:47:11Z",
      "RootCert": "-----BEGIN CERTIFICATE-----\nMIICWjCCAf+gAwIBAgIBBzAKBggqhkjOPQQDAjAWMRQwEgYDVQQDEwtDb25zdWwg\n...\neWXKTgt8Mvzb5sQlgCeJvekBQk6in29TqJHD/ovf\n-----END CERTIFICATE-----\n",
      "IntermediateCerts": null,
      "Active": true,
      "CreateIndex": 8,
      "ModifyIndex": 8
    }
  ]
}
```

Here is the auto-generated CA in the secondary DC:
```
22:08:44 root@ip-10-1-0-22 ~ [0]
> curl -sS http://127.0.0.1:8500/v1/connect/ca/roots | jq .
{
  "ActiveRootID": "ee:75:44:b2:f8:92:06:37:06:cf:55:be:7f:87:d9:93:ee:ad:c8:6e",
  "TrustDomain": "2b56ec58-87f8-dda6-bbf5-b3f3f24fa3ed.consul",
  "Roots": [
    {
      "ID": "ee:75:44:b2:f8:92:06:37:06:cf:55:be:7f:87:d9:93:ee:ad:c8:6e",
      "Name": "Consul CA Root Cert",
      "SerialNumber": 7,
      "SigningKeyID": "39:66:3a:30:38:3a:32:31:3a:64:65:3a:65:30:3a:38:66:3a:61:66:3a:33:66:3a:62:65:3a:63:32:3a:65:64:3a:32:37:3a:64:64:3a:64:64:3a:65:63:3a:36:30:3a:30:65:3a:64:61:3a:33:38:3a:39:30:3a:64:39:3a:64:62:3a:30:64:3a:31:39:3a:35:39:3a:39:62:3a:62:31:3a:33:62:3a:33:39:3a:38:65:3a:65:39:3a:65:34",
      "ExternalTrustDomain": "2b56ec58-87f8-dda6-bbf5-b3f3f24fa3ed",
      "NotBefore": "2019-07-22T21:47:09Z",
      "NotAfter": "2029-07-22T21:47:09Z",
      "RootCert": "-----BEGIN CERTIFICATE-----\nMIICWDCCAf+gAwIBAgIBBzAKBggqhkjOPQQDAjAWMRQwEgYDVQQDEwtDb25zdWwg\n...\nqJRf+hLfFc1SdWq8eiMuyt422i/PSpby05pMnw==\n-----END CERTIFICATE-----\n",
      "IntermediateCerts": null,
      "Active": true,
      "CreateIndex": 8,
      "ModifyIndex": 8
    }
  ]
}

```
=> as we can see, in the secondary DC, the CA is not replicated

Here is the state of the replication in the secondary DC (it's ok):
```
22:11:39 root@ip-10-1-0-22 /var/log [0]
> curl -sS http://127.0.0.1:8500/v1/acl/replication | jq .
{
  "Enabled": true,
  "Running": true,
  "SourceDatacenter": "eu-west-3",
  "ReplicationType": "tokens",
  "ReplicatedIndex": 1090,
  "ReplicatedRoleIndex": 1,
  "ReplicatedTokenIndex": 1131,
  "LastSuccess": "2019-07-22T22:10:00Z",
  "LastError": "0001-01-01T00:00:00Z"
}
```

In the log of the leader in the secondary DC, I have:
```
Jul 22 22:11:39 ip-10-1-0-22 consul[9365]:     2019/07/22 22:11:39 [ERR] consul: RPC failed to server 10.3.0.13:8300 in DC "eu-west-3": rpc error making call: rpc error making call: Permission denied
Jul 22 22:11:39 ip-10-1-0-22 consul[9365]:     2019/07/22 22:11:39 [ERR] connect: error watching primary datacenter roots: rpc error making call: rpc error making call: Permission denied
```

I have tested to replace all the tokens with a global-management token: same error.
I have also tested to restart, deactivate/reactive Connect, etc.
I think the problem lies in RPC message sent by the leader of the secondary DC: it does not include the replication token to check the health of the primary cluster.

See the PR #6193

With this PR, the leader in the secondary cluster immediately replicates the CA:
```
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] consul: New leader elected: ip-10-1-0-22
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] acl: started ACL policy replication
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] acl: started ACL role replication
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] acl: started ACL token replication
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO]  raft: pipelining replication to peer {Nonvoter 9db86766-a5f7-ad14-bf13-a8399a7df6c1 10.1.0.10:8300}
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] connect: updated root certificates from primary datacenter
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] connect: received new intermediate certificate from primary datacenter
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] connect: initialized secondary datacenter CA with provider "consul"
Jul 22 22:47:53 ip-10-1-0-22 consul[12366]:     2019/07/22 22:47:53 [INFO] replication: started Config Entry replication

```
And the old CA is replaced with the one from the primary DC:
```
22:49:36 root@ip-10-1-0-22 /var/log [130]
> curl -sS http://127.0.0.1:8500/v1/connect/ca/roots | jq .
{
  "ActiveRootID": "9a:21:7a:e0:16:ae:19:58:bc:ca:b5:c4:97:3e:fe:d3:0c:8f:af:8e",
  "TrustDomain": "594d66d8-240c-260c-33d0-71589d845d99.consul",
  "Roots": [
    {
      "ID": "9a:21:7a:e0:16:ae:19:58:bc:ca:b5:c4:97:3e:fe:d3:0c:8f:af:8e",
      "Name": "Consul CA Root Cert",
      "SerialNumber": 7,
      "SigningKeyID": "37:63:3a:33:65:3a:39:38:3a:36:34:3a:30:36:3a:30:36:3a:30:61:3a:34:30:3a:33:61:3a:65:30:3a:64:31:3a:36:39:3a:31:61:3a:31:65:3a:31:38:3a:66:35:3a:37:34:3a:38:32:3a:65:63:3a:38:64:3a:33:65:3a:31:66:3a:32:66:3a:35:62:3a:38:31:3a:30:64:3a:65:33:3a:32:65:3a:38:64:3a:64:32:3a:33:39:3a:66:36",
      "ExternalTrustDomain": "594d66d8-240c-260c-33d0-71589d845d99",
      "NotBefore": "2019-07-22T21:47:11Z",
      "NotAfter": "2029-07-22T21:47:11Z",
      "RootCert": "-----BEGIN CERTIFICATE-----\nMIICWjCCAf+gAwIBAgIBBzAKBggqhkjOPQQDAjAWMRQwEgYDVQQDEwtDb25zdWwg\n...\neWXKTgt8Mvzb5sQlgCeJvekBQk6in29TqJHD/ovf\n-----END CERTIFICATE-----\n",
      "IntermediateCerts": null,
      "Active": true,
      "CreateIndex": 691,
      "ModifyIndex": 691
    },
    {
      "ID": "ee:75:44:b2:f8:92:06:37:06:cf:55:be:7f:87:d9:93:ee:ad:c8:6e",
      "Name": "Consul CA Root Cert",
      "SerialNumber": 7,
      "SigningKeyID": "39:66:3a:30:38:3a:32:31:3a:64:65:3a:65:30:3a:38:66:3a:61:66:3a:33:66:3a:62:65:3a:63:32:3a:65:64:3a:32:37:3a:64:64:3a:64:64:3a:65:63:3a:36:30:3a:30:65:3a:64:61:3a:33:38:3a:39:30:3a:64:39:3a:64:62:3a:30:64:3a:31:39:3a:35:39:3a:39:62:3a:62:31:3a:33:62:3a:33:39:3a:38:65:3a:65:39:3a:65:34",
      "ExternalTrustDomain": "2b56ec58-87f8-dda6-bbf5-b3f3f24fa3ed",
      "NotBefore": "2019-07-22T21:47:09Z",
      "NotAfter": "2029-07-22T21:47:09Z",
      "RootCert": "-----BEGIN CERTIFICATE-----\nMIICWDCCAf+gAwIBAgIBBzAKBggqhkjOPQQDAjAWMRQwEgYDVQQDEwtDb25zdWwg\n...\nqJRf+hLfFc1SdWq8eiMuyt422i/PSpby05pMnw==\n-----END CERTIFICATE-----\n",
      "IntermediateCerts": null,
      "Active": false,
      "CreateIndex": 8,
      "ModifyIndex": 691
    }
  ]
}

```

### PR DESCRIPTION
**Pull request by mkeeler**
Fixes #6192 

Essentially this stops using autopilot + RPCs to determine server versions. Instead it just uses the local serf metadata.

This fixes the linked issue by no longer performing the RPCs that would otherwise require a special ACL token. We could have just used the replication token there but really these places already have all the information in the serf metadata so we can just use that instead of making cross-dc requests.

### CODE REVIEW

**Comment by tristan-weil** [comment]
Thank you!

And I think the datacentersMeetMinVersion and autopilotServersMeetMinimumVersion functions in leader_connect.go are no more used, so they could also be deleted.

**Comment by mkeeler** [comment]
Yep, it was dead code and has now been removed.

**Comment by freddygv** [comment]
@mkeeler You may be looking into them already, but those ACL test failures in CI don't look like flakes

File: agent/consul/util.go [hunk 1]
```diff
@@ -276,9 +276,33 @@ func runtimeStats() map[string]string {
...
+		return srv.Status != serf.StatusAlive || !srv.Build.LessThan(minVersion)
+	})
+}
+
+// ServersMeetMinimumVersion returns whether the given alive servers from a particular
+// datacenter are at least on the given Consul version. This requires at least 1 alive server in the DC
+func ServersInDCMeetMinimumVersion(members []serf.Member, datacenter string, minVersion *version.Version) (bool, bool) {
+	found := false
+	ok := ServersMeetRequirements(members, func(srv *metadata.Server) bool {
+		if srv.Status != serf.StatusAlive || srv.Datacenter != datacenter {
```
Comment (banks) [inline agent/consul/util.go]: We allow servers to be not-alive 🤔

Doesn't this mean that all the servers in the other DC could be entirely dead and we'd treat that as "all have the correct version" and plough on with an upgrade? I feel like we'd need to ensure a quorum are alive and at the right version to be safe in the knowledge that there is a leader and that the leader is upgraded?

This is likely how it's always been so I guess we can leave as it is. Chances of doing an upgrade while primary DC is entirely offline seems slim but still this is suspicious logic to me.

Comment (banks) [reply agent/consul/util.go]: Oh, I see the `found` thing that at least ensures that there is at least one alive server on the other side.

But it still feels a bit odd - I came up with all sorts of unlikley cases where this is wrong but then there is a very plausible one (actually the common case I think): 
 - upgrade secondary first, it will sit in a loop checking primary version waiting to init CA
 - first server in primary DC is upgraded, it's not yet leader though since user picked a follower to upgrade first (typical)
 - secondary DC polls again and sees one alive server in the primary DC that is the right version (this logic) and so it goes ahead even though the primary DC's leader is still the old version that doesn't know how to init a secondary CA etc.

I don't know what happens in that case - maybe just a few errors until the primary upgrade is done but it seems like that is the core thing we are trying to prevent here.

Am I missing something?

File: agent/consul/leader_connect_test.go [hunk 2]
```diff
@@ -364,49 +375,45 @@ func TestLeader_SecondaryCA_UpgradeBeforePrimary(t *testing.T) {
...
-		require.NoError(err)
-		require.Equal(1, len(roots1))
-		require.Equal(1, len(roots2))
-		require.NotEqual(roots1[0].ID, roots2[0].ID)
-		require.NotEqual(roots1[0].RootCert, roots2[0].RootCert)
+		require.NoError(t, err)
+		require.Equal(t, 1, len(roots1))
+		require.Equal(t, 1, len(roots2))
+		require.NotEqual(t, roots1[0].ID, roots2[0].ID)
+		require.NotEqual(t, roots1[0].RootCert, roots2[0].RootCert)
```
[the remark this answers is not in the document]
Comment (mkeeler) [reply agent/consul/leader_connect_test.go]: This leaves the behavior as it was before. 

It would be pretty easy to switch in the leader code but there are many tests that rely on and are in fact designed to test this behavior. 

As for this test. I just fixed it to handle require + retry better

File: agent/consul/util.go (hunk 1 above)
Comment (mkeeler) [reply agent/consul/util.go]: For the case you mention how can there be one alive server not of a sufficient version but is not the leader. 

The logic I was going for is that all alive servers must be at that version before it’s allowed to go through. If you are running two servers only (which would be odd) and are upgrading one of them then the only way this is allowed to proceed is if you have already upgraded the other server. If you have 3 servers and are following the prescribed rolling update procedure you are in the same situation. The assumption is that any servers in a failed state will come back online with a version at least as new as the other alive servers. 

You figured out the other part which is that we require at least 1 alive server in the primary before allowing initializing as a secondary CA

File: agent/consul/leader_connect_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (banks) [reply agent/consul/leader_connect_test.go]: OK I misunderstood. I think that's fine.

File: agent/consul/util.go (hunk 1 above)
Comment (banks) [reply agent/consul/util.go]: > The assumption is that any servers in a failed state will come back online with a version at least as new as the other alive servers

Is that OK? I mean it's very very likely true but not guaranteed if something fails during an upgrade or health flaps for some reason etc. I guess given it's low probability, what happens if it does come up? If it's just a few error logs for a bit until primary gets healthy again then fine, if it causes a panic because something is writing new state that a leader can't understand then obviously not fine. In the CA case I _think_ it's the first right?

> all alive servers must be at that version

Ah maybe I got mixed up because of the "at least one alive" part.

I can still dream up many possible scenarios that I have no idea if they would cause crashes etc, but I guess this is as safe as it was before at least and generally good enough.

In cases (possibly not this one) like the new ACL stuff where leader turning on the new feature causes old followers to panic, are we stricter about this or do we use the same logic (so flappy health might allow an old server to be temporarily ignored and then come back and be in a crash loop?

Comment (mkeeler) [reply agent/consul/util.go]: In the situation where one of the servers in the primary has not been upgraded and eventually comes back from a failed state the worst that could happen is that we get some logs about RPC failures in the primary CA roots watch go routine if it tries to get a new signed intermediate and the current primary leader doesn't support that RPC.

The secondary will backoff retrying as necessary.

**Comment by mkeeler** [comment]
Looking int a segfault I had seen before my last force push. It is concerning at the least.

**Comment by mkeeler** [comment]
The segfault was caused by leadership revocation after the secondary ca roots watch had been run. This could have happened even with the old codes behavior so I am reinstating my changes.

We now will disallow initializing a secondary datacenters CA as a primary in the case where the primary can not sign intermediate certs yet (servers in primary are not on new enough versions)
